### DISCUSSION TITLE
[1.21.2] - Ingress Controller and taints?

### DISCUSSION THREAD

**Discussion by rsirny** [rancher/rke2#1575] [Q&A] [answered]
Our cluster was installed with RKE2 1.21.2. I applied taints on some of the worker nodes and noticed that they are respected by the ingress controller daemon set, i.e. the pods are not running on these nodes. I see that other system daemon sets (e.g. kube-proxy) are using tolerations such as:
```yaml
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
```
 Is the lack of tolerations intended for ingress controller?
