### DISCUSSION TITLE
kubelet apiserver ha

### DISCUSSION THREAD

**Discussion by ibrother** [rancher/rke2#1613] [Q&A] [answered]
hi all

i noticed that rke2 kubelet's kubeconfig is `/var/lib/rancher/rke2/agent/kubelet.kubeconfig`,here is the content

```yml
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /var/lib/rancher/rke2/agent/server-ca.crt
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate: /var/lib/rancher/rke2/agent/client-kubelet.crt
    client-key: /vat/lib/rancher/rke2/agent/client-kubelet.key
```

kubelet uses `https://127.0.0.1:6443` to connect to the apiserver, i already setup a ha vip for apiserver, what should i do? just edit this file to use ha vip instead of `127.0.0.1` or any other config to adjust kubelet's kubeconfig?
