### DISCUSSION TITLE
Using Private/custom CA signed certificate for all API communication.

### DISCUSSION THREAD

**Discussion by gauravkarki** [rancher/rke2#1764] [Q&A] [answered]
I am using rke2 v1.20.7. I am using my own private CA signed certificate for Rancher "https://rancher.com/docs/rancher/v2.6/en/installation/resources/tls-secrets/".

However all other API communication between api-server and rest of the components are using the self-signed certificate generated by rke2 itself.

**Sample Vulnerability Scan output**

> TLS/SSL certificate is self-signed.
> TLS/SSL certificate signed by unknown, untrusted CA: CN=Kubernetes Ingress Controller Fake Certificate, O=Acme Co -- [Path does not chain with any of the trust anchors].
> 
I believe all the certificate are stored in 

- /var/lib/rancher/rke2/server/tls/ for server node
- /var/lib/rancher/rke2/agent/ for agent node

Going through the rke2 installation and "Advanced Options and Configuration" section under https://docs.rke2.io/, I did not find any information. 

**Question.**
Is there anyway to use custom/private CA cert for all API communication?

**Comment by brandond** [comment, marked as answer]
> TLS/SSL certificate signed by unknown, untrusted CA: CN=Kubernetes Ingress Controller Fake Certificate, O=Acme Co

The cert you're seeing here is (as it says) the certificate created by the ingress controller if you don't provide your own ingress cert. Are you trying to change this, or the cluster CA certificates?

**Reply by gauravkarki** [reply]
Brandond, thank you for your prompt response.
I would like to change the ingress controller first and see if that take cares of the vulnerability scans findings. If not then I may have to change Cluster CA Certificates.

Can you please point me to the documentation on changing the TLS on Ingress.

Thanks

**Reply by brandond** [reply]
RKE2 comes with ingress-nginx as the default ingress controller. You can find the docs here: https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate

**Reply by gauravkarki** [reply]
Brandond, thanks for the information. I was able to locate the  rke2-ingress-nginx-controller under kube-system namespaces. I also creates tls secrets with my custom TLS certs.
But it does not allows me edit the deployment. I believe this was implemented as a static pod but in Rancher I am not sure where to add this extra config.
```
The Pod "rke2-ingress-nginx-controller-xxxxxxx-xxxx" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
        Volumes:        {{Name: "rke2-ingress-nginx-token-7gntf", VolumeSource: {Secret: &{SecretName: "rke2-ingress-nginx-token-7gntf", DefaultMode: &420}}}},
        InitContainers: nil,
        Containers: []core.Container{
 {
                        Name:    "rke2-ingress-nginx-controller",
                        Image:   "rancher/nginx-ingress-controller:nginx-0.30.0-rancher1",
                        Command: nil,
                        Args: []string{
                                ... // 3 identical elements
                                "--ingress-class=nginx",
                                "--configmap=kube-system/rke2-ingress-nginx-controller",
-                               "--default-ssl-certificate=kube-system/ingress-nginx-tls",
                        },
                        WorkingDir: "",
                        Ports:      {{Name: "http", HostPort: 80, ContainerPort: 80, Protocol: "TCP", ...}, {Name: "https", HostPort: 443, ContainerPort: 443, Protocol: "TCP", ...}},
                        ... // 16 identical fields
                },
        },
        EphemeralContainers: nil,
        RestartPolicy:       "Always",
        ... // 25 identical fields
  }
```

**Reply by brandond** [reply]
You cannot customize it by directly editing the pod, for several reasons. It is deployed via helm chart, you should go through the helm chart values to make your changes. See:
* https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig
* https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

**Reply by gauravkarki** [reply]
Thank you Brandond for the link.
I created a config /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
```
cat /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
```
I can see the config got created. 
```
# kubectl get addon -n kube-system 
NAME                        AGE
deployment-default-values   4m30s
rke2-canal                  95d
rke2-coredns                95d
rke2-ingress-nginx          95d
rke2-ingress-nginx-config   22m
rke2-kube-proxy             95d
rke2-metrics-server         95d
# 
```
Still the default-ssl-certificate has not been updated to the rke2-ingress-nginx's spec. Am I missing anything? 
```
spec:
  containers:
  - args:
    - /nginx-ingress-controller
    - --default-backend-service=kube-system/rke2-ingress-nginx-default-backend
    - --election-id=ingress-controller-leader
    - --ingress-class=nginx
    - --configmap=kube-system/rke2-ingress-nginx-controller
```

**Reply by brandond** [reply]
You didn't provide any valuesContent to customize the chart configuration, so it's still using the defaults. What specifically are you expecting to see if you haven't configured anything?

**Reply by gauravkarki** [reply]
Sorry, I didnot copied the last line of /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

```
#cat /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    default-ssl-certificate: "kube-system/ingress-nginx-tls"
~         
```
Where **ingress-nginx-tls** is my private tls cert
```
# kubectl -n kube-system describe secrets ingress-nginx-tls
Name:         ingress-nginx-tls
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  2094 bytes
tls.key:  1704 bytes
```
Right now when I see its using the **fake cert**. I would like to see my private cert.
```
# curl --verbose -k https://10.165.5.173:443
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Sep  7 18:27:38 2021 GMT
*  expire date: Sep  7 18:27:38 2022 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

**Reply by brandond** [reply]
default-ssl-certificate does not appear to be a recognized configuration key; I don't see it in values.yaml. Did you want to add it to the controller's extraArgs?

https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L154-L158

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      extraArgs:
        default-ssl-certificate: "kube-system/ingress-nginx-tls"
```

**Reply by gauravkarki** [reply]
Brandond,
Thank you very much for your help. Your suggestion (creating below file) resolved my issue.

```
# cat /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      extraArgs:
        default-ssl-certificate: "kube-system/ingress-nginx-tls"
```
Regarding my another question on changing the cluster CA certificates: 

- is it advisable to change it to private/custom TLS?
- is there any documentation that explains how to change it?

I guess there is a risk of cluster not working if we change it to private/custom CA certificate when it expires. if we let the default then RKE rotates the certificate before it expires.
