### DISCUSSION TITLE
containerd - allow root for somes images

### DISCUSSION THREAD

**Discussion by HujinoKun** [rancher/rke2#1945] [Q&A]
hello, 

Is it possible to tell containerd with rke2 that it can run a container as root? I still have some images that use the root user 

Version : v1.21.5+rke2r1

**Comment by brandond** [comment]
Containerd doesn't care what user you run images as. Are you perhaps deploying a pod with a securitycontext that doesn't allow running as root?

**Reply by HujinoKun** [reply]
Hello,

Here is some examples :

poste-io : 

```
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 1000
```

Nextcloud :

```
  extraSecurityContext:
    runAsUser: "0"
    runAsGroup: "0"
    runAsNonRoot: false
    readOnlyRootFilesystem: true
```

Output : 

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  16s               default-scheduler  Successfully assigned x/x-nextcloud-69c666f4f4-fz4g9 to x.com
  Normal   Pulled     1s (x4 over 16s)  kubelet            Container image "nextcloud:21.0.4-apache" already present on machine
  Warning  Failed     1s (x4 over 16s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "x-nextcloud-69c666f4f4-fz4g9_(ad9938ef-eca1-42d3-b8a4-a914613d82f6)", container: nextcloud)
```

**Reply by brandond** [reply]
I'm not sure what that is - can you post the entire pod spec? I don't think you've configured it right, as the kubelet (not containerd) is rightly complaining `Error: container has runAsNonRoot and image will run as root` - so you've set runAsNonRoot somewhere, but the image itself runs as root.

**Reply by HujinoKun** [reply]
When i forced these values :

```yaml
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
```

I got this : 

```
44s         Warning   FailedCreate             replicaset/poste-io-598b97f54c                               Error creating: pods "poste-io-598b97f54c-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed]
2m49s       Warning   FailedCreate             replicaset/poste-io-5bc4fb4fb4                               Error creating: pods "poste-io-5bc4fb4fb4-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]
```

For poste-io deployment, here is his configuration : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poste-io
  namespace: mail
  labels:
    app: mail
    client: x
  annotations:
    app: mail
    client: x
spec:
  replicas: 1
  strategy:
    rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: mail
      client: x
  template:
    metadata:
      labels:
        app: mail
        client: x
    spec:
      containers:
      - name: poste-io
        image: analogic/poste.io:2.3.4
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 126Mi
            cpu: 50m
        env:
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - mountPath: /data
          name: poste-io-data
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
#          runAsNonRoot: false
#          runAsUser: 1000
      volumes:
        - name: poste-io-data
          persistentVolumeClaim:
            claimName: poste-io-data
```
