### DISCUSSION TITLE
RKE2 log rotation

### DISCUSSION THREAD

**Discussion by Torkolis** [rancher/rke2#3002] [Q&A] [answered]
Hi,

how can I setup log rotation in a RKE2 cluster so that the container logs don't consume all disk space?
https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level

I have found this:
https://www.suse.com/support/kb/doc/?id=000020071
for k3s, can I also apply it to RKE2? Would
```
curl -sfL https://get.rke2.io | INSTALL_RKE2_EXEC="--kubelet-arg "container-log-max-files=4" --kubelet-arg "container-log-max-size=50Mi"" sh -
```
work?
Or is there a better way? Can it be achieved for example with some parameters in the file /etc/rancher/rke2/config.yaml?

Edit:
I tried using this in the /etc/rancher/rke2/config.yaml file:
```yaml
kubelet-arg:
  - container-log-max-files=3
  - container-log-max-size=2Mi
```
but it seems not to work properly, I can see on the command line (with ps aux) that both parameters are passed to kubelet, but while the files amount is working fine, the log files itself are still large (150 MB) instead of 2, which is also the case without any extra configuration. I don't really understand that, because here https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ it says that default is 10Mi. Do you have any ideas or should I ask in kubelet github repository?

**Comment by brandond** [comment]
Which specific log files are you looking at?

**Reply by Torkolis** [reply]
my own simple deployment which produces tons of logs:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  script.sh: | 
    while :; do echo 'Hit CTRL+C'; done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ubuntu:22.04
        command: ["bash"]
        args: ["/tmp/script.sh"]
        volumeMounts:
          - name: script
            mountPath: /tmp
      volumes:
        - name: script
          configMap:
            name: myapp
```
then I watch with
`watch ls -al /var/log/pods/<POD>/myapp`
