### DISCUSSION TITLE
CPU Management Policies for RKE2

### DISCUSSION THREAD

**Discussion by mittasau** [rancher/rke2#3034] [Q&A] [answered]
I am trying to set up CPU management policies on RKE-2 node (intel NUC quad core i7 8th gen), but changes are not visible after server restart. **I want to change policy from "none" to "static"**

We might be missing something. 
Following Reference - https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy

Changes were made to **/etc/rancher/rke2/config.yaml**.
Following entries were added.
 
```yaml
cpu-manager: true
cpu-manager-policy: static
cpu-manager-policy-options: full-pcpus-only=true
cpu-manager-reconcile-period: 0s
kube-reserved: cpu=1
system-reserved: cpu=1
```

**_After the changes and rke2-server restart, we are checking the **CPU state at /var/lib/kubelet/cpu_manager_state**
 
**_"policyName":"none","defaultCpuSet":"","checksum":1353318690}_**_**
 
I assume policy name should be static here if changes were applied correctly.
 
**Could anyone please help how rke2 can apply these changes and how can we test it once done ?**
