### DISCUSSION TITLE
How to enable TLSv1.3?

### DISCUSSION THREAD

**Discussion by Torkolis** [rancher/rke2#3042] [Q&A]
I just found that it is not enabled by default, when I create a ingress with tls and pass it a secret containing the certificate the URL does not support TLSv1.3. the nginx.conf inside the rke2-ingress-nginx-controller pod just contains
ssl_protocols TLSv1.2;

**Comment by brandond** [comment]
Ingress-nginx configuration is documented upstream at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#configuration-options

The Helm chart allows you to set these options as `controller.config`:
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L45-L46

**Reply by Torkolis** [reply]
Aha, thank you, I had success with
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        ssl-protocols: "TLSv1.2 TLSv1.3"
```
Just an additional question, the configuration docs say that "TLSv1.2 TLSv1.3" is already default for ssl-protocols, why is it so that RKE2 uses only 1.2 by default? Any ideas? Using v1.22.9+rke2r2 btw.
