### DISCUSSION TITLE
Rancher helm-controller vanished!

### DISCUSSION THREAD

**Discussion by xanalogica** [rancher/rke2#3231] [Q&A] [answered]
I have a frustrating problem, where rke2 for v1.23 was working for a week, and then it stopped processing HelmChart manifests, and I believe it is because the helm-controller is nowhere to be found.  Odd thing is, it installed rke2-canal, rke2-coredns and rke2-metrics server fine, but then it won't install cert-manager or Hashicorp vault.

The deploy controller successfully notices the manifests for those two in /var/lib/rancher/rke2/server/manifests and loads them into a namespace, but then no helm-controller comes along to turn them into a helm-install-XXXX job.  And the apiVersion header is correct and matches what is used for rke2 internal manifests.:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.9.1
  set:
    installCRDs: true
  targetNamespace: cert-manager
```

I don't see any error logs from rke2 about shutting down helm-controller.  Does anyone have pointer to where to look next?  I've spent two days on this.  Any tips much appreciated!
