### DISCUSSION TITLE
How to customize etcd backup configuration in config.yaml (backup to s3)

### DISCUSSION THREAD

**Discussion by 0asp0** [rancher/rke2#3369] [Q&A]
Hi, I've setup an rke2 cluster with 3 nodes. For installation I used the script available at https://get.rke2.io.

Now I want to customize the etcd backup. Beside saving the backup on local disk I want the backup to be shipped to an internal minio s3 service.

I was able to get an onDemand Backup shipped to s3 using the following command on console:

```
rke2 etcd-snapshot \
--etcd-s3 \
--etcd-s3-bucket=k8s-local-backup \
--etcd-s3-access-key=myuser \
--etcd-s3-secret-key=mypassword \
--etcd-s3-folder=myfolder \
--etcd-s3-endpoint=minio.local:9000 \
--etcd-s3-endpoint-ca=/etc/pki/ca-trust/source/anchors/my-ca.pem
```

Now I want to add this configuration to the config yaml, but all tries failed. My settings have been ignored, so I assume I made an mistake, using wrong keys or whatever. 
What did I do?
- I only processed one node of the cluster
- drain the node
- change the config
- restart the node
- uncordon the node

Here is my config snipped which I added to the config which does NOT work:

```
etcd-s3: true
etcd-snapshot-schedule-cron value: '*/5 * * * *'
etcd-s3-bucket: k8s-local-backup
etcd-s3-access-key: myuser
etcd-s3-secret-key: mykey
etcd-s3-folder: myfolder
etcd-s3-endpoint: minio.local:9000
etcd-s3-endpoint-ca: /etc/pki/ca-trust/source/anchors/my-ca.pem
```

also this variant does NOT work:

```
etcd:
  disableSnapshots: false
  s3:
    bucket: k8s-local-backup
    endpoint: minio.local:9000
    endpointCA: /etc/pki/ca-trust/source/anchors/my-ca.pem
    folder: myfolder
    accessKey: myuser
    secretKey: mykey
  snapshotRetention: 5
  snapshotScheduleCron: '0 * * * *'
```

Is there a way to config-check the config.yaml on known field basis, not just that is a correct yaml? (rke2-server will not start if it is invalid yaml format)

Can you please point out the correct configuration snippet which I need to insert into config.yaml?

Thanks, Andreas
