### DISCUSSION TITLE
Canal on different iface

### DISCUSSION THREAD

**Discussion by busyboy77** [rancher/rke2#3956] [General]
I'm looking for some guidance what prerequisites are needed for an RKE2 cluster with different interface assigned to the Canal CNI. 

I'm using 
```
cat<<EOF| tee /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
 name: rke2-canal
 namespace: kube-system
spec:
 valuesContent: |-
   flannel:
     iface: "enp9s0"
EOF
```

but I'm not sure how things will work.  and what are the requirements for kube-api-server, kubelet, as there are many more options like

```
kube-apiserver-arg:
  - kubelet-preferred-address-types=InternalIP
```

and what are purposes for internal-IP and external-IP when offloading the CNI traffic onto a different interface.

 I'm learning the RKE2 multi-homed deployment with layered network approach. 

Please find below given diagram as my requirement.

![image](https://user-images.githubusercontent.com/19593617/217818066-d70d4ea0-7a79-48b1-926c-658d897f430c.png)

Where every VM is assigned 3 interfaces, 

1 for  external IP range is 10.192.168.x
1 for CNI using canal's iface -- 172.16.x.x
1 for storage network -- created using multus onto separate iface -- range 192.168.1000.x

now I'm not sure how to configure this layered network approach in cluster. I'm currently using below given config.yaml

```
mkdir -p /etc/rancher/rke2/
mkdir -p  /var/lib/rancher/rke2/server/manifests/


cat<<EOF|tee /etc/rancher/rke2/config.yaml
tls-san:
  - devops67.x.com
  - 10.192.168.67
  - devops61.x.com
  - 10.192.168.61
  - 192.168.100.161
  - devops62.x.com
  - 10.192.168.62
  - 192.168.100.162
  - devops63.x.com
  - 10.192.168.63
  - 192.168.100.163
write-kubeconfig-mode: "0600"
etcd-expose-metrics: true
cni:
   - multus
   - canal

EOF



cat<<EOF| tee /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
      allowSnippetAnnotations: "true"
EOF

cat<<EOF | tee  /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true

EOF


cat<<EOF| tee /var/lib/rancher/rke2/server/manifests/rke2-multus-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    rke2-whereabouts:
      enabled: true
EOF





cat<<EOF| tee /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
 name: rke2-canal
 namespace: kube-system
spec:
 valuesContent: |-
   flannel:
     iface: "enp8s0"
EOF

```

my multus network-attachment-definition looks like this
```


apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp7s0",
      "mode": "bridge",
      "isDefaultGateway": false,
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.0.0/16",
        "rangeStart": "172.16.0.6",
        "rangeEnd": "172.16.254.254",
        "routes": [
          { "dst": "172.16.0.0/16" }
        ],
         "gateway": "172.16.0.1"
      }
    }'

```

all boxes have 3 interface

```
ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:6a:6c:95 brd ff:ff:ff:ff:ff:ff
    inet 10.192.168.61/8 brd 10.255.255.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet 10.192.168.67/32 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe6a:6c95/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:8b:c2:84 brd ff:ff:ff:ff:ff:ff
    inet 172.16.143.196/16 brd 172.16.255.255 scope global dynamic noprefixroute enp7s0
       valid_lft 3210sec preferred_lft 3210sec
    inet6 fe80::12df:51dc:ccf:f770/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
4: enp8s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:0e:5b:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.161/24 brd 192.168.100.255 scope global noprefixroute enp8s0
       valid_lft forever preferred_lft forever
    inet6 fe80::c01e:c56c:dc96:aa06/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

I'm not sure how I'm ending up with this setup. Can someone guide me or point anything in particular.
