### DISCUSSION TITLE
"Restart" rke2-metrics-server and helm-controller understanding question

### DISCUSSION THREAD

**Discussion by mbehrisch** [rancher/rke2#3985] [Q&A]
Hi,

I accidentally killed the rke2-metrics-server deployment (k8s noob mistake) because I thought it had dependencies in the cert-manager namespace that I wanted to eliminate. This one is stuck in "terminating" but this is a different topic :)

Now, I understand that manifests in /var/lib/rancher/rke2/server/manifests get automatically parsed and these add-ons get applied?!
But, when happens this process? Do you know how I can manually invoke the helm install process?

Thanks for your help!!!!

**Comment by Martin-Weiss** [comment]
The manifest gets applied every minute if I remember right - but only if it gets modified.. - so add a comment ;-).

**Reply by brandond** [reply]
That will get it reapplied, but in order to get helm to run again you'll need to create a HelmChartConfig for rke2-metrics-server to give it some dummy content to perform an helm upgrade with.

**Reply by mbehrisch** [reply]
Hi @brandond. Thanks for the answer, but this is entirely unclear to me how this works? What are the process steps here and what has this to do with the helm_controller then?

**Reply by brandond** [reply]
The manifest just deploys a helm chart. Reapplying the manifest with no changes to the chart won't trigger helm to run. You to force helm to run to recreate the missing resources.

https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig

**Reply by mbehrisch** [reply]
Ok, I tried my best. Created a HelmChartConfig (see below) and stored it to `/var/lib/rancher/rke2/server/manifests`. 
Now I waited for the helm_controller to pick it up as a helm upgrade, but nothing happened. Did I misunderstand something?

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-metrics-server
  namespace: kube-system
spec:
  set:
    foo: bar
```

**Reply by brandond** [reply]
What'd you name it?
HelmChartConfig only supports spec.valuesContent, not spec.set.

**Reply by mbehrisch** [reply]
Ha it works. 

`rke2-metrics-server-helm-dummy.yam` is the file name. I guess this means it is not important which name it is.
I changed the file contents to the content below, stored it in  `/var/lib/rancher/rke2/server/manifests` and it gets picked up and helm upgrade deployed.

The only thing is that the Service does not get deployed with it. A bit unclear why this is not contained in the helm chart? 

![Screenshot - 10_03_2023 , 20_30_45](https://user-images.githubusercontent.com/310635/224410277-b7debd33-4516-4838-ad07-b003856d52b4.png)

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-metrics-server
  namespace: kube-system
spec:
  valuesContent: |-
    foo: bar
```
