### DISCUSSION TITLE
RKE2 to select the faster network interface on both the RKE2 server and agent machines that have two network interfaces

### DISCUSSION THREAD

**Discussion by dekaranger00** [rancher/rke2#4086] [Q&A]
I have a cluster of VMs that have two network interfaces installed. I would like to have RKE2 select the faster network interface for internal cluster communication and use the slower network interface for external communication. 

Is there a way to configure the RKE2 to do that?  If so, do I need to redeploy the RKE2 cluster to have it pick up the faster network interface?

Thank you.

**Comment by brandond** [comment]
Kubernetes just selects the interface with the default route. If you want to override that, you can use `--node-ip` to set the interface of the interface you would prefer to use.

**Reply by dekaranger00** [reply]
@brandond : Thank you for your reply. That makes sense. 

Just to confirm, in addition to `--node-ip` , I can also use `--node-external-ip` to set the slower interface to use right?

Then, I also need to tell Canal plugin to use the faster interface by adding a manifest file like below?

```
# /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      iface: "eth1"
```
