### DISCUSSION TITLE
Update Cilium to v1.13.2 for security/bug fixes on 1.26.x

### DISCUSSION THREAD

**Discussion by Jamison1** [rancher/rke2#4158] [Ideas]
Cilium 1.13.2 addresses many security/bug fixes along with a memory leak issue present in v1.13.0
[Debug mode leak](https://github.com/cilium/cilium/security/advisories/GHSA-pg5p-wwp8-97g8)
[Potential network policy bypass](https://github.com/cilium/cilium/security/advisories/GHSA-8fg8-jh2h-f2hc)
[cilium-agent container can access the host](https://github.com/cilium/cilium/security/advisories/GHSA-4hc4-pgfx-3mrx)
[Cilium eBPF filters may be temporarily removed](https://github.com/cilium/cilium/security/advisories/GHSA-r5x6-w42p-jhpp)

I looked into replacing the builtin chart but I see it is pinned to rke2-cilium-1.13.000.tgz
```
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-cilium/rke2-cilium-1.13.000.tgz
```

Any idea how this can be done on my end?

I'm using a HelmChartConfig, but guessing it is not user changeable like this as the chartContent may also need to be updated.
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    metadata:
      annotations:
        helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-cilium/rke2-cilium-1.13.200.tgz
```
