### DISCUSSION TITLE
Registry mirror fallback never worked even containerd configured with multiple endpoints

### DISCUSSION THREAD

**Discussion by zeddit** [rancher/rke2#4387] [General]
My configuration for rke2 registries.yaml looks like below:
```
mirrors:
  docker.io:
    endpoint:
      - "https://harbor.xxx.com/v2/docker.io"
      - "https://registry-1.docker.io"
      - "https://hub.docker.com"
``` 
I expect the image will be downloaded from my private self-hosted harbor by default.
and if the harbor went down, the image will fallback to use the second registry which would be `registry-1.docker` to download the image.
and if the second one is still down, it goes to `hub.docker.com` to find the image.

however, under my test, if my harbor goes down, it would never fallback to the next one to pull the image, and stuck forever until the harbor recovery.
If I understand it correctly, containerd allow specify additional container image registries to use in case the primary registry is not available.

I wonder if my configuration is wrong or there's a bug in implementation. thanks.

**Comment by brandond** [comment]
You have multiple issues with your endpoints
1. `https://harbor.xxx.com/v2/docker.io` - this is unlikely to work. I suspect that you're trying to indicate that images in your harbor registry are prefixed with `docker.io/`, but what you are actually doing here is changing the base path of the registry. That is probably breaking pulls from this registry mirror; what you want is to use a rewrite: https://docs.rke2.io/install/containerd_registry_configuration#rewrites. I could be wrong though, if this is indeed how your harbor registry is configured.
2. `https://registry-1.docker.io` - this is the default endpoint, you don't need to explicitly pass it as it is always tried last.
3. `https://hub.docker.com` - this is not a registry, it is the web interface for browsing images on Docker Hub. You can't actually pull images from it.

**Reply by zeddit** [reply]
Some explanation about my configuration.
1. `https://harbor.xxx.com/v2/docker.io` this works under my test. Why I am using this wired URL is because that harbor has a feature named `Proxy Cache`, which means it can work as a proxy to pull image from a public registry e.g. docker.io. However, a proxy cache with a public registry as backend exists as a repo inside harbor, which means I need to create a repo, and then tie this repo to docker.io. After that, I could pull a docker.io image from harbor but with a changed url. e.g.
```
# here I created a repo named docker.io to cache docker.io images
docker pull harbor.xxx.com/docker.io/rancher/busybox
# is equal to
docker pull rancher/busybox
```
If I want to use this proxy cache repo to download docker.io iamges in my rke2 cluster, a way to achieve it is the one you mentioned as `rewrite`.
```
  docker.io:
    endpoint:
      - "https://harbor.xxx.com"
    rewrite:
      "^(.*)": "docker.io/$1" // add a prefix to reach my harbor repo
```
2. I configured my rke2 cluster to use a harbor deployed above it self. Then, my harbor would fail some time. So I am trying to configure `fallback` registry to make my cluster alive even my harbor is broken. I noticed that `containerd` support multiple endpoint and its mapping in rke2 `registries.yaml` file is the list under `endpoint` attribute. Just like,
```
  docker.io:
    endpoint:
      - "https://harbor.xxx.com"
      - "https://registry-1.docker.io"
    rewrite:
      "^(.*)": "docker.io/$1" // add a prefix to reach my harbor repo
```
However, the original docker.io registry doesn't need `rewrite` image path. Besides, the rke2 yaml doesn't support different rewrite rules for different endpoint under the same registry like `docker.io`. So I am trying to hack it.
I found it could work for harbor without explicit rewrite by adding a `/v2/docker.io` at the end of url. So I did it.
Now my configuration of rke2 registries.yaml change to
```
  docker.io:
    endpoint:
      - "https://harbor.xxx.com/v2/docker.io"
      - "https://registry-1.docker.io" // without any rewrite rules
```
However, even it has multiple endpoint, it cannot fallback to the second one, or a default endpoint one you mentioned when my harbor failed.
3. this one was never be reached, so I didn't know it's a wrong endpoint. Thank you. 

My problem is that I don't know how to configure a fallback registry along with a primary one using harbor `Proxy Cache` in rke2 cluster. Great thanks for your help.
