### DISCUSSION TITLE
How can I modify the name of the cluster role on the server node

### DISCUSSION THREAD

**Discussion by lsyLearn** [rancher/rke2#4406] [Q&A]
On the server node， the cluster role is：
```
NAME      STATUS   ROLES                       AGE   VERSION
master1   Ready    control-plane,etcd,master   43m   v1.24.14+rke2r1
master2   Ready    control-plane,etcd,master   40m   v1.24.14+rke2r1

```
In RKE, the cluster roles are control-plane, etcd, and worker. How can I modify the configuration file to change a master role to a worker role?

**Comment by brandond** [comment]
The `control-plane,etcd,master` role labels are automatically applied to all server nodes, and cannot be removed. Agent nodes do not come with any labels. You can add the `worker` role label to any node by running `kubectl label node NODENAME node-role.kubernetes.io/worker=true`

Note that these are all literally just labels, there is nothing particularly special about them other than they show up in the `kubectl get node` output as the node roles.

**Reply by lsyLearn** [reply]
If I replace the "master" with the "worker" in the role labels, will it affect the functioning of the cluster?

**Reply by brandond** [reply]
Yes, don't do that. There are things with node label selectors that expect those labels on servers. It'll be put back on restart anyway. What exactly are you trying to accomplish?

**Reply by lsyLearn** [reply]
In RKE1, there is no "master" role. We want to migrate some functionalities from RKE1 to RKE2. However, during compatibility testing, we found that the "master" role affects the normal installation of certain components.

**Reply by brandond** [reply]
The `master` and `control-plane` roles serve the same purpose. `master` role is the legacy role, and some packages are still transitioning away from it, so we have opted to retain it. I will note that it is just a label, not a taint, so it should not prevent anything from running on those nodes. Can you show specifically what you're running into that has a problem with that label? Are you sure that the issue is not that things are looking for agent nodes with the `worker` label?

**Reply by lsyLearn** [reply]
In RKE1, a master node does not have the "master" role label, as shown below:
```
kubectl get nodes
NAME      STATUS   ROLES                      AGE   VERSION
master1   Ready    controlplane,etcd,worker   38d   v1.22.5
```
We need to install KubeSphere components based on Kubernetes. The installation configuration of KubeSphere includes multiple judgments on the "master" role label, one of which is as follows:
```
- name: KubeSphere | Getting Kubernetes master num
  shell: >
    {{ bin_dir }}/kubectl get node | awk '{if(NR>1){print $3}}' | grep master | wc -l
  register: masters
  failed_when: false

- name: KubeSphere | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}
  when:
    - enableHA is not defined
```
The master role lable is not included in rke1, but it is included in rke2, so some of the logical processing is different.
