### DISCUSSION TITLE
InhibitDelayMaxSec period is not honoured.

### DISCUSSION THREAD

**Discussion by ravisekhar-akkineni** [rancher/rke2#4688] [Q&A]
Hi

I have enabled GracefulNodeShutdownBasedOnPodPriority and also created different priority classes as listed below,

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  GracefulNodeShutdownBasedOnPodPriority: true
shutdownGracePeriodByPodPriority:
   - priority: 5
     shutdownGracePeriodSeconds: 100
   - priority: 4
     shutdownGracePeriodSeconds: 100
   - priority: 3
     shutdownGracePeriodSeconds: 100
   - priority: 2
     shutdownGracePeriodSeconds: 100
   - priority: 1
     shutdownGracePeriodSeconds: 100
   - priority: 0
     shutdownGracePeriodSeconds: 100
```

terminationGracePeriodSeconds is not configured for any of the pods belong to above priority groups and also intentionally added code to ignore SIGTERM for all of these 6 PODs.  As expected InhibitDelayMaxSec set to 600 in /etc/systemd/logind.conf.d/99-kubelet.conf file. 

I expected that if "systemctl reboot" is executed, systemd waits for atleast 600 seconds as kubelet has to wait for 100 seconds for each of the pod (since SIGTERM is ignored) but device is getting rebooted always after 30 seconds.

What might be the reason for rebooting system after 30 seconds?
