### DISCUSSION TITLE
Migrating from k3s to rke2 CoreDNS customisation

### DISCUSSION THREAD

**Discussion by ataraxus** [rancher/rke2#5006] [Q&A] [answered]
We stumbled upon a minor difference between k3s CoreDNS setup and rke2. We used to add a specific host to our CoreDNS via

```
{{- if .Values.global.coredns.customConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  name: coredns-custom
  namespace: kube-system
data:
  custom-hosts.server: |
```

the k3s core file for CoreDNS looks like this: 
```
.:53 {
    errors
    health
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    hosts /etc/coredns/NodeHosts {
      ttl 60
      reload 15s
      fallthrough
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
import /etc/coredns/custom/*.server
```

the last line is missing in rke2, it seems there is no possibility to achieve the same thing with rke2 without replacing the default core file for CoreDNS, which we are reluctant to because it could cause issues when upgrading. 

Is there a way to add a custom host to be resolved in rke2?

**Comment by ataraxus** [comment]
This issue seems somewhat related: https://github.com/rancher/rke2/issues/4940 but does not provide a solution which we would be fond of, see above. Maybe this is the reason why k3s used the import of custom files?

**Comment by ataraxus** [comment]
It seems there is a "default" https://github.com/coredns/helm/pull/44/files via the extraConfig variable. We will try that. 

https://github.com/rancher/rke2-charts/blob/main/charts/rke2-coredns/rke2-coredns/1.24.007/values.yaml#L154C16-L154C16
antoher good reference i wasnt able to find before posting this: https://github.com/rancher/rke2/issues/1808

**Comment by ataraxus** [comment, marked as answer]
Our solution looks like this: 
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    extraConfig:
      import:
        parameters: /etc/coredns/custom/*.server
    extraVolumes:
      - name: config-volume-custom
        configMap:
          name: coredns-custom
    extraVolumeMounts:
      - name: config-volume-custom
        mountPath: /etc/coredns/custom
        readOnly: true
```

with a core-custom config map like this: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  name: coredns-custom
  namespace: kube-system
data:
  custom-hosts.server: |
    custom.hosts {{ .Values.global.host }} {
      hosts {
        {{ .Values.custom.ip }} {{ .Values.custom.hostname }}
        fallthrough
      }
      whoami
    }
{{- end }}

```

This will hopefully help someone else too.
