### DISCUSSION TITLE
configuring cilium with native routing

### DISCUSSION THREAD

**Discussion by rahulait** [rancher/rke2#5337] [General]
Hi, I am trying to configure cilium with native routing when installing it on RKE2 cluster. I am specifying network options by adding rke2-cilium-config.yaml file at path /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml

Contents of /etc/rancher/rke2/config.yaml
```
root@vpc-master1:~# ip r
default via 10.0.0.1 dev eth0 proto static
10.0.0.0/8 dev eth0 proto kernel scope link src 10.0.0.2
root@vpc-master1:~#
root@vpc-master1:~# cat /etc/rancher/rke2/config.yaml
node-ip: 10.0.0.2
cni: cilium
disable: ['rke2-canal', 'rke2-ingress-nginx']
root@vpc-master1:~#
```

Contents of rke2-cilium-config.yaml
```
root@vpc-master1:~# cat /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    routingMode: native
    kubeProxyReplacement: true
    ipv4NativeRoutingCidr: 10.0.0.0/8
    autoDirectNodeRoutes: true
    tunnel: disabled
    tunnelProtocol: ""
    enableIpv4Masquerade: false
    k8sServiceHost: 10.0.0.2
    k8sServicePort: 6443
    ipv4:
      enabled: true
    ipv6:
      enabled: false
root@vpc-master1:~#
```

Helm install job status:
```
root@vpc-master1:~# kubectl logs -n kube-system helm-install-rke2-cilium-9sv4w | grep 'helm_v3 install'
+ helm_v3 install --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 rke2-cilium /tmp/rke2-cilium.tgz --values /config/values-10_HelmChartConfig.yaml
root@vpc-master1:~#
```

Cluster status:
```
root@vpc-master1:~# k get nodes -o wide
NAME          STATUS   ROLES                       AGE   VERSION          INTERNAL-IP   EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
vpc-master1   Ready    control-plane,etcd,master   28m   v1.28.3+rke2r1   10.0.0.2      XXX.XXX.XXX.XXX   Ubuntu 22.04.3 LTS   5.15.0-92-generic   containerd://1.7.7-k3s1
```

I see following errors for rke2-cilium pod. It keeps crashlooping:
```
root@vpc-master1:~# k logs pod/cilium-wfw2t -n kube-system  | grep -v "level=info"
Defaulted container "cilium-agent" out of: cilium-agent, install-portmap-cni-plugin (init), config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
level=warning msg="If auto-direct-node-routes is enabled, then you are recommended to also configure ipv4-native-routing-cidr. If ipv4-native-routing-cidr is not configured, this may lead to pod to pod traffic being masqueraded, which can cause problems with performance, observability and policy" subsys=config
level=error msg="Start hook failed" error="daemon creation failed: invalid daemon configuration: native routing cidr must be configured with option --ipv4-native-routing-cidr in combination with --enable-ipv4-masquerade --routing-mode=native --ipam=kubernetes --enable-ipv4=true" function="cmd.newDaemonPromise.func1 (daemon_main.go:1645)" subsys=hive
level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*authMapGarbageCollector).handleIdentityChange" name="auth gc-identity-events" subsys=auth
level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*AuthManager).handleAuthRequest" name="auth request-authentication" subsys=auth
level=error msg="Close() called without calling InitIdentityAllocator() first" subsys=identity-cache
level=error msg="Stop hook failed" error="unable to find controller ipcache-inject-labels" function="cmd.newPolicyTrifecta.func2 (policy.go:134)" subsys=hive
level=fatal msg="failed to start: daemon creation failed: invalid daemon configuration: native routing cidr must be configured with option --ipv4-native-routing-cidr in combination with --enable-ipv4-masquerade --routing-mode=native --ipam=kubernetes --enable-ipv4=true; failed to stop: unable to find controller ipcache-inject-labels" subsys=daemon
root@vpc-master1:~#
```
I am not sure what I might have missed to get the pod running in native routing mode. I've tried adding/removing different options from rke2-cilium helmchartconfig but couldn't make much progress. Any ideas what flag I am missing or I might be doing wrong here?

**Comment by brandond** [comment]
> native routing cidr must be configured with option --ipv4-native-routing-cidr in combination with **--enable-ipv4-masquerade** --routing-mode=native --ipam=kubernetes --enable-ipv4=true

>     enableIpv4Masquerade: false

The error message says that you must enable ipv4 masquerade, but you've set that to false in your config. It looks like you also need to use the Kubernetes IPAM?

I would probably defer to the cilium docs for details on all this, since this is more about configuring cilium than RKE2 itself.

**Reply by rahulait** [reply]
I had tried setting ipv4 masquerade to true as well and also ipam mode as kubernetes but it didn't helped. Something like:
```
  valuesContent: |-
    routingMode: native
    kubeProxyReplacement: true
    ipv4NativeRoutingCidr: 10.0.0.0/10
    autoDirectNodeRoutes: true
    tunnel: disabled
    tunnelProtocol: ""
    enableIpv4Masquerade: true
    k8sServiceHost: 10.0.0.2
    k8sServicePort: 6443
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
```
