### DISCUSSION TITLE
CNI version and configuration upgrades

### DISCUSSION THREAD

**Discussion by febus982** [rancher/rke2#5682] [Q&A] [answered]
* Do RKE2 updates also upgrade the installed CNI charts? (e.g. cilium from 1.14 to 1.15) 

* Is it possible to change the relevant `HelmChartConfig` after the CNI plugin has been installed? (e.g. enabling Hubble after the cluster is up and running) 

```
# /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
```
