### DISCUSSION TITLE
Cant uninstall cilium.... it keeps getting reinstalled... how to uninstall?

### DISCUSSION THREAD

**Discussion by Smithx10** [rancher/rke2#5769] [Q&A]
I've recently installed Cilium to replace kube-proxy,  and wanted to revert that change.  

For some reason after I've deleted all things cilium eventually rke2 or something is reinstalling it.

I uninstalled it all..... and it keeps coming back lol..... my cluster feels haunted.

```
#!/bin/bash
rm /var/lib/rancher/rke2/server/manifests/cilium.yaml
rm -rf /var/run/cilium/cilium.pid
rm /opt/cni/bin/cilium-cni
./cilium-dbg post-uninstall-cleanup -f
rm -rf /root/.kube/cache/discovery/127.0.0.1_6443/cilium.io
rm -rf /var/lib/cni/results/cilium-*
rm -rf /etc/sysctl.d/99-zzz-override_cilium.conf
rm -rf /run/live/overlay/rw/etc/sysctl.d/99-zzz-override_cilium.conf
rm -rf /var/lib/rancher/rke2/data/v1.29.0-rke2r1-491b1a599021/charts/rke2-cilium.yaml

for r in $(k get crd | grep cilium | awk '{print $1}'); do kubectl delete crd $r; done
kubectl delete configmap chart-content-cilium -n kube-system
kubectl delete addon cilium-proxy -n kube-system

```

**Comment by brandond** [comment]
Did you restart rke2 with a different CNI, or with `cni: none`? The selected CNI will be redeployed every time RKE2 restarts...

**Comment by Smithx10** [comment]
We currently run kube-ovn.    We installed the cluster with cni: none in order to install kube-ovn.  After installing Kube-OVN we went to experiment with removing kube-proxy for ciliums proxy by adding "cilium-proxy.yaml" to 
/var/lib/rancher/rke2/server/manifests/cilium-proxy.yaml.

After failing and creating the following issue: https://github.com/kubeovn/kube-ovn/issues/3908 we attempted to uninstall.... and now we are stuck with it coming back to life,  and not really knowing from where.  


cilium-proxy.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  bootstrap: true
  chart: cilium
  targetNamespace: kube-system
  version: 1.15.3
  repo: https://helm.cilium.io
  valuesContent: |-
    routingMode: native
    devices: nodeip
    kubeProxyReplacement: true
    k8sServiceHost: 172.16.0.100
    k8sServicePort: 6443
    loadBalancer:
      algorithm: maglev
      mode: dsr
      dsrDispatch: opt

```

config.yaml
```
token: $mytoken
data-dir: /var/lib/rancher/rke2
cni: none
tls-san:
        - cluster.local
        - 172.16.0.1
        - 172.16.0.2
        - 172.16.0.3
        - 172.16.0.100
        - 10.91.230.10
        - 10.91.230.11
        - 10.91.230.12
        - 10.91.230.100
node-ip: 172.16.0.1
node-external-ip: 10.91.230.10
cluster-cidr: 172.16.128.0/17
cluster-dns: 172.16.64.10
service-cidr: 172.16.64.0/18
cluster-domain: cluster.local
snapshotter: zfs
node-taint:
        - CriticalAddonsOnly=true:NoExecute
node-label:
        - kube-ovn/role=master
disable:
  - cilium-proxy
  - cilium

```
