### DISCUSSION TITLE
How to properly mirror registries?

### DISCUSSION THREAD

**Discussion by EStork09** [rancher/rke2#5950] [Q&A] [answered]
I have a private registry that I am trying to get all pods to get proxied through. No matter what settings I seem to try for my mirrors, the configs show up in the file, but when I pull an image from a registry it doesn't matter, and the logs from containerd don't seem to acknowledge anything. Any help would be appreciated!

```
rke2 -v
rke2 version v1.29.4+rke2r1 (d30ec2a3fc17b931e2574fa8e7f082a48e8cfc0b)
go version go1.21.9 X:boringcrypto
```

```
mirrors:
  "docker.io":
    endpoint:
      - "https://harbor.example.com:443"
    rewrite:
      "(.*)": "docker/$1"
  "quay.io":
    endpoint:
      - "https://harbor.example.com:443"
    rewrite:
      "(.*)": "quay/$1"
  "ghcr.io":
    endpoint:
      - "https://harbor.example.com:443"
    rewrite:
      "(.*)": "ghcr/$1"
```

```
# File generated by rke2. DO NOT EDIT.

server = "https://registry-1.docker.io/v2"
capabilities = ["pull", "resolve", "push"]


[host]
[host."https://harbor.example.com:443/v2"]
  capabilities = ["pull", "resolve"]
  [host."https://harbor.example.com:443/v2".rewrite]
    "(.*)" = "docker/$1"
```
