### DISCUSSION TITLE
Network policy - deny access to ingress

### DISCUSSION THREAD

**Discussion by fritz0011** [rancher/rke2#6854] [General]
So, I have defined an ingress in namespace harbor, for  a harbor helm deployment

```
 kubectl get svc -n harbor
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
harbor-core         ClusterIP   10.43.251.132   <none>        80/TCP              51d
harbor-database     ClusterIP   10.43.222.205   <none>        5432/TCP            51d
harbor-jobservice   ClusterIP   10.43.221.235   <none>        80/TCP              51d
harbor-portal       ClusterIP   10.43.188.90    <none>        80/TCP              51d
harbor-redis        ClusterIP   10.43.183.121   <none>        6379/TCP            51d
harbor-registry     ClusterIP   10.43.213.208   <none>        5000/TCP,8080/TCP   51d
harbor-trivy        ClusterIP   10.43.28.68     <none>        8080/TCP            51d

```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-except
  namespace: harbor
spec:
  podSelector:
    matchLabels:
      component: portal 
  policyTypes:
    - Ingress
  ingress:
    # Deny traffic from the IP 2.4.3.2
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0   # Internet access (all IPs)
            except:
              - 2.4.3.2/32    # Deny only this IP
      ports:
        - protocol: TCP
          port: 443           # Allow only port 443 for the service

```

Applying define network policy and I cut access completely from EVERYWHERE, is something that  am I missing ?
