### DISCUSSION TITLE
Ingress Requests Drop Unexpectedly in RKE2 Cluster with Cilium (v1.30.6 +rke2r1)

### DISCUSSION THREAD

**Discussion by Halilmehmet** [rancher/rke2#7435] [Q&A]
### **Description of the Issue**
In an RKE2 cluster, requests to applications suddenly stop being processed by the `rke2-ingress-nginx-controller`.  

Restarting the `rke2-ingress-nginx-controller` pod temporarily resolves the issue, but it reoccurs after some time. I suspect the issue is related to Cilium. However, I cannot capture any meaningful error logs.

---

### **Steps to Reproduce**
1. Deploy an RKE2 cluster with the following configurations:
   - Cilium is enabled with `kubeProxyReplacement: true`.
   - `disable-kube-proxy: true` in the RKE2 configuration.
2. Send requests to applications through the ingress (e.g., HTTP service).
3. After some time, requests stop being processed.
4. Restarting the `rke2-ingress-nginx-controller` pod temporarily resolves the issue.

---

### **Environment Information**
- **RKE2 Version:** `v1.30.6 +rke2r1`  
- **Operating System:** Ubuntu 24.04  
- **Cluster Nodes:** 3 server, 4 agent  
- **CNI:** Cilium  

---
```
/etc/rancher/rke2/config.yaml
tls-san:
  - 10.10.10.10
token: token
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
cni:
  - cilium
disable-kube-proxy: "true"

```
```
/var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    eni:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        frontend:
          image:
            tag: "v0.12.3"
        backend:
          image:
            tag: "v0.12.3"

```

---
I would appreciate your assistance in diagnosing and resolving this issue. Thank you!  

---
