### DISCUSSION TITLE
Could not find the requested service rke2-agent: host

### DISCUSSION THREAD

**Discussion by penguinpages** [rancher/rke2#7628] [Q&A]
First off.. this repo is very helpful. Well done and well documented. This was missing from RKE for some time and is big step forward for automation of RKE2 deployments.

Design: Simple 3 vm deploy of SLES 15 and create supervisor cluster.  Then post deploy is link to Fleet and use that to deploy workload clusters.  

Simple use of SLES to deploy RKE2 cluster on vmware 8. 

```
---
rke2_cluster:
  children:
    rke2_servers:
      vars:
        ansible_user: ansible
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        rke2_manifest_config_directory: "environments/dv_eng_dash_acme_com/rke-lz1-sc/pre-deploy-manifests"
        rke2_manifest_config_post_run_directory: "environments/dv_eng_dash_acme_com/rke-lz1-sc/post-deploy-manifests"
        group_rke2_config:
          # Use Cilium as the CNI
          cni:
            - cilium
          # Cilium will replace this
          disable-kube-proxy: true
      hosts:
        rke-lz1-sc-01.dv.eng.acme.com:
        rke-lz1-sc-02.dv.eng.acme.com:
        rke-lz1-sc-03.dv.eng.acme.com:
```

Error

```
RUNNING HANDLER [rancherfederal.rke2_ansible.rke2 : Restart rke2-server] *******
changed: [rke-lz1-sc-01.dv.eng.acme.com]
RUNNING HANDLER [rancherfederal.rke2_ansible.rke2 : Restart rke2-agent] ********
fatal: [rke-lz1-sc-01.dv.eng.acme.com]: FAILED! => {"changed": false, "msg": "Could not find the requested service rke2-agent: host"}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
rke-lz1-sc-01.dv.eng.acme.com : ok=71   changed=15   unreachable=0    failed=1    skipped=48   rescued=0    ignored=3   
rke-lz1-sc-02.dv.eng.acme.com : ok=58   changed=12   unreachable=0    failed=0    skipped=49   rescued=0    ignored=3   
rke-lz1-sc-03.dv.eng.acme.com : ok=58   changed=12   unreachable=0    failed=0    skipped=49   rescued=0    ignored=3   
```

Which is odd.  This should not need to find agents and therefor.. restart them.
