### DISCUSSION TITLE
Question about Cilium in RKE2 config file

### DISCUSSION THREAD

**Discussion by JulesPichon84** [rancher/rke2#7765] [Q&A]
Hello, I would like to know how to install the cni Cilium via the config file RKE2 please. I looked for a tuto but every time, people don't install Cilium via config file but with Helm. Here is an example of my RKE2 config file:

```
write-kubeconfig-mode: "0644"
tls-san:
- 192.168.8.100
cni: cilium
node-taint:
- "CriticalAddonsOnly=true:NoExecute"
```

When I installed RKE2 with this file, a part of pods is in *pending* state because of the node taint. So can we install Cilium with a node taint on the master ? Also, does Cilium cni deploy Ingress controller ?

Thank you for your feedback !

**Comment by brandond** [comment]
RKE2 does not ship with any Taints by default, and the cilium chart does not have any Tolerations.

If you are going to add Taints to your nodes, you should add matching Tolerations to the chart values for things that you want to run on those nodes:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
```

**Reply by brandond** [reply]
> does Cilium cni deploy Ingress controller

No. RKE2 bundles ingress-nginx (default) or traefik for Ingress.

**Reply by JulesPichon84** [reply]
Hello brandond, thank you for your response. Is it normal that when I install cilium native rke2 config, the rke2 server install canal instead ?

Here is my rke2 config file:
```
write-kubeconfig-mode: "0644"
tls-san:
  - "192.168.1.20"
cni: cilium
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
```

My cilium config file:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
```
On the rke2 doc, they said that cilium automatically replace kube-proxy. Or if I don't put `kubeProxyReplacement: true` rke2 deploys kube-proxy.

Finally, in the config file, do I have to put all my IPs from my 3 masters (on `tls-san` section) and install cilium on every master's node ?
