### DISCUSSION TITLE
NGINX Ingress - Non-HTTP TCP ConfigMap Issues

### DISCUSSION THREAD

**Discussion by BradSherwin** [rancher/rke2#7992] [Q&A]
Hey all,

RKE2 Version: `v1.31.6+rke2r1`
NGINX Version: `rke2-ingress-nginx-4.12.005`

I've been having a few issues with configuring NGINX to use a custom ConfigMap.  Followed NGINX official documentation in conjunction with RKEs etc and struggling haha!

Im appending the standard rke2-ingress file with the below:

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      publishService:
        enabled: true
      service:
        enabled: true
      tcp:
        configMapNamespace: "ns"
      extraArgs:
        tcp-services-configmap: "ns/tcp-services"
```

I apply the ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ns
data:
  13511: "ns/link-clusterip-service:13511"
```

Helm controller picks up the new config and applies.  Checking the nginx-controller logs all seems well and the configmap is detected.

_I0401 12:13:27.433465       7 event.go:377] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ns", Name:"tcp-services", UID:"cb94f31b-179c-412a-ac5a-bf8bc5b1f7ae", APIVersion:"v1", ResourceVersion:"1687679", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ns/tcp-services_

But when I refresh services, 13511 hasnt been added:
```bash
kubectl get services -A
NAMESPACE          NAME                                      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
cert-manager       cert-manager                              ClusterIP      10.43.2.164     <none>          9402/TCP                     5d21h
cert-manager       cert-manager-cainjector                   ClusterIP      10.43.16.100    <none>          9402/TCP                     5d21h
cert-manager       cert-manager-webhook                      ClusterIP      10.43.136.49    <none>          443/TCP,9402/TCP             5d21h
default            kubernetes                                ClusterIP      10.43.0.1       <none>          443/TCP                      5d22h
external-secrets   external-secrets-webhook                  ClusterIP      10.43.225.82    <none>          443/TCP                      5d21h
kube-system        rke2-coredns-rke2-coredns                 ClusterIP      10.43.0.10      <none>          53/UDP,53/TCP                5d22h
kube-system        rke2-ingress-nginx-controller             LoadBalancer   10.43.59.130    10.70.125.108   80:31257/TCP,443:32647/TCP   78m
kube-system        rke2-ingress-nginx-controller-admission   ClusterIP      10.43.243.103   <none>          443/TCP                      3d18h
kube-system        rke2-metrics-server                       ClusterIP      10.43.203.226   <none>          443/TCP                      5d22h
metallb-system     metallb-webhook-service                   ClusterIP      10.43.96.253    <none>          443/TCP                      5d21h
ns                link-clusterip-service              ClusterIP      10.43.211.79    <none>          80/TCP,13511/TCP             5d21h
```

I know my micro service deployment is ok because if I reploy NGINX with the below then NGINX opens the port just fine -  

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      publishService:
        enabled: true
      service:
        enabled: true
    tcp:
      13511: "ns/link-clusterip-service:13511"
```

```bash
kubectl get services rke2-ingress-nginx-controller -n kube-system
NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                      AGE
rke2-ingress-nginx-controller   LoadBalancer   10.43.59.130   10.70.125.108   80:31257/TCP,443:32647/TCP,13511:30929/TCP   92m
```

Appreicate any help as always.

Many Thanks,

Brad
