### ISSUE TITLE
Cannot pass empty strings to helm charts via HelmChart.spec.set

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1015]
The following example will not work:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-cilium/rke2-cilium-1.9.604.tgz
  creationTimestamp: null
  name: rke2-cilium
  namespace: kube-system
spec:
  bootstrap: true
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
```

Examining the helm pod log shows that the empty string is being passed in to the helm CLI as a zero:
```console
+ helm_v3 install --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 --set global.systemDefaultRegistry=0 rke2-cilium /rke2-cilium.tgz
```

This in turn is coming from helm-controller:
```yaml
spec:
  containers:
  - args:
    - install
    - --set-string
    - global.clusterCIDR=10.42.0.0/16
    - --set-string
    - global.clusterDNS=10.43.0.10
    - --set-string
    - global.clusterDomain=cluster.local
    - --set-string
    - global.rke2DataDir=/var/lib/rancher/rke2
    - --set-string
    - global.serviceCIDR=10.43.0.0/16
    - --set
    - global.systemDefaultRegistry=0
```

This is because we are not handling IntOrString properly, although this might be a case where the correct behavior is hard to determine:
https://github.com/k3s-io/helm-controller/blob/764affdf873b9999f5503c755fbe05fa3096fbcd/pkg/helm/controller.go#L402-L408
