### ISSUE TITLE
The 'etcd-expose-metrics' setting causes the etcd livenessProbe to fail

### ISSUE THREAD

**Issue by SeanThomasWilliams** [rancher/rke2#1100]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)

Node(s) CPU architecture, OS, and Version: 
x86_64, RHEL 8.3 Linux

Cluster Configuration:
3 HA Servers, 3+ agents (autoscaling)

**Describe the bug:**

Setting `etcd-expose-metrics` to `true` causes etcd to die due to the pod `livenessProbe`

When this option is enabled, the etcd config file at `/var/lib/rancher/rke2/server/db/etcd/config` sets the line:
```listen-metrics-urls: http://HOST_IP:2381```
when off, this line is:
```listen-metrics-urls: http://127.0.0.1:2381```

This causes the etcd metrics endpoint to only bind to the HOST_IP interface, and not localhost/127.0.0.1

The etcd pod liveness probe does the following check in all cases:
```
livenessProbe:
  httpGet:
    path: /health
    port: 2381
    host: 127.0.0.1
    scheme: HTTP
  initialDelaySeconds: 15
  timeoutSeconds: 15
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 8
```

Since the probe is looking for the metric endpoint on the loopback interface, the pod gets terminated and eventually restarted. 

**Steps To Reproduce:**

- Installed RKE2
- Deployed server nodes with the `etcd-expose-metrics` configuration set to `true`
- Observe the failed etcd pod(s) 15 + 10*8 seconds after starting, when the liveness probe will terminate it

**Expected behavior:**

Etcd would bind to loopback + HOST_IP, or the livenessProbe would be changed to work against the bound HOST_IP. I couldn't find where the `livenessProbe` for etcd could be updated without live patching.

**Actual behavior:**

All etcd pods die and wait in `CrashLoopBackOff`. Cluster becomes very upset without etcd.

**Additional context / logs:**
