### ISSUE TITLE
kubectl top node: error: metrics not available yet

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#1102]
**Environmental Info:**
RKE2 Version: rke2 version v1.19.11+rke2r1 (5a38609f60e8b9e325eae087a367a96c5477b282)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: Centos 8 with selinux Linux  4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: we see this on 24 different rke2 clusters. Works on our old rke clusters. 

The metrics-server doesnt get any metrics from nodes. `kubectl top pod` works just fine but `kubectl top node` returns no data.
I tried using raw api and no data: 
```
$ kubectl get --raw /apis/metrics.k8s.io/v1beta1/nodes | jq
{
  "kind": "NodeMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/metrics.k8s.io/v1beta1/nodes"
  },
  "items": []
}

```

We have no errors in the logs from metrics-server. So i guess it can scrape `https://nodeip:10250/stats/summary?only_cpu_and_memory=true` successfully.

**Comment by brandond** [comment]
Check your apiserver logs - is it able to reach the metrics server?

**Comment by jonaz** [comment]
Yes. The pod metrics is there as well. As you can see my raw test worked ( for both pods and nodes but the nodes data is just empty )

**Comment by brandond** [comment]
Hmm, that's interesting.  I can confirm that I get a `Error from server (ServiceUnavailable): the server is currently unable to handle the request` message if the apiserver can't reach the metric-server service, so it's not that. 

We're don't make any major changes to the metrics-server deployment compared to upstream; can you post what the metrics-server pod logs DO say? Can you try increasing the metrics-server log verbosity?

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-metrics-server
  namespace: kube-system
spec:
  valuesContent: |-
    args:
      - --kubelet-preferred-address-types=InternalIP
      - --v=9
```
