### ISSUE TITLE
[release-1.20] `--cloud-provider-name=vsphere` breaks use of in-tree vsphere cloud provider

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1115]
From #1114

In https://github.com/rancher/rke2/issues/916 we chose to add some special logic that is enabled by setting `--cloud-provider-name=vsphere`, with the understanding that no-one was using the in-tree vsphere providers, in favor of the out-of-tree providers (via the helm chart).

This turned out not to be the case; we should use `--cloud-provider-name=rancher-vsphere` instead.

This will constitute a breaking change for the 1.20 release, we should release note it.

**Comment by rancher-max** [comment]
#### Validated on release-1.20 branch using commitid `1d35a0d00baa9d1bff1324171d878616809a51a6`

- Fresh install using `rancher-vsphere` works correctly as before
- Using in-tree vsphere cloud provider works using config like:
  ```
  # /etc/rancher/rke2/config.yaml
  cloud-provider-name: vsphere
  cloud-provider-config: /etc/rancher/rke2/vsphere.conf
  ```
  And vsphere.conf like:
  ```
  [Global]
  datacenters = "<redacted>"
  insecure-flag = "1" # set to 1 if the vCenter uses a self-signed cert
  user = "<redacted>"
  password = "<redacted>"
  server = "<redacted>"
  port = "443"
  
  [VirtualCenter "<redacted>"]
  user = "<redacted>"
  password = "<redacted>"
  port = "443"
  datacenters = "E<redacted>"
  
  [Workspace]
  server = "<redacted>"
  datacenter = "<redacted>"
  default-datastore = "<redacted>"
  resourcepool-path = "<redacted>"
  folder = "test"
  ```
- Am able to migrate from this in-tree to out-of-tree provider by following these steps:
  1. Install v1.20.6+rke2r1 using in tree vsphere cloud provider
  2. Stop rke2 service 
  3. Change config.yaml to:
  ```
  cloud-provider-name: rancher-vsphere
  ```
  4. Setup cpi and csi yaml file in `/var/lib/rancher/rke2/server/manifests/`, ensuring to include migration flag for csi:
  ```
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    name: rancher-vsphere-cpi
    namespace: kube-system
  spec:
    valuesContent: |-
      vCenter:
        host: "<redacted>"
        datacenters: "<redacted>"
        username: "<redacted>"
        password: "<redacted>"
        credentialsSecret:
          generate: true
  ---
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    name: rancher-vsphere-csi
    namespace: kube-system
  spec:
    valuesContent: |-
      vCenter:
        host: "<redacted>"
        datacenters: "<redacted>"
        username: "<redacted>"
        password: "<redacted>"
        clusterId: "maxrke2"
        configSecret:
          generate: true
      storageClass:
        datastoreURL: "<redacted>"
      csiMigration:
        enabled: true
  ```
