### ISSUE TITLE
Cilium SELinux AVC denials

### ISSUE THREAD

**Issue by bluikko** [rancher/rke2#1273]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
go version go1.16.4b7
```
Node(s) CPU architecture, OS, and Version: 

```
Linux host 5.13.0-1.el7.elrepo.x86_64 #1 SMP Sun Jun 27 19:45:23 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

- 3 servers
- dual-stack
- cilium
- kube-proxy-less

**Describe the bug:**

SELinux AVC denials are seen when using Cilium CNI, at least in kube-proxy-less mode: noticed when trying to turn on host-reachable services.

**Steps To Reproduce:**

- Installed RKE2: 

/var/lib/rancher/rke2/server/manifests/rke2-cilium.yml
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipv6:
      enabled: true
```
/etc/rancher/rke2/config.yaml
```yaml
bind-address: "192.0.2.1"
advertise-address: "192.0.2.1"
cluster-cidr: "10.0.0.0/10,2001:db8:1000::/48"
service-cidr: "10.128.0.0/12,2001:db8:1001::/48"
cluster-dns: "10.128.0.10"
cluster-domain: "c.domain"
node-ip: "192.0.2.1,2001:db8::1"
node-external-ip: "172.16.0.1,2001:db8:f::1"
token: "something"
tls-san:
  - "lb.domain"
  - "192.0.2.1"
  - "192.0.2.2"
  - "192.0.2.3"
  - "2001:db8::1"
  - "2001:db8::2"
  - "2001:db8::3"
cni: cilium
disable:
  - rke2-kube-proxy
```

**Expected behavior:**

SELinux should work in enforcing mode.

**Actual behavior:**

SELinux needs to be put to permissive mode or AVC denials happen.

**Additional context / logs:**

AVC denials:
```
: avc:  denied  { ioctl } for  pid=1234 comm="ip6tables" path="/sys/fs/cgroup" dev="tmpfs" ino=1 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
: avc:  denied  { ioctl } for  pid=1234 comm="iptables" path="/sys/fs/cgroup" dev="tmpfs" ino=1 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:cgroup_t:s0 tclass=dir permissive=1
: avc:  denied  { map_create } for  pid=1234 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { map_read map_write } for  pid=1234 comm="cilium-agent" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { prog_load } for  pid=1234 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
: avc:  denied  { prog_run } for  pid=1234 comm="bpftool" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=bpf permissive=1
```
