### ISSUE TITLE
Dual-stack documentation

### ISSUE THREAD

**Issue by bluikko** [rancher/rke2#1277]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)
go version go1.16.4b7
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

```
Linux host 5.13.0-1.el7.elrepo.x86_64 #1 SMP Sun Jun 27 19:45:23 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

- 3 servers
- dual-stack
- cilium
- kube-proxy-less

**Describe the bug:**

The documentation around dual-stack clusters could be improved. It takes looking at GitHub issues to find out for example what is the formatting expected to give 2 IP addresses in `config.yaml` - is it a yaml list or a string with comma-separated addresses? Both examples are listed in various GitHub issues here. Are IPv6 addresses expected to be enclosed in `[]`?

Currently I am testing with for example:
```yaml
cluster-cidr: "10.0.0.0/10,2001:db8:1000::/48"
```

**Steps To Reproduce:**

- Installed RKE2: 
- Installed RKE2: 

/var/lib/rancher/rke2/server/manifests/rke2-cilium.yml
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipv6:
      enabled: true
```
/etc/rancher/rke2/config.yaml
```yaml
bind-address: "192.0.2.1"
advertise-address: "192.0.2.1"
cluster-cidr: "10.0.0.0/10,2001:db8:1000::/48"
service-cidr: "10.128.0.0/12,2001:db8:1001::/48"
cluster-dns: "10.128.0.10"
cluster-domain: "c.domain"
node-ip: "192.0.2.1,2001:db8::1"
node-external-ip: "172.16.0.1,2001:db8:f::1"
token: "something"
tls-san:
  - "lb.domain"
  - "192.0.2.1"
  - "192.0.2.2"
  - "192.0.2.3"
  - "2001:db8::1"
  - "2001:db8::2"
  - "2001:db8::3"
cni: cilium
disable:
  - rke2-kube-proxy
```

**Expected behavior:**

More details for dual-stack installation - either examples or list the formatting of the strings.

**Actual behavior:**

Details are lacking in dual-stack documentation. Didn't get dual-stack working yet - the lack of documentation makes the work more slow.

**Additional context / logs:**

Separated from #1273 

Specific areas to improve:
- Formatting in `config.yaml` file.
- Formatting in CLI switches.
