### ISSUE TITLE
IP_AUTODETECTION_METHOD For Calico/Canal not in RKE2 charts

### ISSUE THREAD

**Issue by wilkerd1** [rancher/rke2#1353]
RKE2 Version:
rke2 v1.21.2+rke2r1

Node(s) CPU architecture, OS, and Version:
3 - RHEL 8.x Virtual Box Nodes created by Vagrant.

I have HelmChartConfig override file that seemed to start resolving the issue with Vagrant/VirtualBox and the NAT interface they create on eth0. As I commented in [https://github.com/rancher/rke2/issues/1263](url) flannel needs to be told not to grab what's on the default route.

But it appears more is needed for a vagrant/virtualbox multimaster config. It appears the Calico also needs to be told what interface to use as well. This is similar but technically different parameter. For Calico it's called IP_AUTODETECTION_METHOD that is an environment variable. It also gets set to `interface=[whatever interface is not the NAT interface]`. In my case I want to point it to eth1 just like flannel in my HelmChartConfig. Is this how this is done in RKE2? I ask this because the IP_AUTODETECTION_METHOD or anything like that is available in calico section of the Canal chart. How does this get set correctly in RKE2? My HelmChartConfig file directing flannel is below.

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
    name: rke2-canal
    namespace: kube-system
    spec:
        valuesContent: |-
            flannel:
                iface: "eth1"

Also I notice no matter what changes I make and bounce the rke2 nodes it still wants to hang on to the NAT interface:

Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Starting rke2 v1.21.2+rke2r1 (d58ad6197b05144711671cec03a9027058969bf0)"
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.709080  501675 client.go:360] parsed scheme: "endpoint"
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.713234  501675 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379  <nil> 0 <nil>>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="certificate CN=rke2,O=rke2 signed by CN=rke2-server-ca@1625690274: notBefore=2021-07-07 2>
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.722605  501675 client.go:360] parsed scheme: "passthrough"
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.722639  501675 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] >
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.722647  501675 clientconn.go:948] ClientConn switching balancer to "pick_first"
Jul 16 19:50:25 node1 rke2[501675]: I0716 19:50:25.722684  501675 clientconn.go:897] blockingPicker: the picked transport is not ready, loop back to repick
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Running kube-apiserver --advertise-address=172.28.128.24 --advertise-port=6443 --allow-pr>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Running kube-scheduler --address=127.0.0.1 --bind-address=127.0.0.1 --kubeconfig=/var/lib>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-add>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Applying network policies..."
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Node token is available at /var/lib/rancher/rke2/server/token"
**Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="To join node to cluster: rke2 agent -s https://10.0.2.15:9345 -t ${NODE_TOKEN}"**
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Wrote kubeconfig /etc/rancher/rke2/rke2.yaml"
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Run: rke2 kubectl"
**Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. >**
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Cluster-Http-Server 2021/07/16 19:50:25 http: TLS handshake error from 127.0.0.1:52398: r>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=info msg="Cluster-Http-Server 2021/07/16 19:50:25 http: TLS handshake error from 127.0.0.1:52406: r>
Jul 16 19:50:25 node1 rke2[501675]: time="2021-07-16T19:50:25Z" level=debug msg="password verified locally for node 'node1'"

For Reference: 

This blog post shows the solution. What's not clear is mechanically how to do this with RKE2.
https://www.jeffgeerling.com/blog/2019/debugging-networking-issues-multi-node-kubernetes-on-virtualbox

From the Calico Docs:
https://docs.projectcalico.org/networking/ip-autodetection

**Comment by janeczku** [comment]
@wilkerd1 This should work today using a [HelmChartConfig resource to override the default Calico configuration](https://docs.rke2.io/install/network_options/).


The resource would look like so. The possible options for `nodeAddressAutodetectionV4` are documented [here](https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.NodeAddressAutodetection).

```
# Filepath: /var/lib/rancher/rke2/server/manifests/rke2-calico-config.yml
# Ref: https://docs.rke2.io/install/network_options/
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          # FirstFound uses default interface matching parameters to select
          # an interface, performing best-effort filtering based on well-known interface names.
          # This is the default.
          firstFound: true
          # Interface enables IP auto-detection based on interfaces that match the given regex.
          interface:
          # SkipInterface enables IP auto-detection based on interfaces that do not match the given regex.
          skipInterface:
          # CanReach enables IP auto-detection based on which source address on the node is used to reach
          # the specified IP or domain.
          canReach:
          # CIDRS enables IP auto-detection based on which addresses on the nodes are within one of the provided CIDRs.
          cidrs: []
```
