### ISSUE TITLE
Add CoreDns metrics port in default default-network-dns-policy

### ISSUE THREAD

**Issue by sebastienmusso** [rancher/rke2#1383]
**Environmental Info:**
RKE2 Version: 
rke2 -v
rke2 version v1.21.2+rke2r1 (d58ad61)
go version go1.16.4b7

Node(s) CPU architecture, OS, and Version: 
Linux rke2-master1 #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 master
1 worker

**Describe the bug:**
coredns is by default bootstraped with opemetrics port enabled, but when default network dns policy is applied by rke2 on cluster bootstrap, this policy has only 53 tcp/udp port in ingress authorized.
When I deploy prometheus to scrape coredns metrics, prometheus job hang with timeout.

**Steps To Reproduce:**
Deploy any version of a kubernetes cluster and try to scrape coredns metrics.

**Expected behavior:**
scraping should return metrics page.

**Actual behavior:**
scraping hang with timeout

**Additional context / logs:**
in order to resolve this bug, port 9153 should be added in ingress field of the default-network-dns-policy.
pull request have been submitted (<https://github.com/rancher/rke2/pull/1345>)  and can be backported in all other rke2 branches easily.

**Comment by QuinnBast** [comment]
Is there a way to get this working in `v1.28.7+rke2r1`? I manually edited the network policy to apply this change but it's not permanent and I would have to manually apply it every install.

Is there some configuration for this somewhere?

**Comment by brandond** [comment]
It didn't regress, the proposed change was never merged because it is not the correct approach to fixing this.

If you're deploying something to scrape metrics, and using network policy, you should deploy a network policy that specifically allows your scraper to access metrics ports. There is no reason that the coredns metrics port should be open to anything **by default**.

Don't edit the policies that come with RKE2, deploy specific policies to cover your metrics scrape traffic.

**Comment by QuinnBast** [comment]
Thanks! I wasn't sure if adding an additional network policy would cause the two to clash. It appears that adding a second network policy works just fine.

For future souls, you can just apply this `NetworkPolicy` to allow Prometheus to scrape the coredns pods:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    np.rke2.io/dns: resolved
  name: prometheus-coredns-policy
  namespace: kube-system
spec:
  ingress:
    - ports:
        - port: 9153
          protocol: TCP
        - port: 9153
          protocol: UDP
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
    - Ingress
```
