### ISSUE TITLE
[release-1.21] Air-gapped image rewrite fails if path begins with docker.io

### ISSUE THREAD

**Issue by sigsteve** [rancher/rke2#1460]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
x86_64

Cluster Configuration:
1 server

**Describe the bug:**
For air-gapped setups using the rewrite rules in registries.yaml, the rewrite will remove docker.io from the path if it starts with docker.io.

registries.yaml:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://sm00.suselab.com:5000/v2/"
    rewrite:
      "(.*)": "docker.io/$1"  //<-- NOTE: docker.io is completely removed from the path below:
```

```console
INFO[0000] Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.21.3-rke2r1 
DEBU[0000] Registry endpoint URL modified: https://index.docker.io/v2/rancher/rke2-runtime/manifests/v1.21.3-rke2r1 => https://sm00.suselab.com:5000/v2/rancher/rke2-runtime/manifests/v1.21.3-rke2r1 
```

As a workaround, we prefix with a / and that allows the image to pull correctly.

registries.yaml:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://sm00.suselab.com:5000/v2/"
    rewrite:
      "(.*)": "/docker.io/$1"  //<-- NOTE: If we include a '/' at the beginning, it preserves the /docker.io in the path below:
```

```console
INFO[0000] Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.21.3-rke2r1 
DEBU[0000] Registry endpoint URL modified: https://index.docker.io/v2//docker.io/rancher/rke2-runtime/manifests/v1.21.3-rke2r1 => https://sm00.suselab.com:5000/v2//docker.io/rancher/rke2-runtime/manifests/v1.21.3-rke2r1 
```

**Steps To Reproduce:**
Create an endpoint in registries.yaml and add a rewrite that begins with docker.io.

**Expected behavior:**
Pull the image and preserve the path as described.

**Actual behavior:**
See above

**Additional context / logs:**
See above

**Comment by brandond** [comment]
This will need to be fixed in rancher/wharfie - I believe it has something to do with docker.io being dropped from the image name due to it being an implicit default.
https://github.com/rancher/wharfie/blob/main/pkg/registries/registries.go#L68

**Comment by rancher-max** [comment]
#### Validated using v1.21.5-rc2+rke2r1 in an airgapped environment

- Setup private registry and used registries.yaml like:
```yaml
# /etc/rancher/rke2/registries.yaml
mirrors:
  docker.io:
    endpoint:
      - https://my.reg.com
    rewrite:
      "(.*)": "docker.io/$1"
configs:
  my.reg.com:
    auth:
      username: fakeuser
      password: fakepass
    tls:
      ca_file: /home/ubuntu/ca.pem
```
- Started rke2 in debug mode and confirmed the rewrite occurred:
```
Sep 22 17:58:03 ip-172-31-25-213 rke2[5244]: time="2021-09-22T17:58:03Z" level=info msg="Pulling runtime image index.docker.io/rancher/rke2-runtime:v1.21.5-rc2-rke2r1"
Sep 22 17:58:03 ip-172-31-25-213 rke2[5244]: time="2021-09-22T17:58:03Z" level=debug msg="Registry endpoint URL modified: https://index.docker.io/v2/ => https://my.reg.com/v2/"
Sep 22 17:58:03 ip-172-31-25-213 rke2[5244]: time="2021-09-22T17:58:03Z" level=debug msg="Registry endpoint URL modified: https://index.docker.io/v2/docker.io/rancher/rke2-runtime/manifests/v1.21.5-rc2-rke2r1 => https://my.reg.com/v2/docker.io/rancher/rke2-runtime/manifests/v1.21.5-rc2-rke2r1"
```

- Also confirmed this still works with the additional prefixed slash.
- Standard airgap tests continue to pass
