### ISSUE TITLE
Agent nodes fail to upgrade

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#147]
**Description:**
After the server nodes successfully upgrade, the agent nodes fail to upgrade. The pods are stuck in Init status: `system-upgrade   pod/apply-rke2-agent-on-ip-172-31-23-212-with-875f6669ea37507-crrqc   0/1     Init:0/2    0          14m`

Logs from system-upgrade-controller pod shows:
```
$ k logs -n system-upgrade system-upgrade-controller-7ccb757cf8-hmt8p | grep -i error
E0731 21:19:27.050684       1 controller.go:135] error syncing 'system-upgrade/rke2-server': handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller system-upgrade/rke2-server: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D472c6e055857ffc04a848a084f0978b8e3c264dc: unexpected EOF, requeuing
E0731 21:19:27.159022       1 controller.go:135] error syncing 'system-upgrade/rke2-server': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/system-upgrade/plans/rke2-server/status: dial tcp 10.43.0.1:443: connect: connection refused, requeuing
```

This fails the same way whether using system-upgrade-controller directly or trying to upgrade through Rancher UI.

**Setup Information:**
Setup Configuration: 3 servers, 3 workers
RKE2 Version: alpha22, tried to upgrade to beta1
Original Install commands:
```
# Initial node:
curl -sfL https://raw.githubusercontent.com/rancher/rke2/v1.18.4-alpha22+rke2/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha22+rke2 INSTALL_RKE2_EXEC="--token secret --tls-san my.domain" sh -

# Other server nodes:
curl -sfL https://raw.githubusercontent.com/rancher/rke2/v1.18.4-alpha22+rke2/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha22+rke2 INSTALL_RKE2_EXEC="server --token secret --server https://my.domain:9345 --tls-san my.domain" sh -

# Agent nodes:
curl -sfL https://raw.githubusercontent.com/rancher/rke2/v1.18.4-alpha22+rke2/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha22+rke2 INSTALL_RKE2_EXEC="agent --token secret --server https://my.domain:9345" sh -
```

**Comment by dweomer** [comment]
@rancher-max can you share the log for the prepare container in the apply job's pod?

**Comment by rancher-max** [comment]
Logs are just looping the below:
```
$ k logs -n system-upgrade pods/apply-rke2-agent-on-ip-172-31-18-131-with-8303a4eec02a94b-dj946 -c prepare -f
+ prepare rke2-server
+ set +e
+ KUBECTL_BIN='/opt/rke2 kubectl'
+ MASTER_PLAN=rke2-server
+ '[' -z rke2-server ]
+ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
+ NAMESPACE=system-upgrade
+ true
+ /opt/rke2 kubectl get plan rke2-server -o 'jsonpath={.metadata.name}' -n system-upgrade
+ PLAN=
+ '[' -z  ]
+ info 'master plan rke2-server doesn'"'"'t exist'
+ echo '[INFO] ' 'master plan rke2-server doesn'"'"'t exist'
+ sleep 5
[INFO]  master plan rke2-server doesn't exist
+ continue
+ true
+ /opt/rke2 kubectl get plan rke2-server -o 'jsonpath={.metadata.name}' -n system-upgrade
+ PLAN=
+ '[' -z  ]
+ info 'master plan rke2-server doesn'"'"'t exist'
+ echo '[INFO] ' 'master plan rke2-server doesn'"'"'t exist'
+ sleep 5
[INFO]  master plan rke2-server doesn't exist
+ continue
+ true
+ /opt/rke2 kubectl get plan rke2-server -o 'jsonpath={.metadata.name}' -n system-upgrade
[INFO]  master plan rke2-server doesn't exist
+ PLAN=
+ '[' -z  ]
+ info 'master plan rke2-server doesn'"'"'t exist'
+ echo '[INFO] ' 'master plan rke2-server doesn'"'"'t exist'
+ sleep 5
+ continue
+ true
+ /opt/rke2 kubectl get plan rke2-server -o 'jsonpath={.metadata.name}' -n system-upgrade
+ PLAN=
+ '[' -z  ]
+ info 'master plan rke2-server doesn'"'"'t exist'
+ echo '[INFO] ' 'master plan rke2-server doesn'"'"'t exist'
+ sleep 5
[INFO]  master plan rke2-server doesn't exist
```

The plan it is mentioning is present in the `system-upgrade` namespace:
```
$ k get plans -A
NAMESPACE        NAME          AGE
system-upgrade   rke2-agent    3m41s
system-upgrade   rke2-server   3h32m
```

**Comment by dweomer** [comment]
I don't think the `rke2 kubectl` in the rancher/rke2-upgrade container is working as expected. As https://github.com/rancher/rke2-upgrade/blob/master/scripts/upgrade.sh#L54-L62 is basically a copy of the k3s-upgrade script with k3s -> rke2 maybe the underlying assumption is not valid (that being that the top level executable has a kubectl subcommand). The prepare script needs access to a `kubectl` command.

**Comment by dweomer** [comment]
IF rke2 doesn't bundle kubectl, subcommand or otherwise, we will need to modify the rke2-upgrade container to include it, e.g. https://github.com/rancher/kubectl/blob/master/Dockerfile#L6-L9

**Comment by rancher-max** [comment]
#### Validated by upgrading to beta1

- This is possible now through standalone system-upgrade-controller applications by applying the following yamls:
```yaml
# system-upgrade-controller.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-controller-env
  namespace: system-upgrade
data:
  SYSTEM_UPGRADE_CONTROLLER_DEBUG: "true"
  SYSTEM_UPGRADE_CONTROLLER_THREADS: "2"
  SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: "900"
  SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: "99"
  SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: "Always"
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: "rancher/kubectl:v1.18.3"
  SYSTEM_UPGRADE_JOB_PRIVILEGED: "true"
  SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: "900"
  SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: "15m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
spec:
  selector:
    matchLabels:
      upgrade.cattle.io/controller: system-upgrade-controller
  template:
    metadata:
      labels:
        upgrade.cattle.io/controller: system-upgrade-controller # necessary to avoid drain
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {key: "node-role.kubernetes.io/master", operator: In, values: ["true"]}
      serviceAccountName: system-upgrade
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: system-upgrade-controller
          image: rancher/system-upgrade-controller:v0.6.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: default-controller-env
          env:
            - name: SYSTEM_UPGRADE_CONTROLLER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['upgrade.cattle.io/controller']
            - name: SYSTEM_UPGRADE_CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: etc-ssl
              mountPath: /etc/ssl
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: etc-ssl
          hostPath:
            path: /etc/ssl
            type: Directory
        - name: tmp
          emptyDir: {}
```
```yaml
# plan.yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-server
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 1
  version: v1.18.4-beta1-rke2
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/rke2-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-agent
  namespace: system-upgrade
  labels:
    rke2-upgrade: agent
spec:
  concurrency: 2
  version: v1.18.4-beta1-rke2
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/rke2-upgrade
    args: ["prepare", "rke2-server"]
  drain:
    force: true
  upgrade:
    image: rancher/rke2-upgrade
```
- It is also possible through rancher by just selecting to upgrade to `beta1` of v1.18.4 rke2.
- Validated multiple setups and configurations, including drain, concurrency, upgrade when workers are powered off and powered back on, adding nodes, and ensuring workers do not upgrade until all server node upgrades are complete.
