### ISSUE TITLE
[release-1.21] kube-proxy static pod is not automatically disabled if rke2-kube-proxy HelmChart has been customized prior to upgrade

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1505]
Backport fix for **kube-proxy static pod is not automatically disabled if rke2-kube-proxy HelmChart has been customized prior to upgrade** to branch **release-1.21**:
* #1455

**Comment by rancher-max** [comment]
Validated in an upgrade from v1.21.2+rke2r1 to v1.21.3-rc4+rke2r2

- Had the initial kube-proxy daemonset customized with:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |-
    proxy:
      mode: "ipvs"
```

After upgrading, kube-proxy remained a daemonset with this configuration.

- In a scenario where I did not have the kube-proxy daemonset modified, the kube-proxy pod successfully upgraded to a static pod.
