### ISSUE TITLE
Windows workloads fail to pull image

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1557]
**Environmental Info:**
RKE2 Version: 

v1.21.3-rc3+rke2r2

Node(s) CPU architecture, OS, and Version: 

ubuntu server, windows:
```
PS C:\Users\Administrator> Get-ComputerInfo

WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 7/24/2021 6:08:30 AM
WindowsProductId                                        : 00430-00000-00000-AA230
WindowsProductName                                      : Windows Server 2019 Datacenter
WindowsRegisteredOrganization                           : Amazon.com
WindowsRegisteredOwner                                  : EC2
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 1809
```

Cluster Configuration:

1 server 1 agent

**Describe the bug:**

Workloads fail to run on windows agent. Running simply with `kubectl run winpod --image=ranchertest/testcontainer:windows`

**Steps To Reproduce:**

- Install rke2 with windows agent
- Run windows workload on agent

**Expected behavior:**

Pod should be up and running

**Actual behavior:**

Image never actually pulls. Describing the pod gives:
```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m25s  default-scheduler  Successfully assigned default/otherwin to ec2amaz-vcoi858
  Normal  Pulling    2m53s  kubelet            Pulling image "ranchertest/testcontainer:windows"
```
Waited 10m and it was always stuck in ContainerCreating state.

**Additional context / logs:**

**Comment by rancher-max** [comment]
I was using the wrong servercore image which is why this never built. Also, on a smaller box (2vcpu,4gbram,20gb disk), it took 24 minutes to build the following but actually built:

```
apiVersion: v1
kind: Deployment
metadata:
  name: iis-servercore-1809
  labels:
    app: 1809-iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1809-iis
  template:
    metadata:
      labels:
        app: 1809-iis
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: iis-servercore-1809
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        ports:
        - containerPort: 80
        env:
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_HOST
            value: "10.43.0.10"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP
            value: "tcp://10.43.0.10:53"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_ADDR
            value: "10.43.0.10"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_PORT
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_PORT
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_SERVICE_PORT_TCP_53
            value: "53"
          - name: RKE2_COREDNS_RKE2_COREDNS_PORT_53_TCP_PROTO
            value: "tcp"
---
apiVersion: v1
kind: Service
metadata:
  name: iis-servercore-1809-svc
  labels:
    app: 1809-iis
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: 1809-iis
---
```

On a larger machine it built much quicker. The ClusterIP service is working as well. NodePort services are not working but that is out of scope of this issue and is currently being debugged by the windows team. We will open a new issue when more information is determined.
