### ISSUE TITLE
Protect against starting rke2-server "by accident" on rke2-agent nodes

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#1590]
**Is your feature request related to a problem? Please describe.**
We have started rke2-server instead of rke2-agent "by accident" on a system. This i.e. caused one more etcd to be created  and this also caused a change in the cluster CIDR settings for kube-proxy, because on agents the settings for CIRD were not included in the config.yaml.

**Describe the solution you'd like**
We should have a config option "agent or server" in the config.yaml and have only one single service.
Or we should detect during server or agent start, that the "other" one has been enabled  or similar..

**Describe alternatives you've considered**
Do not make "human" mistakes ;-).

**Comment by brandond** [comment]
For the RPM packages at least, we only install the unit for one - whichever is selected during install:
https://github.com/rancher/rke2/blob/cfa99d2092e56d45c3445fa8f5ad986ae74bf413/install.sh#L25-L27. We could probably modify the tarball installer to not drop the unit for the other type.

The two units also conflict with each other, so you can't start them at the same time:
https://github.com/rancher/rke2/blob/cfa99d2092e56d45c3445fa8f5ad986ae74bf413/bundle/lib/systemd/system/rke2-agent.service#L6

**Comment by Martin-Weiss** [comment]
But "systemctl stop rke2-agent; systemctl start rke2-server" does work and has caused a big problem....

**Comment by mstrent** [comment]
Just accidentally ran "systemctl start rke2-server" on all of my agent nodes and Bad Things happened. Still working on recovering.

**Comment by mstrent** [comment]
I had to completely blow away and recreate the cluster. I didn't capture all the logs or issues or things I tried. But suffice to say, doing this is very bad and should be more actively prevented.

**Comment by mstrent** [comment]
In the mean time, I'm adding this to my Ansible deploy scripts for agent nodes:

```
# Accidentally starting rke2-server on an agent can totally b0rk the cluster.
- name: Delete rke2-server systemd unit files for safety
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/lib/systemd/system/rke2-server.env
    - /usr/local/lib/systemd/system/rke2-server.service
  register: server_service
  run_once: true

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: server_service.changed
```
