### ISSUE TITLE
Calico not processing the ipamconfig correctly

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#1617]
**Environmental Info:**
RKE2 Version: v1.21.3

**Describe the bug:**

```
+--------------------+-------+
|      PROPERTY      | VALUE |
+--------------------+-------+
| StrictAffinity     | false |
| AutoAllocateBlocks | true  |
| MaxBlocksPerHost   |     0 |
+--------------------+-------+
```
Even though we are explicitly passing the config:
```
apiVersion: crd.projectcalico.org/v1
kind: IPAMConfig
metadata:
  name: rancher-config
spec:
  autoAllocateBlocks: true
  strictAffinity: true
```

**Steps To Reproduce:**

Deploy rke2 with calico and check:

`./calicoctl ipam show --show-configuration`

**Expected behavior:**

```
./calicoctl ipam show --show-configuration
+--------------------+-------+
|      PROPERTY      | VALUE |
+--------------------+-------+
| StrictAffinity     | true  |
| AutoAllocateBlocks | true  |
| MaxBlocksPerHost   |     0 |
+--------------------+-------+
```

**Actual behavior:**

```
./calicoctl ipam show --show-configuration
+--------------------+-------+
|      PROPERTY      | VALUE |
+--------------------+-------+
| StrictAffinity     | false |
| AutoAllocateBlocks | true  |
| MaxBlocksPerHost   |     0 |
+--------------------+-------+
```
**Additional context / logs:**
