### ISSUE TITLE
Add ability to customize helm charts via CRD

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#162]
Proposing a new CRD: "helmChartConfig"

User can already supply values.yaml in the /manifests/ dir -- we need to be able to do it via the CRD and the helm-controller should pick this up and do a helm upgrade.

**Comment by brandond** [comment]
Does this need to be a CRD? Helm supports multiple `--values` flags. It would be pretty easy to pull the values from sections in an appropriately-named ConfigMap in the same namespace as the chart. 

1. Given sample HelmChart:
    ```yaml
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: traefik 
      namespace: kube-system
    spec:
      chart: stable/traefik
      set:
        rbac.enabled: "true"
        ssl.enabled: "true"
    ```
1. User provides a ConfigMap with name **traefik**-chart-values in the **kube-system** namespace:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: kube-system
      name: traefik-chart-values
    data:
      values01.yaml: |
        providers:
          kubernetesCRD:
            enabled: false
      values02.yaml: |
        additionalArguments:
          - "--providers.kubernetesingress.ingressclass=traefik-internal"
          - "--log.level=DEBUG"
    ```
1. klipper-helm will look for a \<chartname\>-chart-values ConfigMap in the same namespace as the chart.  If available, this ConfigMap will be attached to the helm Job as a Volume, and all files passed in to the helm command as `--values=</path/to/key>`

If we do add a CRD I would propose doing the same thing, but requiring the HelmValues resource to match the name of the HelmChart. The downside to using a CRD is that we can't simply mount the resource as a Volume as we can with ConfigMaps, so we will have to handle writing the content out to disk ourselves.

Potential issues:
1. Override priority. The order of precedence, from least to greatest is chart values.yaml, --values=file (in provided order ), --set=key=val. This means that any options currently being passed through from the HelmChart CRD's `set` field cannot be overridden by values from the ConfigMap or HelmValues CRD.
    I would suggest that we stop using `set` on the HelmChart CRD to override values, and instead use a `values` field that is rendered out to disk, and passed as the very first `--values=file` option. Using the example above, this would look like:
    ```yaml
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: traefik 
      namespace: kube-system
    spec:
      chart: stable/traefik
      values:
        rbac:
          enabled: true
        ssl:
          enabled: true
    ```

**Comment by davidnuzik** [comment]
cc @cjellick ^^ https://github.com/rancher/rke2/issues/162#issuecomment-670772319

**Comment by brandond** [comment]
Thinking about other things that a user might want to override - should we allow altering other things besides just chartValues -  would we want to support override namespace, repository, version, etc? At what point should we require the user just bite the bullet and disable the integrated chart?

**Comment by brandond** [comment]
Will use hybrid approach, and only allow overriding chartValues at the moment. Will create new CRD called HelmChartConfig in case we want to add additional options later.

**Comment by davidnuzik** [comment]
It's already linked but just calling it out here for posterity. This has a docs PR which is available here: https://github.com/rancher/docs/pull/2638 by my understanding this functionality shall be in k3s v1.19.0 and thus that PR will need to wait until that K3s release until we can merge.

**Comment by ShylajaDevadiga** [comment]
Works fine if rke2 is already up. But if the charts CRD is needed to be there before installation and if manifests dir exists, rke2 skips extracting charts into manifests dir. Fixed in PR #230

**Comment by ShylajaDevadiga** [comment]
Validating using master build rke2 version v1.18.4-dev+e3330898
coredns currently has label kube-dns
```
kdp rke2-coredns-rke2-coredns-7979fc655-tvzn9 |grep kube-dns
              k8s-app=kube-dns
```
Created config file in manifests dir with changes to ValuesContent to change for testing purpose
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |
    k8sApp: coredns
```
Updated label
```
kdp rke2-coredns-rke2-coredns-77b9967f7-mxpxn |grep "k8s-app"
              k8s-app=coredns
```

**Comment by ShylajaDevadiga** [comment]
Multiple values support validation.
Config file having multiple values to customize coredns as well as ingress-nginx
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |
    k8sApp: coredns
```
Updated label with coredns and registry with ingress-nginx to use private-registry
```
kdp rke2-coredns-rke2-coredns-7979fc655-tvzn9 |grep kube-dns
              k8s-app=kube-dns

kdp rke2-ingress-nginx-controller-d78b898d5-xg4sj 
...
Events:
  Type     Reason       Age        From                     Message
  ----     ------       ----       ----                     -------
  Normal   Scheduled    <unknown>  default-scheduler        Successfully assigned kube-system/rke2-ingress-nginx-controller-d78b898d5-xg4sj to ip-172-31-6-12
  Warning  FailedMount  45m        kubelet, ip-172-31-6-12  MountVolume.SetUp failed for volume "rke2-ingress-nginx-token-p6d27" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       45m        kubelet, ip-172-31-6-12  Container image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0" already present on machine
  Normal   Created      45m        kubelet, ip-172-31-6-12  Created container rke2-ingress-nginx-controller
  Normal   Started      45m        kubelet, ip-172-31-6-12  Started container rke2-ingress-nginx-controller
```
With config
```
kdp rke2-coredns-rke2-coredns-77b9967f7-mxpxn |grep "k8s-app"
              k8s-app=coredns

kdp rke2-ingress-nginx-default-backend-7d984996f9-r9x2w 
...
Events:
  Type    Reason     Age        From                     Message
  ----    ------     ----       ----                     -------
  Normal  Scheduled  <unknown>  default-scheduler        Successfully assigned kube-system/rke2-ingress-nginx-default-backend-7d984996f9-r9x2w to ip-172-31-6-12
  Normal  Pulling    94s        kubelet, ip-172-31-6-12  Pulling image "prireg.com:5000/k8s.gcr.io/defaultbackend-amd64:1.5"
  Normal  Pulled     94s        kubelet, ip-172-31-6-12  Successfully pulled image "prireg.com:5000/k8s.gcr.io/defaultbackend-amd64:1.5"
  Normal  Created    94s        kubelet, ip-172-31-6-12  Created container rke2-ingress-nginx-default-backend
  Normal  Started    93s        kubelet, ip-172-31-6-12  Started container rke2-ingress-nginx-default-backend
```

**Comment by ShylajaDevadiga** [comment]
Validated PR on k3s
k3s version v1.18.8+k3s-c4ac620b

config.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tolerations:
      - key: "key"
        operator: "Exists"
        effect: "PreferNoSchedule"
```
Added toleration the HelmChartConfig
```
 kubectl describe pod -n kube-system traefik-7465f9c544-5wxlt  |grep key
Tolerations:     key:PreferNoSchedule
```
