### ISSUE TITLE
documentation error: Example on helm integration page has incorrect format of values for image

### ISSUE THREAD

**Issue by FruityWelsh** [rancher/rke2#1636]
me basic information on the cluster configuration. For example, "3 servers, 2 agents". -->

**Describe the bug:**

Example on (helm)[https://docs.rke2.io/helm/] integration page has incorrect format of values for image  

it shows:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    image: coredns/coredns
    imageTag: v1.7.1
 ```
 when it should be:
 ```
 apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      repository: coredns/coredns
      imageTag: v1.7.1
```

Or at least that is the working model I have for my deployment.
