### ISSUE TITLE
Introduce new vsphere CPI and CSI charts

### ISSUE THREAD

**Issue by cjellick** [rancher/rke2#1724]
We are introducing new versions of the vsphere charts (version 100.0.0). These new versions can select control plane nodes for the controller workloads to run on based on the existence of either the node label "controlplane" or "control-plane".

The old version of the chart (1.0.0) assumed "controlplane" and the user had to override that in a HelmChartConfig.

Now in the new version, the user should not have to specify that.

Related rancher issue: https://github.com/rancher/rancher/issues/33875

**Comment by rancher-max** [comment]
#### Validated on v1.21.4-rc2+rke2r2

- Fresh install works correctly and does NOT require the additional chart parameters added in the helmconfigs of:
```
    csiController:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
# and 
    cloudControllerManager:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
```
- Upgrades when using the additional parameters works correctly
- Image versions in all cases are the expected values as defined in https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.0.0/values.yaml and https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.0/values.yaml:
```
# CSI Deployment: 
rancher/mirrored-k8scsi-csi-attacher:v3.1.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.2.1,rancher/mirrored-k8scsi-livenessprobe:v2.2.0,rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v2.2.1,rancher/mirrored-k8scsi-csi-provisioner:v2.1.0

# CSI Daemonset:
rancher/mirrored-k8scsi-csi-node-driver-registrar:v2.1.0,rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.2.1,rancher/mirrored-k8scsi-livenessprobe:v2.2.0

# CPI Daemonset:
rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.2.1
```
- Confirmed chart versions using 100.0.0 as expected by seeing annotations on the two charts in `/var/lib/rancher/rke2/server/manifests/...`
