### ISSUE TITLE
Cilium custom chart values aren't applied

### ISSUE THREAD

**Issue by vaisov** [rancher/rke2#1734]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.21.4+rke2r2 (d5746a33b001dcf1a24cd3256e9f1df2a43ff3dd)
go version go1.16.6b7
```

Node(s) CPU architecture, OS, and Version: 
```
Linux rancher-hetzner-prod-1 5.14.0-1.el7.elrepo.x86_64 #1 SMP Sun Aug 29 18:48:34 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 master (testing Cilium setup)

**Describe the bug:**
Cilium custom chart values aren't applied, hence Wireguard encryption doesn't work.

**Steps To Reproduce:**
```
mkdir -p /etc/rancher/rke2/
cat << EOF > /etc/rancher/rke2/config.yaml
cni:
  - cilium
disable:
  - rke2-canal
tls-san:
  - rancher.domain.com
  - 123.123.123.123
EOF

mkdir -p /var/lib/rancher/rke2/server/manifests/
cat << EOF > /var/lib/rancher/rke2/server/manifests/rke2-cilium.yml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  valuesContent: |-
    version: v1.10.3
    ipam.mode: "kubernetes"
    hubble.relay.enabled: true
    hubble.ui.enabled: true
    l7Proxy: false
    encryption.enabled: true
    encryption.type: wireguard
EOF

curl -sfL https://get.rke2.io | sh - && systemctl enable rke2-server.service && systemctl start rke2-server.service && journalctl -u rke2-server -f
```

**Expected behavior:**
Cilium configmap should have encryption features enabled and Cilium Wireguard encryption should work. But it doesn't probably because of missing features.

**Actual behavior:**
Cilium configmap is missing features and Wireguard encryption doesn't work

**Comment by brandond** [comment]
Avoid naming your custom manifest with an rke2- prefix, these are reserved for RKE2 packaged components. In this case, we ship a [rke2-cilium](https://github.com/rancher/rke2/blob/master/Dockerfile#L96) manifest that is temporarily written out to disk, and then removed if the cilium CNI is not selected by the --cni flag. This is likely overwriting your custom manifest. Also note that you don't need to specifically disable rke2-canal; all other CNIs are implicitly disabled when you use the --cni flag.

If you want to customize the packaged Cilium chart instead of replacing it, you should provide a HelmChartConfig manifest with valuesContent to customize the packaged cilium chart, as documented at https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig. If you want to instead replace the packaged cilium chart, you should specify --cni=none and provide a HelmChart with a unique name.

**Comment by vaisov** [comment]
This is what I've tried based on your feedback, but the issue still the same - the version is correct, it takes it from config, but other options are still missing:
```
mkdir -p /etc/rancher/rke2/
cat << EOF > /etc/rancher/rke2/config.yaml
cni: none
tls-san:
  - rancher.syntropystack.com
  - 167.233.13.28
EOF

mkdir -p /var/lib/rancher/rke2/server/manifests/
cat << EOF > /var/lib/rancher/rke2/server/manifests/cilium.yml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  valuesContent: |-
    cilium:
      version: v1.10.3
      ipam.mode: "kubernetes"
      hubble.relay.enabled: true
      hubble.ui.enabled: true
      l7Proxy: false
      encryption.enabled: true
      encryption.type: wireguard
EOF
```

**Comment by brandond** [comment]
You have all the chart values nested under the top-level `cilium` key, which doesn't appear to exist in the upstream chart's values.yaml: https://github.com/cilium/cilium/blob/v1.10.3/install/kubernetes/cilium/values.yaml

The version is correct just because that's the latest version; if you wanted to set a specific chart version for the Helm operation to use, that should go in the version field of the spec, not within the values text.

**Comment by vaisov** [comment]
I've also tried following, but still the issue persists:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  valuesContent: |-
    version: v1.10.3
    ipam.mode: "kubernetes"
    hubble.relay.enabled: true
    hubble.ui.enabled: true
    l7Proxy: false
    encryption.enabled: true
    encryption.type: wireguard
```

**Comment by vaisov** [comment]
Thank you for help, now it works with following. Looks like I was just templating in wrong way:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  version: v1.10.3
  valuesContent: |-
    ipam:
      mode: "kubernetes"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    l7Proxy: false
    encryption:
      enabled: true
      type: wireguard
```
