### ISSUE TITLE
"Flakey Pulls" after setting private registries

### ISSUE THREAD

**Issue by ianbuilds** [rancher/rke2#1829]
**Environmental Info:**
RKE2 Version: v1.20.6+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux server6 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers in rke2 cluster, 1 load balancer in front HA install

**Describe the bug:**
After `registries.yaml` is set, I can only pull images from my private registry and cannot pull images from public registries. If the `registries.yaml` is not set, then I can pull from public registries and not from my private registry.

**Steps To Reproduce:**
1. Install rke2 on 3 nodes (no registries.yaml set yet)
```
tls-san:
  - internal ip
  - external ip of load balancer
  - fqdn1
  - fdqn2
```
2. Install cert-manager and rancher UI (rancher signed certs)
3. Set `registries.yaml` on each node and restart `rke2-server.service` according to https://docs.rke2.io/install/containerd_registry_configuration/
```
---
mirrors:
  docker.io:
    endpoint:
      - "https://my.registry.io/"
      - "https://hub.docker.com/"
      - "https://k8s.gcr.io/"
configs:
  "my.registry.io":
    auth:
      username: un
      password: pw
    tls:
      cert_file: /path/to/cert
      key_file: /path/to/key
      ca_file: /path/to/cert
```
4. Attempt to Install any application from Cluster Explorer
5. Note: even the script from Longhorn returns the following in the pod logs:
```
Failed to pull image "busybox": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:9107b6d3e14b28b4df27e609465a58d81a5b4fb7b9dd139cd9d017ea257077b3: not found
```

**Expected behavior:**
Any Application to pull images successfully from private and public registries.

**Actual behavior:**
Pod logs return versions of the following:
```
Failed to pull image "busybox": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for shashasha: not found
```

**Additional context / logs:**
- If the `registries.yaml` is set on, say just node1, the other nodes 2 and 3 will be able to pull from public registries fine, but not private.

- Setting the `registries.yaml` seems so silo the ability to pull from registries, either private or public, but not both. I'm sure that this is just an issue of misunderstanding the docs; so any help on setting the `registries.yaml` to pull from private AND public registries would be greatly appreciated. 🙏🏻

**Comment by brandond** [comment]
registries.yaml is node-local configuration, and is not shared by the cluster. The file needs to be manually placed on each node.

Also, the configuration example you gave will configure containerd to pull images from your registry, then docker hub, then gcr.io, when you ask for an image from docker.io - which is not I think what you want.

**Comment by ianbuilds** [comment]
Understood. Yes, I've placed them on each node as well.

That makes sense, so what I got is that the _order_ of the endpoints affects the image pulls.

So, if I reverse the order to:
```
endpoint:
      - "https://hub.docker.com/"
      - "https://k8s.gcr.io/"
      - "https://my.registry.io/"
```

The public registries will always be checked first...? And so pulls from private registries will be checked against the first two endpoints (won't succeed) and then succeed at the last private endpoint?

**Comment by brandond** [comment]
No, don't do any of that - why would you want it to pull from k8s.gcr.io when you ask for an image from docker.io? Also. hub.docker.com is not the correct address for the docker.io registry, which is why you're getting weird errors about "unexpected media type text/html".

Two more nits:
* You should either use the bare scheme and protocol, or the full path to the registry v2 API - so use either `https://my-docker-mirror.example.com` or `https://my-docker-mirror.example.com/v2/`.
* You should not use the same local mirror for multiple registries, as they might both have (for example) a "busyboxy" image and it would be unclear which one you wanted to use.
* You don't need to specify the default endpoint for a registry; containerd will try that one last even if it's not listed.

I think what you want is this:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://my-docker-mirror.example.com"
mirrors:
  k8s.gcr.io:
    endpoint:
      - "https://my-k8s-mirror.example.com"
configs:
  "my-docker-mirror.example.com":
    auth:
      username: un
      password: pw
    tls:
      cert_file: /path/to/cert
      key_file: /path/to/key
      ca_file: /path/to/cert
  "my-k8s-mirror.example.com":
    auth:
      username: un
      password: pw
    tls:
      cert_file: /path/to/cert
      key_file: /path/to/key
      ca_file: /path/to/cert
```
