### ISSUE TITLE
istioctl-installer pod fails to run when default cluster psp is set to restricted option

### ISSUE THREAD

**Issue by jesseagonzalez** [rancher/rke2#1847]
**Describe the bug:**

This issue was related to the latest (1.10.4) istio helm chart deployment stalling primarily due to `isioctl-installer` job hanging in pending state. When reviewing further, the following error was found in pod description `'container has runAsNonRoot and image will run as root (pod: "istioctl-installer-9lrgx_istio-system(1e4b2b22-5bff-4718-a623-6358f09951f6)"`. 

In this particular cluster / environment, the default psp was set to leverage the `restricted` psp.

**Steps To Reproduce:**

- Deploy / Reconfigure Cluster and Enable PSP with default policy to "restricted"
- Navigate to Apps & Marketplace on Cluster Explorer and Deploy Istio
- Monitor Pod deployments and on failure run a kubectl describe against `istioctl-installer` pod

**Expected behavior:**

Expectation is that `istioctl-installer` pod is fully initialized without need to reconfigure psp restricted mode to unrestricted and completes end to end istio deployment.  Steps to reconfigure psp with unrestricted policy are documented below:

**Actual behavior:**

istioctl-installer pod sits in the following state  Steps to reconfigure psp with unrestricted policy are documented below:

```
  containerStatuses:
  - image: gitlabserver/rancher/rancher/rancher/istio-installer:1.10.4-rancher1
    imageID: ""
    lastState: {}
    name: istioctl-installer
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'container has runAsNonRoot and image will run as root (pod: "istioctl-installer-9lrgx_istio-system(1e4b2b22-5bff-4718-a623-6358f09951f6)",
          container: istioctl-installer)'
        reason: CreateContainerConfigError
```

**Additional context / logs:**

The following steps were performed to address the issue in interim.  Perhaps a documented workaround would suffice for this scenario...

Attach system-unrestricted-psp-role to default and installer:

```
kubectl  create clusterrolebinding istio-installer-system-unrestricted-psp  --clusterrole=system-unrestricted-psp-role  --serviceaccount=istio-system:istio-installer
kubectl create  clusterrolebinding istio-default-system-unrestricted-psp  --clusterrole=system-unrestricted-psp-role  --serviceaccount=istio-system:default
```

Delete installer pod so it gets new psp:

`kubectl delete po -l job-name=istioctl-installer -n istio-system`

Attach system-unrestricted-psp-role to istio-cni:

`kubectl  create clusterrolebinding istio-cni-system-unrestricted-psp  --clusterrole=system-unrestricted-psp-role  --serviceaccount=istio-system:istio-cni`

Patch daemonset to have privileged:

`kubectl  -n istio-system patch daemonset.apps/istio-cni-node -p  '{"spec":{"template":{"spec":{"containers":[{"name":"install-cni","securityContext":{"privileged":true}}]}}}}'`
