### ISSUE TITLE
HelmChart CRD Manifests .yaml file does not pass the valuesContent fields to helm_v3 install

### ISSUE THREAD

**Issue by sdiao217** [rancher/rke2#1953]
**Environmental Info:**
RKE2 Version:  
rke2 version v1.21.5+rke2r2 (9e4acdc6018ae74c36523c99af25ab861f3884da)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux ip-xxx-xx-xx-xxx.us-east-2.compute.internal 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server only

**Describe the bug:**
Before installing rancher, we were trying to use self-signed certificates. 
In REHL7, we were successfully using a HelmChart CRD manifest to pass the ingress.tls.source=secret via valuesContent.
However, in REHL8, the fields after valuesContent were not recognized by the helm_v3 install.

**Steps To Reproduce:**

-Installed RKE2: 
`curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=stable INSTALL_RKE2_VERSION=v1.21.5+rke2r2 INSTALL_RKE2_TYPE=server sh -`

```
cp -f /usr/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/60-rke2-cis.conf
systemctl restart systemd-sysctl
```

`useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U`

`systemctl enable rke2-server.service`

`systemctl start rke2-server.service`

RKE2 Config file:
```
token-file: "/var/lib/rancher/rke2/server/node-token"
write-kubeconfig-mode: "0644"
selinux: true
profile: "cis-1.6"
```

`systemctl restart rke2-server.service`

Configure nginx to be daemonset:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
```

Create namespace:
`kubectl create namespace cattle-system`

Create HelmChart resource definition:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  targetNamespace: cattle-system
  version: v2.5.8
  repo: https://releases.rancher.com/server-charts/latest
  helmVersion: v3
  set:
    hostname: "ec2-X-XXX-XX-XXX.us-east-2.compute.amazonaws.com"
  valuesContent: |-
    ingress.tls.source: secret
    privateCA: true
```
**Expected behavior:**
The Rancher server was installed and was able to access the Rancher UI.

**Actual behaviour:**
The helm-install-rancher POD enters a CrashLoopBackOff.

**Additional context / logs:**
![image](https://user-images.githubusercontent.com/92451965/137161205-675209f4-e8a0-4b5d-ad71-5329576c3f07.png)
