### ISSUE TITLE
missing affinity settings on Deploymentt rke2-coredns-rke2-coredns

### ISSUE THREAD

**Issue by andrehofman** [rancher/rke2#1955]
**Environmental Info:**
RKE2 Version:  v1.21.5+rke2r2

Node(s) CPU architecture, OS, and Version:  

```
3 x x86_64 (8 x vcpu / 8GB ram), Ubuntu 20.04 LTS
```

Cluster Configuration:

Nodes:
```
NAME          STATUS   ROLES                       AGE   VERSION
rke2-26x-01   Ready    control-plane,etcd,master   91m   v1.21.5+rke2r2
rke2-26x-02   Ready    control-plane,etcd,master   90m   v1.21.5+rke2r2
rke2-26x-03   Ready    control-plane,etcd,master   88m   v1.21.5+rke2r2
```
**Describe the bug:**

I see that the Deployment `rke2-coredns-rke2-coredns` does not have affinity settings, which makes the pods run on the same node.

**Steps To Reproduce:**

- Installed RKE2:
  - node 1
    ```
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.21.5+rke2r2 sudo sh -
    systemctl enable rke2-server
    systemctl start rke2-server
    ```
  - node 2 & 3
    ```
    mkdir /etc/rancher/rke2
    cat > /etc/rancher/rke2/config.yaml <<EOF
    server: https://{{ ipaddress }}:9345
    token: {{ nodetoken }}
    tls-san:
      - rancher.{{ tld }}
    EOF
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=v1.21.5+rke2r2 sudo sh -
    systemctl enable rke2-server
    systemctl start rke2-server
    ```
**Expected behavior:**

I expect the 2 pods to run on different nodes, helped by some affinity configuration in the Deployment.  
The content below I picked from the rancher that runs on top of this rke2 cluster and it makes it work:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rke2-coredns-rke2-coredns
  namespace: kube-system
spec:
  [...]
  template:
    [...]
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: NotIn
                values:
                - windows
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
            weight: 100
      [...]
```

**Actual behavior:**

The 2 `rk2-coredns-rke2-coredns` pods appear on the same node

**Additional context / logs:**
