### ISSUE TITLE
Ability to specify private registry for charts

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#197]
We need to be able to customize the charts so they can pull images from a specified private registry. This should follow the pattern established by rancher/charts.

To allow for a custom registry to be used, add this [helper](https://github.com/rancher/system-charts/blob/cb84791246fad83dd4bfe909fc7245ea23f69fa1/charts/rancher-monitoring/v0.1.3/templates/_helpers.tpl#L126-L132) and its [global value](https://github.com/rancher/system-charts/blob/cb84791246fad83dd4bfe909fc7245ea23f69fa1/charts/rancher-monitoring/v0.1.3/values.yaml#L386-L387). You can see this template getting called in the format above.

**Comment by ShylajaDevadiga** [comment]
Waiting on #230 for manifest dir check

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.18.4-dev+e3330898. Keeping issue open until we have a beta release 
Installation was successful using private registry.
Steps followed:
1. Configure the private registry.
2. Copy the rke2 binary to /usr/local/bin dir
2. Copy rke2-airgap.tar and rke2-runtime.tar into /var/lib/rancher/rke2/agent/images dir (only for testing with master builds)
3. Create registries.yaml
4. Run INSTALL_RKE2_SKIP_DOWNLOAD=true ./install.sh
cat /etc/rancher/rke2/registries.yaml 
```
mirrors:
  docker.io:
    endpoint:
      - "https://prireg.com:5000"
  k8s.gcr.io:
    endpoint:
      - "https://prireg.com:5000"
  quay.io:
    endpoint:
      - "https://prireg.com:5000"
  registry.prireg.com:
    endpoint:
      - "https://prireg.com:5000"
configs:
  prireg.com:5000:
    auth:
      username: admin
      password: *****
    tls:
      cert_file: /tmp/server.crt
      key_file: /tmp/server.key
```

**Comment by ShylajaDevadiga** [comment]
Validated using beta16, HelmChartConfig is used to pull images by charts
```
rke2 -v
rke2 version v1.18.4-beta16+rke2 (9c11691024ae4c812af40a4573f0323ea7537201)
```
Note: Images tar file need to be copied for the following images to be present which is part of the rke2-images.linux-amd64.tar tarball and not separately available.
```
docker.io/rancher/rke2-runtime:v1.18.4-beta16-rke2
docker.io/rancher/kubernetes:v1.18.4-beta16-rke2
docker.io/rancher/etcd:v3.4.13
docker.io/rancher/klipper-helm:v0.3.0
```
1. Configured private registry.
2. Copy the rke2 binary to /usr/local/bin dir
3. Copy rke2-images.linux-amd64.tar into /var/lib/rancher/rke2/agent/images dir 
4. Create registries.yaml with **configs** only
```
cat /etc/rancher/rke2/registries.yaml 
configs:
  prireg.com:5000:
    auth:
      username: admin
      password: admin
    tls:
      cert_file: /tmp/server.crt
      key_file: /tmp/server.key
      ca_file: /tmp/root.crt
```

5. Create helmChartConfig with below content pointing to private registry to pull images used by the charts.
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-kube-proxy
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-metrics-server
  namespace: kube-system
spec:
  valuesContent: |
    global:
      systemDefaultRegistry: prireg.com:5000
```
6. Start rke2 server
```
rke2 server
```
Pod info:
```
Normal   Pulling      4m46s  kubelet, ip-172-31-42-178  Pulling image "prireg.com:5000/rancher/flannel:v0.13.0-rancher1-rc1"
  Normal   Pulled       4m45s  kubelet, ip-172-31-42-178  Successfully pulled image "prireg.com:5000/rancher/flannel:v0.13.0-rancher1-rc1"
  Normal   Created      4m45s  kubelet, ip-172-31-42-178  Created container kube-flannel
  Normal   Started      4m45s  kubelet, ip-172-31-42-178  Started container kube-flannel
```
