### ISSUE TITLE
Ingress network policy

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#2034]
Hello,

we are using rke2 1.21.5 for two clusters. One baremetal, one hosted in openstack. The openstack cluster uses openstack octavia load balancer for ingress. The baremetal uses purelb as loadbalancer. Both clusters use the same default network policy (this is default policy from rke2):
```
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
```

The openstack cluster works as expected, traffic from the loadbalancer is sent to nginx ingress pod in kube-system. However, for baremetal cluster, the traffic is blocked unless we add this network policy:

``` 
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
  - Ingress
```

I wonder why one is ok and the other needs additional network policy. Is this expected?

I understand that traffic from loadbalancer is not a pod originating traffic so the default network policy does not let it in. But why it does in openstack cluster?
