### ISSUE TITLE
One Conformance test fails on Centos on rke2 1.22.3 rc

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#2068]
**Environmental Info:**
RKE2 Version:
v1.22.3-rc1+rke2r1

**Node(s) CPU architecture, OS, and Version:**
Centos 8.2 Hardened and non-hardened
No fails seen on SLES SP2 

**Cluster Configuration:**
3 servers 1 agent

**Describe the bug:**
Failed conformance test:
[sig-node] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [LinuxOnly] [NodeConformance] [Conformance]

**Steps To Reproduce:**
Install rke2 1.22.3 on CentOS
Run Conformance test 

**Expected behavior:**
No fails should be seen while running e2e conformance test on any supported OS

**Actual behavior:**
One test fails on rke2 1.22.3-rc1+rke2r1 on CentOS

**Additional context / logs:**
Logs attached
[e2e.log](https://github.com/rancher/rke2/files/7444721/e2e.log)

**Comment by brandond** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-host-network-pod
spec:
  hostNetwork: true
  containers:
  - image: k8s.gcr.io/e2e-test-images/agnhost:2.32
    name: busybox-1
    args:
    - pause
    volumeMounts:
    - mountPath: /etc/hosts-original
      name: host-etc-hosts
  - image: k8s.gcr.io/e2e-test-images/agnhost:2.32
    name: busybox-2
    args:
    - pause
    volumeMounts:
    - mountPath: /etc/hosts-original
      name: host-etc-hosts
  volumes:
  - name: host-etc-hosts
    hostPath:
      path: /etc/hosts
      type: FileOrCreate
```

```bash
kubectl exec -it --container busybox-1 test-host-network-pod -- cat /etc/hosts-original
kubectl exec -it --container busybox-2 test-host-network-pod -- cat /etc/hosts-original
```
