### ISSUE TITLE
When agent starts before server, kubelet.kubeconfig connects to server_url instead of 127.0.0.1

### ISSUE THREAD

**Issue by gitlawr** [rancher/rke2#2101]
**Environmental Info:**
RKE2 Version: 
v1.21.6+rke2r1

Node(s) CPU architecture, OS, and Version: 
ubuntu 20.04

**Steps To Reproduce:**

1. create the following config file on server node:
```
# $ cat /etc/rancher/rke2/config.yaml
token: my-shared-secret
tls-san:
  - 172.31.15.154
```
2. create the following config file on agent node:
```
# $cat /etc/rancher/rke2/config.yaml
server: https://172.31.15.154:9345
token: my-shared-secret
```
3. Start rke2-agent
4. Wait a minute then start rke2-server

**Result:**
Print the kubelet.kubeconfig on agent node
```
# $cat /var/lib/rancher/rke2/agent/kubelet.kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: https://172.31.15.154:6443
    certificate-authority: /var/lib/rancher/rke2/agent/server-ca.crt
  name: local
...
```

**Additional context / logs:**
I'm not sure if it is a bug, but it behaves differently from the case when we start the server node first. The agent kubelet always connects to the loopback proxy. As a consequence, if we use a server node IP to join the agent, kubelet will fail to connect apiserver when the server node is down in an HA setup.
