### ISSUE TITLE
http2: client connection lost on nginx ingress installation from 1.21.4 to > 1.21.4

### ISSUE THREAD

**Issue by sigi4** [rancher/rke2#2114]
Hi,

i'm running rke2 in v1.21.4+rke2r1 for a while and was upgrading last week to v1.21.6+something. Unfortunate the nginx ingress helm installation pod broke with the error message: 

```console
"Error: unable to build kubernetes objects from release manifest: Get "https://192.168.0.1:443/openapi/v2?timeout=32s": http2: client connection lost
+ exit"
```

I did not understand why it happened and played around, analysed it, could'nt find anything and resettetd the cluster to make sure not the upgrade broke something. The issue stayed.

I then switched to v1.21.5 and had the same issue. I was expecting the new nginx ingress helm chart (it switched from 3.x to 4.x in 1.21.6) but also no luck.

Reverting back to my version 1.21.4 and my cluster now just works again. I still haven't found the underlying issue but the change in 1.21.5 was the cilium chart and i run it with cilium.

My rke2 config is very lightweight, i only changed detalis regarding the private network setup (which i just prefer):

```yaml
#server: "https://api.foobar.io:9345"
#token: <FILLINTOKEN>
tls-san:
  - "api.foobar.io"
advertise-address: {{ node_ip }}
node-ip: {{ node_ip }}
kube-apiserver-arg:
  - kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP,LegacyHostIP
#cloud-provider-name: "external"
cni: cilium
disable:
  - rke2-canal
#  - rke2-ingress-nginx
#  - rke2-kube-proxy
cluster-cidr: 172.16.0.0/16
service-cidr: 192.168.0.0/18
cluster-dns: 192.168.0.10
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
node-label:
  - "foo=bar"
  - "something=amazing"
write-kubeconfig-mode: "0644"
```

When i had 1.21.6 running, i also run a debug pod on the kube-system namespace (same as the helm nginx install one) and tried to reach the kubernetes svc and had no issues.

I would like to avoid switching back to > 1.21.4 but i'm happy to analyse more if you could provide some hints on how i could analyse it. Or have you seen this issue before?

Are there e2e tests for cilium as well?
