### ISSUE TITLE
When running default (open) security profile, seccomp and apparmor changes are blocked

### ISSUE THREAD

**Issue by Boojapho** [rancher/rke2#2156]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.21.6+rke2r1 (b915fc986e84582458af7131fe7f4e686f2af493)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version: 
Linux pi2 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
4 servers

**Describe the bug:**
The default Pod Security Policy for wide-open access blocks pods with seccomp and/or apparmor annotations. 

**Steps To Reproduce:**
/etc/rancher/rke2/config.yaml:
```yaml
token: foo
tls-san:
  - 192.168.1.2
disable:
  - rke2-ingress-nginx
```
1. Download the following images:
   - rke2-images.linux-amd64.tar.zst
   - rke2-images.linux-amd64.txt
   - rke2.linux-amd64.tar.gz
   - sha256sum-amd64.txt
   - install script from RKE2 (save as `install-rke2.sh`
2. Run install script:  `sudo INSTALL_RKE2_ARTIFACT_PATH=$(realpath ".") sh ./install-rke2.sh`
3. Enable and start service:
   ```shell
   sudo systemctl enable rke2-server.service
   sudo systemctl start rke2-server.service
   ```
4. Join other nodes using same procedure (update config.yaml for `tls-san` and `server`
5. Wait for all nodes to be ready
6. Deploy any pod with an `annotation` of `seccomp.security.alpha.kubernetes.io/pod: runtime/default`

**Expected behavior:**
Pod would be deployed

**Actual behavior:**
Pod is denied by pod security policies that do not allow changes to seccomp.

**Additional context / logs:**
The `global-unrestricted-psp` pod security policy does not have any annotations related to `seccomp` or `apparmor`.  According to the [Kubernetes docs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp) the lack of a setting means that the default (blank in this case) cannot be changed.  

In order to open the policy up, the `global-unrestricted-psp` should have the following added:
```yaml
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
```
> I only tested the `seccomp` annotation.  I'm assuming the apparmor annotation works in the same way.

**Comment by brandond** [comment]
Are you suggesting that we should change the default?

**Comment by Boojapho** [comment]
@brandond Yes, I'm suggesting that the "open" policy should not be blocking anything by default.  Right now it blocks seccomp and apparmor profiles.

**Comment by janlauber** [comment]
For the newest version of FluxCD (v0.26.1) I had to add the following annotation to the `global-unrestricted-psp`:
```yaml
seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
```

**Comment by brandond** [comment]
@briandowns I think you did most of the work on the PSPs; does this change sound reasonable?
> In order to open the policy up, the global-unrestricted-psp should have the following added:
>
>```yaml
>metadata:
>  annotations:
>    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
>    apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
>```

**Comment by mdrahman-suse** [comment]
**Reproduced** with rke2 Release [v1.22.6+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.22.6%2Brke2r1)

- Config
```
token: foo
tls-san:
  - 192.168.1.2
disable:
  - rke2-ingress-nginx
```
- Install rke2 and start the service
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.22.6+rke2r1 sh -
...
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
...
```
- Workload to be deployed `wasmcloud.yaml`
```
# Source: wasmcloud-host/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
---
# Source: wasmcloud-host/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: washboard
      protocol: TCP
      name: washboard
    - port: 8080
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
---
# Source: wasmcloud-host/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-host
      app.kubernetes.io/instance: wasmcloud-host-1644521927
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-host
        app.kubernetes.io/instance: wasmcloud-host-1644521927
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        apparmor.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: wasmcloud-host-1644521927
      securityContext:
        {}
      containers:
        - name: wasmcloud-host
          securityContext:
            {}
          image: "wasmcloud/wasmcloud_host:0.51.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: WASMCLOUD_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_PROV_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_PROV_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_CTL_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_CTL_PORT
              value: "4222"
            - name: HOST_kubernetes
              value: "true"
          ports:
            - name: washboard
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/livez
              port: washboard
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: washboard
          resources:
            {}
        - name: nats
          securityContext:
            {}
          image: "nats:2.6-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - name: client
              containerPort: 4222
            - name: clustering
              containerPort: 6222
            - name: management
              containerPort: 8222
          resources:
            {}
```
- After deployment
```
$ kubectl apply -f wasmcloud.yaml
serviceaccount/wasmcloud-host-1644521927 created
service/wasmcloud-host-1644521927 created
Warning: spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: deprecated since v1.19; use the "seccompProfile" field instead
deployment.apps/wasmcloud-host-1644521927 created
$ kubectl get pods
No resources found in default namespace.
```

**Verified** the fix with rke2 Release 1.22 commit 508eec5cd25171955caeb35c0bd55d95be0e58c9

- Same config as before
- Install rke2 and start the service
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=508eec5cd25171955caeb35c0bd55d95be0e58c9 sh -
...
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
...
```
- Deployed the same workload `wasmcloud.yaml`
- After deployment
```
$ kubectl apply -f wasmcloud.yaml
serviceaccount/wasmcloud-host-1644521927 created
service/wasmcloud-host-1644521927 created
kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
wasmcloud-host-1644521927-64b78c8455-sgh5q   2/2     Running   0          2m36s
```

**Comment by bguzman-3pillar** [comment]
Validated using commit: 578156a9e267b5af45f7e2b886a217c27e32aef2
```
$ kubectl get node -A -o wide
NAME               STATUS   ROLES                       AGE   VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-39-243   Ready    control-plane,etcd,master   27m   v1.23.3+rke2r1   172.31.39.243   <none>        Ubuntu 20.04.3 LTS   5.11.0-1022-aws   containerd://1.5.9-k3s1
```

Config.yaml
```
$ cat /etc/rancher/rke2/config.yaml 
token: foo
tls-san:
  - 192.168.1.2
disable:
  - rke2-ingress-nginx
```

Using this annotations within this workload, should be deployed correctly:
`seccomp.security.alpha.kubernetes.io/pod: runtime/default`
`apparmor.security.alpha.kubernetes.io/pod: runtime/default`


```
# Source: wasmcloud-host/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
---
# Source: wasmcloud-host/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: washboard
      protocol: TCP
      name: washboard
    - port: 8080
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
---
# Source: wasmcloud-host/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-host
      app.kubernetes.io/instance: wasmcloud-host-1644521927
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-host
        app.kubernetes.io/instance: wasmcloud-host-1644521927
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        apparmor.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: wasmcloud-host-1644521927
      securityContext:
        {}
      containers:
        - name: wasmcloud-host
          securityContext:
            {}
          image: "wasmcloud/wasmcloud_host:0.51.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: WASMCLOUD_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_PROV_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_PROV_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_CTL_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_CTL_PORT
              value: "4222"
            - name: HOST_kubernetes
              value: "true"
          ports:
            - name: washboard
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/livez
              port: washboard
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: washboard
          resources:
            {}
        - name: nats
          securityContext:
            {}
          image: "nats:2.6-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - name: client
              containerPort: 4222
            - name: clustering
              containerPort: 6222
            - name: management
              containerPort: 8222
          resources:
            {}
```
Workload deployed correctly:
```
$ kubectl get pods 
NAME                                         READY   STATUS    RESTARTS   AGE
wasmcloud-host-1644521927-6cb8b47b59-4krzt   2/2     Running   0          24m
```
