### ISSUE TITLE
RKE2 Ignores multiple endpoint setting of private registry servers

### ISSUE THREAD

**Issue by asemen2608** [rancher/rke2#2159]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Set main and fall back mirror in **registries.yaml** 

registries.yaml 
```
Customer registries.yaml  shown below.
mirrors:
  docker.io:
    endpoint:
      - "https://repo.infra.example.com/de:5002"
  mirror.lab.example.com:
    endpoint:
      - "https://mirror.lab.example.com:5000"
      - "https://repo.lab.example.com:5000"
```

Shut down 1st mirror mirror.lab.exaple.com:5000. 
The image will not be downloaded from 2nd mirror https://repo.lab.example.com:5000

**Result:**
```
# cricti -D mirror.lab.example.com:5000/gisys/oes-httpd:2.4.46-2
Error message is:
rpc error: code = Unknown desc = failed to pull and unpack image "mirror.lab.example.com:5000" connect: no route to host
```

**Other details that may be helpful:**

The idea is to use the 2nd server as a fallback in case the first endpoint is offline. 

Based on the Rancher RKE2 documentation the setting in registries.yaml with two mirrors looks correct.
The documentation says: Each mirror must have a name and set of endpoints. When pulling an image from a registry, containerd will try these endpoint URLs one by one, and use the first working one. 

Also /var/lib/rancher/rke2/agent/etc/containerd/config.toml  shows both mirrors set.
```
[plugins.cri.registry.mirror."mirror.lab.example.com:5002"]
endpoint = [https://mirror.lab.example.com:5000", "https://repo.lab.example.com:5000"]
```

If the first set mirror is up and running, the image will be downloaded. 

**Environment information**
- Rancher version `Rancher v2.5.7`
- Installation option RKE 2 HA

**Cluster information**
- Cluster type Custom
- Machine type VM Nexus 3  (OSS Version, running outside of Kubernetes on VMs in Docker )
- Kubernetes version  v1.20.4

SF#280713

**Comment by cjellick** [comment]
@brandond to do the paperwork for traking issues

**Comment by cjellick** [comment]
needs 1.21 backport

**Comment by rancher-max** [comment]
#### Validated using v1.22.4-rc1+rke2r3

Created a mirrors file like below:
```
mirrors:
  docker.io:
    endpoint:
      - https://rancher-max.fake.registry
      - https://rancher-max.real.registry
  mirror.lab.example.com:
    endpoint:
      - https://mirror.lab.example.com:5000
      - https://rancher-max.real.registry
```
where `https://rancher-max.fake.registry` is a essentially a random url that is not a valid registry or even accessible, and `https://rancher-max.real.registry` is a valid registry that contains all necessary runtime images.

- All images, including rke2-runtime, successfully pulled and my cluster was up and running. Note that it did take some time and there was a lot of waiting (30+ minutes) for the internal containerd timeouts to be reached, but there were no issues and the cluster was running.

- Additionally, custom images I had in my registry could be pulled into the cluster as well. I deployed the following manifest, which has the image specified to use mirror.lab.example.com:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: othertest-deploy
  labels:
    app: othertest
spec:
  selector:
    matchLabels:
      app: othertest
  template:
    metadata:
      labels:
        app: othertest
    spec:
      containers:
      - name: othertest
        image: mirror.lab.example.com/maxross/mytestcontainer:unprivileged
        imagePullPolicy: Always
```
The image successfully pulled quickly:
```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  20s   default-scheduler  Successfully assigned default/othertest-deploy-2j7gz to ip-172-31-1-141
  Normal  Pulling    20s   kubelet            Pulling image "mirror.lab.example.com/maxross/mytestcontainer:unprivileged"
  Normal  Pulled     16s   kubelet            Successfully pulled image "mirror.lab.example.com/maxross/mytestcontainer:unprivileged" in 4.329534385s
  Normal  Created    15s   kubelet            Created container othertest
  Normal  Started    15s   kubelet            Started container othertest
```
