### ISSUE TITLE
Private registry documentation

### ISSUE THREAD

**Issue by alefr** [rancher/rke2#2167]
Hi,

I'm currently evaluating a move from RKE1 to RKE2 and got stuck on private registries.
After a while I got things rolling but I have a question regarding the documentation.

If I look at the documentation it couples `config` settings to mirror `endpoints`, e.g. as in: https://github.com/rancher/rke2/blob/master/docs/install/containerd_registry_configuration.md?plain=1#L110 

I didn't get this working, but when coupling the config to the mirror keys (registries) instead it started working.

So continue with the example linked above it would mean changing:
```diff
mirrors:
  docker.io:
    endpoint:
      - "http://registry.example.com:5000"
configs:
-  "registry.example.com:5000":
+  docker.io:
    auth:
      username: xxxxxx # this is the registry username
      password: xxxxxx # this is the registry password
```

This goes in line with the [linked documentation](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-endpoint) as well, which connects the mirror and config by "key", eg `gcr.io` as displayed below:
```toml
version = 2

[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://registry-1.docker.io"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["https://gcr.io"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."gcr.io".auth]
      username = "_json_key"
      password = 'paste output from jq'
```

Moving from the world of `RKE1` and `docker` to `RKE2` and `containerd` I'm trying to get a grasp on how things should be done (both RKE2 and containerd is new to me). Tying configuration to endpoints makes sense, as it looks like you can have several endpoints for one mirror.
But I didn't get that workin in my case.

Is the documentation correct? Should both cases work (config tied to endpoints, and to mirror key)?

**Comment by brandond** [comment]
Keys for `mirrors` sections are the registries themselves - docker.io, k8s.gcr.io, etc. For each registry you can override the endpoints.

Keys for the `configs` sections are endpoints - the `host:port` portion of the endpoint URL.

In the example, we are configuring containerd to use a local registry endpoint at `registry.example.com:5000` instead of pulling directly from Docker Hub, and are providing credentials to use when pulling from that registry endpoint.

**Comment by alefr** [comment]
Thank you for the reply @brandond 

I understood how the mapping was setup. I just took it as an example as I referenced the documentation, it's now what we're actually using.

So our problem was that we didn't get it working with using the `host:port` for the `configs`.
When changing to the `registry` instead, it started working.

This goes inline with the linked `containerd` documentation which also uses the registry as keys for the `config` portion.
(Although it's deprecated that's how I interpret the documentation for `mirrors`/`configs`).

But if it is supposed to work, is it something with our setup?
E.g. we specify endpoints without ports as it's not needed.

Hopefully clarifying what I mean and possible spot any errors I've extracted a part of our private registry file and included what worked and didn't work below (with sensitive data omitted ofc).

### Didn't work

`registry.yaml`:
```yaml
mirrors:
  registry.gitlab.com:
    endpoint:
      - "https://registry.gitlab.com"
configs:
  "https://registry.gitlab.com":
    auth:
      username: XXXXX
      password: YYYYY
```

Generates this in the `config.toml` file:
```toml
[plugins.cri.registry.mirrors]

[plugins.cri.registry.mirrors."registry.gitlab.com"]
  endpoint = ["https://registry.gitlab.com"]

[plugins.cri.registry.configs."https://registry.gitlab.com".auth]
  username = "XXXXX"
  password = "YYYYY"
```

### Works

`registry.yaml`:
```yaml
mirrors:
  registry.gitlab.com:
    endpoint:
      - "https://registry.gitlab.com"
configs:
  gitlab.registry.com:
    auth:
      username: XXXXX
      password: YYYYY
```

Generates this in the `config.toml` file:
```toml
[plugins.cri.registry.mirrors]

[plugins.cri.registry.mirrors."registry.gitlab.com"]
  endpoint = ["https://registry.gitlab.com"]

[plugins.cri.registry.configs."registry.gitlab.com".auth]
  username = "XXXXX"
  password = "YYYYY"
```

Which goes in line with the containerd documentation (having the same key for mirror and config).

But is there something with our setup that's inproper?

**Comment by brandond** [comment]
As I said earlier:
> Keys for the configs sections are endpoints - the host:port portion of the endpoint URL.

With the caveat that, if you're not including the port in the registry endpoint (ie, using the default http or https port), you don't need to include the port in the config section either.

>```yaml
>configs:
>  "https://registry.gitlab.com":
>    auth:
>      username: XXXXX
>      password: YYYYY
>```

You have a full URL here, which is what I said wouldn't work. It's not working. I'm not sure what the source of the confusion is?

**Comment by alefr** [comment]
I don't see a reason to take this any further so I'll close it, but just to shed some light on some of the questions (and maybe clarifying the source of confusion and my reason for writing).

> With the caveat that, if you're not including the port in the registry endpoint (ie, using the default http or https port), you don't need to include the port in the config section either.

I'm not sure if I'm interpreting you correctly, but we're not including the port in neither the endpoint or the config. I'm using the "default" in both cases and expect them to match but doesn't seem like it does, or at least it's not working for us.

> Also note that in your example configuration, you don't need to provide a mirrors section at all. Mirrors are mostly meant for configuring local mirrors for public registries such as Docker Hub. If you are explicitly pulling your images from registry.gitlab.com, then https://registry.gitlab.com/v2 will be used as the default endpoint. You're just explicitly configuring what is already the default behavior.

Ah ok, thanks, I did not know that. I thought the config was mapped to what was defined in the mirrors.

> I'm not sure what the source of the confusion is?

Well, the source of my confusion was that I expected the configuration to work. From my point of view I mapped the config to the endpoint in the mirror (even when omitting the port, by using the default). But that might have been a missinterpretation on my side.

I think the documentation can be improved upon, e.g. it mentions nothing about coupling config sections to registries (keys), only to endpoints. That information needs to be interpreted from the containerd toml. 

I didn't know that you could omit the mirror part and only use config, thanks for clarifying that. Looking at the documentation , [config](https://github.com/rancher/rke2/blob/master/docs/install/containerd_registry_configuration.md?plain=1#L42) is explained as: 
> The configs section defines the TLS and credential configuration for each mirror. For each mirror you can define `auth` and/or `tls`.

As I'm new to containerd the RKE2 private registry documentation was my first encounter with private registries for containerd, I interpeted it as you explicitly coupled config to mirrors.
But then again that might be common sense for someone more well versed in containerd than I am. 
The current mirror/config configuration is also deprecated by containerd, that might be another reason not to change anything right now (as it might change).

So I'll close this right now.
Thank you for the help.

**Comment by MrAmbiG** [comment]
```
mirrors:
  docker.io:
    endpoint:
      - "http://my-artifactory.company.com:5000"

configs:
  my-artifactory.company.com:5000:
    auth:
      username: admin # this is the registry username
      password: xxxxxxx # this is the registry password
    tls:
      insecure_skip_verify: true
```
_http: server gave HTTP response to HTTPS client_

**Comment by emoxam** [comment]
So what is the working config and in what file ?

**Comment by emoxam** [comment]
I edit /etc/rancher/rke2/registries.yaml on the node-1 VM

```
mirrors:
  "nexus.xxx.com5000":
    endpoint:
      - "https://nexus.xxx.com:5000"
configs:
  nexus.xxx.com:5000:
    auth:
      username: registry-to-k8s
      password: *******
    tls:
      insecure_skip_verify: true
```

After i reboot the node file become default - {"configs":{},"mirrors":null}

at /var/lib/rancher/rke2/agent/etc/containerd/config.toml  there is nothing new.

Am i on the right way ? And what is going on ? Where is the manual for this moment ? I need to add apps to rancher from http registry!
thanks
