### ISSUE TITLE
[release-1.21] Wrong images in `rke2-images-multus.linux-amd64.txt`

### ISSUE THREAD

**Issue by bk201** [rancher/rke2#2229]
**Environmental Info:**
RKE2 Version: `v1.21.7+rke2r1`

**Describe the bug:**

Multus images have been bumped to newer versions:
https://github.com/rancher/rke2-charts/blob/28ac3605e54d09e6e52549deffb07d3bbad34a04/packages/rke2-multus/charts/values.yaml#L1-L16
```
multus:
  image:
    repository: rancher/hardened-multus-cni
    tag: v3.7.1-build20211119

cniplugins:
  image:
    repository: rancher/hardened-cni-plugins
    tag: v0.9.1-build20211119
```

But the [published images list](https://github.com/rancher/rke2/releases/download/v1.21.7%2Brke2r1/rke2-images-multus.linux-amd64.txt) file `rke2-images-multus.linux-amd64.txt` of `v1.21.7+rke2r1` still has older ones:
```
docker.io/rancher/hardened-multus-cni:v3.7.1-build20210416
docker.io/rancher/hardened-cni-plugins:v0.9.1-build20210414
```

Harvester relies on the images list file to fetch images for air-gapped environments.
