### ISSUE TITLE
[Release 1.20] rke2 1.20.12 sets wrong network in net-conf.json of rke2-canal due to change in variable name clusterCIDR to clusterCIDRv4

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#2309]
**Environmental Info:**
RKE2 Version:  1.20.12

Node(s) CPU architecture, OS, and Version: 
x86_64 sles15

Cluster Configuration:
3 server, 3 or more agents

**Describe the bug:**
After the upgrade from 1.20.11 to 1.20.12 the settings in config.yaml for cluster cidr are not effective in canal and due to this cluster communication is broken.

We have adjusted the network settings in config.yaml this way:

cluster-cidr: "192.168.0.0/17"
service-cidr: "192.168.128.0/20"
cluster-dns: "192.168.128.10"

And with 1.20.11 the cluster-cidr is in the rke2-canal configmap 

```
  net-conf.json: |
    {
      "Network": "192.168.0.0/17",
      "Backend": {
        "Type": "vxlan"
      }
    }

```

After the upgrade to rke2 1.20.12 we can see this in the configmap:

```
  net-conf.json: |
    {
      "Network": "10.42.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }

```

This leads to wrong network config and broken communication within the cluster!

**Steps To Reproduce:**
Install rke2 1.20.11 with customized network settings, verify the canal config and then upgrade to rke2 1.20.12 and verify the canal config.

**Expected behavior:**
The canal config must not change during upgrade!

**Actual behavior:**
The canal config changes and breaks the cluster.

**Additional context / logs:**
We did some analysis and it seems that rke2 sets these helm values:

```
global:
  clusterCIDR: 192.168.0.0/17
  clusterDNS: 192.168.128.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 192.168.128.0/20
  systemDefaultRegistry: ""

```

But the helm chart does not look for clusterCIDR - instead it looks for clusterCIDRv4! 

```
  net-conf.json: |
    {
      "Network": {{ coalesce .Values.global.clusterCIDRv4 .Values.podCidr | quote }},
{{- if coalesce .Values.global.clusterCIDRv6 .Values.podCidrv6 }}
      "IPv6Network": {{ coalesce .Values.global.clusterCIDRv6 .Values.podCidrv6 | quote }},
      "EnableIPv6": true,
{{- end }}
      "Backend": {
        "Type": {{ .Values.flannel.backend | quote }}
      }
    }

```

Could it be that by accident there was a major change introduced in 1.20.12 for adding support for dual stack in this minor patch release?

**Comment by manuelbuil** [comment]
I am not sure what is going on but `global.clusterCIDR"` and `"global.clusterCIDRv4"` should give the same output: https://github.com/rancher/rke2/blob/master/pkg/bootstrap/bootstrap.go#L256-L257. So, that should not be the problem.

From what I see, the system is reacting as if `clusterCIDR=10.42.0.0/16`. Can you please show me the output of: `kubectl get nodes -o yaml | grep CIDRs -n2`

**Comment by manuelbuil** [comment]
Could it be that you are configuring `cluster-cidr: "192.168.0.0/17"` only in one server and not in the 3 HA servers? That will explain why you are suddenly seeing the default network `10.42.0.0/16`

**Comment by Martin-Weiss** [comment]
> Could it be that you are configuring `cluster-cidr: "192.168.0.0/17"` only in one server and not in the 3 HA servers?  That will explain why you are suddenly seeing the default network `10.42.0.0/16`

No - we have it identical everywhere with `cluster-cidr: "192.168.0.0/17"`

But we can see this:

```
helm -n kube-system get values rke2-canal

USER-SUPPLIED VALUES:
global:
  clusterCIDR: 192.168.0.0/17
  clusterDNS: 192.168.128.10
  clusterDomain: cluster.local
  rke2DataDir: /var/lib/rancher/rke2
  serviceCIDR: 192.168.128.0/20
  systemDefaultRegistry: ""
```

But the helm chart looks for .`Values.global.clusterCIDRv4 .Values.podCidr`

So somehow rke2 does the helm install of rke2-canal without `clusterCIDRv4`

**Comment by manuelbuil** [comment]
Found the problem. Somehow the rke2 chart we for canal in v1.19 and v1.20 (https://github.com/rancher/rke2-charts/tree/main-source/packages/rke2-canal-1.19-1.20) contains dual-stack logic and it should not. rke2 v1.20 code does not have access to `clusterCIDRv4` variable because dual-stack support started in v1.21. Give me 5 minutes to prepare a correct canal helm chart for you

**Comment by manuelbuil** [comment]
In the meanwhile, applying this config should fix the problem:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    global:
      clusterCIDRv4: "192.168.0.0/17"
```

```

**Comment by Martin-Weiss** [comment]
Already worked around this way:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    podCidr: 192.168.0.0/17
```

But - this bug seems to be a critical one as anyone who wants to address CVE-2021-25742 will have to upgrade to 1.20.12 and AFAIK this is also the only version Rancher 2.5.11 offers via its data.json. There is rke2 1.20.13 in the online version of the rancher data.json but that does not cover airgapped.

Does this issue exist in 1.20.13 and 1.20.14, too?
