### ISSUE TITLE
Update canal to latest flannel and calico images

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2370]
**Is your feature request related to a problem? Please describe.**

Calico and flannel have new versions. We should move canal to them

**Describe the solution you'd like**

Use latest versions of canal and flannel

**Describe alternatives you've considered**

None

**Additional context**

**Comment by dgiebert** [comment]
Btw this is the needed HelmChartConfig to get Wireguard to work:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      image:
        repository: rancher/hardened-flannel
        tag: v0.16.1-build20220119
      backend: "wireguard"
```

Should I write a section and add it here: https://github.com/rancher/rke2/blob/master/docs/install/network_options.md

**Comment by manuelbuil** [comment]
> Btw this is the needed HelmChartConfig to get Wireguard to work:
> 
> ```yaml
> apiVersion: helm.cattle.io/v1
> kind: HelmChartConfig
> metadata:
>   name: rke2-canal
>   namespace: kube-system
> spec:
>   valuesContent: |-
>     flannel:
>       image:
>         repository: rancher/hardened-flannel
>         tag: v0.16.1-build20220119
>       backend: "wireguard"
> ```
> 
> Should I write a section and add it here: https://github.com/rancher/rke2/blob/master/docs/install/network_options.md

That'd be nice! Under the `"Canal CNI plugin"` section. Please specify that this is a feature for v1.23 of rke2

**Comment by bguzman-3pillar** [comment]
RKE2 commit: d038f7d16353a7de031e1d64bec2a090f986cbcb
Once RKE2 is running, deploy this:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      image:
        repository: rancher/hardened-flannel
        tag: v0.16.1-build20220119
      backend: "wireguard"
```
Get the output with the latest flannel and calico images:

`$ kubectl get all -A -o wide
`
```
.
.
.
NAMESPACE     NAME                                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   CONTAINERS                      IMAGES                                                                                         SELECTOR
kube-system   daemonset.apps/rke2-canal                      1         1         1       1            1           kubernetes.io/os=linux   11m   calico-node,kube-flannel        rancher/hardened-calico:v3.21.2-build20220119,rancher/hardened-flannel:v0.16.1-build20220119   k8s-app=canal
```

`
$ kubectl describe daemonset -n kube-system rke2-canal
`
```
Image:      rancher/hardened-calico:v3.21.2-build20220119
.
.
.
Image:      rancher/hardened-flannel:v0.16.1-build20220119

```
