### ISSUE TITLE
Failed to create pod because of PSP constraints, can I disable it?

### ISSUE THREAD

**Issue by liyimeng** [rancher/rke2#2437]
**Environmental Info:**
RKE2 Version: 
1.23.2
Node(s) CPU architecture, OS, and Version: 

ubuntu 20.04

Cluster Configuration:

single vm node
**Describe the bug:**

Failed to create pod, as below: 

```
apiVersion: v1
kind: Pod
metadata:
  name: rancher-test
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: xpod
    resources:
      limits:
        cpu: "2"
        memory: 4G
      requests:
        cpu: 400m
        memory: 512M
    securityContext:
      capabilities:
        add:
        - AUDIT_WRITE
        - CHOWN
        - IPC_LOCK
        drop:
        - ALL
      seccompProfile:
         type: Unconfined
    stdin: true
    tty: true
  hostIPC: true
  nodeName: master0
  restartPolicy: OnFailure

```

Pod failed with errors 
```
Error from server (Forbidden): error when creating "pod.yaml": pods "rancher-test" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used 
pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/xpod]: Forbidden: seccomp may not be set 
spec.containers[0].securityContext.capabilities.add: Invalid value: "AUDIT_WRITE": capability may not be added 
spec.containers[0].securityContext.capabilities.add: Invalid value: "CHOWN": capability may not be added 
spec.containers[0].securityContext.capabilities.add: Invalid value: "IPC_LOCK": capability may not be added 
pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/xpod]: Forbidden: seccomp may not be set 
pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/xpod]: Forbidden: seccomp may not be set 
pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/xpod]: Forbidden: seccomp may not be set]

```

If remove 

```
      seccompProfile:
         type: Unconfined

```
Pod will be created properly.  In k3s, work for both cases.  I don't see if PSP allow to configure seccomProfile, is this a upstream bugs? Can I disable pop and use Pod Security Standards instead #2387 
  
**Steps To Reproduce:**

Kubectl apply -f <above.yaml>
**Expected behavior:**

Pod created
**Actual behavior:**

Pod failed with psp contstraints.

**Additional context / logs:**
