### ISSUE TITLE
[Release-1.21] - When running default (open) security profile, seccomp and apparmor changes are blocked

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#2444]
Backport fix for When running default (open) security profile, seccomp and apparmor changes are blocked

* #2156

**Comment by VestigeJ** [comment]
**Validated with COMMIT=07dabe6fc4f6b0c0fe936e0429b77842c842a265**

$ rke2 -v
```
rke2 version v1.21.9-dev+07dabe6f (07dabe6fc4f6b0c0fe936e0429b77842c842a265)
go version go1.16.10b7
```

$ cat /etc/rancher/rke2/config.yaml
```
token: foo
tls-san:
  - 192.168.1.4
disable:
  - rke2-ingress-nginx
```

$ watch kubectl get pods
```
Every 2.0s: kubectl get pods                                                                                                                                                   ip-172-31-30-144: Thu Feb 10 19:29:21 2022

NAME                                         READY   STATUS    RESTARTS   AGE
nginx-nodeport-deployment-54d9cb6f8c-2rxc2   1/1     Running   0          14m
nginx-nodeport-deployment-54d9cb6f8c-cdq4l   1/1     Running   0          14m
nginx-nodeport-deployment-54d9cb6f8c-czcbw   1/1     Running   0          14m
nginx-nodeport-deployment-54d9cb6f8c-xfnnp   1/1     Running   0          14m
wasmcloud-host-1644521927-5d64dbc654-vsxl7   2/2     Running   0          12m
```

---------------------------------------------------------------------------------------------
  **Verbose Configs**
---------------------------------------------------------------------------------------------

$ cat nodeport.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app-node
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-app-node
      annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
        apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-node
  name: nginx-nodeport-svc
  namespace: default
  annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
        apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30096
      name: http
  selector:
    app: nginx-app-node
```

$ cat wasmcloud.yaml 
```
# Source: wasmcloud-host/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
---
# Source: wasmcloud-host/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: washboard
      protocol: TCP
      name: washboard
    - port: 8080
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
---
# Source: wasmcloud-host/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-host
      app.kubernetes.io/instance: wasmcloud-host-1644521927
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-host
        app.kubernetes.io/instance: wasmcloud-host-1644521927
      annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
        apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
    spec:
      serviceAccountName: wasmcloud-host-1644521927
      securityContext:
        {}
      containers:
        - name: wasmcloud-host
          securityContext:
            {}
          image: "wasmcloud/wasmcloud_host:0.51.4"
          imagePullPolicy: IfNotPresent
          env: 
            - name: WASMCLOUD_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_PROV_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_PROV_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_CTL_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_CTL_PORT
              value: "4222"
            - name: HOST_kubernetes
              value: "true"
          ports:
            - name: washboard
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/livez
              port: washboard
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: washboard
          resources:
            {}
        - name: nats
          securityContext:
            {}
          image: "nats:2.6-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - name: client
              containerPort: 4222
            - name: clustering
              containerPort: 6222
            - name: management
              containerPort: 8222
          resources:
            {}
```
