### ISSUE TITLE
[Release-1.22] - When running default (open) security profile, seccomp and apparmor changes are blocked

### ISSUE THREAD

**Issue by briandowns** [rancher/rke2#2445]
Backport fix for When running default (open) security profile, seccomp and apparmor changes are blocked

* #2156

**Comment by mdrahman-suse** [comment]
**Reproduced** with rke2 Release [v1.22.6+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.22.6%2Brke2r1)

- Config
```
token: foo
tls-san:
  - 192.168.1.2
disable:
  - rke2-ingress-nginx
```
- Install rke2 and start the service
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.22.6+rke2r1 sh -
...
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
...
```
- Workload to be deployed wasmcloud.yaml
```
# Source: wasmcloud-host/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
---
# Source: wasmcloud-host/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: washboard
      protocol: TCP
      name: washboard
    - port: 8080
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
---
# Source: wasmcloud-host/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-host-1644521927
  labels:
    helm.sh/chart: wasmcloud-host-0.2.4
    app.kubernetes.io/name: wasmcloud-host
    app.kubernetes.io/instance: wasmcloud-host-1644521927
    app.kubernetes.io/version: "0.51.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-host
      app.kubernetes.io/instance: wasmcloud-host-1644521927
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wasmcloud-host
        app.kubernetes.io/instance: wasmcloud-host-1644521927
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        apparmor.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: wasmcloud-host-1644521927
      securityContext:
        {}
      containers:
        - name: wasmcloud-host
          securityContext:
            {}
          image: "wasmcloud/wasmcloud_host:0.51.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: WASMCLOUD_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_PROV_RPC_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_PROV_RPC_PORT
              value: "4222"
            - name: WASMCLOUD_CTL_HOST
              value: "127.0.0.1"
            - name: WASMCLOUD_CTL_PORT
              value: "4222"
            - name: HOST_kubernetes
              value: "true"
          ports:
            - name: washboard
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/livez
              port: washboard
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: washboard
          resources:
            {}
        - name: nats
          securityContext:
            {}
          image: "nats:2.6-alpine"
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
          ports:
            - name: client
              containerPort: 4222
            - name: clustering
              containerPort: 6222
            - name: management
              containerPort: 8222
          resources:
            {}
```
- After deployment
```
$ kubectl apply -f wasmcloud.yaml
serviceaccount/wasmcloud-host-1644521927 created
service/wasmcloud-host-1644521927 created
Warning: spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: deprecated since v1.19; use the "seccompProfile" field instead
deployment.apps/wasmcloud-host-1644521927 created
$ kubectl get pods
No resources found in default namespace.
```

**Verified** the fix with rke2 Release 1.22 commit https://github.com/rancher/rke2/commit/508eec5cd25171955caeb35c0bd55d95be0e58c9

- Same config as before
- Install rke2 and start the service
```
$ curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=508eec5cd25171955caeb35c0bd55d95be0e58c9 sh -
...
$ sudo systemctl enable rke2-server.service && sudo systemctl start rke2-server.service
...
```
- Deployed the same workload wasmcloud.yaml
- After deployment
```
$ kubectl apply -f wasmcloud.yaml
serviceaccount/wasmcloud-host-1644521927 created
service/wasmcloud-host-1644521927 created
kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
wasmcloud-host-1644521927-64b78c8455-sgh5q   2/2     Running   0          2m36s
```
