### ISSUE TITLE
Network policies with CIS-1.6 profile

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#2492]
**Environmental Info:**
RKE2 Version: 1.21.9 rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux kub-a5.priv.cerit-sc.cz 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

5 servers, 15 agents

**Describe the bug:**

if CIS-1.6 profile is enabled, network policies for kube-system name space are a bit weird.

There is default policy:
```
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
```

which I guess shoudl enable all incoming traffic or am I wrong?

If I am not wrong, it actually does not enable all ingress traffic. Traffic that originates on a different node thus passing vxlan tunel is OK and is allowed to destination pod in kube-system (e.g., rke2-nginx-ingress). However, traffic originating on the same node as destination pod (e.g., source pod and nginx are on the same physical node), is dropped. 

For nginx, the following additional policy fixes the problem:
```
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rke2-ingress-nginx
  policyTypes:
  - Ingress
```

however, the question is, why the first default network policy is not enough? Is this all bug or a feature?
