### ISSUE TITLE
How to modify v1.node resource / spec.podCIDRs to extend POD allocatable IP address space on already configured Rke2 cluster

### ISSUE THREAD

**Issue by ludurr** [rancher/rke2#2517]
Hi, first i would like to  Thank you for a such a great tools for local k8s clusters:) Thx for any tips!

**Environmental Info:**
RKE2 Version: 
   1.22 (v1.22.4+rke2r1) [linux/amd64]

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04.3 LTS        5.4.0-84-generic                      containerd://1.5.8-k3s1

Cluster Configuration:
RKE2:

sudo cat > /etc/rancher/rke2/config.yaml"
```
node-label:
  - "role=control"
tls-san:
  *.example.com
  *.example.com
  *.*.*.*
etcd-expose-metrics: true
etcd-snapshot-schedule-cron: "0*/4***"
etcd-snapshot-retention: 30
cni:
  - cilium
disable:
  - rke2-ingress-nginx
disable-cloud-controller: true
disable-kube-proxy: true
service-cidr: 10.24.0.0/16
cluster-cidr: 10.26.0.0/16
cluster-dns: 10.24.0.10
kubelet-arg:
  - "max-pods=400"
  - 
CILLIUM:
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      kubeProxyReplacement: "strict"
      k8sServiceHost: "*.*.*.*"
      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: false
        type: wireguard
      l7Proxy: false
      hubble:
        metrics:
          enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        relay:
          enabled: true
        ui:
          enabled: true
          replicas: 1
          ingress:
            enabled: true
            hosts:
              - hubble.k8s.intra
            annotations:
              cert-manager.io/cluster-issuer: ca-issuer
            tls:
            - secretName: ingress-hubble-ui-tls
              hosts:
              - hubble.k8s.intra
      prometheus:
        enabled: true
        port: 19090
```
**Describe the bug:**
Each workernode within local k8s cluster has only limited IP address space with CIDRs/24 of allocable IP addresses for POds within cillium CNI network, but we have defined IP address space with CIDRs/16 for services and pods

**Steps To Reproduce:**
install rke2 via tarball 

**Expected behavior:**
We would like to have on each configured workernode a POD's network with CIDR/16 - class B network.
**IPAM:                   IPv4: ***/**** allocated from 10.225.19.0/16,** 

**Actual behavior:**
```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.4+rke2r1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens2 158.234.171.222 (Direct Routing)]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 24 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   

`IPAM:                   IPv4: 250/254 allocated from 10.225.19.0/24,`

BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [ens2]   10.225.19.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      1251/1251 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 1055.31   Metrics: Ok
Encryption:             Disabled
Cluster health:         19/19 reachable   (2022-02-28T17:25:56Z)
```
