### ISSUE TITLE
Ingress throwing 400: "Failed to decode request body"

### ISSUE THREAD

**Issue by 0xErnie** [rancher/rke2#2572]
**Environmental Info:**
RKE2 Version: v1.23.4+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux ovh-k8s-brain-2 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers

**Describe the bug:**
After installation and having access to the api, checking that everything is fine, I tried setting up an ingress. But whatever I do, the reply is: **400 Bad Request** and the log output of the controller is:
`server.go:75] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"`

**Steps To Reproduce:**
- Start 3 VMs sharing the same subnet on Openstack, using Ubuntu 20.04 and make shure all updates are installed
- Install RKE2 via https://galaxy.ansible.com/lablabs/rke2
- the config looks like this:
```
server: https://10.250.250.159:9345
token: sometoken
cni: canal
tls-san:
  - cluster.local
  - 10.250.250.159
snapshotter: overlayfs
node-name: ovh-k8s-brain-2
```
- setup a pod, svc and ingress
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: rke2.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
```
- try to access the nginx via a port forward
```
kubectl port-forward svc/nginx-svc 8080:80
curl -k http://localhost:8080 -v
```
- try to access the nginx via ingress
`curl -k https://rke2.test.local:8443 --resolve rke2.test.local:8443:10.250.250.159 -v`

**Expected behavior:**
Both curl commands should output the same nginx default page.

**Actual behavior:**
Curl with port-forward outputs the nginx default page.

Ingress output is:
```
* Added rke2.test.local:8443:10.250.250.159 to DNS cache
* Hostname rke2.test.local was found in DNS cache
*   Trying 10.250.250.159:8443...
* Connected to rke2.test.local (10.250.250.159) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=nil2
*  start date: Mar  8 19:55:35 2022 GMT
*  expire date: Feb 12 19:55:35 2122 GMT
*  issuer: O=nil1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: rke2.test.local:8443
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Date: Wed, 09 Mar 2022 12:46:32 GMT
< Content-Length: 0
<
* Connection #0 to host rke2.test.local left intact
```

**Additional context / logs:**
output of ingress contoller:
`rke2-ingress-nginx-controller-4b748 rke2-ingress-nginx-controller E0309 12:46:32.503952       8 server.go:75] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"`

```
# kubectl describe ingress my-ingress
Name:             my-ingress
Labels:           <none>
Namespace:        default
Address:          10.250.250.102,10.250.250.159,10.250.250.244
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host             Path  Backends
  ----             ----  --------
  rke2.test.local
                   /   nginx-svc:80 (10.42.2.4:80)
Annotations:       <none>
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  Sync    11m (x2 over 11m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    11m (x2 over 11m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    11m (x2 over 11m)  nginx-ingress-controller  Scheduled for sync
```
