### ISSUE TITLE
Document usage of AWS cloud provider for v1.23+

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2589]
Users should either begin migrating to out-of-tree aws cloud provider or set CSIMigrationAWS feature-gate to false.
More testing is needed to determine the full impact, but currently if a user brings up a fresh cluster using v1.23.4+rke2r1 and sets config option `cloud-provider-name: aws`, then by default it will not deploy the EBS CSI provisioner, so the in-tree cloud provider will not provision EBS volumes. 

It is unclear currently what happens on an upgrade to v1.23; more testing will give us this information and allow us to make recommendations.

As in-tree cloud providers are being removed upstream in v1.24, now might be the time to encourage users to start migrating before even upgrading to v1.23.

**Comment by rancher-max** [comment]
It looks like enabling the feature gate works and creates the volume in AWS EBS correctly. However, when I create a pod to use that volume, it stays stuck in pending.

The only event in the pod is: `0/4 nodes are available: 4 node(s) had volume node affinity conflict.`

logs in kube-scheduler show:
```
I0311 04:10:18.717375       1 trace.go:205] Trace[123574548]: "Scheduling" namespace:default,name:hello-7bcd65fcf-z8j2s (11-Mar-2022 04:10:18.580) (total time: 122ms):
Trace[123574548]: ---"Prioritizing done" 122ms (04:10:18.703)
Trace[123574548]: [122.627117ms] [122.627117ms] END
E0311 04:25:55.651051       1 scheduler.go:487] "Error selecting node for pod" err="running PreFilter plugin \"VolumeBinding\": error getting PVC \"default/ebs-claim\": could not find v1.PersistentVolumeClaim \"default/ebs-claim\"" pod="default/mypod"
E0311 04:25:55.671083       1 factory.go:225] "Error scheduling pod; retrying" err="running PreFilter plugin \"VolumeBinding\": error getting PVC \"default/ebs-claim\": could not find v1.PersistentVolumeClaim \"default/ebs-claim\"" pod="default/mypod"
```

The pvc ebs-claim does exist in the default namespace.

The pv associated with it has the correct availability zone (matches what  both the ebs volume is and all the nodes):
```
Node Affinity:     
  Required Terms:  
    Term 0:        topology.kubernetes.io/zone in [us-east-2a]
                   topology.kubernetes.io/region in [us-east-2]
```

Tried some additional things from https://stackoverflow.com/questions/51946393/kubernetes-pod-warning-1-nodes-had-volume-node-affinity-conflict which didn’t resolve this for me.

**Comment by brandond** [comment]
Did you create the volume manually and then try to bind it with a PVC? I usually just create a PVC for the pod and let it create the volume for itself.

**Comment by rancher-max** [comment]
Nope just the PVC. Here is what I deployed:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sctest
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sctest
  resources:
    requests:
      storage: 4Gi
```

```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "mypod"
  labels:
    name: "frontendhttp"
spec:
  containers:
    -
      name: "myfrontend"
      image: openshift/hello-openshift
      ports:
        -
          containerPort: 80
          name: "http-server"
      volumeMounts:
        -
          mountPath: "/var/www/html"
          name: "pvol"
  volumes:
    -
      name: "pvol"
      persistentVolumeClaim:
        claimName: "ebs-claim"
```
