### ISSUE TITLE
Regression: Tolerations in vSphere CPI are incorrect

### ISSUE THREAD

**Issue by braunsonm** [rancher/rke2#2619]
In the new version of the vSphere CPI released which is used in RKE2 1.21.7rke2r2, the tolerations are now wrong. They were correct in 1.21.5rke2r2.

In the new version of the chart the tolerations are:
```yaml
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
          operator: Exists
        # Rancher specific change: These tolerations are added to account for RKE1 and RKE2 taints
        - key: node-role.kubernetes.io/controlplane
          effect: NoSchedule
          value: "true"
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
          value: "true"
        - key: node-role.kubernetes.io/etcd
          effect: NoSchedule
          value: "true"
```

The last two are the ones that matter on RKE2. These need to be:
```yaml
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
          operator: Exists
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute
```

In RKE2, upgrading from 1.21.5 to 1.21.7, these tolerations do **not** have labels. And additionally, the `etcd` key is a `NoExecute` effect, **not** `NoSchedule`.

These were correct in version `100.0.0` of the chart, and is now broken in version `100.1.0`.
