### ISSUE TITLE
Propagate system-default-registry to vsphere charts

### ISSUE THREAD

**Issue by ron1** [rancher/rke2#2719]
**Environmental Info:**
RKE2 Version: 1.21.8+rke2r1

Node(s) CPU architecture, OS, and Version:  centos7

Cluster Configuration: 3 servers, 6 agents

**Describe the bug:**
system-default-registry property value is not propagated to vsphere cpi/csi chart resources.

**Steps To Reproduce:**
Set system-default-registry and vsphere cloud-provider properties.

- Installed RKE2: 

**Expected behavior:**

vSphere cpi/csi chart resources applied to cluster have image names that incorporate the system-default-registry. 
**Actual behavior:**

vSphere cpi/csi chart resources applied to cluster have image names that do not incorporate the system-default-registry. 
**Additional context / logs:**

In my v1.21.8+rke2r1 cluster, the rancher-vsphere-cpi/csi pods are not honoring the RKE2 system-default-registry config.yaml property setting. I see the deployed cpi/csi HelmChart resources have property `global.systemDefaultRegistry` set.

However, it seems the actual cpi/csi helm charts are looking for property `global.cattle.systemDefaultRegistry` and not `global.systemDefaultRegistry`. The following RKE2 go bootstrap code sets `global.systemDefaultRegistry` here: https://github.com/rancher/rke2/blob/9947db5011b8e6bb3e3dbd574f077ec3096457ee/pkg/bootstrap/bootstrap.go#L265. The rancher-vsphere-cpi helm chart defines value `global.cattle.systemDefaultRegistry` here:
https://github.com/rancher/vsphere-charts/blob/3b3c63349abd6e8f4c501a9532f000a6e331d071/charts/rancher-vsphere-cpi/values.yaml#L61. Is there glue code somewhere that is supposed to map the one property value to the other? I see the rancher-harvester charts also define value global.cattle.systemDefaultRegistry.

**Comment by brandond** [comment]
There's not currently any logic to tie the two values together. We could probably either:
* Add a patch to the charts when they're pulled into rke2-charts to use `global.systemDefaultRegistry` if `global.cattle.systemDefaultRegistry` isn't set.
* Modify the code in RKE2 to inject the CLI value as `global.cattle.systemDefaultRegistry`

**Comment by phillipsj** [comment]
These are related: https://github.com/rancher/rancher/issues/36467

**Comment by rancher-max** [comment]
### Validated in all of v1.21.12-rc4+rke2r1, v1.22.9-rc4+rke2r1, and v1.23.6-rc4+rke2r1 

All contain `global.cattle.systemDefaultRegistry` in the helm chart values for all charts now, including vsphere, and that value matches what is in `global.systemDefaultRegistry`. See below taken from a cluster by: `sudo cat /var/lib/rancher/rke2/server/manifests/rancher-vsphere-csi.yaml | grep -A 9 "set:"`

```
  set:
    global.cattle.systemDefaultRegistry: <redacted.value.com>
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: <redacted.value.com>
```

Also confirmed by checking the pod logs and jobs themselves that these values are used.
