### ISSUE TITLE
[Release 1.22] Enable dual-stack config for Cilium automatically

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#2746]
Backport: https://github.com/rancher/rke2/issues/2741

**Comment by bguzman-3pillar** [comment]
Validated with commit: 1b2c0002af746bdb1db73b0935300cb745fe5645

```
$ rke2 --version
rke2 version v1.22.9-rc1+rke2r1 (1b2c0002af746bdb1db73b0935300cb745fe5645)
go version go1.16.14b7
```

Steps to verify `deploy rke2+cilium with dual-stack config (cluster-cidr and service-cidr) and pods should get two ips per interface (ipv4 + ipv6).`

Using this config.yaml
```
write-kubeconfig-mode: "0644"
token: "secrettrouble"
cluster-cidr: 10.11.0.0/16,2022:aced:42:0::/56
service-cidr: 11.12.0.0/16,2022:aced:42:1::/112
cni: cilium
node-ip:<ipv4 redacted><ipv6 redacted>
node-external-ip: <ipv4 redacted><ipv6 redacted>
```

Pods has te IPs (ipv4 and ipv6) correctly!
- Also some dual-stack validations have been completed successfully.
- Using only IPv4 `There are no changes when only using ipv4`, correctly

config.yaml

```
write-kubeconfig-mode: "0644"
token: "secrettrouble"
cni: cilium
```

- Upgrading scenario:

Using an older version `v1.22.8+rke2r1`

config file:
```
write-kubeconfig-mode: "0644"
token: "secrettrouble"
cluster-cidr: 10.11.0.0/16,2022:aced:42:0::/56
service-cidr: 11.12.0.0/16,2022:aced:42:1::/112
cni: cilium
node-ip: <internal ip>,<ipv6>
node-external-ip: <internal ip>,<ipv6>
```

helmChart
```
# Located at /var/lib/rancher/rke2/server/manifests/cilium-values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    ipv6:
      enabled: true
```

- Deployed ipv4 and ipv6 services using `kubectl apply -f https://gist.githubusercontent.com/aojea/90768935ab71cb31950b6a13078a7e92/raw/99ceac308f2b2658c7313198a39fbe24b155ae68/dual-stack.yaml` and saw success from both the ipv6 and ipv4 endpoints
- Upgrading using commit 1b2c0002af746bdb1db73b0935300cb745fe5645
- The already deployed services continued working
- Everything worked correctly!
