### ISSUE TITLE
Flannel wireguard interfaces are not removed

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#2960]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

Use wireguard with Canal
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      backend: "wireguard"
```

**Describe the bug:**

In case wireguard is used on flannel with canal `flannel-wg` and `flannel-wg-v6` interfaces are not deleted by the killall script

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
