### ISSUE TITLE
Cloud Provider not working.

### ISSUE THREAD

**Issue by mrjson79** [rancher/rke2#2965]
**Environmental Info:**
RKE2 Version: 

V1.22.7-rke2r2

Node(s) CPU architecture, OS, and Version: 

```
Linux k8s-sandbox-sc-mr-cloud-control-plane-dc04-7852da59-jbpxc 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 Node - with Control Plan, Etcd and Worker.

**Describe the bug:**

We are provisioning the cluster with terraform. And we want yo use the Openstack Cloud provider. So we have set "disable-cloud-controlller=true"  and "cloud-provider-name="external"" in the machine_selector_config. With that we see that the node gets created and the cluster node comes up in Openstack. But no workload is scheduled on the node - and thats expected due to the node getting a taint when setting the initialisation to be handled externally. But cluster core components like coreDNS ans Cattle-cluster-agent are stuck in Pending mode.

**Steps To Reproduce:**

- Installed RKE2 with terraform
- deploys the following helm Chart:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openstack-cloud-controller-manager
  namespace: kube-system
spec:
  chart: openstack-cloud-controller-manager
  repo: https://kubernetes.github.io/cloud-provider-openstack
  targetNamespace: kube-system
  bootstrap: True
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  valuesContent: |-
    cloudConfig:
      global:
        auth-url: our-auth-url:5000/v3
        tenant-id: our-tenant-id
        username: our-user
        password: super-secret-password
        domain-name: default
        region: our-region
```

**Expected behavior:**

Cluster comes up and reports back to rancher with all "Core" components working.

**Actual behavior:**

Core components stuck in pending due to the fact of the cloud provider stated above.

**Additional context / logs:**
