### ISSUE TITLE
Calico chart overrides ipPools value

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#2977]
**Environmental Info:**
RKE2 Version: 

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

When the following manifest is configured at node startup
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 2001:cafe:42::/56      
          blockSize: 122
```

**Describe the bug:**

The ipPools value is different then the configured one
```
kubectl get installation -o yaml
apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Installation
  metadata:
    annotations:
      meta.helm.sh/release-name: rke2-calico
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2022-05-23T18:04:53Z"
    finalizers:
    - tigera.io/operator-cleanup
    generation: 3
    labels:
      app.kubernetes.io/managed-by: Helm
    name: default
    resourceVersion: "7562"
    uid: 0e101a4a-d29b-447b-a13f-6612fb89733f
  spec:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 122
        cidr: 2001:cafe:42::/56
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV6:
        firstFound: true
```

**Steps To Reproduce:**

- Copy the config on `/var/lib/rancher/rke2/server/manifests/`
- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**

The ipPool value should be the one configured

**Additional context / logs:**

**Comment by rancher-max** [comment]
#### Still not working using master branch commit `139c31c8b75d96e1ec60be65a4b334ef456de30d`

I see the helm chart updated
```
NAME               	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rke2-calico        	kube-system	1       	2022-05-24 20:11:36.078154931 +0000 UTC	deployed	rke2-calico-v3.23.103                       	v3.23.1 
```

**However, it does not look like this is working correctly and it still isn't accepting the values:**
```
$ k get installation -o yaml
...
spec:
    calicoNetwork:
      bgp: Disabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 26
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        firstFound: true
...
```

```
$ cat /var/lib/rancher/rke2/server/manifests/values.yaml 
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 2001:cafe:42::/56      
          blockSize: 122
```

**Comment by rbrtbnfgl** [comment]
Is this a new deployment or are you updating an older one?
The configuration of the cluster should be also the same of the ipPools, if on the manifest you have one IPv6 the configuration should have the same addresss configured as CIDR.

**Comment by rancher-max** [comment]
This is a completely fresh VM.

I also tried with:
```
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          blockSize: 122
```

with a simple config.yaml like:
```
cni: calico
write-kubeconfig-mode: 644
```

Would this be a valid configuration? Result from this is also not taking the ipPools (or bgp Enabled part of calicoNetwork):
```
calicoNetwork:
      bgp: Disabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 26
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
```
