### ISSUE TITLE
[Release 1.23] Calico chart overrides ipPools value

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#2978]
Backport for  #2977

**Comment by VestigeJ** [comment]
**Validated with COMMIT=a0e81e4a88665d55d4433773e3e9513ef0196d50**


$ rke2 -v
```
rke2 version v1.23.6-dev+a0e81e4a (a0e81e4a88665d55d4433773e3e9513ef0196d50)
go version go1.17.5b7
```

$ kg installation -o yaml
```
----
  spec:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 122
        cidr: 2022:cafe:42::/56
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV6:
        firstFound: true
    cni:
      ipam:
        type: Calico
      type: Calico
----
```

$ sudo cat /var/lib/rancher/rke2/server/manifests/charts.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 2022:cafe:42::/56      
          blockSize: 122
```
