### ISSUE TITLE
Tunnel server egress proxy rejecting connection to <pod IP>:<port>

### ISSUE THREAD

**Issue by bootc** [rancher/rke2#3016]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.24.1+rke2r1 (29d227c5a5352a94b14e54ae58667ac48b07df15)
go version go1.18.1b7
```

Node(s) CPU architecture, OS, and Version: 
Debian bookworm (testing)
```
Linux hudson 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64 GNU/Linux
```

Cluster Configuration:
2 servers in the cluster

**Describe the bug:**
Following the upgrade from v1.23.6+rke2r2 to v1.24.1+rke2r1 my v1beta1.metrics.k8s.io and v3.projectcalico.org APIServices are unavailable ("FailedDiscoveryCheck") despite the pods being healthy and the services being accessible from either node.

The status message is:
```
failing or missing response from https://10.44.207.181:8443/apis/metrics.k8s.io/v1beta1: Get "https://10.44.207.181:8443/apis/metrics.k8s.io/v1beta1": proxy error from 127.0.0.1:9345 while dialing 10.44.207.181:8443, code 500: 500 Internal Server Error
```

When running `rke2 server` with debugging enabled I see messages like the following:

```
Jun 05 09:36:58 hudson rke2[509519]: time="2022-06-05T09:36:58+01:00" level=debug msg="Tunnel server handing HTTP/1.1 CONNECT request for //10.44.207.181:8443 from 127.0.0.1:36616"
Jun 05 09:36:58 hudson rke2[509519]: time="2022-06-05T09:36:58+01:00" level=debug msg="Tunnel server egress proxy rejecting connection to 10.44.207.181:8443"
```

**Steps To Reproduce:**
Uncertain. For me this coincided with the upgrade from v1.23.6+rke2r2 to v1.24.1+rke2r1.

**Expected behavior:**
The APIServices should continue to work, and the proxy should presumably allow these connections.

**Actual behavior:**
As above.

**Additional context / logs:**
My `config.yaml` is:
```yaml
server: https://<SNIP>:9345
token: <SNIP>
tls-san:
  - <SNIP>

debug: true

node-ip: 10.0.96.41,<SNIP IPv6>
cluster-cidr: 10.44.0.0/16,<SNIP IPv6>/56
service-cidr: 10.45.0.0/16,<SNIP IPv6>/112

write-kubeconfig-mode: "0440"

kube-apiserver-arg:
  - default-not-ready-toleration-seconds=30
  - default-unreachable-toleration-seconds=30

kube-controller-manager-arg:
  - bind-address=0.0.0.0
  - node-monitor-grace-period=16s
  - node-monitor-period=2s
  - pod-eviction-timeout=30s

kube-scheduler-arg:
  - bind-address=0.0.0.0

kubelet-arg:
  - node-status-update-frequency=4s
  - kube-reserved=cpu=250m,memory=4096Mi,ephemeral-storage=1Gi
  - system-reserved=cpu=250m,memory=4096Mi,ephemeral-storage=1Gi

kube-proxy-arg:
  - metrics-bind-address=0.0.0.0:10249
  - proxy-mode=ipvs

kube-proxy-extra-mount:
  - /lib/modules:/lib/modules:ro

disable:
  - rke2-canal
  - rke2-ingress-nginx

protect-kernel-defaults: true
secrets-encryption: true

etcd-expose-metrics: true
```

**Comment by bootc** [comment]
In case anyone else runs into this, the fix is to add `egress-selector-mode: disabled` to your configuration. This restores the behaviour prior to v1.24.1+rke2r1 and v1.23.7+rke2r1 and makes kube-apiserver connect directly to pods on other nodes rather than attempting to proxy via rke2, which clearly isn't up to the job (in some situations at least).

The culprit appears to be https://github.com/k3s-io/k3s/commit/615020eed9afa120efdace526ca3ba292f254f6b (a cherry pick of https://github.com/k3s-io/k3s/commit/9d7230496d131fe47485ce02b5697c57e1068a29). It configures the default `egress-selector-mode` to `pod`, which is the breaking change in behaviour that causes my issue.

**Comment by brandond** [comment]
Currently tracking this in https://github.com/k3s-io/k3s/issues/5637

**Comment by bootc** [comment]
> Currently tracking this in https://github.com/k3s-io/k3s/issues/5637

That issue is related but not the same. In my case the affected pods are not hostNetwork pods, they have IPs in the pod network and are easily reachable. In this case the proxy just actively refuses to forward the connection.

**Comment by brandond** [comment]
Hmm, it appears that you're not using the packaged default CNI, but instead of setting `cni: none`, you have left `cni: canal` and set `disable: rke2-canal`. That's not the expected way to disable the packaged CNIs, but it would certainly work, but it's not handled by the code that was intended to disable the egress selector when the packaged CNIs are not in use.

**Comment by brandond** [comment]
Canal doesn't use the node's assigned PodCIDR for pod addresses, it uses its own IPAM and ignores the ranges assigned by the Kubernetes IPAM. That's the root cause of the errors. The fix I'm adding switches to watching pods assigned to the node and authorizing their actual assigned pod IPs, instead of assuming that all pods on the node will use the node's assigned CIDR block.

**Comment by VestigeJ** [comment]
##Environment Details
 
*Infrastructure*
- [x] Cloud
- [ ] Hosted 

*Node(s) CPU architecture, OS, and Version:*

Linux 5.4.0-1009-aws x86_64 GNU/Linux-Ubuntu 20.04 LTS

 ```
*Cluster Configuration:*

NAME               STATUS   ROLES                       AGE     VERSION
ip-3-2-2-1   Ready    <none>                      7m13s   v1.24.1+rke2r1
ip-3-2-2-5   Ready    control-plane,etcd,master   8m31s   v1.24.1+rke2r1 
```

*Config.yaml:* (server)
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
node-external-ip: 3.2.2.5
disable: rke2-canal
cni: canal
```
## Replication Steps
``` 
$  VERSION=v1.23.6+rke2r2
$  sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh 
$  sudo systemctl enable rke2-server --now
$  vim values.yaml
$  kubectl create namespace tigera-operator
$  get.helm (downloads and installs helm)
$  helm repo add projectcalico https://projectcalico.docs.tigera.io/charts
$  kubectl create namespace tigera-operator
$  helm install calico projectcalico/tigera-operator --version v3.23.2 -f values.yaml --namespace tigera-operator
$  kubectl get nodes
$  kubectl top node
$  kubectl top pods -A
$  VERSION=v1.24.1+rke2r1
$  sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh 
$  sudo systemctl restart rke2-server
$  kubectl get nodes
$  journalctl -eu rke2-server | grep -i -e "egress proxy mode"
```
**Results:**
$ k top nodes
```
NAME               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-3-2-2-1   62m          3%     1284Mi          32%       
ip-3-2-2-5   158m         7%     1980Mi          50% 
```
$ kubectl top pods -A
```
NAMESPACE       NAME                                                    CPU(cores)   MEMORY(bytes)   
calico-system   calico-kube-controllers-769b49cc7-7j4p8                 4m           14Mi            
calico-system   calico-node-6654t                                       17m          81Mi            
calico-system   calico-typha-5b964bcd55-82f8w                           3m           18Mi            
kube-system     kube-proxy-ip-3-2-2-5                             16m          13Mi            
kube-system     kube-scheduler-ip-3-2-2-5                         74m          12Mi            
kube-system     rke2-coredns-rke2-coredns-547d5499cb-ppnsw              2m           12Mi            
kube-system     rke2-coredns-rke2-coredns-autoscaler-65c9bb465d-d4rh8   1m           6Mi             
kube-system     rke2-ingress-nginx-controller-lk4qh                     2m           67Mi            
```

$ journalctl -eu rke2-server | grep -i -e "egress proxy mode"
```
Jun 28 23:42:07 ip-3-2-2-5 rke2[14566]: time="2022-06-28T23:42:07Z" level=info msg="Tunnel server egress proxy mode: pod"
```

-------------------------------------------------------------------------------------------
**Validated by upgrading from VERSION=v1.23.6+rke2r2 --> VERSION=v1.23.8-rc1+rke2r1**

$ kgn
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-3-2-2-1   Ready    <none>                      25m   v1.23.8+rke2r1
ip-3-2-2-5   Ready    control-plane,etcd,master   26m   v1.23.8+rke2r1
```

$ k top nodes
```
NAME               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-3-2-2-1   816m         40%    1440Mi          36%       
ip-3-2-2-5   837m         41%    1930Mi          49% 
 ```
$ k top pods -A
```
NAMESPACE         NAME                                                    CPU(cores)   MEMORY(bytes)   
calico-system     calico-kube-controllers-769b49cc7-7j4p8                 4m           16Mi            
calico-system     calico-node-6654t                                       20m          80Mi            
calico-system     calico-node-cfgjl                                       24m          80Mi            
calico-system     calico-typha-5b964bcd55-82f8w                           3m           20Mi            
kube-system       cloud-controller-manager-ip-3-2-2-5               3m           13Mi            
kube-system       etcd-ip-3-2-2-5                                   27m          98Mi            
kube-system       kube-apiserver-ip-3-2-2-5                         68m          376Mi           
kube-system       kube-controller-manager-ip-3-2-2-5                15m          54Mi            
kube-system       kube-proxy-ip-3-2-2-5                             8m           12Mi            
kube-system       kube-proxy-ip-3-2-2-5                             7m           12Mi            
kube-system       kube-scheduler-ip-3-2-2-5                         3m           17Mi            
kube-system       rke2-coredns-rke2-coredns-545d64676-6mplv               2m           11Mi            
kube-system       rke2-coredns-rke2-coredns-545d64676-xsgdl               6m           10Mi            
kube-system       rke2-coredns-rke2-coredns-autoscaler-5dd676f5c7-nrlhg   1m           5Mi             
kube-system       rke2-ingress-nginx-controller-qdn69                     19m          69Mi            
kube-system       rke2-metrics-server-6564db4569-5s8nz                    3m           17Mi            
tigera-operator   tigera-operator-9d47d96d7-2jw2l                         5m           29Mi  
```

$ sudo journalctl -eu rke2-server | grep -i -e "egress proxy mode"
```
Jun 28 23:57:36 ip-3-2-2-5 rke2[26326]: time="2022-06-28T23:57:36Z" level=info msg="Tunnel server egress proxy mode: disabled"
```

**Additional context / logs:**
$ cat values.yaml
```
imagePullSecrets: {}

installation:
  controlPlaneTolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Enabled
  imagePath: "rancher"
  imagePrefix: "mirrored-calico-"
  flexVolumePath: "/var/lib/kubelet/volumeplugins/"

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

resources: {}

# Configuration for the tigera operator
tigeraOperator:
  image: rancher/mirrored-calico-operator
  version: v1.27.1
  registry: docker.io
calicoctl:
  image: rancher/mirrored-calico-ctl
  tag: v3.23.1

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

# Config required by Windows nodes
ipamConfig:
  strictAffinity: true
  autoAllocateBlocks: true

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
```
