### ISSUE TITLE
[Backport release-1.22] Add whereabouts IPAM to Multus

### ISSUE THREAD

**Issue by thomasferrandiz** [rancher/rke2#3044]
This is a backport for issue https://github.com/rancher/rke2/issues/3008.

**Comment by VestigeJ** [comment]
Environment Details
 
*Infrastructure*
- [x] Cloud
- [ ] Hosted 

*Node(s) CPU architecture, OS, and Version:*
Linux 5.4.0-1009-aws x86_64 GNU/Linux-Ubuntu 20.04 LTS

*Cluster Configuration:*
```
NAME              STATUS   ROLES                       AGE   VERSION
ip-1-1-1-3   Ready    control-plane,etcd,master   35m   v1.22.11+rke2r1 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
cni: multus,canal
```

## Replication Steps

``` 
$  sudo mkdir -p /var/lib/rancher/rke2/server/manifests/
$  sudo vim /var/lib/rancher/rke2/server/manifests/rke2-multus-config.yaml
$  VERSION=v1.22.11-rc1+rke2r1
$  sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server sh - ./install-rke2.sh 
$  kga -o wide (wait for ready state)
$  k apply -f wheres.yaml -f pod.yaml 
$  k describe pod samplepod
```

**Results:**

```
Name:         samplepod
Namespace:    default
Priority:     0
Node:         ip-1-1-1-3/1.1.1.3
Start Time:   Tue, 21 Jun 2022 18:27:44 +0000
Labels:       <none>
Annotations:  cni.projectcalico.org/containerID: 8f6d6714cce8bed0c088d8b4dbaf39b48256fe73d5f60dfa2e7a270c4c23ee3a
              cni.projectcalico.org/podIP: 10.42.0.83/32
              cni.projectcalico.org/podIPs: 10.42.0.83/32
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "10.42.0.83"
                    ],
                    "default": true,
                    "dns": {}
                },{
                    "name": "default/macvlan",
                    "interface": "net1",
                    "ips": [
                        "49.49.49.225"
                    ],
                    "mac": "96:cc:16:98:a7:9a",
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks: macvlan
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "10.42.0.83"
                    ],
                    "default": true,
                    "dns": {}
                },{
                    "name": "default/macvlan",
                    "interface": "net1",
                    "ips": [
                        "49.49.49.225"
                    ],
                    "mac": "96:cc:16:98:a7:9a",
                    "dns": {}
                }]
              kubernetes.io/psp: global-unrestricted-psp
Status:       Running
IP:           10.42.0.83
IPs:
  IP:  10.42.0.83
```

-------------------------------------------------------------------------------------------
**Validated with-**

"v1.22.11-rc1+rke2r1" 

** rke2 Version/Commit:**
 
**Additional context / logs:**
$ cat wheres.yaml
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "macvlan-main",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth0",
      "ipam": {
            "type": "whereabouts",
            "range": "49.49.49.225/28"
      }
    }'
EOF
```
$ cat pod.yaml
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF
```
$ sudo cat /var/lib/rancher/rke2/server/manifests/rke2-multus-config.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    rke2-whereabouts:
      enabled: true
```
