### ISSUE TITLE
[Backport release-1.22] Tunnel server egress proxy rejecting connection to <pod IP>:<port>

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#3098]
This is a backport issue for https://github.com/rancher/rke2/issues/3016, automatically created via rancherbot by @rancher-max

Original issue description:

**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.24.1+rke2r1 (29d227c5a5352a94b14e54ae58667ac48b07df15)
go version go1.18.1b7
```

Node(s) CPU architecture, OS, and Version: 
Debian bookworm (testing)
```
Linux hudson 5.17.0-3-amd64 #1 SMP PREEMPT Debian 5.17.11-1 (2022-05-26) x86_64 GNU/Linux
```

Cluster Configuration:
2 servers in the cluster

**Describe the bug:**
Following the upgrade from v1.23.6+rke2r2 to v1.24.1+rke2r1 my v1beta1.metrics.k8s.io and v3.projectcalico.org APIServices are unavailable ("FailedDiscoveryCheck") despite the pods being healthy and the services being accessible from either node.

The status message is:
```
failing or missing response from https://10.44.207.181:8443/apis/metrics.k8s.io/v1beta1: Get "https://10.44.207.181:8443/apis/metrics.k8s.io/v1beta1": proxy error from 127.0.0.1:9345 while dialing 10.44.207.181:8443, code 500: 500 Internal Server Error
```

When running `rke2 server` with debugging enabled I see messages like the following:

```
Jun 05 09:36:58 hudson rke2[509519]: time="2022-06-05T09:36:58+01:00" level=debug msg="Tunnel server handing HTTP/1.1 CONNECT request for //10.44.207.181:8443 from 127.0.0.1:36616"
Jun 05 09:36:58 hudson rke2[509519]: time="2022-06-05T09:36:58+01:00" level=debug msg="Tunnel server egress proxy rejecting connection to 10.44.207.181:8443"
```

**Steps To Reproduce:**
Uncertain. For me this coincided with the upgrade from v1.23.6+rke2r2 to v1.24.1+rke2r1.

**Expected behavior:**
The APIServices should continue to work, and the proxy should presumably allow these connections.

**Actual behavior:**
As above.

**Additional context / logs:**
My `config.yaml` is:
```yaml
server: https://<SNIP>:9345
token: <SNIP>
tls-san:
  - <SNIP>

debug: true

node-ip: 10.0.96.41,<SNIP IPv6>
cluster-cidr: 10.44.0.0/16,<SNIP IPv6>/56
service-cidr: 10.45.0.0/16,<SNIP IPv6>/112

write-kubeconfig-mode: "0440"

kube-apiserver-arg:
  - default-not-ready-toleration-seconds=30
  - default-unreachable-toleration-seconds=30

kube-controller-manager-arg:
  - bind-address=0.0.0.0
  - node-monitor-grace-period=16s
  - node-monitor-period=2s
  - pod-eviction-timeout=30s

kube-scheduler-arg:
  - bind-address=0.0.0.0

kubelet-arg:
  - node-status-update-frequency=4s
  - kube-reserved=cpu=250m,memory=4096Mi,ephemeral-storage=1Gi
  - system-reserved=cpu=250m,memory=4096Mi,ephemeral-storage=1Gi

kube-proxy-arg:
  - metrics-bind-address=0.0.0.0:10249
  - proxy-mode=ipvs

kube-proxy-extra-mount:
  - /lib/modules:/lib/modules:ro

disable:
  - rke2-canal
  - rke2-ingress-nginx

protect-kernel-defaults: true
secrets-encryption: true

etcd-expose-metrics: true
```

**Comment by mdrahman-suse** [comment]
### Validated on upgrade to v1.22.8-rc1+rke2r1
  
## Environment Details

  
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

Ubuntu 20.04 LTS
  
*Cluster Configuration:*

```
1 server
1 agent
```
  
*Config.yaml:*

```
# server:
write-kubeconfig-mode: 644
disable: rke2-canal
token: summerheat
node-external-ip: <redacted>
cni: canal

# agent:
token: summerheat
node-external-ip: <redacted>
server: https://<server 1 ip>:9345
```
  
*Additional files*

```
# values.yaml (on server)
imagePullSecrets: {}

installation:
  controlPlaneTolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: "NoExecute"
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Enabled
  imagePath: "rancher"
  imagePrefix: "mirrored-calico-"
  flexVolumePath: "/var/lib/kubelet/volumeplugins/"

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

resources: {}

# Configuration for the tigera operator
tigeraOperator:
  image: rancher/mirrored-calico-operator
  version: v1.27.1
  registry: docker.io
calicoctl:
  image: rancher/mirrored-calico-ctl
  tag: v3.23.1

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

# Config required by Windows nodes
ipamConfig:
  strictAffinity: true
  autoAllocateBlocks: true

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
```
  
## Testing Steps

1. Copy config.yaml on both nodes
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Install RKE2 using previous version on both nodes: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.22.9+rke2r2 sh -`
3. Start rke2 server/agent processes:
```
# server:
sudo systemctl enable rke2-server.service --now

# agent:
sudo systemctl enable rke2-agent.service --now
```
4. Install calico:
```
# Run below commands on server:
$ kubectl create namespace tigera-operator
$ helm install calico projectcalico/tigera-operator --version v3.23.2 -f values.yaml --namespace tigera-operator
```
5. Ensure everything is up and running and metrics are working.
6. Upgrade rke2
```
# both nodes:
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=$desired_version sh -

# server:
sudo systemctl restart rke2-server

# agent:
sudo systemctl restart rke2-agent
```
7. Check egress proxy mode: `journalctl -eu rke2-server | grep -i egress`
8. Check metrics:
```
$ kubectl top node
$ kubectl top pods -A
```
  
**Replication Results:**
- _rke2 version used for replication:_
```
Upgrade from v1.22.9+rke2r2 to v1.24.1+rke2r1
```
 

- egress proxy mode is `pod`:
```
$ journalctl -eu rke2-server | grep -i egress
...
Jun 29 00:18:32 ip-172-31-33-44 rke2[28281]: time="2022-06-29T00:18:32Z" level=info msg="Tunnel server egress proxy mode: pod"
```
- metrics do not work:
```
$ kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
$ kubectl top pods -A
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)
```
 
**Validation Results:**
- _rke2 version used for validation:_
```
Upgrade from v1.22.9+rke2r2 to v1.24.2-rc1+rke2r1. Also verified that upgrading from v1.22.9+rke2r2 to 1.22.10+rke2r2 worked as expected
```
 

- egress proxy mode is `disabled` correctly:
```
Jun 29 00:50:43 ip-172-31-33-44 rke2[37640]: time="2022-06-29T00:50:43Z" level=info msg="Tunnel server egress proxy mode: disabled"
```
- metrics work:
```
$ kubectl top node
NAME               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-172-31-33-44    158m         7%     1548Mi          39%
ip-172-31-47-196   75m          3%     964Mi           24%
$ kubectl top pods -A
NAMESPACE         NAME                                                    CPU(cores)   MEMORY(bytes)
calico-system     calico-kube-controllers-5c974bd88c-pwkc6                4m           13Mi
calico-system     calico-node-gdpkb                                       21m          83Mi
calico-system     calico-node-n9chk                                       19m          82Mi
calico-system     calico-typha-778f6d5699-cxng8                           2m           17Mi
kube-system       cloud-controller-manager-ip-172-31-33-44                4m           14Mi
kube-system       etcd-ip-172-31-33-44                                    21m          57Mi
kube-system       kube-apiserver-ip-172-31-33-44                          59m          475Mi
kube-system       kube-controller-manager-ip-172-31-33-44                 12m          56Mi
kube-system       kube-proxy-ip-172-31-33-44                              1m           11Mi
kube-system       kube-proxy-ip-172-31-47-196                             1m           12Mi
kube-system       kube-scheduler-ip-172-31-33-44                          3m           17Mi
kube-system       rke2-coredns-rke2-coredns-76cb76d66-5785l               2m           13Mi
kube-system       rke2-coredns-rke2-coredns-76cb76d66-rbr9w               1m           12Mi
kube-system       rke2-coredns-rke2-coredns-autoscaler-58867f8fc5-tg5wp   1m           5Mi
kube-system       rke2-ingress-nginx-controller-w6kkn                     2m           66Mi
kube-system       rke2-metrics-server-8574659c85-4k8cb                    3m           16Mi
tigera-operator   tigera-operator-6c5cfc598f-b9k29                        3m           29Mi
```
- All nodes and pods are up Ready and Running as expected
