### ISSUE TITLE
nodeAddressAutodetectionV4 is not applied to v1.21.12+rke2r2

### ISSUE THREAD

**Issue by gricuk** [rancher/rke2#3107]
**Environmental Info:**
RKE2 Version: v1.21.12+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux 5.15.0-1014-aws #18-Ubuntu SMP Wed Jun 15 20:04:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server 2 agents. 

**Describe the bug:**
We use multus calico. I try to change calico IPautodetection policy during install , but it doesn't apply.
```
spec:
  defaultPodSecurityPolicyTemplateName: ''
  kubernetesVersion: v1.21.13+rke2r2
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig:
    chartValues:
      rke2-calico:
        installation:
          calicoNetwork:
            mtu: 1400
            nodeAddressAutodetectionV4:
              skipInterface: weave
```
I get the following error
```
{"level":"error","ts":1656167782.200181,"logger":"controller_installation","msg":"Invalid Installation provided","Request.Namespace":"","Request.Name":"default","error":"no more than one node address autodetection method can be specified per-family","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\
```

But it works for our another cluster with v1.21.10+rke2r2 version

**Steps To Reproduce:**
Install default cluster with multus+calico. After cluster provisioning try to change autodetect for calico.

**Expected behavior:**

Calico will ignore weave IP addresses.

**Actual behavior:**

Calico detects weave IP addresses

**Comment by gricuk** [comment]
The problem was solved. Just add to addon:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          firstFound: false
          skipInterface: weave
```

```
firstFound: false
```

Firstfound should be false and Tigera doens't show any errors now.
