### ISSUE TITLE
Unable to connect to RKE2 server from other machine using kubectl 

### ISSUE THREAD

**Issue by samavedulark** [rancher/rke2#3202]
Hi,

I have installed a RKE version: v1.21.14+rke2r1 
Installation was successful and i was able see node running. Copied rke2.yaml to my local machine and changed the IP to server, but not able to connect from local machine to server.
Below is the rke2.yaml, let me know anything is wrong on my side. when i am trying to connect i am getting belwo error.

**Please enter Password: error: You must be logged in to the server (Unauthorized)**

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: AS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlakNDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4TmpVNU1URTVOamd6TUI0WERUSXlNRGN5T1RFNE16UTBNMW9YRFRNeU1EY3lOakU0TXpRMApNMW93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRZMU9URXhPVFk0TXpCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLOVBZc24yNTYxU05GQk02cUFma29Ia0pYMWtWR1hXTHVYbTl4SEUKZWFDSlAwcTIxTTU1RXZ1R0NjTGZNcnJlbEl5akYyVktxM1UyWnp4d3Ivci9adUNqUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU2QyT0doaXlLOU1NQTF3YW5lCnFwY0hVRThhaGpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTBpSDhXSk1yWUlFVis2QlpkMVJLeDYwaUhGdkoKeFFRNDR3Wk9sc3Q3OU0wQ0lRQ3lFTVF4VlowMlNiVjhiaEMycmhLem5vbFg1bXUyTGU2Wk02aUF4bDIxNXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tKL0tBg==
    server: https://XX.XX.XX.XX:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user: 
```
