### ISSUE TITLE
Ingress stopped working after upgrade to 1.23.9

### ISSUE THREAD

**Issue by admun** [rancher/rke2#3217]
**Environmental Info:**
RKE2 Version: 1.23.8 upgrade to 1.23.9

Node(s) CPU architecture, OS, and Version: 
Linux rocky-1.kkhome.net 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Wed Jun 29 17:21:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

All nodes are VM running on Fedora 36 hosts

- Each node are running nebula VPN, there are 2 network interfaces (enp1s0, nebula1)
- SELinux is disabled

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**
I was running into an issue and have to destroy my 1.23.8 cluster and recreate it. I did not specify version, so 1.23.9 was selected.

After reinstall all applications and tools back to the cluster (using FluxCD), all ingress getting connection refused.

**Steps To Reproduce:**
- Installed RKE2: 
using a static yum.repo
```
[rancher-rke2-common-latest]
name=Rancher RKE2 Common Latest
baseurl=https://rpm.rancher.io/rke2/latest/common/centos/8/noarch
enabled=0
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key

[rancher-rke2-1-23-latest]
name=Rancher RKE2 1.23 Latest
baseurl=https://rpm.rancher.io/rke2/latest/1.23/centos/8/x86_64
enabled=0
gpgcheck=1
gpgkey=https://rpm.rancher.io/public.key
```

run `dnf install rke2-server -y`

setup config.yaml
```
write-kubeconfig-mode: "0600"
selinux: false
tls-san:
  - rocky-1.somehost
  - rocky-1.nebula.somehost
cni:
  - cilium
disable:
  - rke2-canal
  - rke2-kube-proxy
  - rke2-metrics-server
```

setup `rke2-ingress-nginx-config.yaml`
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      metrics:
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
```

setup cilium-config.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      kubeProxyReplacement: "strict"
      k8sServiceHost: 192.168.0.50
      k8sServicePort: 6443
      operator:
        replicas: 1
      encryption:
        enabled: false
        type: wireguard
      l7Proxy: false
      hubble:
        metrics:
          enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        relay:
          enabled: true
        ui:
          enabled: true
          replicas: 1
          ingress:
            enabled: true
            hosts:
              - hubble.nebula.edmondhui.net
            annotations:
              cert-manager.io/cluster-issuer: ca-issuer
            tls:
            - secretName: ingress-hubble-ui-tls
              hosts:
              - hubble.nebula.edmondhui.net
      prometheus:
        enabled: true
        # Default port value (9090) needs to be changed since the RHEL cockpit also listens on this port.
        port: 19090
        # Configure this serviceMonitor section AFTER Rancher Monitoring is enabled!
        serviceMonitor:
          enabled: true  
```

then enable and start rke2-server

using the same install method to install agents

**Expected behavior:**
All existing ingress should function without changes.

**Actual behavior:**
All ingress failed, getting connection refused.
