### ISSUE TITLE
Static pod customization values are not applied when parameters are passed as a list.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#3256]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.24.4-rc1+rke2r1

Node(s) CPU architecture, OS, and Version:  Ubuntu 20.04
```
$ uname -a
Linux ip-172-31-5-110 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:
Single node server

**Describe the bug:**
`control-plane-probe-configuration`, `control-plane-resource-requests`, and `control-plane-resource-limits` don’t work properly if you enter them as a list in config.yaml, only the last value is used

**Steps To Reproduce:**
1. Pass the params in the config.yaml as below in list format
```
control-plane-probe-configuration:
  - etcd-startup-initial-delay-seconds=42
  - kube-apiserver-readiness-period-seconds=13
```
2. Install rke2
3. Check the params
**periodSeconds: is set to new value 13**
```
ubuntu@ip-172-31-5-110:~$ kubectl get pods -n kube-system kube-apiserver-ip-172-31-5-110 -o yaml|grep readiness -A 15
    readinessProbe:
      exec:
        command:
        - kubectl
        - get
        - --server=https://localhost:6443/
        - --client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt
        - --client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key
        - --certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt
        - --raw=/readyz
      failureThreshold: 3
      periodSeconds: 13
```
  **delay is set to default value 10s**
```
$ kubectl get node -o yaml|grep startup
      rke2.io/node-args: '["server","--control-plane-probe-configuration","etcd-startup-initial-delay-seconds=42","--control-plane-probe-configuration","kube-apiserver-readiness-period-seconds=13"]'
ubuntu@ip-172-31-5-110:~$ kubectl describe pod -n kube-system etcd-ip-172-31-5-110  |grep -i startup
    Startup:   http-get http://localhost:2381/health%3Fserializable=true delay=10s timeout=5s period=10s #success=1 #failure=24
```
**Expected behavior:**
All params should be configurable

**Actual behavior:**
Replaces previous parameters

**Comment by ShylajaDevadiga** [comment]
Validated using commit id 2437e0432e04e2f8e48bc788fcbec9043cbdedd3 
```
ubuntu@ip-172-31-5-146:~$ cat /etc/rancher/rke2/config.yaml 
control-plane-probe-configuration:
  - etcd-startup-initial-delay-seconds=42
  - kube-apiserver-readiness-period-seconds=13
control-plane-resource-requests:
  - kube-apiserver-cpu=500m
  - kube-apiserver-memory=512M
  - kube-scheduler-cpu=250m
  - kube-scheduler-memory=512M
  - etcd-cpu=1000m
  
ubuntu@ip-172-31-5-146:~$ kubectl get pods -n kube-system kube-apiserver-ip-172-31-5-146 -o yaml|grep readiness -A 15
    readinessProbe:
      exec:
        command:
        - kubectl
        - get
        - --server=https://localhost:6443/
        - --client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt
        - --client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key
        - --certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt
        - --raw=/readyz
      failureThreshold: 3
      periodSeconds: 13
      successThreshold: 1
      timeoutSeconds: 15
    resources:
      requests:
ubuntu@ip-172-31-5-146:~$ kubectl get node -o yaml|grep startup
      rke2.io/node-args: '["server","--control-plane-probe-configuration","etcd-startup-initial-delay-seconds=42","--control-plane-probe-configuration","kube-apiserver-readiness-period-seconds=13"]'
ubuntu@ip-172-31-5-146:~$ kubectl describe pod -n kube-system etcd-ip-172-31-5-146 |grep -i startup
    Startup:   http-get http://localhost:2381/health%3Fserializable=true delay=42s timeout=5s period=10s #success=1 #failure=24

ubuntu@ip-172-31-5-146:~$ kubectl get pods -n kube-system kube-apiserver-ip-172-31-5-146 -o yaml|grep -i requests -A 15 --color
      requests:
        cpu: 500m
        memory: 512M
```
