### ISSUE TITLE
ETCDSnapshot CRs not cleaned up/not following `etcd-snapshot-retention` value

### ISSUE THREAD

**Issue by BenB196** [rancher/rke2#3267]
**Environmental Info:**
RKE2 Version:

`v1.23.9+rke2r1`

Node(s) CPU architecture, OS, and Version:

`Linux k8s01-rancher 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 server nodes, Etcd snapshot enabled.

**Describe the bug:**

ETCDSnapshot CRs are not cleaned up when there are things like failures.

**Steps To Reproduce:**

- Installed RKE2: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.23.9+rke2r1 sh -`
- Configure RKE2 with ETCD support (In my case using S3) (Make sure that you configure it incorrectly so that the backup fails)
```yaml
server: https://<snipped>:9345
token: <snipped>
tls-san:
  - <snipped>
  - <snipped>
  - <snipped>
node-name: k8s01-rancher
secrets-encryption: true
disable:
  - rke2-ingress-nginx
etcd-disable-snapshots: false
etcd-snapshot-name: "etcd-snapshot-rancher"
etcd-snapshot-schedule-cron: "0 */1 * * *"
etcd-snapshot-retention: 20
etcd-s3: true
etcd-s3-endpoint: "<s3_compatible_endpoint>"
etcd-s3-access-key: "<snipped>"
etcd-s3-secret-key: "<snipped>"
etcd-s3-bucket: "rke-rancher-backups-<snipped>"
audit-policy-file: "/etc/rancher/rke2/audit-policy.yaml"
```
- Wait for the backup to run (and then fail)
- Let it fail for a while
- See that there are now >20 fails Snapshot CRs
![image](https://user-images.githubusercontent.com/8277432/186426238-87d6f29f-64ce-410a-9c42-2701d3855adf.png)
- Fix snapshot configuration
- Wait for the backup to run (and then succeed)
- See that there are still the failed Snapshot CRs, but also the successful ones
![image](https://user-images.githubusercontent.com/8277432/186426482-771d80bc-937e-47d5-8a51-b74fb82d9e36.png)

**Expected behavior:**

I expect that at most there should only ever be `etcd-snapshot-retention` number of ETCDsnapshot CRs for a given node.

**Actual behavior:**

I see ETCDsnapshot CRs continue to grow past the `etcd-snapshot-retention`.

**Additional context / logs:**
