### ISSUE TITLE
vsphere : HelmChartConfig value do not override default  HelmChart  value setting ??

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3384]
**Environmental Info:**
RKE2 Version: 1.24.4+rke2r1
Node(s) CPU architecture, OS, and Version: 3.10.0-1160.71.1.el7.x86_64
config.yaml set with cloud-provider-name: rancher-vsphere

**Describe the bug:**
HelmChartConfig do not override default  HelmChart  value setting

The file : https://github.com/rancher/rke2-charts/blob/main/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.2.201/values.yaml
show that we can modify image name and tag   using : 
```
cloudControllerManager:
  repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
  tag: v1.22.5
```

then i create a HelmChartConfigFile  to modify values for  HelmChart rancher-vsphere-cpi
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    cloudControllerManager:
      repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
      tag: v1.22.5
```

i restart rke2-server ,   the HelmChartConfigFile is create, the configmap associate with it too : chart-content-rancher-vsphere-cpi

but the daemonset of vsphere is still using default image :
```
kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get ds -n kube-system rancher-vsphere-cpi-cloud-controller-manager -o jsonpath="{.spec.template.spec.containers[*].image }"

rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.23.0
```

any wrong process from me ?

**Comment by brandond** [comment]
In order for your cloudControllerManager settings to be used, you need to remove the versionOverrides, which (as the name suggests) overrides the default repository/tag values based on the running Kubernetes version.

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    versionOverrides: []
    cloudControllerManager:
      repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
      tag: v1.22.5
```

Why are you trying to use an older version of the image? Is v1.22.5 compatible with Kubernetes v1.24?
