### ISSUE TITLE
Need to create a RKE2 CIS profile that will pass by default.

### ISSUE THREAD

**Issue by maggieliu** [rancher/rke2#339]
Need to have a CIS profile for RKE2 where all tests should be passing or skipped. 
Current result from running `cis-1.5-profile`
- RKE cluster scan summary:
```
summary:
    fail: 82
    notApplicable: 0
    pass: 10
    skip: 0
    total: 92
```
