### ISSUE TITLE
Cannot create pod with unsafe sysctls

### ISSUE THREAD

**Issue by waldner** [rancher/rke2#3410]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.24.6+rke2r1 (473cc354adecd235f00f0d80828611b0556b83e5)
go version go1.18.1b7
```

Node(s) CPU architecture, OS, and Version: 
```
Linux vca 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server

**Describe the bug:**
Pods with capabilities are not created, despite running without profiles

**Steps To Reproduce:**
- Installed RKE2: 
```
node-name: vca
kubelet-arg:
  - "allowed-unsafe-sysctls=net.*"
disable:
  - rke2-ingress-nginx
  - rke2-metrics-server
```

Create this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      restartPolicy: Always
      securityContext:
        sysctls:
        - name: net.ipv4.conf.default.disable_policy
          value: "1"
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: app
```

The deployment is not created with:

```
15s         Warning   FailedCreate              replicaset/app-59c5565dff   Error creating: pods "app-59c5565dff-" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.spec.securityContext.sysctls[0]: Forbidden: unsafe sysctl "net.ipv4.conf.default.disable_policy" is not allowed]
```

**Expected behavior:**
The pod should be created.

**Actual behavior:**
The deployment is not created with the above error messages.

**Additional context / logs:**
