### ISSUE TITLE
RKE2 truncates manifests that contain a HelmChart resource as the first document

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3469]
**Environmental Info:**
RKE2 Version: 
n/a

Node(s) CPU architecture, OS, and Version: 
n/a

Cluster Configuration:
n/a

**Describe the bug:**
RKE2 truncates manifests that contain a HelmChart resource as the first document

**Steps To Reproduce:**
* Drop the following file in `/var/lib/rancher/rke2/server/manifests` prior to starting RKE2
* Note that the file on disk is truncated to just the cert-manager HelmChart resource

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
```

**Expected behavior:**
Cluster configuration values are passed in to all charts in the manifest; other resource types are not changed or lost

**Actual behavior:**
Everything after the first HelmChart resource is removed from the file

**Additional context / logs:**
* Mentioned at https://github.com/rancher/rke2/issues/527#issuecomment-742119875
* https://github.com/rancher/rke2/blob/ace2b88fecedacc0a5aec5c734bbe162f1f80a50/pkg/bootstrap/bootstrap.go#L253-L255

**Comment by VestigeJ** [comment]
Reproduced using VERSION=v1.25.3+rke2r1 
Validated using COMMIT=9364f9d4cdeb7081122491a9f9e4e3b1a6d2ae53

##Environment Details 
*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and Version:*

Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux SUSE Linux Enterprise Server 15 SP4

*Cluster Configuration:*
```
NAME              STATUS   ROLES                       AGE   VERSION
ip-1-1-2-26   Ready    control-plane,etcd,master   97s   v1.25.3+rke2r1 
```
*Config.yaml:*



## Replication Steps
 
```
$  get.rke2; make.etcduser; set.figs rke2
$  sudo mkdir -p /var/lib/rancher/rke2/server/manifests/
$  vim trunc.yaml
$  cat trunc.yaml
$  sudo cp trunc.yaml /var/lib/rancher/rke2/server/manifests/
$  sudo ls /var/lib/rancher/rke2/server/manifests/
$  VERSION=v1.25.3+rke2r1
$  conf rke2
$  sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh 
$  go.rke2
$  kubefig rke2
$ kgn
$  sudo cat /var/lib/rancher/rke2/server/manifests/trunc.yaml 
$  get.report
```
**Results:**

manifest gets truncated as observed in the issue
<details>
<summary><h4>manifest gets truncated vs the original in ~/ </h4></summary>
TRUNC differences v1.25.3+rke2r1


$ sudo cat /var/lib/rancher/rke2/server/manifests/trunc.yaml 
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    global.cattle.systemDefaultRegistry: ""
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
    installCRDs: "true"
  targetNamespace: cert-manager
  version: v1.6.1
status: {}
```
$ cat trunc.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
```  

</details>

----------------------------------------------------------------------------------------
**Validated with-**

Validated using COMMIT=9364f9d4cdeb7081122491a9f9e4e3b1a6d2ae53

  <details>
<summary><h4>Manifest does not get truncated vs original</h4></summary>

```
$  sudo mkdir -p /var/lib/rancher/rke2/server/manifests/
$  sudo cp trunc.yaml /var/lib/rancher/rke2/server/manifests/
$  sudo ls /var/lib/rancher/rke2/server/manifests/
$  COMMIT=9364f9d4cdeb7081122491a9f9e4e3b1a6d2ae53
$  conf rke2
$  sudo INSTALL_RKE2_COMMIT=$COMMIT INSTALL_RKE2_EXEC=server ./install-rke2.sh 
$  go.rke2
$  kubefig rke2
$ kgn
$  sudo cat /var/lib/rancher/rke2/server/manifests/trunc.yaml 
```


*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: coolclouds
selinux: true
cni: cilium
profile: cis-1.23
```

  $ sudo cat /var/lib/rancher/rke2/server/manifests/trunc.yaml 
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    installCRDs: "true"
  targetNamespace: cert-manager
  version: v1.6.1

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    antiAffinity: required
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    hostname: rancher.example.com
    ingress.tls.source: rancher
    replicas: 1
  targetNamespace: cattle-system
  version: v2.6.8

---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
```
$ cat trunc.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
```  


$ cat trunc.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
```
</details>

**Comment by VestigeJ** [comment]
Just updating from a test I did last night where I was able to trigger the truncation again - by rearranging the order of the files below.

<details>
<summary><h4>First yaml moved into manifests directory does not get truncated</h4>
$ cat first.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
```
</summary>
</details>

<details>
<summary><h4>Second yaml moved into manifests directory gets truncated</h4>
$ cat second.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: system-upgrade
  namespace: system-upgrade
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cert-manager
spec:
  targetNamespace: cert-manager
  version: v1.6.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  targetNamespace: cattle-system
  version: v2.6.8
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  set:
    ingress.tls.source: "rancher"
    hostname: "rancher.example.com"
    antiAffinity: "required"
    replicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
</summary>
</details>
