### ISSUE TITLE
Ingress HelmChartConfig -  controller extraArgs  not apply

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3482]
** Environmental Info **
RKE2 Version: 1.24.4+rke2r1
Node(s) CPU architecture, OS, and Version: 3.10.0-1160.71.1.el7.x86_64

**Describe the bug:**

I have file /var/lib/rancher/rke2/server/manifests/ingress-HelmChartConfig.yaml 
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
     controller:
       allowSnippetAnnotations: true
       config:
         use-forwarded-headers: true
       extraArgs:
         enable-ssl-passthrough: true
         default-ssl-certificate: kube-system/sslnginx
```

but checking the daemonSet Setting, the extraArgs are not set.
`kubectl get ds -n kube-system rke2-ingress-nginx-controller -o yaml | grep ssl`

i try delete/apply the HelmChartConfig but got no change,
then I manually delete the HelmChartConfig,  then delete the DaemonSet

```
 kubectl delete -f  /var/lib/rancher/rke2/server/manifests/ingress-HelmChartConfig.yaml 
 kubectl delete ds -n kube-system rke2-ingress-nginx-controller
```

i apply the HelmChartConfig again,

` kubectl apply-f  /var/lib/rancher/rke2/server/manifests/ingress-HelmChartConfig.yaml `

wait for  the daemonset  to be create, fastly check if args in ...  yes they are ...

```
kubectl get ds -n kube-system rke2-ingress-nginx-controller -o yaml | grep ssl
        - --default-ssl-certificate=kube-system/sslnginx
        - --enable-ssl-passthrough=true
```

 but few seconds later ... their not., daemonset was rewrite without.

 ```
kubectl get ds -n kube-system rke2-ingress-nginx-controller -o yaml | grep ssl
```

it is a bit strange, anyoneelse got this behaviour ?
