### ISSUE TITLE
RKE2 with Cilium Kube-Proxy Replacement - Floating IP not working for 80/443 Nginx Ingress

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#3516]
**Environmental Info:**
RKE2 Version: 1.22.13+rke2r1

Node(s) CPU architecture, OS, and Version: 
SLES 15 SP4 x86_64

Cluster Configuration:
3 servers, 4 workers

**Describe the bug:**
We configure RKE2 this way:
```
cni: "cilium"
disable-kube-proxy: true
etcd-expose-metrics: false
cluster-cidr: "172.27.0.0/16"
service-cidr: "172.28.0.0/16"
cluster-dns: "172.28.0.10"
```

We configure cilium this way:
```
rke2-cilium:
  egressGateway:
    enabled: true
  bpf:
    masquerade: true
  l7Proxy: false
  kube-proxy-replacement: strict
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6443
```

**Steps To Reproduce:**

One worker node has 10.1.1.54/24
`
curl https://10.1.1.54` on the host with ip 10.1.1.54 works and gives nginx ingress
`curl https://10.1.1.54` on any other host works and gives nginx ingress

then we do `ip a a 10.1.1.60/24 dev eth0` on the node with 10.1.1.54
`
curl https://10.1.1.60` on the host with ip 10.1.1.54 works and gives nginx ingress
`curl https://10.1.1.60` **on any other host fails**
ping 10.1.1.60 from any other host works
ssh 10.1.1.60 from any other host works
-> just nginx ingress on 80/443 does not work from any other host

**Expected behavior:**
curl https://10.1.1.60 works as cilium shows in cilium services "0.0.0.0/0" for port 80 and 443

**Actual behavior:**
curl https://10.1.1.60 does not work
