### ISSUE TITLE
After Upgrading to 1.24.7,  apply HelmChartConfig failed

### ISSUE THREAD

**Issue by seb-835** [rancher/rke2#3522]
**Environmental Info:**
RKE2 Version:  1.24.7

**Describe the bug:**

HelmChartConfig not apply, 
giving error : 

` rke2[33919]: time="2022-11-04T14:49:52+01:00" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/ingress-HelmChartConfig.yaml: Addon.k3s.cattle.io \"ingress-HelmChartConfig\" is invalid: metadata.name: Invalid value: \"ingress-HelmChartConfig\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"`

with the following manifest : 
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      allowSnippetAnnotations: true
      extraArgs:
        enable-ssl-passthrough: true
        default-ssl-certificate: kube-system/sslnginx
      config:
        use-forwarded-headers: "true"
```

got same behaviour on another HelmChartConfig, not only this one, 
it works well with  rke2 1.24.4.

Bugs or any new change to apply on HelmChartConfig manifest ?
