### ISSUE TITLE
Bump vsphere cpi/csi charts

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#3539]
New images are available that add support for Kubernetes 1.25. We should use them.

**Comment by VestigeJ** [comment]
Validated using COMMIT=30260639e64ad8cf212e12b26dc7d47273817102

$ get.figs rke2
```
=========== rke2 config =========== 
write-kubeconfig-mode: 644
debug: true
cloud-provider-name: "rancher-vsphere"
```

$ get.images
```
docker.io/rancher/mirrored-cloud-provider-vsphere-cpi-release-manager   v1.25.0                        f2d229c077849       17.3MB
docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver    v2.7.0                         d95b92628791a       104MB
docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-syncer    v2.7.0                         7bcfe32f25007       34.5MB
docker.io/rancher/mirrored-sig-storage-csi-attacher                     v3.4.0                         03e115718d258       22.1MB
docker.io/rancher/mirrored-sig-storage-csi-node-driver-registrar        v2.5.1                         720dcdb196378       9.13MB
docker.io/rancher/mirrored-sig-storage-csi-provisioner                  v3.2.1                         19c828b20bb85       25.3MB
docker.io/rancher/mirrored-sig-storage-livenessprobe                    v2.7.0                         4947e46903b36       8.69MB
dock
```

$ sudo cat /var/lib/rancher/rke2/server/manifests/rancher-vsphere-cpi.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.4.100.tgz
```

$ sudo cat /var/lib/rancher/rke2/server/manifests/rancher-vsphere-csi.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rancher-vsphere-csi/rancher-vsphere-csi-2.6.2-rancher100.tgz
```

$ kgn
```
NAME          STATUS   ROLES                       AGE   VERSION
jines-rke2   Ready    control-plane,etcd,master   17m   v1.25.3+rke2r1
```
