### ISSUE TITLE
RKE2 Issue SUC upgrading from previous versions to current RC versions get stuck on Scheduling Disabled 

### ISSUE THREAD

**Issue by est-suse** [rancher/rke2#3559]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.24.7+rke2r1 (5fd5150f752a663efa16ac3ae2aac5d6bba6c364)
go version go1.18.1b7
```

This is also happening on 1.22,1.23,.124 and 1.25

Node(s) CPU architecture, OS, and Version: 

```
Linux ip-172-31-5-238 5.3.18-59.37-default #1 SMP Mon Nov 22 12:29:04 UTC 2021 (d10168e) x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

```
3 servers  - 1 Agent
```
**Describe the bug:**

```
When trying to do a SUC upgrade from previous to current version, it nodes get stuck on Scheduling Disabled.
```
**Steps To Reproduce:**

- Installed RKE2: 
- Apply SUC: kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.10.0-dev.3/system-upgrade-controller.yaml
Apply the following plan:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-server
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 3
  version: v1.24.8-rc2-rke2r1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
  #drain:
  #  force: true
  upgrade:
    image: rancher/rke2-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-agent
  namespace: system-upgrade
  labels:
    rke2-upgrade: agent
spec:
  concurrency: 1
  version: v1.24.8-rc2-rke2r1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/rke2-upgrade
    args: ["prepare", "rke2-server"]
  drain:
    force: true
  upgrade:
    image: rancher/rke2-upgrade
```

![image](https://user-images.githubusercontent.com/106194120/201978149-50c202cb-04ef-4902-843f-70a85b28e655.png)

**Expected behavior:**

Nodes should be able to upgrade without any issue.

NOTE: This is happening for  version 1.22, 1.23, 1.24 and 1.25
