### ISSUE TITLE
rke2-nginx-ingress tcp-services-configmap not working

### ISSUE THREAD

**Issue by gauravkarki** [rancher/rke2#3572]
I am having the same issue as @Fabyao (https://github.com/rancher/rke2/issues/2481). I am running bitbucket in a container and trying to expose TCP port (7999). I followed the instruction provided but I can not connect to the TCP port.
Any help/advise is greatly appreciated.
### Service
#kubectl -n source-management get svc bitbucket -o yaml         
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitbucket
  name: bitbucket
  namespace: source-management
spec:
  ports:
  - name: http
    port: 7990
    protocol: TCP
    targetPort: 7990
  - name: ssh
    port: 7999
    protocol: TCP
    targetPort: 7999
  selector:
    app: bitbucket
    pod: bitbucket
  type: ClusterIP
```
### Ingress
#kubectl -n source-management get ingress bitbucket -o yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: bitbucket
    description: ingress-for-bitbucket
  name: bitbucket
  namespace: source-management
spec:
  rules:
  - host: bitbucket.<domain.com>
    http:
      paths:
      - backend:
          service:
            name: bitbucket
            port:
              number: 7990
        path: /
        pathType: Prefix
      - backend:
          service:
            name: bitbucket
            port:
              number: 7999
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bitbucket.<domain.com>
    secretName: wildcard-cert
status:
  loadBalancer: ## I am not using any LoadBalancer. These Ingress IPs are the IPs of worker Nodes
    ingress:
    - ip: 10.100.x.x
    - ip: 10.100.x.x
    - ip: 10.100.x.x
# kubectl -n source-management get ingress
NAME             CLASS    HOSTS                                     ADDRESS          PORTS     AGE
bitbucket        <none>   bitbucket.<domain.com>   10.100.x.x,10.100.x.x,10.100.x.x   80, 443   21d   <-- TCP port 7999 is not listed in the ingress
```
### HelmChartConfigs
#kubectl get helmchartconfigs.helm.cattle.io -n kube-system rke2-ingress-nginx -o yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      extraArgs:
        tcp-services-configmap: "kube-system/rke2-ingress-tcp-service"
    tcp:
       7999: "source-management/bitbucket:7999"
```
### RKE2 nixing ingress controller Daemonsets
#kubectl -n kube-system describe daemonsets.apps rke2-ingress-nginx-controller | grep tcp-services-configmap
`      --tcp-services-configmap=kube-system/rke2-ingress-tcp-service`

#kubectl -n kube-system describe pod rke2-ingress-nginx-controller-f6tz2 | grep tcp-services-configmap
`      --tcp-services-configmap=kube-system/rke2-ingress-tcp-service`
### ConfigMap
#kubectl -n kube-system get cm rke2-ingress-tcp-service -o yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-ingress-tcp-service
  namespace: kube-system
data:
  "7999": source-management/bitbucket:7999
```
### Connection Test
#telnet 10.100.x.x 443 <-- Connection to 443 is successful.
Trying 10.100.x.x...
Connected to 10.100.x.x.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

#telnet 10.100.x.x 7999 <-- Connection to TCP port using Ingress IP is not successful.
Trying 10.100.x.x...
telnet: connect to address 10.100.x.x: Connection refused

#telnet  10.43.1x.x 7999 <-- However connection to TCP port using the ClusterIP of the service is successful. 
Trying 10.43.x.x...
Connected to 10.43.x.x.
Escape character is '^]'.
SSH-2.0-APACHE-SSHD-2.8.0
^]
telnet> quit
Connection closed.

_Originally posted by @gauravkarki in https://github.com/rancher/rke2/issues/2481#issuecomment-1320964271_
