### ISSUE TITLE
nodePorts not exposed after rke2/cilium upgrade

### ISSUE THREAD

**Issue by bovy89** [rancher/rke2#3602]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.23.14+rke2r1 (83c8eb91b96ed5a2a3beb06c905e075724305a46)
go version go1.17.5b7

Node(s) CPU architecture, OS, and Version: 
Linux 4.18.0-425.3.1.el8.x86_64 #1 SMP Tue Nov 8 14:08:25 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
local testbed: 1 server, 1 agent

**Describe the bug:**
Before proceeding with an upgrade from k8s 1.22 (cilium 1.10.4) to k8s 1.23 (cilium 1.12.3), we are testing a fresh 1.23 setup on a local testbed.

When creating a pod with nodePorts (e.g. ingress-nginx), the port is not exposed on a k8s nodes anymore

**Steps To Reproduce:**
- Installed RKE2:

/etc/rancher/rke2/config.yaml (server):
```
protect-kernel-defaults: true
token-file: /etc/rancher/rke2/token
kube-proxy-arg:
  - "cluster-cidr=10.42.0.0/16"
  - "proxy-mode=ipvs"
  - "metrics-bind-address=0.0.0.0:10249"
kubelet-arg:
  - "system-reserved=cpu=30m,memory=300Mi"
  - "kube-reserved=cpu=70m,memory=1024Mi"
cni: cilium
write-kubeconfig-mode: 420
cluster-cidr: 10.42.0.0/16
service-node-port-range: 30000-32767
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction,PodSecurityPolicy,AlwaysPullImages,DenyServiceExternalIPs"
  - "tls-min-version=VersionTLS12"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "audit-policy-file=/etc/rancher/rke2/audit-policy.yaml"
  - "audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
tls-san:
  - rke-m01.example.com
  - 192.168.20.10
  - 10.0.2.15
node-ip: 192.168.20.10
disable:
  - rke2-ingress-nginx
  - rke2-canal
```

/etc/rancher/rke2/config.yaml (agent):

```
protect-kernel-defaults: true
token-file: /etc/rancher/rke2/token
kube-proxy-arg:
  - "cluster-cidr=10.42.0.0/16"
  - "proxy-mode=ipvs"
  - "metrics-bind-address=0.0.0.0:10249"
server: https://rke-m01.example.com:9345
node-ip: 192.168.20.14
kubelet-arg:
  - "system-reserved=cpu=30m,memory=300Mi"
  - "kube-reserved=cpu=80m,memory=1024Mi"
```

```
kubectl create namespace test --dry-run=client -o yaml | kubectl apply -f - && \
cat <<EOF | kubectl apply -n test -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
EOF
```

```
cat <<EOF | kubectl apply -n test -f -
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32088
  selector:
    run: my-nginx
EOF

$ kubectl get svc -n test
NAME       TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
my-nginx   NodePort   10.43.120.161   <none>        80:32088/TCP   16s

$ kubectl get endpoints
NAME       ENDPOINTS                      AGE
my-nginx   10.42.0.31:80,10.42.1.204:80   33s
```

**Expected behavior:**

```
$ netstat -tlnp | grep 32088
tcp        0      0 0.0.0.0:32088           0.0.0.0:*               LISTEN      2207/kube-proxy
```

**Actual behavior:**

```
$ netstat -tlnp | grep 32088
<empty>
```

**Additional context / logs:**

1) cilium status:

```
# kubectl -n kube-system exec ds/cilium -- cilium status --verbose
Defaulted container "cilium-agent" out of: cilium-agent, install-portmap-cni-plugin (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.23 (v1.23.14+rke2r1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled
Host firewall:          Disabled
CNI Chaining:           portmap
Cilium:                 Ok   1.12.3 (v1.12.3-1c466d2)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 9/254 allocated from 10.42.0.0/24,
Allocated addresses:
  10.42.0.100 (kube-system/hubble-relay-ffd77f856-bws4b[restored])
  10.42.0.117 (ingress-nginx-public/ingress-nginx-public-controller-7xvng[restored])
  10.42.0.211 (router)
  10.42.0.220 (kube-system/rke2-coredns-rke2-coredns-775c5b4bb4-99j2q[restored])
  10.42.0.24 (kube-system/rke2-metrics-server-669b494888-tzqb2[restored])
  10.42.0.244 (kube-system/hubble-ui-77b4dfdf8f-55b86[restored])
  10.42.0.249 (kube-system/rke2-coredns-rke2-coredns-autoscaler-695fc554c9-4pppf[restored])
  10.42.0.31 (test/my-nginx-cf54cdbf7-qgh4q)
  10.42.0.43 (health)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      53/53 healthy
  Name                                          Last success   Last error   Count   Message
  bpf-map-sync-cilium_lxc                       2s ago         never        0       no error
  cilium-health-ep                              1m2s ago       never        0       no error
  dns-garbage-collector-job                     6s ago         never        0       no error
  endpoint-1227-regeneration-recovery           never          never        0       no error
  endpoint-1416-regeneration-recovery           never          never        0       no error
  endpoint-1563-regeneration-recovery           never          never        0       no error
  endpoint-1889-regeneration-recovery           never          never        0       no error
  endpoint-1956-regeneration-recovery           never          never        0       no error
  endpoint-2347-regeneration-recovery           never          never        0       no error
  endpoint-2988-regeneration-recovery           never          never        0       no error
  endpoint-630-regeneration-recovery            never          never        0       no error
  endpoint-941-regeneration-recovery            never          never        0       no error
  endpoint-gc                                   3m6s ago       never        0       no error
  ipcache-inject-labels                         33m4s ago      33m4s ago    0       no error
  k8s-heartbeat                                 6s ago         never        0       no error
  link-cache                                    3s ago         never        0       no error
  metricsmap-bpf-prom-sync                      5s ago         never        0       no error
  resolve-identity-1563                         4m32s ago      never        0       no error
  resolve-identity-1889                         3m2s ago       never        0       no error
  restoring-ep-identity (1227)                  33m3s ago      never        0       no error
  restoring-ep-identity (1416)                  33m3s ago      never        0       no error
  restoring-ep-identity (1956)                  33m3s ago      never        0       no error
  restoring-ep-identity (2347)                  33m3s ago      never        0       no error
  restoring-ep-identity (2988)                  33m3s ago      never        0       no error
  restoring-ep-identity (630)                   33m3s ago      never        0       no error
  restoring-ep-identity (941)                   33m3s ago      never        0       no error
  sync-endpoints-and-host-ips                   3s ago         never        0       no error
  sync-lb-maps-with-k8s-services                33m3s ago      never        0       no error
  sync-policymap-1227                           32s ago        never        0       no error
  sync-policymap-1416                           32s ago        never        0       no error
  sync-policymap-1563                           32s ago        never        0       no error
  sync-policymap-1889                           32s ago        never        0       no error
  sync-policymap-1956                           32s ago        never        0       no error
  sync-policymap-2347                           32s ago        never        0       no error
  sync-policymap-2988                           32s ago        never        0       no error
  sync-policymap-630                            32s ago        never        0       no error
  sync-policymap-941                            32s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1227)             3s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (1416)             3s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (1563)             12s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1889)             11s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1956)             3s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (2347)             3s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (2988)             3s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (630)              8s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (941)              3s ago         never        0       no error
  template-dir-watcher                          never          never        0       no error
  waiting-initial-global-identities-ep (1227)   33m3s ago      never        0       no error
  waiting-initial-global-identities-ep (1416)   33m3s ago      never        0       no error
  waiting-initial-global-identities-ep (1956)   33m3s ago      never        0       no error
  waiting-initial-global-identities-ep (2988)   33m3s ago      never        0       no error
  waiting-initial-global-identities-ep (630)    33m3s ago      never        0       no error
  waiting-initial-global-identities-ep (941)    33m3s ago      never        0       no error
Proxy Status:            OK, ip 10.42.0.211, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 8.23   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                 Disabled
  Socket LB:              Disabled
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled
  - LoadBalancer:   Disabled
  - externalIPs:    Disabled
  - HostPort:       Disabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   65536
  TCP connection tracking       131072
  Endpoint policy               65535
  Events                        4
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           131072
  Neighbor table                131072
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        4
  Sockmap                       65535
  Sock reverse NAT              65536
  Tunnel                        65536
Encryption:                         Disabled
Cluster health:                     2/2 reachable   (2022-11-29T16:08:01Z)
  Name                              IP              Node        Endpoints
  rke-m01.example.com (localhost)   192.168.20.10   reachable   reachable
  rke-w01.example.com               192.168.20.14   reachable   reachable
```

2) ingress-nginx setup (https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#using-a-self-provisioned-edge)

/root/test_ingress/Chart.yaml:
```
apiVersion: v2
name: ingress-nginx
version: 0.1.0

dependencies:
- name: ingress-nginx
  version: 4.2.5
  repository: https://kubernetes.github.io/ingress-nginx
```

an example of values file:
```
ingress-nginx:
  controller:
    kind: DaemonSet
    service:
      externalTrafficPolicy: Local
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
    ingressClass: nginx-public
    ingressClassResource:
      name: nginx-public
      controllerValue: "k8s.io/ingress-nginx-public"
      enabled: true
    ingressClassByName: true
    admissionWebhooks:
      enabled: false
    publishService:
      enabled: false
    resources: null
    electionID: ingress-controller-leader-public
    metrics:
      enabled: false
    config:
      use-http2: "true"
      use-gzip: "true"
      gzip-level: "5"
      ssl-redirect: "true"
      ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
      ssl-protocols: "TLSv1.2 TLSv1.3"
      ssl-session-tickets: "false"
      server-tokens: "false"
      hide-headers: "X-Powered-By,Server"
      server-snippet: |
        location ~ /\.(?!well-known\/) {
            deny all;
            return 404;
        }
      proxy-cookie-path: "/ \"/; SameSite=None; HTTPOnly; Secure\""
      use-proxy-protocol: "true"
      annotation-value-word-blocklist: "load_module,lua_package,_by_lua,root,proxy_pass,serviceaccount,',\""
    proxySetHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
  dhParam: "LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBdmRTTnVoZ25CY01kQ3VsenBhakU1L0V3NzJ6NmNFdFNrbXNrM0tsRHp1VzQ1UjlIZE9JZQpJZVVlNlY5NlBnVnNwazZjYXc2ZFF1cTRKY1pyUDU3bklBdmk3bHhOb2xsMms1Q0JhKzZHYUV2SGhFMXE1dDFqCnVDNWxlYjlaUGFwbUFrdUxtVzUzeG9MT2RydFFYNFFUU3ZlSzlkQTY0Unk3MEJKSVFteFhoUVlDV3kvOUJjdVAKUHlsK1l4b2NxTmJ0cjAxUUliYktXVjR0Q0t1MVBxL0MvUzhwWEtXeHVqalZWRm5CZkpoVmpMcThxdWNXdnZFVQpERU1Qb2hXVmxrek1YeVM1TTlFbmVBNUNVMU5LUEhlWUZBRU0ydUtZWW8yeHBlUURtM0hoZHZpTTJ1TTFwY2JoCnl6VDhUeXJsaDgrc1pBZHB3ZVhHaERaZzhFQ0ZLemNxaWVpSTN5K0lwYWFJNkxVdm9NcTFyWTJsbTY2V0RnanEKWHRPTWg5R0RzdXpmUzJ6MjRtenZLQ2F3T2NGekdsN0VWM2ZGMnNFdDlmR2duWEJlb0hGMXdYcStpb0dOTkUvVQpXK0pxalJwUkJLdmh0MzEzT1hMRFhGeGNlMWRzMVZLU1JuWUNYUnp1R00reS8vTHVpeENXVnBFM2dqL2xwblZECkVFNytWdkJYcnpKUk1ETUhIVmpBTGVRLzNNUHc0K1dRRHVZckFIYUhQdDlLSUJDZXdRcmlIam0vUGtXNTB1R2cKK0hZNHdGNTQySTV4U05Mcmp0blp2UXFnUWdYQkdVeURMcENDczl5QXFTSjNsL28xbFZPbXQwQ3NPRk95ZnZQeApUUHBXSStmd2h4UUozR2ZML21zbzhkdEJYb3ZiVFVjT0JoKzBROGRqSWZNN3gyZnl0bXRNNDNNQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg=="
```

setup:
```
helm dependency update /root/test_ingress/ && \
helm template ingress-nginx-public /root/test_ingress/ -n ingress-nginx-public --values /root/test_ingress/values_public.yaml > ingress-nginx-public.yaml && \
kubectl create namespace ingress-nginx-public --dry-run=client -o yaml | kubectl apply -f - && \
kubectl apply -f ingress-nginx-public.yaml -n ingress-nginx-public
```
