### ISSUE TITLE
Update metrics-server tag to latest build

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#3652]
Bump metrics-server tag from 2.11.100-build2022101106 --> 2.11.100-build2022101107

**PRs:**
- #3647 
- 1.23 Backport #3649 
- 1.24 Backport #3648

**Comment by VestigeJ** [comment]
Validated correct version here extra output below - https://github.com/rancher/rke2/issues/3619#issuecomment-1341507604

$ sudo cat /var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-metrics-server/rke2-metrics-server-2.11.100-build2022101107.tgz
  name: rke2-metrics-server
  namespace: kube-system
```
