### ISSUE TITLE
Hubble UI Connection problems

### ISSUE THREAD

**Issue by kdakss** [rancher/rke2#3655]
I am trying to run Cilium on RKE2 and am running in to an issue when it comes to using Hubble 
Hubble enable gives me 
```
Healthcheck (via localhost:4245): Ok
Current/Max Flows: 0/0
Flows/s: N/A
Connected Nodes: 0/0
While cilium status shows:
Containers:       cilium             Running: 2
                  hubble-ui          Running: 1
                  cilium-operator    Running: 2
                  hubble-relay       Running: 1
Cluster Pods:     13/13 managed by Cilium
```
So all looks good with cilium but not hubble. 
Diving deeper 
```
k describe pod -n kube-system cilium-operator-7f9698fd46-pqntg 
Tolerations:                 op=Exists
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  38m   default-scheduler  0/2 nodes are available: 2 node(s) didn't have free ports for the requested pod ports.
```

firewalld is off so I don't know how any ports could be a problem. 

My /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml is
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    cilium:
      global:
        cni:
          binPath: /etc/cni/net.d/
      containerRuntime:
        integration: containerd
        socketPath: /run/k3s/containerd/containerd.sock
      externalIPs:
        enabled: true
      hostServices:
      enabled: true
      hubble:
        listenAddress: ":4244"
        enabled: true
        relay:
          enabled: true
        tls:
          server:
            enabled: true
        ui:
          enabled: true
          ingress:
            enabled: true
            hosts:
            - scrub.local
      k8sServiceHost: 172.16.7.50
      k8sServicePort: 6443
      kubeProxyReplacement: strict
      nodePort:
        enabled: true
```
Does anybody know why hubble is not connecting to the nodes?
