### ISSUE TITLE
Problems to get container logs inside Rancher

### ISSUE THREAD

**Issue by Jonas18175** [rancher/rke2#3673]
Hey, i have a crazy problem... I hope somebody could me help to identify what is wrong here.

**Environmental Info:**
RKE2 Version: 

rke2 version v1.24.8+rke2r1 (b061438ce1f04518d980aac842b62f92095d793d)
go version go1.18.1b7

Node(s) CPU architecture, OS, and Version: 

```
Linux k8s-prod-control-plane-3 6.0.8-1-default #1 SMP PREEMPT_DYNAMIC Fri Nov 11 08:02:50 UTC 2022 (1579d93) x86_64 x86_64 x86_64 GNU/Linux
```

```
NAME="openSUSE MicroOS"
# VERSION="20221128"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20221128"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20221128"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo-MicroOS"
```

Additional Information:
- Selinux: Enabled
- Hetzner-Cloud-Server

Cluster Configuration:

3x control-planes
4x agents

CNI: calico (self-deployed typha operator)
-> "disable-network-policy": true

Calico configuration:
```yaml
installation:
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    containerIPForwarding: Enabled
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 26
      cidr: 10.42.0.0/16
      encapsulation: IPIPCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      cidrs:
        - 10.10.0.0/16
  cni:
    ipam:
      type: Calico
    type: Calico
  controlPlaneReplicas: 3
  kubeletVolumePluginPath: /var/lib/kubelet
  flexVolumePath: /var/lib/kubelet/volumeplugins
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  nonPrivileged: Disabled
  variant: Calico
```

Control-Plane configuration:
```yaml
"advertise-address": "10.10.255.103"
"cni": "none"
"disable":
- "rke2-ingress-nginx"
"disable-cloud-controller": true
"disable-kube-proxy": false
"disable-network-policy": true
"flannel-backend": "none"
"flannel-iface": "eth1"
"kube-controller-manager-arg": "flex-volume-plugin-dir=/var/lib/kubelet/volumeplugins"
"kubelet-arg":
- "cloud-provider=external"
- "volume-plugin-dir=/var/lib/kubelet/volumeplugins"
"kube-apiserver-arg":
- "kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
"node-ip": "10.10.255.103"
"node-label": []
"node-name": "k8s-prod-control-plane-1"
"node-taint":
- "node-role.kubernetes.io/control-plane:NoSchedule"
"server": "https://localhost:10345"
"tls-san":
- "127.0.0.1"
- ** retracted public ips **
- "10.10.255.101"
- "10.10.255.102"
- "10.10.255.103"
- "10.10.0.101"
- "10.10.0.102"
- "10.10.0.103"
- "10.10.1.101"
"token": "** retracted **"
"write-kubeconfig-mode": "0644"
```

Control-Plane Loadbalancer: HA-Proxy (local on control-plane nodes)
Ports:
6443 -> 10443
9345 -> 10345

**Describe the bug:**

When I try to open the container logs - it works only after many retries.

Mostly I get this message:
```
Failed to load logs: Get "https://10.10.0.103:10250/containerLogs/mysql-cluster/mysql-cluster-operator-percona-xtradb-cluster-operator-558zk5cg/percona-xtradb-cluster-operator?tailLines=502&timestamps=true": proxy error from 127.0.0.1:9345 while dialing 10.10.0.103:10250, code 503: 503 Service Unavailable
Reason: undefined (500)
```

Pods that also like to read the logs - like the Percona PXC Operator - also fails with the same problem.

The network communication between pods works without issues - but something with the kube-proxy stuff goes wrong.
On the nodes I can access the 9345 port without any issues.

Is there a way to change the 127.0.0.1:9345 address for the proxy on internal use to my haproxy load-balancer port? 

**Steps To Reproduce:**

**Expected behavior:**
Open the logs all the time without issues

**Actual behavior:**
Logs will be open only on many retries.

**Additional context / logs:**
