### ISSUE TITLE
[Backport release-1.24] When Hubble configured with cilium it fails to start

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#3685]
This is a backport issue for https://github.com/rancher/rke2/issues/3683, automatically created via rancherbot by @rbrtbnfgl

Original issue description:

Cluster Configuration:

Configure Hubble with cilium
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
```
**Describe the bug:**

Cilium fails to start

**Steps To Reproduce:**

- Installed RKE2: 
- enable Cilium with the above configuration
- 
**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
