### ISSUE TITLE
[Backport release-1.23] When Hubble configured with cilium it fails to start

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#3686]
This is a backport issue for https://github.com/rancher/rke2/issues/3683, automatically created via rancherbot by @rbrtbnfgl

Original issue description:

Cluster Configuration:

Configure Hubble with cilium
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
```
**Describe the bug:**

Cilium fails to start

**Steps To Reproduce:**

- Installed RKE2: 
- enable Cilium with the above configuration
- 
**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by est-suse** [comment]
Validated on v1.23.15-rc4+rke2r1

Cluster Configuration:

```
1 server
```
Config.yaml:
```
cni: cilium
write-kubeconfig-mode: 644

```

Additional files
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
```


Testing Steps

- Copy config.yaml sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
- sudo cp rke2-cilium-config.yaml /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
- Validate images are present

```
NAME                    STATUS   ROLES                       AGE     VERSION
node/ip-172-31-15-200   Ready    control-plane,etcd,master   5m13s   v1.23.15+rke2r1

NAMESPACE     NAME                                                        READY   STATUS      RESTARTS   AGE
kube-system   pod/cilium-operator-5d66fc5946-2t5cc                        0/1     Pending     0          4m44s
kube-system   pod/cilium-operator-5d66fc5946-g9vv6                        1/1     Running     0          4m44s
kube-system   pod/cilium-th26k                                            1/1     Running     0          4m22s
kube-system   pod/cloud-controller-manager-ip-172-31-15-200               1/1     Running     0          5m8s
kube-system   pod/etcd-ip-172-31-15-200                                   1/1     Running     0          4m43s
kube-system   pod/helm-install-rke2-cilium-6ggpf                          0/1     Completed   0          4m34s
kube-system   pod/helm-install-rke2-coredns-bxnsg                         0/1     Completed   0          4m56s
kube-system   pod/helm-install-rke2-ingress-nginx-j5k8k                   0/1     Completed   0          4m56s
kube-system   pod/helm-install-rke2-metrics-server-px7q9                  0/1     Completed   0          4m56s
kube-system   pod/hubble-relay-5f9b8647bf-xqvzg                           1/1     Running     0          4m28s
kube-system   pod/hubble-ui-76f9dfb455-v4wlb                              2/2     Running     0          4m28s
kube-system   pod/kube-apiserver-ip-172-31-15-200                         1/1     Running     0          4m39s
kube-system   pod/kube-controller-manager-ip-172-31-15-200                1/1     Running     0          5m10s
kube-system   pod/kube-proxy-ip-172-31-15-200                             1/1     Running     0          5m2s
kube-system   pod/kube-scheduler-ip-172-31-15-200                         1/1     Running     0          5m10s
kube-system   pod/rke2-coredns-rke2-coredns-775c5b4bb4-mhrcq              1/1     Running     0          4m44s
kube-system   pod/rke2-coredns-rke2-coredns-autoscaler-695fc554c9-9sn6r   1/1     Running     0          4m44s
kube-system   pod/rke2-ingress-nginx-controller-lrc7w                     1/1     Running     0          3m56s
kube-system   pod/rke2-metrics-server-644f588b5-9g2lm                     1/1     Running     0          4m4s
```

```
sudo /var/lib/rancher/rke2/bin/crictl -r /var/run/k3s/containerd/containerd.sock images|grep hubble
I1214 20:58:07.879428    6252 util_unix.go:103] "Using this endpoint is deprecated, please consider using full URL format" endpoint="/var/run/k3s/containerd/containerd.sock" URL="unix:///var/run/k3s/containerd/containerd.sock"
docker.io/rancher/mirrored-cilium-hubble-relay                  v1.12.4                         3699453eb3e43       14.7MB
docker.io/rancher/mirrored-cilium-hubble-ui-backend             v0.9.2                          7805e70d8cf23       15.5MB
docker.io/rancher/mirrored-cilium-hubble-ui                     v0.9.2                          e7c3d8afc3c6d       12.6MB

```
