### ISSUE TITLE
[Backport release-1.25] Ingress-nginx is missing required RBAC permissions

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#3708]
This is a backport issue for https://github.com/rancher/rke2/issues/3702, automatically created via rancherbot by @dereknola

Original issue description:

**Environmental Info:**
RKE2 Version: 

v1.25.5-rc3+rke2r1, v1.24.9-rc3+rke2r1, v1.23.15-rc3+rke2r1

Node(s) CPU architecture, OS, and Version: 

Any -- tested using SLES 15 SP4

Cluster Configuration:

3 servers 1 agent

**Describe the bug:**

After upgrade to any of the above versions, ingress resources stop working and newly created ingress resources also fail to function properly. There are effectively two issues that are easily seen:
1. The ingress address IPs are not returned on the ingress resource: `kubectl get ingress`
2. `curl`ing what the ingress resource IP should be fails with a 503 error.

After some debugging, it was determined that we are missing roles in the `rke2-ingress-nginx` `clusterrole` related to https://github.com/bitnami/charts/issues/11192. The same error from that issue is seen here in the ingress-nginx pod logs:
`E1213 16:43:09.662046       7 leaderelection.go:330] error retrieving resource lock kube-system/ingress-controller-leader: leases.coordination.k8s.io "ingress-controller-leader" is forbidden: User "system:serviceaccount:kube-system:rke2-ingress-nginx" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"`
After adding those, the ingress-nginx pod logs then give: `E1213 16:57:35.400322       7 reflector.go:140] k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:rke2-ingress-nginx" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope`

It seems the full workaround is to apply the following to `clusterroles/rke2-ingress-nginx` (`kube-system` namespace):
```yaml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
```

**Steps To Reproduce:**

- Installed RKE2 using new version.
- Deploy an ingress resource:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: auto-ingress
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: auto-ingress
  labels:
    k8s-app: nginx-app-ingress
spec:
  rules:
  - host: foo1.bar.com
    http:
      paths:
      - backend:
          service:
            name: nginx-ingress-svc
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: auto-ingress
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-ingress-svc
 namespace: auto-ingress
 labels:
   k8s-app: nginx-app-ingress
spec:
 ports:
 - port: 8080
   targetPort: 8080
   protocol: TCP
   name: http
 selector:
   k8s-app: nginx-app-ingress
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: test-ingress
 namespace: auto-ingress
spec:
 replicas: 2
 selector:
   k8s-app: nginx-app-ingress
 template:
   metadata:
     labels:
       k8s-app: nginx-app-ingress
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: ranchertest/mytestcontainer:unprivileged
       ports:
       - containerPort: 8080
```
- In my testing, I installed previous version then upgraded

**Expected behavior:**

Ingress should function correctly

**Actual behavior:**

Ingress fails

**Additional context / logs:**

All relevant info is in the description
