### ISSUE TITLE
Upgrade controller use v1.25.4+rke2r1 instead of v1.26.0 at latest channel

### ISSUE THREAD

**Issue by VuiDJi** [rancher/rke2#3755]
RKE2 Version: v1.26.0+rke2r1

Cluster Configuration: 3 servers

**Describe the bug:**
I've deployed RKE2 cluster v 1.24.7 (3 servers) few months ago.

Few days ago I created upgrade plan:
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
       - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists  
  cordon: true
  drain:
    force: true
  upgrade:
    image: rancher/rke2-upgrade
  channel: https://update.rke2.io/v1-release/channels/latest
```

Upgrade controller updated all cluster servers to v1.26.0.

However, today I've noticed, that some upgrading process is running. Looking at the Rancher nodes page I was supprised, because on of servers was downgraded to v1.25.4-rke2r1, and after 10 minutes all servers started working on version v1.25.4-rke2r1.

As it turned out, URL https://update.rke2.io/v1-release/channels/latest now redirects to URL https://github.com/rancher/rke2/releases/tag/v1.25.4+rke2r1 instead of https://github.com/rancher/rke2/releases/tag/v1.26.0+rke2r1

<img width="504" alt="image" src="https://user-images.githubusercontent.com/44698/211106542-1414908e-66f2-40ed-8248-651673d74ec7.png">

**Expected behavior:**
https://update.rke2.io/v1-release/channels/latest redirects to https://github.com/rancher/rke2/releases/tag/v1.26.0+rke2r1, even if new version of v1.25 has been released.

**Actual behavior:**
https://update.rke2.io/v1-release/channels/latest redirects to https://github.com/rancher/rke2/releases/tag/v1.25.4+rke2r1
