### ISSUE TITLE
Worker Nodes lose their metrics connection

### ISSUE THREAD

**Issue by venomone** [rancher/rke2#3803]
Hello,

since a couple of days I'm using RKE2 now, most things are running smoothly, but for some reason one of my worker nodes never has a metrics connection, in sum I have 4 workers were always just 3 of them of them report their metrics.
I also have tried to drain the worker and restart it, then I get back the metrics for this specific worker, but the issue then occurs with the next worker, and I'm back in this 3/4 workers reporting their metrics situation.

I currently can only say that this issue occurs as soon as I spin up my Galera Clusters, this is the manifest of the statefulset I'm using to run Galera:

```

apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera
  namespace: test
  labels:
    app: mariadb-galera
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      nodePort: null
  selector:
    app: mariadb-galera
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mariadb-galera-hpa
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mariadb-galera
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-headless
  namespace: test
  labels:
    app: mariadb-galera
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: galera
      port: 4567
      targetPort: galera
    - name: ist
      port: 4568
      targetPort: ist
    - name: sst
      port: 4444
      targetPort: sst
  selector:
    app: mariadb-galera
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-galera
  namespace: test
  labels:
    app: mariadb-galera
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app: mariadb-galera
  serviceName: mariadb-galera
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb-galera
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: mariadb-galera
          image: docker.io/bitnami/mariadb-galera:10.3.37-debian-11-r22
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -ec
            - |
                exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
          envFrom:
            - configMapRef:
                name: mariadb-galera-env
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MARIADB_GALERA_CLUSTER_NAME
              value: "galera"
            - name: MARIADB_GALERA_CLUSTER_ADDRESS
              value: "gcomm://mariadb-galera-headless.test.svc.cluster.local"
            - name: MARIADB_ROOT_USER
              value: "root"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root-pwd
                  key: password
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pwd
                  key: password
            - name: MARIADB_DATABASE
              value: "app"
            - name: MARIADB_GALERA_MARIABACKUP_USER
              value: mariabackup
            - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-galera-mariabackup-password
                  key: password
            - name: MARIADB_ENABLE_LDAP
              value: "no"
            - name: MARIADB_ENABLE_TLS
              value: "no"
          ports:
            - name: mysql
              containerPort: 3306
            - name: galera
              containerPort: 4567
            - name: ist
              containerPort: 4568
            - name: sst
              containerPort: 4444
          livenessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  exec mysqladmin status -u$MARIADB_ROOT_USER -p$MARIADB_ROOT_PASSWORD
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  exec mysqladmin status -u$MARIADB_ROOT_USER -p$MARIADB_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 750m
              memory: 3072Mi
            limits:
              cpu: 2500m
              memory: 6144Mi
          volumeMounts:
            - name: previous-boot
              mountPath: /opt/bitnami/mariadb/.bootstrap
            - name: data
              mountPath: /bitnami/mariadb
            - name: mariadb-galera-config
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: previous-boot
          emptyDir: {}
        - name: mariadb-galera-config
          configMap:
            name: mariadb-galera-configuration
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: mariadb-galera
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 50Gi
```

What I do not understand is, why does my statefulset with Galera interrupt the metrics exchange?
It seems that as soon as the worker hosts mariadb-galera-0 the metric die for this worker ...?!

I'm running on rancher 2.7.0 and my RKE version is v1.24.8+rke2r1.
All machines are running the AMD Epic Rome Architecture.  All workers have at least 32GB of RAM and at least 10 CPU cores, all KVM virtualized, all interconnected with at least 2,5 Gbit/s.
