### ISSUE TITLE
kube-apiserver is unable to start with kube-apiserver-arg values

### ISSUE THREAD

**Issue by kursattokpinar** [rancher/rke2#3820]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.26.0+rke2r2 (c1c17943417cea06948ba10b04854455fbf47aea)
go version go1.19.3 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux master01 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
When the option `--enable-admission-plugins=NodeRestriction,PodSecurityPolicy,EventRateLimit,AlwaysPullImages,ServiceAccount` is added to the `kube-apiserver-arg` field in the config.yaml file, the kube-apiserver service is unable to start. Similarly, if the option `--event-qps=0` is also added, the same issue occurs. This can be observed by checking the logs from journalctl, which will show repeated error messages.
```
Jan 21 01:48:29 master01 rke2[44831]: time="2023-01-21T01:48:29+03:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Jan 21 01:48:32 master01 rke2[44831]: time="2023-01-21T01:48:32+03:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```
Here is the failing version of config.yaml:
```yaml
tls-san:
- master.cluster1.bulutarti.internal
cluster-domain: cluster1.bulutarti.internal
profile: cis-1.23
node-taint:
- "CriticalAddonsOnly=true:NoExecute"
kube-apiserver-arg:
- "--enable-admission-plugins=NodeRestriction,PodSecurityPolicy,EventRateLimit,AlwaysPullImages,ServiceAccount"
- "--admission-control-config-file=/etc/rke2/eventratelimit.yaml"
- "--audit-policy-file=/etc/rke2/audit-policy.yaml"
#- "--event-qps=0" 
```
The outcome is the same if either of the following scenarios are executed:

The parameter `--event-qps=0` is added while all other lines are removed
The parameter `--event-qps=0` is added while all other lines remain unchanged.

Here is the running version of the config.yaml
```yaml
tls-san:
- master.cluster1.bulutarti.internal
cluster-domain: cluster1.bulutarti.internal
profile: cis-1.23
node-taint:
- "CriticalAddonsOnly=true:NoExecute"
kube-apiserver-arg:
#- "--enable-admission-plugins=NodeRestriction,PodSecurityPolicy,EventRateLimit,AlwaysPullImages,ServiceAccount"
#- "--admission-control-config-file=/etc/rke2/eventratelimit.yaml"
- "--audit-policy-file=/etc/rke2/audit-policy.yaml"
#- "--event-qps=0"
```

**Steps To Reproduce:**

- Installed RKE2: 
```
curl -sfL https://get.rke2.io --output install.sh
chmod +x install.sh
export INSTALL_RKE2_VERSION=v1.26.0+rke2r2 INSTALL_RKE2_TYPE=server && ./install.sh
```
- Set kernel parameters:
```
sudo cp -f /usr/local/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/60-rke2-cis.conf
sudo systemctl restart systemd-sysctl
```
- Started the daemon
```
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

**Expected behavior:**
We must be able to see a log line contains following and kube-apiserver must be up and running:
`"Kube API server is now running"`

**Actual behavior:**
Kube API server never became up and running. `systemctl start rke2-server.service` command is failing with the following lines:
```
Job for rke2-server.service failed because the control process exited with error code.
See "systemctl status rke2-server.service" and "journalctl -xe" for details.
```

**Additional context / logs:**
For the failing scenario there is no log lines are emitted under this directory: `/var/lib/rancher/rke2/server/logs`
Content of the `eventratelimit.yaml` is as follows:
```yaml
apiVersion: v1
kind: Configuration
limits:
- type: Pod
  qps: 10
  burst: 20
```
