### ISSUE TITLE
create image use harbor `x509: certificate signed by unknown authority`

### ISSUE THREAD

**Issue by baerwang** [rancher/rke2#3904]
# build jobs
## use openssl tls
...

## rke2 version

```shell
kubectl get nodes
```

```
NAME     STATUS   ROLES                  AGE     VERSION
master   Ready    control-plane,master   3d22h   v1.24.10+k3s1
```

## create registries.yaml

```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://wxx.com"
configs:
  "https://wxx.com":
    auth:
      username: rxxx
      password: xxxxxRc
    tls:
      cert_file: ca.crt
      key_file: ca.key
      ca_file: xxx.cert
      insecure_skip_verify: true
```
## restart rke2

```shell
systemctl restart rke2-server
```

## see containerd config.toml

```shell
cat /var/lib/rancher/rke2/agent/etc/containerd/config.toml
```

<img width="793" alt="image" src="https://user-images.githubusercontent.com/52104949/218702341-3d452211-9ad6-444f-9d9c-2af7fb3dd300.png">

## test harbor api

```shell
curl -sk https://wxx.com/v2/wxx/wxx-test/manifests/v1.x
```

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/52104949/218701675-b567dd68-247d-44a0-96e8-d5f1b144bc71.png">

## kubectl describe xxx

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/52104949/218702817-6e4c9a50-e0b1-4e24-84a4-e9f6ef019ec4.png">

## Valid here in k3s
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/52104949/218703280-4ae99f36-dab4-4044-abcc-85e17c9062a6.png">

## use docker login 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/52104949/218703441-624728a2-e74a-421d-82de-355a6fa7e667.png">
