### ISSUE TITLE
ClusterRole 'view' don´t work for CRDs

### ISSUE THREAD

**Issue by tgruenert** [rancher/rke2#4045]
**Environmental Info:**
RKE2 Version: v1.25.5+rke2r2

**Describe the bug:**
As a user based on ClusterRole 'view' i can´t list instances of CRDs. So it is impossible to view a CRD object as 'Viewer'.

**Steps To Reproduce:**
ClusterRole 'view'
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - Application
      - ApplicationSet
      - AppProject

...

aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: 'true'

``` 
As a user of ClusterRole 'view' i get
```
$ kubectl auth can-i --list | grep argoproj
AppProject.argoproj.io                                 []                  []               [get list watch]
ApplicationSet.argoproj.io                             []                  []               [get list watch]
Application.argoproj.io                                []                  []               [get list watch]
```
but 
```
$ kubectl get apps -n argocd
Error from server (Forbidden): applications.argoproj.io is forbidden: User "tg@****.com" cannot list resource "applications" in API group "argoproj.io" in the namespace "argocd"
```

**Expected behavior:**
As a user of ClusterRole 'view' CRDs should be listable and readable.

Any hints where i should adapt my settings are welcome.
