### ISSUE TITLE
Bump coredns to v1.10.1

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4073]
coredns 1.10.1 is out, and upstream is using it. So should we.

**Comment by bguzman-3pillar** [comment]
### Validated on commit `be54040d8e8591cb2e6b2705df6308830f33de00`
  
## Environment Details

  
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
  
*Cluster Configuration:*

```
1 server
```
  
*Config.yaml:*

```
```
  
*Additional files*

```
cat dep.yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: auto-dns
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: auto-dns
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
  
## Testing Steps

1. Install RKE2 `sudo curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=be54040d8e8591cb2e6b2705df6308830f33de00 sh -`
2. Look for coredns `v1.10.1`


 
**Validation Results:**

```
$ kubectl get all -l k8s-app=kube-dns -n kube-system -o wide
NAME                                            READY   STATUS    RESTARTS   AGE    IP          NODE              NOMINATED NODE   READINESS GATES
pod/rke2-coredns-rke2-coredns-f6f4ff467-mcm2d   1/1     Running   0          6m3s   10.42.0.3   ip-172-31-41-33   <none>           <none>

NAME                                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE    SELECTOR
service/rke2-coredns-rke2-coredns   ClusterIP   10.43.0.10   <none>        53/UDP,53/TCP   6m3s   app.kubernetes.io/instance=rke2-coredns,app.kubernetes.io/name=rke2-coredns,k8s-app=kube-dns

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES                                           SELECTOR
deployment.apps/rke2-coredns-rke2-coredns   1/1     1            1           6m3s   coredns      rancher/hardened-coredns:v1.10.1-build20230406   app.kubernetes.io/instance=rke2-coredns,app.kubernetes.io/name=rke2-coredns,k8s-app=kube-dns

NAME                                                  DESIRED   CURRENT   READY   AGE    CONTAINERS   IMAGES                                           SELECTOR
replicaset.apps/rke2-coredns-rke2-coredns-f6f4ff467   1         1         1       6m3s   coredns      rancher/hardened-coredns:v1.10.1-build20230406   app.kubernetes.io/instance=rke2-coredns,app.kubernetes.io/name=rke2-coredns,k8s-app=kube-dns,pod-template-hash=f6f4ff467
```

```
$ kubectl exec -n auto-dns -t dnsutils -- nslookup kubernetes.default
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.43.0.1

```
 

```
```
 
**Additional context / logs:**
```
```
