### ISSUE TITLE
rke2-calico chart is wrong pro Felixconfiguration

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#4091]
The current rke2-calico chart sets `failsafeInboundHostPorts` and `failsafeOutboundHostPorts` using this part of chart (`templates/felixconfig.yaml`):
```
  failsafeInboundHostPorts: {{ .Values.felixConfiguration.failsafeInboundHostPorts }}
  failsafeOutboundHostPorts: {{ .Values.felixConfiguration.failsafeOutboundHostPorts }}
```

however, according to calico documentation, these two items need array of maps:
https://docs.tigera.io/calico/latest/reference/resources/felixconfig
like:
```
failsafeInboundHostPorts:
- protocol: tcp
  port: 22
- protocol: udp
  port: 68
- protocol: tcp
  port: 179
```

and I believe, it is not possible to set it via this `failsafeInboundHostPorts: {{ .Values.felixConfiguration.failsafeInboundHostPorts }}` construct. Or is it?
