### ISSUE TITLE
[Backport release-1.26] Update Cilium to v1.13.2 for security/bug fixes

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#4172]
This is a backport issue for https://github.com/rancher/rke2/issues/4159, automatically created via rancherbot by @rbrtbnfgl

Original issue description:

### Discussed in https://github.com/rancher/rke2/discussions/4158

<div type='discussions-op-text'>

<sup>Originally posted by **Jamison1** April 28, 2023</sup>
Cilium 1.13.2 addresses many security/bug fixes along with a memory leak issue present in v1.13.0
[Debug mode leak](https://github.com/cilium/cilium/security/advisories/GHSA-pg5p-wwp8-97g8)
[Potential network policy bypass](https://github.com/cilium/cilium/security/advisories/GHSA-8fg8-jh2h-f2hc)
[cilium-agent container can access the host](https://github.com/cilium/cilium/security/advisories/GHSA-4hc4-pgfx-3mrx)
[Cilium eBPF filters may be temporarily removed](https://github.com/cilium/cilium/security/advisories/GHSA-r5x6-w42p-jhpp)

I looked into replacing the builtin chart but I see it is pinned to rke2-cilium-1.13.000.tgz
```
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-cilium/rke2-cilium-1.13.000.tgz
```

Any idea how this can be done on my end?

I'm using a HelmChartConfig, but guessing it is not user changeable like this as the chartContent may also need to be updated.
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    metadata:
      annotations:
        helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-cilium/rke2-cilium-1.13.200.tgz
```
</div>
