### ISSUE TITLE
1.27.1 server fails to start due to aws cloud-provider-name

### ISSUE THREAD

**Issue by daniel-palmer-gu** [rancher/rke2#4183]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.27.1+rke2r1 (9ce3825ec005872a0873307844ba99a2bdd4ee19)
go version go1.20.3 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux <redacted> 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**
Not sure if I am missing something in the changelog for 1.27.x but adding `cloud-provider-name: aws` to the rke2 config results in the server not starting

This is still listed as a valid option (although it doesn't have the valid values) in the docs here: https://docs.rke2.io/reference/server_config

**Steps To Reproduce:**
- Installed RKE2: 

config.yaml:
```yaml
profile: cis-1.23
disable:
  - "rke2-ingress-nginx"
selinux: true
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"

write-kubeconfig-mode: "0640"

token: <redacted>
cloud-provider-name: aws
 ```

**Expected behavior:**
Server is able to start

**Actual behavior:**
Server fails to start. See logs below.

**Additional context / logs:**
This configuration worked on 1.26.4 but is now failing on 1.27.1

Relevant kubelet logs:
```
I0508 19:05:36.802408    2488 server.go:415] "Kubelet version" kubeletVersion="v1.27.1+rke2r1"
I0508 19:05:36.802480    2488 server.go:417] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
E0508 19:05:36.802807    2488 run.go:74] "command failed" err="failed to run Kubelet: unknown cloud provider \"aws\""
```
