### ISSUE TITLE
Update vSphere CPI/CSI charts

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4275]
RKE2 tracking issue for:
* https://github.com/rancher/rancher/issues/40908
* https://github.com/rancher/rancher/issues/41017
* https://github.com/rancher/rancher/issues/41098
* https://github.com/rancher/rancher/issues/41626

**Comment by rancher-max** [comment]
### Validated using v1.27.2-rc2+rke2r1 in Rancher v2.7-head commit `fbca7c3`

- Validated chart versions:
```
rancher-vsphere-cpi:1.5.100 
rancher-vsphere-csi:3.0.1-rancher100 
rke2-snapshot-controller:1.7.202
rke2-snapshot-controller-crd:1.7.202 
rke2-snapshot-validation-webhook:1.7.101 
```
- ProviderID set on all nodes:
```
$ kubectl describe nodes | grep -i providerid
ProviderID:                   vsphere://420873b0-4186-f99d-a3db-7c61a276ca8a
ProviderID:                   vsphere://4208a48f-bba5-6553-5d2d-a4e997d27fcd
ProviderID:                   vsphere://42081bb3-ee92-0698-41dd-ca660fa063e6
ProviderID:                   vsphere://42085d71-436c-6855-5c1e-c724eba88183
```
- Deploying pvc and pod functions correctly by deploying in vsphere datastore:
```yaml
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```
<img width="670" alt="image" src="https://github.com/rancher/rke2/assets/55997940/5dc9f102-7437-471e-87d5-616a80aa662b">

---

Although all charts seemed to deploy and everything seemed to function as expected, the vsphere-csi helm install is CrashLooping. I feel this is a false error, as this cluster is 1.27 created in Rancher where it's unsupported. Will see what happens with 1.26/1.25/1.24 and in a standalone setup to confirm, but these are the logs on the chart:
```
$ k logs -n kube-system pod/helm-install-rancher-vsphere-csi-2stj7
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
        echo "KUBERNETES_SERVICE_HOST is using IPv6"
        CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
        CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ true != \t\r\u\e ]]
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ shopt -s nullglob
+ [[ -f /config/ca-file.pem ]]
+ [[ -f /tmp/ca-file.pem ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/rancher-vsphere-csi.tgz.base64
+ CHART_PATH=/tmp/rancher-vsphere-csi.tgz
+ [[ ! -f /chart/rancher-vsphere-csi.tgz.base64 ]]
+ base64 -d /chart/rancher-vsphere-csi.tgz.base64
+ CHART=/tmp/rancher-vsphere-csi.tgz
+ set +e
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ [[ /tmp/rancher-vsphere-csi.tgz == stable/* ]]
+ [[ -n '' ]]
+ helm_update install --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ tr '[:upper:]' '[:lower:]'
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ helm_v3 ls --all -f '^rancher-vsphere-csi$' --namespace kube-system --output json
+ LINE=3.0.1-rancher1,failed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-10_HelmChartConfig.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ 3.0.1-rancher1 =~ ^(|null)$ ]]
+ [[ failed =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ failed == \d\e\p\l\o\y\e\d ]]
+ [[ failed =~ ^(deleted|failed|null|unknown)$ ]]
+ [[ reinstall == \r\e\i\n\s\t\a\l\l ]]
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ echo 'Uninstalling failed helm_v3 chart'
+ helm_v3 uninstall rancher-vsphere-csi --namespace kube-system
release "rancher-vsphere-csi" uninstalled
+ echo Deleted
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 rancher-vsphere-csi /tmp/rancher-vsphere-csi.tgz --values /config/values-10_HelmChartConfig.yaml
Deleted
Error: INSTALLATION FAILED: 1 error occurred:
        * deployments.apps "vsphere-csi-controller" already exists
```
