### ISSUE TITLE
[Backport release-1.24] Update vSphere CPI/CSI charts

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#4278]
This is a backport issue for https://github.com/rancher/rke2/issues/4275, automatically created via rancherbot by @brandond

Original issue description:

RKE2 tracking issue for:
* https://github.com/rancher/rancher/issues/40908
* https://github.com/rancher/rancher/issues/41017
* https://github.com/rancher/rancher/issues/41098
* https://github.com/rancher/rancher/issues/41626

**Comment by mdrahman-suse** [comment]
## Validated with v1.24.14-rc3+rke2r1

From Rancher

<img width="1584" alt="Screen Shot 2023-05-30 at 2 54 51 PM" src="https://github.com/rancher/rke2/assets/91496375/d09d4385-246a-4ca6-aba1-28d7cd380831">

- Uploaded pvc.yaml and bound to pod
```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```
```
> kubectl get pvc -A
NAMESPACE   NAME     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
default     claim2   Bound    pvc-c46176d4-75b2-4a6e-b61d-00b8bf6b6cc2   1Gi        RWO            vsphere-csi-sc   2m4s

> kubectl describe pvc claim2
Name:          claim2
Namespace:     default
StorageClass:  vsphere-csi-sc
Status:        Bound
Volume:        pvc-c46176d4-75b2-4a6e-b61d-00b8bf6b6cc2
Labels:        objectset.rio.cattle.io/hash=d5135b4a9ccf177a208eb99fbc10a009731e793d
Annotations:   objectset.rio.cattle.io/applied:
...
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       basic
Events:
  Type    Reason                 Age    From                                                                                                 Message
  ----    ------                 ----   ----                                                                                                 -------
  Normal  ExternalProvisioning   2m50s  persistentvolume-controller                                                                          waiting for a volume to be created, either by external provisioner "csi.vsphere.vmware.com" or manually created by system administrator
  Normal  Provisioning           2m50s  csi.vsphere.vmware.com_vsphere-csi-controller-7849fdb4cb-2vjjk_69c0af75-f26f-43c2-9867-98f1d7e997b5  External provisioner is provisioning volume for claim "default/claim2"
  Normal  ProvisioningSucceeded  2m49s  csi.vsphere.vmware.com_vsphere-csi-controller-7849fdb4cb-2vjjk_69c0af75-f26f-43c2-9867-98f1d7e997b5  Successfully provisioned volume pvc-c46176d4-75b2-4a6e-b61d-00b8bf6b6cc2
```
- Check providerID is vsphere
```
>  kubectl describe nodes | grep -i providerid
ProviderID:                   vsphere://42084db1-8d7a-cae2-cbc4-4b8b2b998bf0
ProviderID:                   vsphere://4208e8d1-df8e-9934-b6e6-670cd6e53953
ProviderID:                   vsphere://4208455c-5110-b210-d419-a58a5abdd760
ProviderID:                   vsphere://4208ce73-e4df-b515-dcde-166deb50c4ff
```
