### ISSUE TITLE
[Backport release-1.25] Failing secret webhook causes unexpected behavior

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#4330]
This is a backport issue for https://github.com/rancher/rke2/issues/4266, automatically created via rancherbot by @brandond

Original issue description:

**Environmental Info:**
RKE2 Version: v1.26.4+rke2r1

Node(s) CPU architecture, OS, and Version: 
Not relevant. 

Cluster Configuration:
1 server node

**Describe the bug:**
The existing of a set of failing webhook configurations in a cluster blocks RKE2 server from starting up successfully, but RKE2 server still happily starts up pretending like nothing is wrong.

**Steps To Reproduce:**
1. Install RKE2 server
2. Let it come up and become healthy
3. Remove the `kube-controller-manager.yaml` static pod manifest from `/var/lib/rancher/rke2/agent/pod-manifests`
4. Restart `rke2-server` 
5. See `kube-controller-manager` never comes back online

**Expected behavior:**
`rke2-server` errors out on startup, starts failing, or something more useful than just silently failing.

**Actual behavior:**
`rke2-server` silently fails creating the `kube-controller-manager` manifest and the coordinator is stuck without proper feedback as to the fact that `rke2-server` is not really healthy beyond looking at symptoms.

**Additional context / logs:**
I hit this when manually validating: 

The `rke2-server` log message was: 
```
May 19 15:03:43 kskcm-pool1-2876d649-4xn4n rke2[17126]: time="2023-05-19T15:03:43Z" level=warning msg="Failed to create Kubernetes secret: Internal error occurred: failed calling webhook \"rancher.cattle.io.secrets\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation/secrets?timeout=10s\": context deadline exceeded"
```

There is a corresponding `rancher/rancher` issue filed here: https://github.com/rancher/rancher/issues/41613 but while this will fix this instance of the "storm", it is not a holistic solution as there may be other webhook configurations that manipulate secrets (OPA?)

**Comment by mdrahman-suse** [comment]
## Validated using RC
```console
$ rke2 -v
rke2 version v1.25.11-rc3+rke2r1 (32743355da1b2628a4a880ce150f05fe8647aaf9)
go version go1.19.10 X:boringcrypto
```
### Environment details
*Infrastructure*
Cloud

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 22.04

*Cluster Configuration*
1 server, 1 agent
- config.yaml
```
write-kubeconfig-mode: 644
token: summer
```
*Additional files*
- cat wh.yaml
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: https://httpbin.org/status/502
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.secrets
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - secrets
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
```
### Testing Steps

1. Install rke2
2. Apply a bad webhook configuration wh.yaml (this one just calls out to httpbin.org for a 502 error response)
3. Attempt to join a new agent
4. Ensure the agent node joins successfully

### Replicated using v1.25.10+rke2r1
- Observed that the agent was unable to join after applying the wh.yaml and logs the error below
```console
Jun 21 17:34:32  rke2[1591]: time="2023-06-21T17:34:32Z" level=error msg="Internal error occurred: failed calling webhook \"rancher.cattle.io.secrets\": failed to call webhook: an error on the server (\"\") has prevented the request from succeeding"
Jun 21 17:34:40  rke2[1591]: time="2023-06-21T17:34:40Z" level=error msg="Internal error occurred: failed calling webhook \"rancher.cattle.io.secrets\": failed to call webhook: Post \"https://httpbin.org/status/502?timeout=5s\": context deadline exceeded"
```
<details>
<summary>Issue Validation</summary>

- No errors were observed
- Agent joined successfully after applying wh.yaml
```console
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-xxx-xx-xx-1     Ready    <none>                      3m   v1.25.11+rke2r1
ip-xxx-xx-xx-216   Ready    control-plane,etcd,master   5m   v1.25.11+rke2r1
```

</details>
