### ISSUE TITLE
Validate Rocky 9.2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4350]
**RKE2 Versions to be Validated**

- 1.27
- 1.26

**Testing Considerations**

_QA to edit as necessary_
1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade

**Additional Information**

**Jira Ticket**: https://jira.suse.com/browse/SURE-6485

This should be validated in a hardened setup:
```yaml
# /etc/rancher/rke2/config.yaml
profile: cis-1.23
selinux: true
```
