### ISSUE TITLE
Validate RHEL 9.2

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#4352]
**RKE2 Versions to be Validated**

- 1.27
- 1.26

**Testing Considerations**

_QA to edit as necessary_
1. Install and run sonobuoy conformance tests on a hardened cluster
2. Validate SUC upgrade

**Additional Information**

**Jira Ticket**: https://jira.suse.com/browse/SURE-6485

This should be validated in a hardened setup:
```yaml
# /etc/rancher/rke2/config.yaml
profile: cis-1.23
selinux: true
```

**Comment by aganesh-suse** [comment]
RHEL 9.2 Sonobuoy tests:
v1.26.5
https://jenkins.int.rancher.io/job/rancher_qa/view/common-Jobs/job/rancher-v3_sonobuoy_test/73/
v1.27.2
https://jenkins.int.rancher.io/job/rancher_qa/view/common-Jobs/job/rancher-v3_sonobuoy_test/74/

**Comment by aganesh-suse** [comment]
Using sample config:
```
cat /etc/rancher/rke2/config.yaml
token: secret
profile: cis-1.23
selinux: true
protect-kernel-defaults: true
cni: canal
node-external-ip: 52.15.223.138
write-kubeconfig-mode: "0644"
```
Special privilege for system-upgrade namespace in CRD: kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/[v0.11.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.11.0-dev.1)/system-upgrade-controller.yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    # We are setting these to our _desired_ `enforce` level.
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
```

was able to install and upgrade from v1.25.10 to 1.26.5 to 1.27.2 after setting the privilege for system-upgrade namespace.
