### ISSUE TITLE
Registry mirror fallback never worked even containerd configured with multiple endpoints

### ISSUE THREAD

**Issue by zeddit** [rancher/rke2#4383]
My configuration for rke2 registries.yaml looks like below:
```
mirrors:
  docker.io:
    endpoint:
      - "https://harbor.xxx.com/v2/docker.io"
      - "https://registry-1.docker.io"
      - "https://hub.docker.com"
``` 
I expect the image will be downloaded from my private self-hosted harbor by default.
and if the harbor went down, the image will fallback to use the second registry which would be `registry-1.docker` to download the image.
and if the second one is still down, it goes to `hub.docker.com` to find the image.

however, under my test, if my harbor goes down, it would never fallback to the next one to pull the image, and stuck forever until the harbor recovery.

I wonder if my configuration is wrong or there's a bug in implementation. thanks.
