### ISSUE TITLE
[Backport release-1.25] Support "windows-bgp" mode in Calico for Windows

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#4458]
This is a backport issue for https://github.com/rancher/rke2/issues/3945, automatically created via rancherbot by @rbrtbnfgl

Original issue description:

**Is your feature request related to a problem? Please describe.**
Currently the rke2 executable sets Calico in vxlan mode by default (as per https://github.com/rancher/rke2/issues/3380)
Even with "cni: none" set, once a Calico manifest is deployed to the cluster, the deployed Windows nodes still deploy calico with the hardcoded vxlan mode, preventing any ability to manually deploy Calico on the node with the required settings.

**Describe the solution you'd like**
Support the ability to either change the CNI config.yaml from vxlan to windows-bgp, or allow for BGP to be enabled in the installation file at cluster creation

**Describe alternatives you've considered**
There's no way to currently prevent rke2 from deploying Calico so no alternatives seem to have worked from what I've tried.

**Additional context**
The reason for requiring windows-bgp mode is to support load balancing of pods directly from an external load balancer. There's no easy way to add an external non k8s node to participate in vxlan with Calico unlike flannel.

**Comment by est-suse** [comment]
Validated on branch 1.25 https://github.com/k3s-io/k3s/commit/cc87f300a42060b37fd89f7a034b5485b8a758cc

```
rke2 version v1.25.11-dev+cc87f300 (cc87f300a42060b37fd89f7a034b5485b8a758cc)
go version go1.19.10 X:boringcrypto
```
Environment Details

Infrastructure
Cloud EC2 instance


Node(s) CPU architecture, OS, and Version:
Ubuntu 22.04

Cluster Configuration:
1 server 1 Windows agent

Config.yaml
```
token: secret
write-kubeconfig-mode: 644
cni: calico
```

Validation Steps:
```
Install rke2 
BGP enabled on the helm config:

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 10.42.0.0/16
          blockSize: 24
```

On the windows node:
```
Setup Windows node:
Install the required services using the following Powershell commands:

Install-WindowsFeature RemoteAccess
Install-WindowsFeature RSAT-RemoteAccess-PowerShell
Install-WindowsFeature Routing
Restart the node:

Restart-Computer -Force
Configure the RemoteAccess service:

Install-RemoteAccess -VpnType RoutingOnly
Start the RKE2 service following the [quickstart documentation](https://docs.rke2.io/install/quickstart#windows-agent-worker-node-installation)

```
