### ISSUE TITLE
rke2 agent Kubelet exited: exit status 1 in selinux true hardened environment

### ISSUE THREAD

**Issue by uchalasani** [rancher/rke2#4512]
**Environmental Info:**
RKE2 Version: 
v1.27.2+rke2r1

Node(s) CPU architecture, OS, and Version: 

Linux ktdso1 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Linux ktdso2 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

I tested with all 3 server nodes. That seems to come up fine. But when I uninstalled and re-installing with either 2servers/1agent or 1server/2agents, Only the first server is coming up.

**Describe the bug:**

Only first server node comes up and the remaining are failing to join the cluster.
journalctl -u rke2-agent -f
-- Logs begin at Wed 2023-07-26 14:58:44 EDT. --
Jul 26 15:22:13 ktdso2 rke2[1527]: time="2023-07-26T15:22:13-04:00" level=error msg="Kubelet exited: exit status 1"
Jul 26 15:22:18 ktdso2 rke2[1527]: time="2023-07-26T15:22:18-04:00" level=error msg="Kubelet exited: exit status 1"

**Steps To Reproduce:**

- Installed RKE2: 
**using First Server config file and Tar method using Ansible:**
```yaml
node-label:
  - "nodeload=control"
debug: false
write-kubeconfig-mode: "0644"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
token: <CustomPrefix>-rke2-v1-27-2-2023-07-10
tls-san:
  - rancher.<PrivateDomain>
  - 127.0.0.1
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
selinux: true
system-default-registry: "<PrivateDockerRegistryServerName>:5000"
```

**Second Agent Node config file:**
```yaml
token: <CustomPrefix>-rke2-v1-27-2-2023-07-10
server: https://rancher.<PrivateDomain>:9345
write-kubeconfig-mode: "0644"
tls-san:
  - rancher.<PrivateDomain>
  - 127.0.0.1
node-label:
  - "nodeload=medium"
  - "node-role.kubernetes.io/worker=true"
selinux: true
```

**Expected behavior:**

kubectl get nodes -o wide: .hould display all 3 nodes/

**Actual behavior:**

See only 1 first server node shows up, but not the rest of the 2 more nodes.
kubectl get nodes -o wide
NAME     STATUS   ROLES                       AGE   VERSION          INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
ktdso1   Ready    control-plane,etcd,master   46m   v1.27.2+rke2r1   <Private IP>   <none>        CentOS Linux 7 (Core)   3.10.0-1160.92.1.el7.x86_64   containerd://1.7.1-k3s1

**Additional context / logs:**

None
