### ISSUE TITLE
Cannot customize canal pod resources

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#4525]
*From @AJMansfield in https://github.com/rancher/rke2-charts/pull/359*

> Add additional `resources` helm value configuration options to `rke2-canal`. It replaces the previously-hardcoded 250m CPU request on the `calico-node` container with a helm-configured request, and also adds the option to the `flannel-node` container.

The pod resource requests are currently hardcoded, and cannot be customized by chart values.

**Comment by rancherbot** [comment]
@rancher-max, Not creating `backport` issue for issue `4525` in repository `rke2` because milestone `v1.24.17+rke2r1` does not exist or is not an open milestone

**Comment by aganesh-suse** [comment]
Validated on commit: e0e231e8d082730dd5dc82fc335ad0e570729a77 on master branch

OS: Ubuntu 22.04
Configuration: 1 server/ 1 agent

Validation Steps followed: 

1. /etc/rancher/rke2/config.yaml content: 
```
token: secret
write-kubeconfig-mode: "0644"
cni: canal
```
2. Create directory: /var/lib/rancher/rke2/server/manifests
3. Push file content in this directory: custom_manifest.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    calico:
      resources:
        requests:
          cpu: 350m
          memory: 128Mi
        limits:
          cpu: 350m
          memory: 256Mi
    flannel:
      resources:
        requests:
          memory: 32Mi
          cpu: 200m
        limits:
          memory: 128Mi
          cpu: 550m          
```
Refer to 
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/values.yaml
for changing values ^^
4. Install RKE2 and start service: 
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='e0e231e8d082730dd5dc82fc335ad0e570729a77' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
5. Enable RKE2 service. 
```
sudo systemctl enable --now rke2-server
```
6. Apply the custom_manifest.yaml
```
kubectl apply -f /var/lib/rancher/rke2/server/manifests/custom_manifest.yaml
```
7. Get pod name for rke2-canal: 
```
kubectl get pods -A | grep canal
```
8. Get the yaml config details for the canal pods/daemonset
```
kubectl get pod rke2-canal-2vgsv -n kube-system -o yaml
```

Results: 

On the validation setup: 
```
rke2 -v
rke2 version v1.27.4+dev.e0e231e8 (e0e231e8d082730dd5dc82fc335ad0e570729a77)
go version go1.20.5 X:boringcrypto
```
Updated pod yaml contained : 
```
kubectl get pod rke2-canal-mqgns -n kube-system -o yaml
    name: calico-node
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: localhost
        path: /readiness
        port: 9099
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      limits:
        cpu: 350m
        memory: 256Mi
      requests:
        cpu: 350m
        memory: 128Mi

    name: kube-flannel
    resources:
      limits:
        cpu: 550m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 32Mi
```



On the reproduced setup with version: v1.27.4+rke2r1
```
rke2 -v
rke2 version v1.27.4+rke2r1 (3aaa57a9608206d95eeb9ce3f79c0ec2ea912b20)
go version go1.20.5 X:boringcrypto
```
```
 kubectl get pod rke2-canal-2vgsv -n kube-system -o yaml
    name: calico-node
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: localhost
        path: /readiness
        port: 9099
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 250m

    name: kube-flannel
    resources: {}
```
