### ISSUE TITLE
[Backport release-1.25] Cannot customize canal pod resources

### ISSUE THREAD

**Issue by rancherbot** [rancher/rke2#4531]
This is a backport issue for https://github.com/rancher/rke2/issues/4525, automatically created via rancherbot by @rancher-max

Original issue description:

*From @AJMansfield in https://github.com/rancher/rke2-charts/pull/359*

> Add additional `resources` helm value configuration options to `rke2-canal`. It replaces the previously-hardcoded 250m CPU request on the `calico-node` container with a helm-configured request, and also adds the option to the `flannel-node` container.

The pod resource requests are currently hardcoded, and cannot be customized by chart values.

**Comment by brandond** [comment]
This was pulled in when the canal chart was updated in:
* https://github.com/rancher/rke2/pull/4565

**Comment by aganesh-suse** [comment]
### Validated on release-1.25 branch with commit 1ab228b72420eaf4704859d4f1a6c5361e823a80 / version <version>
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 22.04.2 LTS"
$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
1 server/1 agent
```
  
*Config.yaml:*

```
token: secret
write-kubeconfig-mode: "0644"
cni: canal
```
  
*Additional files*

Create directory: /var/lib/rancher/rke2/server/manifests
    Push file content in this directory: rke2-canal-config.yaml

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    calico:
      resources:
        requests:
          cpu: 350m
          memory: 128Mi
        limits:
          cpu: 350m
          memory: 256Mi
    flannel:
      resources:
        requests:
          memory: 32Mi
          cpu: 200m
        limits:
          memory: 128Mi
          cpu: 550m          
```
Refer to
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/values.yaml
for knowing what values to edit ^^
Also refer to https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig to know more about HelmChartConfig and how to work with them.

  
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
2. Create directory: /var/lib/rancher/rke2/server/manifests;
Push file content in this directory: rke2-canal-config.yaml 
3. Install RKE2: 
```curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='1ab228b72420eaf4704859d4f1a6c5361e823a80' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -```
or
```curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION='v1.25.12+rke2r1' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -```
4. Enable RKE2 service.
```sudo systemctl enable --now rke2-server```
5. Get pod name for rke2-canal:
```
kubectl get pods -A | grep canal
kube-system   helm-install-rke2-canal-b4wgt                           0/1     Completed   0          33m
kube-system   rke2-canal-ckf4q                                        2/2     Running     0          32m
kube-system   rke2-canal-hh6vv                                        2/2     Running     0          33m
```
6. Get the yaml config details for the canal pods/daemonset
```kubectl get pod rke2-canal-ckf4q -n kube-system -o yaml```
  
**Replication Results:**
- rke2 version used for replication:

```
rke2 -v
rke2 version v1.25.12+rke2r1 (a0aa49e91d86a9a5eec8d94cdab13afabe11bfb6)
go version go1.20.6 X:boringcrypto
```
 

We can see the flannel and calico values are not updated in the pod yaml output
```
kubectl get pod rke2-canal-xxx -n kube-system -o yaml

    name: calico-node
    resources:
      requests:
        cpu: 250m
        
    name: kube-flannel
    resources: {}
```
 
**Validation Results:**
- rke2 version used for validation:

```
rke2 -v
rke2 version v1.25.12-dev+1ab228b7 (1ab228b72420eaf4704859d4f1a6c5361e823a80)
go version go1.20.6 X:boringcrypto
```
 

We can see the flannel and calico values have been updated correctly:
```
kubectl get pod rke2-canal-xxx -n kube-system -o yaml
    name: calico-node
    resources:
      limits:
        cpu: 350m
        memory: 256Mi
      requests:
        cpu: 350m
        memory: 128Mi

    name: kube-flannel
    resources:
      limits:
        cpu: 550m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 32Mi

```
