### ISSUE TITLE
Multus 4.x broken with the lastest rke versions

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#4568]
**Environmental Info:**
RKE2 Version: v1.26.7+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux kub-b14.priv.cerit-sc.cz 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
cni: calico,multus

**Describe the bug:**
If using additional network attachement, pod does not start:
```
Events:
  Type     Reason                  Age              From               Message
  ----     ------                  ----             ----               -------
  Normal   Scheduled               26s              default-scheduler  Successfully assigned beegfs/beegfs-mgmtd-0 to kub-b10.priv.cerit-sc.cz
  Normal   AddedInterface          25s              multus             Add eth0 [10.42.11.18/32 2001:718:801:42cb:8:2:f625:7e21/128] from k8s-pod-network
  Normal   AddedInterface          25s              multus             Add ib0 [10.16.59.2/24] from beegfs/ibnet-beegfs
  Normal   AddedInterface          25s              multus             Add eth0 [10.42.11.18/32 2001:718:801:42cb:8:2:f625:7e21/128] from multus-cni-network
  Warning  FailedCreatePodSandBox  24s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e32935913443085ffc5aa0044dc4d893147d7d539e8358f13330bcdc7e2670d5": plugin type="multus" name="multus-cni-network" failed (add): [beegfs/beegfs-mgmtd-0/e34930ae-588e-4295-890c-7ac7a3a83ea2:ibnet]: error adding container to network "ibnet": DelegateAdd: cannot set "ipoib" interface name to "ib0": validateIfName: interface name ib0 already exists
  Normal   AddedInterface          23s              multus             Add eth0 [10.42.11.136/32 2001:718:801:42cb:8:2:f625:7e22/128] from k8s-pod-network
  Normal   AddedInterface          23s              multus             Add ib0 [10.16.59.2/24] from beegfs/ibnet-beegfs
  Normal   AddedInterface          23s              multus             Add eth0 [10.42.11.136/32 2001:718:801:42cb:8:2:f625:7e22/128] from multus-cni-network
  Warning  FailedCreatePodSandBox  22s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3547a281ec36762a2d08719401e8adea05f9cdb926d393028d16e7bd71409be4": plugin type="multus" name="multus-cni-network" failed (add): [beegfs/beegfs-mgmtd-0/e34930ae-588e-4295-890c-7ac7a3a83ea2:ibnet]: error adding container to network "ibnet": DelegateAdd: cannot set "ipoib" interface name to "ib0": validateIfName: interface name ib0 already exists
  Normal   AddedInterface          21s              multus             Add eth0 [10.42.11.89/32 2001:718:801:42cb:8:2:f625:7e1c/128] from k8s-pod-network
  Normal   AddedInterface          21s              multus             Add ib0 [10.16.59.2/24] from beegfs/ibnet-beegfs
  Normal   AddedInterface          21s              multus             Add eth0 [10.42.11.89/32 2001:718:801:42cb:8:2:f625:7e1c/128] from multus-cni-network
  Warning  FailedCreatePodSandBox  20s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "130f86345ef798dd736b3163d5fafaa5a6dd48fa4cc8f5e1b22a0450b97a1c76": plugin type="multus" name="multus-cni-network" failed (add): [beegfs/beegfs-mgmtd-0/e34930ae-588e-4295-890c-7ac7a3a83ea2:ibnet]: error adding container to network "ibnet": DelegateAdd: cannot set "ipoib" interface name to "ib0": validateIfName: interface name ib0 already exists
  Normal   AddedInterface          19s              multus             Add eth0 [10.42.11.102/32 2001:718:801:42cb:8:2:f625:7e01/128] from k8s-pod-network
  Normal   AddedInterface          19s              multus             Add ib0 [10.16.59.2/24] from beegfs/ibnet-beegfs
  Normal   AddedInterface          19s              multus             Add eth0 [10.42.11.102/32 2001:718:801:42cb:8:2:f625:7e01/128] from multus-cni-network
  Warning  FailedCreatePodSandBox  18s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "49f3583246b7e6cb8d83546867a3c9f1e3fe834687a56938f036f05c085ebe12": plugin type="multus" name="multus-cni-network" failed (add): [beegfs/beegfs-mgmtd-0/e34930ae-588e-4295-890c-7ac7a3a83ea2:ibnet]: error adding container to network "ibnet": DelegateAdd: cannot set "ipoib" interface name to "ib0": validateIfName: interface name ib0 already exists
```

It worked in the version v1.26.6+rke2r1, which has multus 3.x. Maybe related to:
https://github.com/k8snetworkplumbingwg/multus-cni/issues/1130 ?

**Comment by thomasferrandiz** [comment]
Hi @xhejtman 
I tried to reproduce your issue but my deployment is working.

Can you share more details on what you're doing?
Especially, the manifest for the NetworkAttachmentDefinition and pod definition would be useful to reproduce.

**Comment by xhejtman** [comment]
and the statefulset

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beegfs-mgmtd
spec:
  replicas: 1
  serviceName: beegfs
  selector:
    matchLabels:
      app: beegfs-mgmtd
  template:
    metadata:
      labels:
        app: beegfs-mgmtd
      annotations:
         k8s.v1.cni.cncf.io/networks: "beegfs/ibnet-beegfs"
    spec:
      containers:
      - name: beegfs-mgmtd
        image: cerit.io/os/beegfs:7.3.3
        command:
          - /opt/beegfs/sbin/beegfs-mgmtd
          - cfgFile=/etc/beegfs/beegfs-mgmtd.conf
          - runDaemonized=false
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            rdma/hca: 1
        volumeMounts:
          - mountPath: /mnt
            name: mgmt-dir
          - name: connauth
            mountPath: /etc/beegfs-auth
          - name: config
            mountPath: /etc/beegfs
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        seccompProfile:
           type: RuntimeDefault
      volumes:
      - name: mgmt-dir
        persistentVolumeClaim:
          claimName: pvc-beegfs-mgmt
      - name: connauth
        secret:
          secretName: connauthfile
      - name: config
        configMap:
          name: mgmtd-conf
```
