### ISSUE TITLE
Update Calico chart to accept any FelixConfiguration through helm

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#4692]
**Is your feature request related to a problem? Please describe.**

On the current chart configuration only the values defined on https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico/v3.26.100/templates/felixconfig.yaml#L6 are accepted as `FelixConfiguration` within the helm chart configuration.

**Describe the solution you'd like**

Add the capability to configure every accepted values https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico-crd/v3.26.100/templates/calico/crd.projectcalico.org_felixconfigurations.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by VestigeJ** [comment]
Is the intended use of this to be for a user to supply these values in our existing config.yaml or as a helmchartconfig file in the manifests directory that the cluster will pick up and append to the CRD?

**Comment by rbrtbnfgl** [comment]
yes the user can provide the CRD values on the helmchart config.

**Comment by VestigeJ** [comment]
@rbrtbnfgl Can you share the sample configuration file you used when testing this locally? I've been toying around with a lot of the values for bpf, wireguard, and some logging swaps and I cannot reliably bring up the calico-system pods with the correct data I've passed in from the file


$ sudo journalctl -u rke2-server //highlighting that the file is being read and patched

``` 
time="2023-10-27T04:11:16Z" level=debug msg="DesiredSet - Updated crd.projectcalico.org/v1, Kind=FelixConfiguration /default for  kube-system/rke2-felix -- application/merge-patch+json {\"metadata\":{\"annotations\":{\"objectset.rio.cattle.io/applied\":\"H4sIAAAAAAAA/4yRTWvjMBCG/8oyZ8fxR9abFfRQ+gGlUAqB3kfS2FatSEYaOw0h/70oKSWXhh41D+/zjpgD4GjeKETjHQhQQedj8O+kWKE1yuc+dMu5hAwG4zQIeCRrPu68a003BeQUy2BLjBoZQRwAnfN8AjE9vUyySJwH43OFzJZy45cmySD7kfudo7Do5gEEDHW8IHOZ/Xk2Tt/can1qv65wuCUQEAaqFm1a/leJOKJKsWGStIj7yLSFYwYWJdmr/+ox9iCAir/luimrtmlQrYv/Zan/6dWqWdd1Xemqlg2qWrZFkn5tqKnFyXKaxJFUKukJLfevPjCIqiyKIgPruw3NFAzvN/sIAu5JTh1ksDOBugmDfnAoLWkQHCa6mD85ptCiopdz3zfIZ7RGn295PH4GAAD//03sNtoSAgAA\",\"objectset.rio.cattle.io/id\":\"\",\"objectset.rio.cattle.io/owner-gvk\":\"k3s.cattle.io/v1, Kind=Addon\",\"objectset.rio.cattle.io/owner-name\":\"rke2-felix\",\"objectset.rio.cattle.io/owner-namespace\":\"kube-system\"},\"labels\":{\"objectset.rio.cattle.io/hash\":\"e0518612f66ac80911d7d44683332d23b6ac3bf0\"}},\"spec\":{\"healthPort\":21000,\"logSeveritySys\":\"Debug\",\"wireguardEnabled\":true,\"wireguardInterfaceName\":\"wireguard.validation\"}}"
Oct 27 04:11:16 ip-1-1-1-128 rke2[18568]: I1027 04:11:16.341564   18568 event.go:294] "Event occurred" object="kube-system/rke2-felix" fieldPath="" kind="Addon" apiVersion="k3s.cattle.io/v1" type="Normal" reason="AppliedManifest" message="Applied manifest at \"/var/lib/rancher/rke2/server/manifests/rke2-felix.yaml\""
```

$ ip a //expecting interface to be named wireguard.validation instead of the default wireguard.cali here

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 06:5c:e6:99:53:f1 brd ff:ff:ff:ff:ff:ff
    inet 172.31.17.128/20 brd 172.31.31.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::45c:e6ff:fe99:53f1/64 scope link
       valid_lft forever preferred_lft forever
22: wireguard.cali: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.42.168.15/32 scope global wireguard.cali
       valid_lft forever preferred_lft forever
49: cali484c558b8e0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-aaaf551d-407d-e3a1-c13a-dfd50bc7d6fb
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
50: cali349aa61963a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-4bdf1e0b-92df-5702-15c0-61c4c4088747
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
51: cali11ec80da9bb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-2ddde3fd-68cc-f5f7-8f84-a80d48b33906
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
52: calie75367bd3bf@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-84cf7644-c783-9c65-6e8e-aa545c0659ae
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
53: cali1210473522a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-8b628715-f974-59b4-3429-708bf354d8c1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
54: calicc0fa3fe9c3@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-d388de67-7b95-e9d3-acfb-473184415ab7
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
55: calicacd665a2e6@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-6e17449c-355c-846e-0a0d-1013917d6af5
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
56: calib5cff2ffbc2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-82189151-d380-82a2-cf4c-73288c304b6d
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
```      


$ cat rke2-felix.yaml

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  healthPort: 21000
  wireguardEnabled: True
  wireguardInterfaceName: "wireguard.validation"
  logSeveritySys: "Debug"
``` 

$ cat rke2-felix-configz.yaml //another attempt that I do think worked to enable bpf but the node was inaccessible afterwards

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  healthPort: 21000
  logSeveritySys: Debug
  wireguardEnabled: True
  bpfEnabled: true
```

$ cat another-felix.yaml

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  healthPort: 21000
  wireguardEnabled: True
  wireguardInterfaceName: "wireguard.validation"
  logFilePath: "/home/ec2-user/calico-modded/felix.log"
  logPrefix: "calico-packet-modified-for-validations"
  logSeverityFile: "Debug"
  logSeveritySys: "Debug"
  #prometheusMetricsEnabled: True
```

$ cat another-another-felix-conf.yaml

```
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  healthPort: 21000
  wireguardEnabled: True
  wireguardMTU: 1500
  wireguardInterfaceName: "wireguard.validation"
  logFilePath: "/home/ec2-user/calico-modded/felix.log"
  logPrefix: "calico-packet-modified-for-validations"
  logSeverityFile: "Debug"
  logSeveritySys: "Debug"
  prometheusMetricsEnabled: True
```


It IS good that I can see wireguard is getting created/setup with default values but I don't seem to be able to customize much else without the pods or even the namespace failing to come up.

**Comment by rbrtbnfgl** [comment]
The felix configuration are right. I get some errors with `wireguardInterfaceName` maybe it needs other configurations.

**Comment by rbrtbnfgl** [comment]
I tried with the following config and it setted the right interface value
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 10.42.0.0/16
          blockSize: 24
    felixConfiguration:
      healthPort: 21000
      wireguardEnabled: True
      wireguardMTU: 1500
      wireguardInterfaceName: "wireguard.val"
      logSeverityFile: "Debug"
      logSeveritySys: "Debug"
      prometheusMetricsEnabled: True
```
