### ISSUE TITLE
Cilium 1.14.0 CIDR based rules ignored

### ISSUE THREAD

**Issue by corym-vermeer** [rancher/rke2#4749]
Cilium 1.14.0 isn't usable with CIDR based network policies.   Upstream project has addressed these and released 1.14.1  
[Cilium Issue #27210](https://github.com/cilium/cilium/issues/27210)

**Environmental Info:**
RKE2 Versions: 
v1.25.13+rke2r1
v1.24.17+rke2r1

Node(s) CPU architecture, OS, and Version: 
5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 29 17:06:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 separate clusters,   1 node in the v1.25 "Cluster",   second cluster is configured with 5 nodes,  3 of those are control pane.

**Describe the bug:**
CiliumNetworkPolicies containing either fromCIDR or toCIDR are not being read.

**Steps To Reproduce:**
Define a CiliumNetworkPolicy containing an example such as this: 
```
    - fromCIDR:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 2a0e:97c0:250::/44
        - 2a02:2c8:f000::/48
        - fd00::/8
      toPorts:
        - ports:
          - port: "8443"
            protocol: TCP
          - port: "8000"
            protocol: TCP
```
- Installed RKE2: 

**Expected behavior:**

**Actual behavior:**
See the following issue:  [Cilium Issue #27210](https://github.com/cilium/cilium/issues/27210)

**Additional context / logs:**
Testing of Cilium 1.14.1 was done by overriding the rke2-cilium image tag with the following example: 
```yaml
rkeConfig:
    additionalManifest: |
      ---
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-cilium
        namespace: kube-system
      spec:
        valuesContent: |-
          image: 
            tag: "v1.14.1"    
          dnsProxy:
            dnsRejectResponseCode: nameError
          kubeProxyReplacement: strict
          k8sServiceHost: 127.0.0.1
          k8sServicePort: 6443
          operator:
            replicas: 1
            image:
              tag: "v1.14.1"
~~~
```
