### ISSUE TITLE
rke2v1.27.3+rke2r1 cannot mount glusterfs volume

### ISSUE THREAD

**Issue by Thatwho** [rancher/rke2#4770]
**Environmental Info:**
RKE2 Version:  rke2-v1.27.3+rke2r1

Node(s) CPU architecture, OS, and Version: 3.10.0-1160.el7.x86_64

Cluster Configuration: 1 server 0 agents

**Describe the bug:** 
I have create a pv and pvc use gluster volume, which shows bound, 
```
NAME          STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS   AGE
gluster-pvc   Bound    gluster-pv   10Gi       RWX                           26m
```
but when I create a pod trying to  mount that pvc, it shows:
```
  Warning  FailedMount       2m31s (x112 over 27m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[gluster-volume], unattached volumes=[], failed to process volumes=[gluster-volume]: failed to get Plugin from volumeSpec for volume "gluster-pv" err=no volume plugin matched
```

**Steps To Reproduce:**

- Installed RKE2: 
- apply the yaml:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: mysql
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: gluster-test-container
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: "/mnt/gluster"
        name: gluster-volume
  volumes:
  - name: gluster-volume
    persistentVolumeClaim:
      claimName: gluster-pvc
      readOnly: false
```
**Expected behavior:**

the pod running and mount the volume
**Actual behavior:**

the pod cannot mount the volumn
**Additional context / logs:**
