### ISSUE TITLE
RKE2 Control Plane node rotation fails after installing kyverno

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rke2#4781]
**Environmental Info:**
RKE2 Version: v1.26.7+rke2r1

Cluster Configuration: 3 CP / 3 Workers

**Describe the bug:**
Control Plane node rotation fails after installed [kyverno](https://kyverno.io/)
New node comes up and some k8s components are actually getting provisioned except `kube-proxy`.
`rke2-server` is crashlooping and kube-proxy is never gets provisioned. In `rke2-server` logs not much going on related to kube-proxy:
```
Sep 21 12:41:55 ip-172-29-195-214 rke2[21652]: time="2023-09-21T12:41:55Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```
For some reason `kube-proxy.yaml` manifests is not getting created in `/var/lib/rancher/rke2/agent/pod-manifests/`

and there are only:
``` 
$ ls /var/lib/rancher/rke2/agent/pod-manifests/
etcd.yaml                     kube-apiserver.yaml           kube-controller-manager.yaml  kube-scheduler.yaml
```

Manual creation of `/var/lib/rancher/rke2/agent/pod-manifests/kube-proxy.yaml` allows to bootstrapping CP node to continue and then it works fine.

This bug can't be reproduced with kyverno admission controller scaled down.

**Steps To Reproduce:**
- Provision RKE2 cluster
- Install kyverno admission controller
- Rotate any CP node

**Expected behavior:**
CP node is rotated and on new CP node all k8s core components are deployed and functioning as expected

**Actual behavior:**
CP node is rotated and on new CP node `kube-proxy` is missing which prevents CP node to transition to healthy state.

**Additional context / logs:**
All kyverno policies are in Audit mode so shouldn't be actually blocking anything and I believe it will reproduce even without any policies created it looks like the issue is kyverno mutation/validation webhooks which are supposed to intercept all traffic to API server. Looks like rke2-server is attempting to perform some k8s API calls but it is getting failed as kyverno is not accessible without kube-proxy.

**Comment by brandond** [comment]
Have you opened an issue on the kyverno side? I will note that just putting it into audit mode will not help you if the webhooks are set to fail closed; if the webhook is set to intercept management of secrets or other resources that are critical to the startup of rke2, failing closed when the backend is unavailable can easily break things to the point where the cluster will not start until you remove the webhook configuration. This is a known issue with webhooks in general.

**Comment by riuvshyn** [comment]
Thanks for looking in to this one!
I did not open ticket on kyverno side as I believe that it is not kyverno specific problem, as you mentioned it fails due to the validating webhook not being able to connect to the controller due to missing `kube-proxy` and it is indeed has `failurePolicy: Fail`.
I understand the problem with webhooks but thought that `kube-proxy.yaml` can be actually created even if k8s API is not reachable, if it is not the case I guess I will need to thing about some workarounds.

**Comment by riuvshyn** [comment]
Also, what other resources are critical for start up rke2 other than secrets?

**Comment by brandond** [comment]
kube-proxy should be able to run without webhooks, as it is a static pod deployed on each node - it does not rely on the apiserver being available. It is possible that the webhook might be blocking the overall startup of RKE2 though, including the bit that drops the kube-proxy static pod manifest. You should see errors in the rke2 journald logs about this though. Have you checked that yet?

**Comment by riuvshyn** [comment]
kube-proxy is able to run for sure, but manifest for it isn't getting created in `/var/lib/rancher/rke2/agent/pod-manifests/` for some reason... If I create manifest manually it gets picked up and works then.
the only kube-proxy related logs in rke2-server I see is:
```
Sep 21 12:41:55 ip-172-29-195-214 rke2[21652]: time="2023-09-21T12:41:55Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
```


Kyverno also have resource filtering, I will try to configure it maybe I can configure filter to skip resources on `cattle-*` namespaces

**Comment by brandond** [comment]
There should be other messages in there that indicate why the readyz check isn't passing, such as waiting for the apiserver or roles or so on.

You can also do `kubectl get --raw /readyz?verbose` on the server to see what apiserver health checks are failing, if any.

**Comment by riuvshyn** [comment]
Looks like all apiserver endpoints are ok

```kubectl get --raw /readyz?verbose
[+]ping ok
[+]log ok
[+]etcd ok
[+]etcd-readiness ok
[+]informer-sync ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/priority-and-fairness-filter ok
[+]poststarthook/storage-object-count-tracker-hook ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]poststarthook/priority-and-fairness-config-producer ok
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/start-kube-apiserver-identity-lease-controller ok
[+]poststarthook/start-kube-apiserver-identity-lease-garbage-collector ok
[+]poststarthook/start-legacy-token-tracking-controller ok
[+]poststarthook/aggregator-reload-proxy-client-cert ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/apiservice-openapiv3-controller ok
[+]shutdown ok
readyz check passed
```

**Comment by riuvshyn** [comment]
here is also kyverno validatingWH rules:
```
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - persistentvolumeclaims
    - pods
    - pods/ephemeralcontainers
    - replicationcontrollers
    scope: '*'
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    scope: '*'
  - apiGroups:
    - autoscaling
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - horizontalpodautoscalers
    scope: '*'
  - apiGroups:
    - autoscaling
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - horizontalpodautoscalers
    scope: '*'
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - cronjobs
    - jobs
    scope: '*'
  - apiGroups:
    - flowcontrol.apiserver.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - flowschemas
    - prioritylevelconfigurations
    scope: '*'
  - apiGroups:
    - flowcontrol.apiserver.k8s.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - flowschemas
    - prioritylevelconfigurations
    scope: '*'
  - apiGroups:
    - monitoring.coreos.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - prometheusrules
    scope: '*'
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - ingresses
    scope: '*'
  - apiGroups:
    - policy
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - poddisruptionbudgets
    scope: '*'
  - apiGroups:
    - rbac.authorization.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - clusterrolebindings
    - rolebindings
    scope: '*'
  - apiGroups:
    - scheduling.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - priorityclasses
    scope: '*'
  - apiGroups:
    - storage.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - csistoragecapacities
    scope: '*'
  - apiGroups:
    - storage.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - csistoragecapacities
    scope: '*'
```

It doesn't track secrets/configMaps  etc...
