### ISSUE TITLE
Uninstallation not cleaning up calico wireguard interfaces from host

### ISSUE THREAD

**Issue by VestigeJ** [rancher/rke2#4962]
**Environmental Info:**
RKE2 Version: 

Not a release blocker

Present on all new releases/RCs
v1.28.3
v1.27.7
v1.26.10
v1.25.15

Node(s) CPU architecture, OS, and Version: 

```
Linux ip-172-31-29-133 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 server node

**Describe the bug:**

Instantiation of a new node using calico HelmChartConfig for WireGuard correctly creates the interface labeled but the existing uninstall process does not account for removing these interfaces leaving them behind. Use the below HelmChartConfig to create interfaces changing the wireguardInterfaceName value for multiple re-installs. Then run killall/uninstall scripts and observe the interfaces are still present on the node.

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - natOutgoing: Enabled
          encapsulation: None
          cidr: 10.42.0.0/16
          blockSize: 24
    felixConfiguration:
      healthPort: 23200
      wireguardEnabled: True
      wireguardMTU: 3100
      wireguardInterfaceName: "lothlorien.wiza"
      logSeverityFile: "Debug"
      logSeveritySys: "Debug"
      prometheusMetricsEnabled: True
```

```
 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 06:31:8d:89:aa:b3 brd ff:ff:ff:ff:ff:ff
    inet 12.13.12.133/20 brd 12.13.12.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::413:1ced:aced:a763/64 scope link
       valid_lft forever preferred_lft forever
13: wireguard.val: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.42.226.15/32 scope global wireguard.val
       valid_lft forever preferred_lft forever
38: wireguard.orcs: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 2900 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
63: lothlorien.wiza: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 3100 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
```

**Steps To Reproduce:**

```
$ sudo mkdir -p /var/lib/rancher/rke2/server/manifests/
$ sudo cp rke2-felix.yaml /var/lib/rancher/rke2/server/manifests/
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh //default install script not modified
$ ip a //observe creation of interface
$ sudo /usr/local/bin/rke2-killall
$ sudo /usr/local/bin/rke2-uninstall.sh 
$ ip a //observe interfaces still present on the node
```

**Expected behavior:**

Resources created by the instantiation of the server node to be removed after removing the server node.

**Actual behavior:**

Installation artifacts left behind in system configuration

**Additional context / logs:**
