### ISSUE TITLE
Long wireguard interface names passed via HelmChartconfig result in calico-nodes failing to start

### ISSUE THREAD

**Issue by VestigeJ** [rancher/rke2#4963]
**Environmental Info:**
RKE2 Version: 

Not a release blocker

Present on all new releases/RCs
v1.28.3
v1.27.7
v1.26.10
v1.25.15

Node(s) CPU architecture, OS, and Version: 

```
Linux ip-172-31-29-133 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

1 server node

**Describe the bug:**

If the wireguardInterfaceName: value is too long the calico pods fail to come up to a ready status.

this sample works

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      felixConfiguration:
      wireguardEnabled: True
      wireguardMTU: 3100
      wireguardInterfaceName: "lothlorien.wiza"
```

this sample fails 

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      felixConfiguration:
      wireguardEnabled: True
      wireguardMTU: 3100
      wireguardInterfaceName: "lothlorien.wizards"
```

**Steps To Reproduce:**

```
$ sudo mkdir -p /var/lib/rancher/rke2/server/manifests/
$ sudo cp rke2-felix.yaml /var/lib/rancher/rke2/server/manifests/
$ sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_EXEC=server ./install-rke2.sh //default install script not modified
$ sudo systemctl enable rke2-server --now
$ export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
$ watch -n 4 kubectl get pods -n calico-namespace
```

```
calico-system     calico-node-9c7zb                                       0/1     CrashLoopBackOff   1 (19s ago)   46s
```

**Expected behavior:**

The users either valid interface name is honored or rejected and cluster is not started until a valid value is present?

**Actual behavior:**

Cluster starts but calico-pods enter crashloopbackoff and cluster is broken

**Additional context / logs:**
