### ISSUE TITLE
/etc/rancher/rke2/registries.yaml doesn't work if $RKE2_HOME/agent/etc/containerd/config.toml.tmpl exists

### ISSUE THREAD

**Issue by zhenlohuang** [rancher/rke2#5084]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.3+rke2r2 (cf6c1ae3f199c2e838ba19125cbd2d522c8765d3)
go version go1.20.10 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux llm-installer-dev 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**
I found /etc/rancher/rke2/registries.yaml  didn't work if $RKE2_HOME/agent/etc/containerd/config.toml.tmpl existed. $RKE2_HOME/agent/etc/containerd/config.toml was overrwritten by the config.toml.tmpl and didn't merge with registries.yaml.
/etc/rancher/rke2/registries.yaml:
```
mirrors:
  docker.io:
    endpoint:
      - "http://my-registry:30000"
  my-registry:
    endpoint:
      - "http://my-registry:30000"
```
