### ISSUE TITLE
RKE2 v1.27.8+rke2r1 does not start if using cilium with disabled kube-proxy

### ISSUE THREAD

**Issue by nugzarg** [rancher/rke2#5107]
**Environmental Info:**
RKE2 Version:  v1.27.8+rke2r1

**Node(s) CPU architecture, OS, and Version:**

x86_64, Ubuntu 22.04.3, Kernel 6.2.0-37-generic

**Cluster Configuration:**

```yaml
etcd-snapshot-schedule-cron: "0 */5 * * *"
etcd-snapshot-retention: "30"
node-name: "master1.kube.example.com"
node-ip: "222.111.222.1111"
tls-san:
- "master1.kube.example.com"
node-taint:
- "CriticalAddonsOnly=true:NoExecute"
kubelet-arg:
- feature-gates=LocalStorageCapacityIsolation=true,SizeMemoryBackedVolumes=true,SeccompDefault=true
- seccomp-default=true
- pod-max-pids=2048
cni:
  - cilium
disable:
  - rke2-canal
  - rke2-kube-proxy
```

Single server

**Describe the bug:**

RKE2 server service does not start if cilium is defined as CNI in rke2 config.yaml and kube-proxy is disabled (because ciliums kube-proxy replacement is used). See rke2 config.yaml above.
Seems that only RKE2  v1.27.x is affected. RKE2 v1.26.11+rke2r1 starts fine.

**Steps To Reproduce:**
[rke2-server.log](https://github.com/rancher/rke2/files/13612066/rke2-server.log)

1. Install rke2: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server " INSTALL_RKE2_VERSION=v1.27.8+rke2r1 sh -
2. Start rke2-server.service: systemctl start rke2-server.service
3. Watch output: journalctl -fu rke2-server.service

**Expected behavior:**
rke2-server service should start

**Actual behavior:**
starting rke2-server service fails. It's in endless restart loop.

**Additional context / logs:**

Please see attached log file.

**Comment by nugzarg** [comment]
Update:
The same problem with RKE2 v1.28.4+rke2r1. If removing rke2-kube-proxy disabling option, both versions can start.

**Comment by brandond** [comment]
> does not start if cilium is defined as CNI in rke2 config.yaml and kube-proxy is disabled (because ciliums kube-proxy replacement is used).

What steps did you take to enable cilium's kube-proxy replacement? Its not enabled by default, so without taking additional steps you've left yourself without any kube-proxy functionality.

Ref: https://github.com/rancher/rke2-charts/blob/main/charts/rke2-cilium/rke2-cilium/1.14.400/values.yaml#L1579

**Comment by nugzarg** [comment]
Sorry, I forgot to post cilium HelmChartConfig file. Here rke2-cilium-config.yaml placed in /var/lib/rancher/rke2/server/manifests directory:

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
      ipv4:
        enabled: true
      ipv6:
        enabled: false
      devices: "eth0 eth1 eth2"
      kubeProxyReplacement: "strict"
      k8sServiceHost: 127.0.0.1
      k8sServicePort: 6443
      tunnel: disabled
      autoDirectNodeRoutes: true
      enableIPv4Masquerade: true
      masquerade: true
      ipv4NativeRoutingCIDR: 10.0.0.0/16
      nativeRoutingCIDR: 10.0.0.0/16
      egressGateway:
        enabled: false
        installRoutes: false
      bandwidthManager:
        bbr: true
        enabled: true
      loadBalancer:  
        acceleration: native
        algorithm: maglev
        mode: dsr
      maglev:
        tableSize: 65521
        hashSeed: XXXXXXXXX
      encryption:
        enabled: false
      bpf:
        clockProbe: true
        preallocateMaps: true
        hostRouting: true
        masquerade: true
        tproxy: true
        hostLegacyRouting: false
      installIptablesRules: true
      installNoConntrackIptablesRules: true
      l7Proxy: true
      cni:
        exclusive: false
      nodePort:
        enabled: true
        mode: dsr
        range: "30000,32767"
        bindProtection: false
        acceleration: native
      hostPort:
        enabled: true
      hostServices:
        enabled: true
        protocols: tcp,udp
        hostNamespaceOnly: true
      hostFirewall:
        enabled: true
      endpointRoutes:
        enabled: false
      ingressController:
        enabled: false
        enforceHttps: false
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      operator:
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
      hubble:
        enabled: true
        relay:
          enabled: true
        ui:
          enabled: true
          ingress:
            enabled: true
            replicas: 2
            hosts:
              - hubble.kube.example.com
        metrics:
          enabled:
             - dns:query;ignoreAAAA
             - drop
             - tcp
             - flow
             - icmp
             - http
          serviceMonitor:
            enabled: true
```
We have 13 nodes rke2 cluster (3 master and 10 worker nodes) which is running whith this configuration (without kube-proxy) about 2 years. We are testing upgrade from v1.26.11+rke2r1 to v1.27.8+rke2r1 not on production cluster, but on single node testing cluster with the same configuration upgrade failes, because rke2-server servise does not start.

**Comment by brandond** [comment]
> cluster with the same configuration upgrade failes, because rke2-server servise does not start.

Can you post the rke2-server logs from journald? Why specifically is it failing to start?

**Comment by brandond** [comment]
```yaml
cni:
  - cilium
disable:
  - rke2-canal
```

fyi you don't have to specifically disable rke2-canal if you set the cni to cilium; all other cni charts are disabled and only the selected one left enabled.
