### ISSUE TITLE
[1.28] Update vSphere CPI/CSI charts

### ISSUE THREAD

**Issue by caroline-suse-rancher** [rancher/rke2#5217]
This issue is to track the progress on updating the vSphere CPI/CSI charts for 1.28 release line. For reference to how we've done this in the past, please see #4275

**Comment by mdrahman-suse** [comment]
## Validated on RC v1.28.8-rc1+rke2r1

## Testing 

<details>

<summary>pvc.yaml</summary>

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```

</details>

<details>

<summary>pod.yaml</summary>

```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim1"
```

</details>

- Create a Ubuntu VM in vSphere7
- Add config and vsphere details
- Install rke2
- Ensure the cluster is up
- Deploy pvc.yaml and pod.yaml attached to pvc
- Validate pvc attached to instance in vSphere

## Replication

<details>

- Observed *vsphere-csi pods in ImagePullBackOff, pod deployment in Pending state and no pvc is attached to the instance
```
$ rke2 -v
rke2 version v1.28.7+rke2r1 (fe8538a165d25755050d2a0827dbf982f72611fa)
go version go1.21.7 X:boringcrypto
```
- ProviderID
```
$ kubectl describe nodes | grep -i provider
                    rke2.io/node-args: ["server","--write-kubeconfig-mode","644","--cloud-provider-name","rancher-vsphere"]
ProviderID:                   vsphere://4216015c-0cf7-8d41-5ed6-3fc7eab87537
```
- Cluster
```
NAME            STATUS   ROLES                       AGE   VERSION
node/ubuntu22   Ready    control-plane,etcd,master   10m   v1.28.7+rke2r1

NAMESPACE     NAME                                                    READY   STATUS             RESTARTS   AGE
default       basic                                                   0/1     Pending            0          4m38s
kube-system   etcd-ubuntu22                                           1/1     Running            0          14m
kube-system   helm-install-rancher-vsphere-cpi-64gnk                  0/1     Completed          0          14m
kube-system   helm-install-rancher-vsphere-csi-9gfhz                  0/1     Completed          0          14m
kube-system   helm-install-rke2-canal-qvzfg                           0/1     Completed          0          14m
kube-system   helm-install-rke2-coredns-59tss                         0/1     Completed          0          14m
kube-system   helm-install-rke2-ingress-nginx-9nrlb                   0/1     Completed          0          14m
kube-system   helm-install-rke2-metrics-server-z69kz                  0/1     Completed          0          14m
kube-system   helm-install-rke2-snapshot-controller-cgv7k             0/1     Completed          2          14m
kube-system   helm-install-rke2-snapshot-controller-crd-xg4ch         0/1     Completed          0          14m
kube-system   helm-install-rke2-snapshot-validation-webhook-8pxj8     0/1     Completed          0          14m
kube-system   kube-apiserver-ubuntu22                                 1/1     Running            0          14m
kube-system   kube-controller-manager-ubuntu22                        1/1     Running            0          14m
kube-system   kube-proxy-ubuntu22                                     1/1     Running            0          14m
kube-system   kube-scheduler-ubuntu22                                 1/1     Running            0          14m
kube-system   rancher-vsphere-cpi-cloud-controller-manager-vw42z      1/1     Running            0          14m
kube-system   rke2-canal-pmmtd                                        2/2     Running            0          14m
kube-system   rke2-coredns-rke2-coredns-6c8d9bb6d-5lnc2               1/1     Running            0          14m
kube-system   rke2-coredns-rke2-coredns-autoscaler-55fb4bbbcf-kccdg   1/1     Running            0          14m
kube-system   rke2-ingress-nginx-controller-5chbx                     1/1     Running            0          13m
kube-system   rke2-metrics-server-544c8c66fc-5hcbf                    1/1     Running            0          13m
kube-system   rke2-snapshot-controller-59cc9cd8f4-m69pd               1/1     Running            0          13m
kube-system   rke2-snapshot-validation-webhook-54c5989b65-w7ccj       1/1     Running            0          14m
kube-system   vsphere-csi-controller-65dfb876cd-fdhks                 0/5     ImagePullBackOff   0          14m
kube-system   vsphere-csi-controller-65dfb876cd-gwjx4                 0/5     ImagePullBackOff   0          14m
kube-system   vsphere-csi-controller-65dfb876cd-vpxmp                 0/5     ImagePullBackOff   0          14m
kube-system   vsphere-csi-node-cnckw                                  0/3     ImagePullBackOff   0          14m
```
- Chart status and version
```
$ helm ls -A
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/rke2/rke2.yaml
NAME                            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rancher-vsphere-cpi             	kube-system	1       	2024-03-18 18:24:09.230144665 +0000 UTC	deployed	rancher-vsphere-cpi-1.5.100                 	1.26.1
rancher-vsphere-csi             	kube-system	1       	2024-03-18 18:24:09.371645221 +0000 UTC	deployed	rancher-vsphere-csi-3.0.1-rancher101        	3.0.1-rancher1
...
```

</details>

## Validation

<details>

- Observed *vsphere-csi pods, pod deployment in Running state and pvc is attached
<img width="756" alt="Screen Shot 2024-03-18 at 1 52 43 PM" src="https://github.com/rancher/rke2/assets/91496375/adda033b-4eda-43c3-8ca0-da927afb3773">

```
$ rke2 -v
rke2 version v1.28.8-rc1+rke2r1 (42cab2f61939504cb17073e47deaea0b29fe2c1b)
go version go1.21.8 X:boringcrypto
```
- ProviderID
```
$ kubectl describe nodes | grep -i provider
                     rke2.io/node-args: ["server","--write-kubeconfig-mode","644","--cloud-provider-name","rancher-vsphere"]
ProviderID:                   vsphere://4216015c-0cf7-8d41-5ed6-3fc7eab87537
```
- Cluster
```
NAME       STATUS   ROLES                       AGE   VERSION
ubuntu22   Ready    control-plane,etcd,master   13m   v1.28.8+rke2r1

NAMESPACE     NAME                                                   READY   STATUS      RESTARTS        AGE
default       basic                                                  1/1     Running     0               25s
kube-system   etcd-ubuntu22                                          1/1     Running     0               3m48s
kube-system   helm-install-rancher-vsphere-cpi-nd9l9                 0/1     Completed   0               3m46s
kube-system   helm-install-rancher-vsphere-csi-kv2hz                 0/1     Completed   0               3m46s
kube-system   helm-install-rke2-canal-l2xrz                          0/1     Completed   0               3m46s
kube-system   helm-install-rke2-coredns-zr8kj                        0/1     Completed   0               3m46s
kube-system   helm-install-rke2-ingress-nginx-nrpdh                  0/1     Completed   0               3m46s
kube-system   helm-install-rke2-metrics-server-9jgzl                 0/1     Completed   0               3m45s
kube-system   helm-install-rke2-snapshot-controller-79h2k            0/1     Completed   1               3m45s
kube-system   helm-install-rke2-snapshot-controller-crd-w7jhd        0/1     Completed   0               3m45s
kube-system   helm-install-rke2-snapshot-validation-webhook-kj5xb    0/1     Completed   0               3m45s
kube-system   kube-apiserver-ubuntu22                                1/1     Running     0               3m51s
kube-system   kube-controller-manager-ubuntu22                       1/1     Running     0               3m51s
kube-system   kube-proxy-ubuntu22                                    1/1     Running     0               3m54s
kube-system   kube-scheduler-ubuntu22                                1/1     Running     0               3m51s
kube-system   rancher-vsphere-cpi-cloud-controller-manager-mpf5p     1/1     Running     0               3m37s
kube-system   rke2-canal-lg9df                                       2/2     Running     0               3m32s
kube-system   rke2-coredns-rke2-coredns-84b9cb946c-2z9kh             1/1     Running     0               3m32s
kube-system   rke2-coredns-rke2-coredns-autoscaler-b49765765-xf5vk   1/1     Running     0               3m32s
kube-system   rke2-ingress-nginx-controller-g7qj9                    1/1     Running     0               2m11s
kube-system   rke2-metrics-server-544c8c66fc-dptj9                   1/1     Running     0               2m34s
kube-system   rke2-snapshot-controller-59cc9cd8f4-lfv2j              1/1     Running     0               2m34s
kube-system   rke2-snapshot-validation-webhook-54c5989b65-n6qdn      1/1     Running     0               2m31s
kube-system   vsphere-csi-controller-7bd49dff97-8hvn7                5/5     Running     0               3m32s
kube-system   vsphere-csi-controller-7bd49dff97-pj9gs                5/5     Running     0               3m32s
kube-system   vsphere-csi-controller-7bd49dff97-xpc8l                5/5     Running     1 (2m28s ago)   3m32s
kube-system   vsphere-csi-node-ptcr4                                 3/3     Running     2 (2m27s ago)   3m15s
```
- Chart status and version
```
$ helm ls -A
NAME                            	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                       	APP VERSION
rancher-vsphere-cpi             	kube-system	1       	2024-03-18 18:45:54.109966266 +0000 UTC	deployed	rancher-vsphere-cpi-1.7.001                 	1.28.0
rancher-vsphere-csi             	kube-system	1       	2024-03-18 18:45:54.082980931 +0000 UTC	deployed	rancher-vsphere-csi-3.1.2-rancher101        	3.1.2-rancher1
...
```

</details>

**Comment by mdrahman-suse** [comment]
Also validated in Rancher v2.8.3-rc5, used a split-roles setup (2cp, 1 etcd, 1 worker) and observed the cluster being active and pods running. The issue https://github.com/rancher/rancher/issues/44754 still exists and hence needed to add the manifest manually via Add-on Config
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "wrangler7.provo.rancherlabs.com"
      datacenters: "/Datacenter"
      username: "administrator@wrangler7.provo.rancherlabs.com"
      password: "Password@1234"
      credentialsSecret:
        generate: true
    cloudControllerManager:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-csi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "wrangler7.provo.rancherlabs.com"
      datacenters: "/Datacenter"
      username: "administrator@wrangler7.provo.rancherlabs.com"
      password: "Password@1234"
      clusterId: "maxtestcluster2"
      configSecret:
        generate: true
    storageClass:
      datastoreURL: "ds:///vmfs/volumes/64dc15b5-b9e6a409-3cca-ecf4bbe74510/"
    csiController:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
```
