### ISSUE TITLE
multus debug

### ISSUE THREAD

**Issue by ianb-mp** [rancher/rke2#5238]
**Describe the solution you'd like**
It would be useful to be able to enable debug log for Multus (the one bundled with rke2) e.g. adding these lines to Multus config file
```
   "logFile": "/var/log/multus.log",
   "logLevel": "debug",
```
I tried modifying `/etc/cni/net.d/00-multus.conf` however it gets overwritten when `rke2-multus-ds` is restarted

**Comment by brandond** [comment]
Use the chart values, don't try to edit files out from under it.

https://github.com/rancher/rke2-charts/blob/main/charts/rke2-multus/rke2-multus/v4.0.2-build2023081107/values.yaml#L99

**Comment by ianb-mp** [comment]
I wasn't aware of the ability to configure Helm chart values post install. For anyone wondering how to do it (the [doco](https://docs.rke2.io/helm?_highlight=helmchartconfig#customizing-packaged-components-with-helmchartconfig) is not clear on this IMHO) - create yaml:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    config:
      cni_conf:
        logFile: /var/log/multus.log
        logLevel: debug
 ```
Load via kubectl (e.g. `kubectl apply -f multus-conf.yaml`) and redeploy Multus daemonset
