### ISSUE TITLE
Selinux mls set level in static pod

### ISSUE THREAD

**Issue by patsys** [rancher/rke2#5273]
Hello,

I use rke2 with a MLS enabled selinux and same static pods, like etcd, have no level set and after restart the level changed randomly and the pod can't get access needed files.

Solution:
Append the same level to all system static-pods or let the level set with a parameter

**Comment by brandond** [comment]
Can you provide an example of how you're doing this for other pods?

**Comment by patsys** [comment]
I need the following part in my etcd.yaml and other static pods:

```
  securityContext:
    ...
    seLinuxOptions:
      level: s0:c100,c102
      type: rke2_service_db_t
```

this is the full etcd.yml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    etcd.k3s.io/initial: '{"initial-cluster":"phk8sm1-58b4dae3=https://10.232.1.104:2380,phk8sm2-b022fc8a=https://10.232.1.105:2380","initial-cluster-state":"existing"}'
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
  uid: 2dfdce2c4c1662dbd466c841f0209bf2
spec:
  containers:
  - args:
    - --config-file=/var/lib/rancher/rke2/server/db/etcd/config
    command:
    - etcd
    env:
    - name: FILE_HASH
      value: c49841fdd41cbb435af2075d97dae33d5d4a0b4a1e7d86b8478149bb07295599
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    image: index.docker.io/rancher/hardened-etcd:v3.5.9-k3s1-build20230802
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      privileged: false
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
    volumeMounts:
    - mountPath: /var/lib/rancher/rke2/server/db/etcd
      name: dir0
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      name: file0
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      name: file1
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      name: file2
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      name: file3
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      name: file4
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      name: file5
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/db/etcd/config
      name: file6
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  securityContext:
    runAsGroup: 999
    runAsUser: 999
    seLinuxOptions:
      level: s0:c100,c102
      type: rke2_service_db_t
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd
      type: DirectoryOrCreate
    name: dir0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.crt
      type: File
    name: file0
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-client.key
      type: File
    name: file1
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
      type: File
    name: file2
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.crt
      type: File
    name: file3
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-server-client.key
      type: File
    name: file4
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt
      type: File
    name: file5
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd/config
      type: File
    name: file6
status: {}
```
