### ISSUE TITLE
Pulling img from insecure registry

### ISSUE THREAD

**Issue by sirrutyna** [rancher/rke2#5287]
Hello, 

Got a problem. Trying to pull image from insecure registry and dont want to use https. My registry:
/etc/rancher/rke2/registries.yaml
mirrors:
  docker.io:
    endpoint:
      - "http://registry.domain.xx:port"

looks like this and when im pulling img I got:
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  20m                default-scheduler  Successfully assigned default/test-b885444s-qwwww to hostname
  Warning  Failed     18m (x6 over 20m)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    18m (x4 over 20m)  kubelet            Pulling image "registry.domain.xx:port/microservicetemplate:latest"
  Warning  Failed     18m (x4 over 20m)  kubelet            Failed to pull image 
"registry.domain.xx:port/microservicetemplate:latest": rpc error: code = Unknown desc = failed to pull and unpack image "registry.domain.xx:port/microservicetemplate:latest": failed to resolve reference "registry.domain.xx:port
/microservicetemplate:latest": failed to do request: Head "https://registry.domain.xx:port/v2/microservicetemplate/manifests/latest": http: server gave HTTP response to HTTPS client
  Warning  Failed     18m (x4 over 20m)  kubelet            Error: ErrImagePull
  Normal   BackOff    9s (x87 over 20m)  kubelet            Back-off pulling image "registry.domain.xx:port/microservicetemplate:latest"

---
What did I do wrong? I tried couple of version of registries.yaml:
mirrors:
```yaml
"registry.domain.xx:port":
    endpoint:
      - "http://registry.domain.xx:port/"
```
---
```yaml
mirrors:
  docker.io:
    endpoint:
      - "http://registry.example.com:5000"
  registry.example.com:
    endpoint:
      - "http://registry.example.com:5000"
```

same issue any helpers?

**Comment by Martin-Weiss** [comment]
I guess you should enable https on your registry and configure the endpoints for https as well. Not sure if these days someone out there is still using http.. there are some references for http here https://github.com/containerd/containerd/blob/release/1.5/docs/hosts.md#bypass-tls-verification-example - so maybe you need to create / adjust the containerd config in rke2 - see https://docs.rke2.io/advanced#configuring-containerd

**Comment by sirrutyna** [comment]
yeah I had to make a quick progress to I decided to go as error indicate and configure repo for https. Anyway I would love to see if there is any chance to work it around http.

**Comment by brandond** [comment]
You were close:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "http://registry.example.com:5000"
  registry.example.com:5000:
    endpoint:
      - "http://registry.example.com:5000"
```

Are you explicitly pulling images from this registry, or are you trying to use it as a mirror for docker.io? or both?
