### ISSUE TITLE
cilium_wg0 is note removed by the rke2-killall.sh script

### ISSUE THREAD

**Issue by faelis** [rancher/rke2#5288]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.27.6+rke2r1 (5cc9c774d6bf349b9ca3bcfab2a6010554fcffa7)
go version go1.20.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux XXXXXXXX 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 8 agents
cilium + wireguard, no kube-proxy 

**Describe the bug:**
When running the rke2-killall.sh script, the virtual interface cilium_wg0 is not deleted.

**Steps To Reproduce:**
add in config.yaml
```
disable-kube-proxy: true
cni: cilium
```
add this HelmChartConfig
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: XXXX
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

    encryption:
      enabled: true
      type: wireguard
```

- Installed RKE2: 

**Expected behavior:**
The cilium_wg0 is removed by the rke2-killall.sh script.

**Actual behavior:**
The cilium_wg0 is still there, even after running rke2-killall.sh script.

**Additional context / logs:**

**Comment by manuelbuil** [comment]
Could you please specify what config you used to deploy rke2 with: `cilium + wireguard, no kube-proxy` under `Steps To Reproduce:` section? Thanks!

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit 992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
or
```
1 server/ 1 agent
```
  
*Config.yaml:*

```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
cni: cilium
```
  
*Helm chart config to add in manifest folder*

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <control_plane_ip_alias_kube_api_server_ip>
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

    encryption:
      enabled: true
      type: wireguard
```
  
## Testing Steps

1. Copy `config.yaml`
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
Copy helm chart config into manifest folder: `/var/lib/rancher/rke2/server/manifests`

2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Check the list of interfaces, uninstall rke2 and re-check the status of virtual network interfaces. For Ex:
```
$ ip address show | grep cilium
$ rke2-killall.sh
$ ip address show | grep cilium
```
Ensure that `cilium_wg0` virtual network interface is removed post uninstall. 
  
**Replication Results:**
- rke2 version used for replication:

```
$ rke2 -v
rke2 version v1.29.1+rke2r1 (e6a0d1b4d779b0a0c73ecb2ee8ae2703d0025e6f)
go version go1.21.6 X:boringcrypto
```
 

Post uninstall check the virtual network interface list:
```
$ ip address show | grep cilium
cilium_wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 8921 qdisc noqueue state UNKNOWN group default 
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.29.1+dev.992194bd (992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92)
go version go1.21.6 X:boringcrypto
```
 

```
$ ip address show | grep cilium
```
