### ISSUE TITLE
Klipper Service LB not working with air-gap install

### ISSUE THREAD

**Issue by jagipson** [rancher/rke2#529]
rke2 version v1.18.10+rke2r1 (8e418583df2c62932657afd3c05973b577064cf5)
After performing an air-gap install and deploying nginx (5 replicas), I attempt to create a LoadBalancer to provide access to the nginx cluster from outside.  RKE2 is missing the documentation at https://docs.rke2.io/networking/#how-the-service-lb-works so I am basing my knowledge from https://rancher.com/docs/k3s/latest/en/networking/?#service-load-balancer assuming that it will work the same, since RKE2 is based off K3s.  I chose not to use the NGINX ingress controller because it appears to be meant for http traffic and what I'm doing here is a test setup for what will eventually be all kinds of TCP and UDP traffic.
```
  kubectl apply -f - <<EOF
  apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    selector:
      matchLabels:
        app: nginx
    replicas: 5 # tells deployment to run 5 pods matching the template
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: blueberry:5000/nginx:1.14.2
          ports:
          - containerPort: 80
  EOF
```
```
[root@blueberry manifests]# kubectl describe deployment
Name:                   nginx-deployment
Namespace:              default
CreationTimestamp:      Wed, 11 Nov 2020 16:47:54 -0500
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=nginx
Replicas:               5 desired | 5 updated | 5 total | 5 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=nginx
  Containers:
   nginx:
    Image:        blueberry:5000/nginx:1.14.2
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   nginx-deployment-595c57c47b (5/5 replicas created)
Events:          <none>
```
```
[root@blueberry manifests]# kubectl get pods -o wide 
NAME                                READY   STATUS    RESTARTS   AGE   IP          NODE        NOMINATED NODE   READINESS GATES
nginx-deployment-595c57c47b-2kkfq   1/1     Running   0          42h   10.42.1.5   pear        <none>           <none>
nginx-deployment-595c57c47b-bvklw   1/1     Running   0          42h   10.42.1.2   pear        <none>           <none>
nginx-deployment-595c57c47b-nzlrc   1/1     Running   0          42h   10.42.1.4   pear        <none>           <none>
nginx-deployment-595c57c47b-v5rsz   1/1     Running   0          42h   10.42.1.3   pear        <none>           <none>
nginx-deployment-595c57c47b-vj66c   1/1     Running   0          42h   10.42.0.4   blueberry   <none>           <none>
```
```
[root@blueberry manifests]#  kubectl get nodes -o wide
NAME        STATUS   ROLES         AGE   VERSION           INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                 CONTAINER-RUNTIME
blueberry   Ready    etcd,master   43h   v1.18.10+rke2r1   192.168.122.8     <none>        CentOS Linux 8 (Core)   4.18.0-193.28.1.el8_2.x86_64   containerd://1.3.6-k3s2
pear        Ready    <none>        42h   v1.18.10+rke2r1   192.168.122.185   <none>        CentOS Linux 8 (Core)   4.18.0-193.28.1.el8_2.x86_64   containerd://1.3.6-k3s2
```
```
[root@blueberry manifests]# kubectl get services -o wide
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
kubernetes     ClusterIP      10.43.0.1      <none>        443/TCP        43h   <none>
your-service   LoadBalancer   10.43.24.137   <pending>     80:30310/TCP   54m   app=nginx
```
This error DOES appear in the log:
`E1111 21:32:33.812218       1 core.go:89] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail`
