### ISSUE TITLE
404 not found for repomod.xml on RKE 1.29 and CentOS 9 derivates

### ISSUE THREAD

**Issue by mbranchnl** [rancher/rke2#5330]
**Environmental Info:**
RKE2 Version: v1.29.0+rke2r1

Node(s) CPU architecture, OS, and Version: 
Rocky Linux release 9.3 (Blue Onyx)
Architecture: x86_64

Cluster Configuration:
1 server

**Describe the bug:**
404 on repomd.xml when upgrading with install-script.
URL: https://rpm.rancher.io/rke2/stable/1.29/centos/9/x86_64/repodata/repomd.xml

**Steps To Reproduce:**
I'm building a ansible-role that maintains my RKE2 clusters with a auto-update function. During the following ansible-task:

```yaml
- name: Download install.sh
  ansible.builtin.get_url:
    url: https://get.rke2.io/
    dest: "{{ rke2_artifact_path }}/install.sh"
    mode: '0755'

- name: Run RKE2 installer
  ansible.builtin.shell:
    cmd: "{{ rke2_artifact_path }}/install.sh"
  environment:
    INSTALL_RKE2_VERSION: '{{ rke2_version }}'
    INSTALL_RKE2_TYPE: server
```
with vars:
```yaml
rke2_artifact_path: /tmp/
rke2_version: v1.29.0+rke2r1 (as mentioned as latest release in github)
```

gives the following error:
```yaml
fatal: [rke2]: FAILED! => changed=true
  cmd: /tmp//install.sh
  delta: '0:00:05.062107'
  end: '2024-01-28 15:11:11.344734'
  msg: non-zero return code
  rc: 1
  start: '2024-01-28 15:11:06.282627'
  stderr: |-
    Error: Failed to download metadata for repo 'rancher-rke2-1.29-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
    Errors during downloading metadata for repository 'rancher-rke2-1.29-stable':
      - Status code: 404 for https://rpm.rancher.io/rke2/stable/1.29/centos/9/x86_64/repodata/repomd.xml (IP: 104.21.2.160)
    Error: Failed to download metadata for repo 'rancher-rke2-1.29-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
  stderr_lines: <omitted>
  stdout: |-
    [INFO]  using 1.29 series from channel stable
    Rancher RKE2 1.29 (stable)                      347  B/s | 387  B     00:01
  stdout_lines: <omitted>
```

Manual download https://rpm.rancher.io/rke2/stable/1.29/centos/9/x86_64/repodata/repomd.xml also fails.

Working versions are:
https://rpm.rancher.io/rke2/stable/1.27/centos/9/x86_64/repodata/repomd.xml
https://rpm.rancher.io/rke2/stable/1.28/centos/9/x86_64/repodata/repomd.xml

**Expected behavior:**
A http-status 200 for: https://rpm.rancher.io/rke2/stable/1.29/centos/9/x86_64/repodata/repomd.xml

**Additional context / logs:**
This also is the case for CentOS version 8 related;
https://rpm.rancher.io/rke2/stable/1.29/centos/8/x86_64/repodata/repomd.xml
