### ISSUE TITLE
Update Cilium to v1.15.0

### ISSUE THREAD

**Issue by mgfritch** [rancher/rke2#5354]

**Comment by aganesh-suse** [comment]
### Validated on master branch with commit 992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
or
```
1 server/ 1 agent
```
  
*Config.yaml:*

```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
cni: cilium
```
  
*Helm chart config to add in manifest folder*

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <control_plane_ip_alias_kube_api_server_ip>
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

    encryption:
      enabled: true
      type: wireguard
```
  
## Testing Steps

1. Copy `config.yaml`
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
Copy helm chart config into manifest folder: `/var/lib/rancher/rke2/server/manifests`

2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Check the cilium image version is v1.15.0:
```
$ POD_NAME=$(/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pods -n kube-system | grep -i cilium | grep -v helm | awk '{print $1}' | head -n 1)
$/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pod/"${POD_NAME}" -n kube-system -o yaml | grep -i image
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.29.1+dev.992194bd (992194bd7e2f1eb8a9bbd8f2f4ae78e3ee314b92)
go version go1.21.6 X:boringcrypto
```
 

```
$ /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pod/cilium-operator-76846f5568-7kjs8 -n kube-system -o yaml | grep -i image | head -n 1
  image: rancher/mirrored-cilium-operator-generic:v1.15.0
```
