### ISSUE TITLE
[Release-1.28] - cilium_wg0 is note removed by the rke2-killall.sh script

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5403]
Backport fix for cilium_wg0 is note removed by the rke2-killall.sh script

* #5288

**Comment by aganesh-suse** [comment]
### Validated on release-1.28 branch with commit 42eefe402823d3a5d89a31b9fa934db1a164bff5
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
or
```
1 server/ 1 agent
```
  
*Config.yaml:*

```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
cni: cilium
```
  
*Helm chart config to add in manifest folder*

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <control_plane_ip_alias_kube_api_server_ip>
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

    encryption:
      enabled: true
      type: wireguard
```
  
## Testing Steps

1. Copy `config.yaml`
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
Copy helm chart config into manifest folder: `/var/lib/rancher/rke2/server/manifests`

2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='42eefe402823d3a5d89a31b9fa934db1a164bff5' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Check the list of interfaces, uninstall rke2 and re-check the status of virtual network interfaces. For Ex:
```
$ ip address show
$ rke2-killall.sh
$ ip address show
```
Ensure that `cilium_wg0` virtual network interface is removed. 
  
**Replication Results:**
- rke2 version used for replication:

```
$ rke2 -v
rke2 version v1.28.6+rke2r1 (572f367fd08e0e650a278477fdeea551dba48af7)
go version go1.20.13 X:boringcrypto
```
 

Post uninstall check the interface list: 
```
$ ip address show | grep cilium_wg0
cilium_wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 8921 qdisc noqueue state UNKNOWN group default
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.28.6+dev.42eefe40 (42eefe402823d3a5d89a31b9fa934db1a164bff5)
go version go1.20.13 X:boringcrypto
```
 

Post uninstall check the interface list: 
```
$ ip address show | grep cilium_wg0
```
