### ISSUE TITLE
[Release-1.27] - cilium_wg0 is note removed by the rke2-killall.sh script

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5404]
Backport fix for cilium_wg0 is note removed by the rke2-killall.sh script

* #5288

**Comment by aganesh-suse** [comment]
### Validated on release-1.27 branch with commit 335307711eaac128e10eafab8ea375c135ebfdb3
  
## Environment Details

  
*Infrastructure*
- [x] Cloud
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"

$ uname -m
x86_64
```
  
*Cluster Configuration:*

```
HA : 3 server / 1 agent
```
or
```
1 server/ 1 agent
```
  
*Config.yaml:*

```
token: xxxx
write-kubeconfig-mode: "0644"
node-external-ip: 1.1.1.1
cni: cilium
```
  
*Helm chart config to add in manifest folder*

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <control_plane_ip_alias_kube_api_server_ip>
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

    encryption:
      enabled: true
      type: wireguard
```
  
## Testing Steps

1. Copy `config.yaml`
```
$ sudo mkdir -p /etc/rancher/rke2 && sudo cp config.yaml /etc/rancher/rke2
```
Copy helm chart config into manifest folder: `/var/lib/rancher/rke2/server/manifests`

2. Install RKE2
```
curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_COMMIT='335307711eaac128e10eafab8ea375c135ebfdb3' INSTALL_RKE2_TYPE='server' INSTALL_RKE2_METHOD=tar sh -
```
3. Start the RKE2 service
```
$ sudo systemctl enable --now rke2-server
or 
$ sudo systemctl enable --now rke2-agent
```
4. Check the list of interfaces, uninstall rke2 and re-check the status of virtual network interfaces. For Ex:
```
$ ip address show
$ rke2-killall.sh
$ ip address show
```
Ensure that `cilium_wg0` virtual network interface is removed. 
  
**Replication Results:**
- rke2 version used for replication:

```
$ rke2 -v
rke2 version v1.27.10+rke2r1 (915672bd6cab658edb974d0aedb33ec5a32c239a)
go version go1.20.13 X:boringcrypto
```
 

```
$ ip address show | grep cilium
cilium_wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 8921 qdisc noqueue state UNKNOWN group default 
```
 
**Validation Results:**
- rke2 version used for validation:

```
$ rke2 -v
rke2 version v1.27.10+dev.33530771 (335307711eaac128e10eafab8ea375c135ebfdb3)
go version go1.20.13 X:boringcrypto
```
 

```
$ ip address show | grep cilium
```
