### ISSUE TITLE
Add "metrics" port 9153 to coredns service

### ISSUE THREAD

**Issue by kfkawalec** [rancher/rke2#544]
Prometheus expects to find metrics on port 9153, and when not found it raises an alert:
```
no service port 9153 found for service rke2-coredns-rke2-coredns"
```

When using rke2-coredns-rke2-coredns, I'd like the kube-dns service's ports have metrics port, not only the dns ports:
```
        "ports": [
            {
                "name": "udp-53",
                "port": 53,
                "protocol": "UDP",
                "targetPort": 53
            },
            {
                "name": "tcp-53",
                "port": 53,
                "protocol": "TCP",
                "targetPort": 53
            },
# missing part - start
            {
                "name": "metrics",
                "port": 9153,
                "protocol": "TCP",
                "targetPort": 9153
            }
# missing part - end
        ],
```

Related: https://github.com/coreos/prometheus-operator/issues/2278

**Comment by jonaz** [comment]
Also ran into this now when migrating from rke to rke2. The labels are correct and matched defaults in kube-prometheus. Just that the port named metrics is missing!

**Comment by kfkawalec** [comment]
Any update on this issue?
It's annoying when I create a new cluster.

**Comment by brandond** [comment]
This is an optional feature of the chart that is not enabled by default. If you want to opt into this, you can drop the following content in at `/var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml`:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    prometheus:
      service:
        enabled: true
```

You can find more info on customizing the packaged components here: https://docs.rke2.io/helm/#customizing-packaged-components-with-helmchartconfig

**Comment by zlmitchell** [comment]
If anyone walks into this this is configurable on downstream clusters from Rancher

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
spec:
  rkeConfig:
    chartValues:
      rke2-coredns:
        prometheus:
          service:
            enabled: true
```
