### ISSUE TITLE
rke2-multus does not adapt to the architecture (ARM64)

### ISSUE THREAD

**Issue by tardich** [rancher/rke2#5538]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.29.0+rke2r1 (4fd30c26c91dd3f2f623c5af00d1ebcfec8c2709)
go version go1.21.5 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux dietpi5 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Cluster Configuration:
3 masters in full HA mode

**Describe the bug:**
After an upgrade from 1.28.x to 1.29.0, I realized that multus pods did not start. After a deeper look, I found out that, even if my platform is an arm64 (aarch64), the daemonset for rke2-multus still try to lookup for nodes of amd64 (node labels):

```
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
```

This, in fact, isn't new. I remember seeing this in a previous upgrade, but did fix and forgot it afterward...

**Steps To Reproduce:**

- Installed RKE2: 

Did the installation strictly following the documentation for the nodes, apart from the kube-vip installation between first master and subsequent masters for the HA.

/etc/rancher/rke2/config.yaml looks like:

```
tls-san:
  - kubernetes.01.internal.fqdn
  - kubernetes.default.svc.cluster.01.internal.fqdn
cluster-cidr:
  - 10.46.0.0/16
service-cidr:
  - 10.47.0.0/16
cluster-domain:
  - cluster.01.internal.fqdn
disable:
  - rke2-ingress-nginx
cni:
  - multus,canal
kubelet-arg:
  - --cpu-cfs-quota=false
```
**Expected behavior:**
multus-pods starts normally

**Actual behavior:**
multus-pods do not start

**Additional context / logs:**

I would think that having an item in the config.yaml, like:

```
platform:
  - arm64
```

and, obviously, have the other rke2-brought helm charts using it would solve the issue, maybe defaulting to amd64 for the most common usecases. Anyway, it indeed is the default. And looking at the values.yaml file from the helm chart, I see:

```
labels:
  nodeSelector:
    kubernetes.io/arch: amd64
```

**Comment by brandond** [comment]
@mgfritch @manuelbuil it sounds like the chart needs an update to remove the `kubernetes.io/arch: amd64` nodeSelector.

In the mean time, you should be able to use something like this:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    labels:
      nodeSelector: 
        kubernetes.io/arch: null
```

**Comment by tardich** [comment]
Thanks for the HelmChartConfig tip, it works!  Added to my pipeline so I don't forget  :-)

**Comment by tardich** [comment]
Something else I found out....  I added, in the helmChartConfig, these lines so I get whereabouts installed:

```
spec:
  valuesContent: |-
    rke2-whereabouts:
      enabled: true
      nodeSelector:
        kubernetes.io/arch: arm64
```
Please note that I had to add nodeSelector again to target the right architecture

Now, I have rke2-multus-rke2-whereabouts daemonset installed, which is great, BUT.....

It's missing two CRD's (ippools.whereabouts.cni.cncf.io and overlappingrangeipreservations.whereabouts.cni.cncf.io) I can find in the whereabouts subchart, but they're not referenced anywhere, so I still can't use whereabouts (as these are required prior giving an IP to a workload.   If I try to install them manually, I can see them for a few seconds, then they disappear for whatever reason).

Anybody can help here ?

**Comment by tardich** [comment]
Just updated to v1.29.2+rke2r1, and I can see there<s an issue with rke2-multus helm chart:

From the rke2-server logs, just after the upgrade:

`msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/Chart.yaml: Addon.k3s.cattle.io \"Chart\" is invalid: metadata.name: Invalid value: \"Chart\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/Chart.yaml: Addon.k3s.cattle.io \"Chart\" is invalid: metadata.name: Invalid value: \"Chart\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/templates/cluster_role.yaml: Addon.k3s.cattle.io \"cluster_role\" is invalid: metadata.name: Invalid value: \"cluster_role\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/templates/cluster_role_binding.yaml: Addon.k3s.cattle.io \"cluster_role_binding\" is invalid: metadata.name: Invalid value: \"cluster_role_binding\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/templates/daemonset.yaml: yaml: line 6: could not find expected ':', failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/templates/serviceaccount.yaml: invalid character '{' looking for beginning of object key string, failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/charts/rke2-whereabouts/values.yaml: Object 'Kind' is missing in '{\"affinity\":{},\"fullnameOverride\":\"\",\"image\":{\"pullPolicy\":\"IfNotPresent\",\"repository\":\"rancher/hardened-whereabouts\",\"tag\":\"v0.6.2-build20231009\"},\"imagePullSecrets\":[],\"nameOverride\":\"\",\"namespaceOverride\":\"kube-system\",\"nodeSelector\":{\"kubernetes.io/arch\":\"amd64\"},\"podAnnotations\":{},\"podSecurityContext\":{},\"resources\":{\"limits\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}},\"securityContext\":{\"privileged\":true},\"serviceAccount\":{\"annotations\":{},\"create\":true},\"successfulJobsHistoryLimit\":0,\"tolerations\":[{\"effect\":\"NoSchedule\",\"operator\":\"Exists\"}],\"updateStrategy\":\"RollingUpdate\"}', failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/clusterRole.yaml: Addon.k3s.cattle.io \"clusterRole\" is invalid: metadata.name: Invalid value: \"clusterRole\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/clusterRoleBinding.yaml: Addon.k3s.cattle.io \"clusterRoleBinding\" is invalid: metadata.name: Invalid value: \"clusterRoleBinding\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/configMap.yaml: Addon.k3s.cattle.io \"configMap\" is invalid: metadata.name: Invalid value: \"configMap\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/customResourceDefinition.yaml: Addon.k3s.cattle.io \"customResourceDefinition\" is invalid: metadata.name: Invalid value: \"customResourceDefinition\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/daemonSet.yaml: Addon.k3s.cattle.io \"daemonSet\" is invalid: metadata.name: Invalid value: \"daemonSet\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/templates/serviceAccount.yaml: Addon.k3s.cattle.io \"serviceAccount\" is invalid: metadata.name: Invalid value: \"serviceAccount\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?([\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*](file://.[a-z0-9]([-a-z0-9]*[a-z0-9])%3f)*)'), failed to process /var/lib/rancher/rke2/server/manifests/rke2-multus/values.yaml: Object 'Kind' is missing in '{\"cniplugins\":{\"image\":{\"repository\":\"rancher/hardened-cni-plugins\",\"tag\":\"v1.2.0-build20231009\"},\"skipcnis\":\"flannel\"},\"config\":{\"cni_conf\":{\"multusConfFile\":\"auto\"}},\"global\":{\"systemDefaultRegistry\":\"\"},\"image\":{\"pullPolicy\":\"IfNotPresent\",\"repository\":\"rancher/hardened-multus-cni\",\"tag\":\"v4.0.2-build20231009\"},\"labels\":{\"nodeSelector\":{\"kubernetes.io/arch\":\"amd64\",\"kubernetes.io/os\":\"linux\"}},\"manifests\":{\"clusterRole\":true,\"clusterRoleBinding\":true,\"configMap\":false,\"customResourceDefinition\":true,\"daemonSet\":true,\"serviceAccount\":true},\"pod\":{\"resources\":{\"enabled\":false,\"multus\":{\"limits\":{\"cpu\":\"2000m\",\"memory\":\"1024Mi\"},\"requests\":{\"cpu\":\"250m\",\"memory\":\"128Mi\"}}}},\"rke2-whereabouts\":{\"enabled\":false},\"serviceAccount\":{\"name\":\"multus\"}}'"`

**Comment by rancher-max** [comment]
## Validated on v1.29.3-rc1+rke2r1

## Environment Details

  
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
  
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a && cat /etc/os-release
Linux ip-172-31-15-247 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 16:00:15 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
  
*Cluster Configuration:*

3 servers, 1 agent
  
*Config.yaml:*

```
write-kubeconfig-mode: "0644"
cni: multus,canal
```
  
*Additional files*

- This file needs to be present before starting rke2-server process
```yaml
# /var/lib/rancher/rke2/server/manifests/rke2-multus-config.yaml 
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    rke2-whereabouts:
      enabled: true
```
- This is a file to apply to validate multus functionality
```yaml
# multus-test.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: test-daemonset
spec:
  config: '{
    "cniVersion": "0.3.1",
    "plugins": [
      {
        "type": "macvlan",
        "capabilities": { "ips": true },
        "master": "ens5",
        "mode": "bridge",
        "ipam": {
        "type": "static",
        "routes": [
          {
            "dst": "0.0.0.0/0",
            "gw": "10.1.1.1"
          }
        ]
        }
      }, {
        "capabilities": { "mac": true },
        "type": "tuning"
      }
    ]
  }'
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-macvlan
  name: pod-macvlan
  namespace: test-daemonset
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "macvlan-conf",
      "ips": [ "10.1.1.101/24" ],
      "mac": "c2:b0:57:49:47:f1",
      "gateway": [ "10.1.1.1" ]
      }]'
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: Always
    name: multitool
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod2-macvlan
  name: pod2-macvlan
  namespace: test-daemonset
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "macvlan-conf",
      "ips": [ "10.1.1.102/24" ],
      "mac": "c2:b0:57:45:47:f1",
      "gateway": [ "10.1.1.1" ]
      }]'
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: Always
    name: multitool
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]
```
  
## Testing Steps

1. Install and run rke2 with the given configurations
2. Validate all multus pods are up (both the cni pods and the whereabouts pods): `$ k get all -A | grep -i multus`
3. Ensure multus is functioning as expected
  
**Replication Results:**
- None of the multus pods were up and running

 
**Validation Results:**
- All of the multus pods are up and running:
```
$ k get all -A | grep -i multus
kube-system   pod/helm-install-rke2-multus-48znq                                        0/1     Completed   0             16h
kube-system   pod/rke2-multus-6cwb5                                                     1/1     Running     0             16h
kube-system   pod/rke2-multus-6st5t                                                     1/1     Running     0             16h
kube-system   pod/rke2-multus-jf4t7                                                     1/1     Running     0             16h
kube-system   pod/rke2-multus-ltl5s                                                     1/1     Running     1 (16h ago)   16h
kube-system   pod/rke2-multus-rke2-whereabouts-bb54r                                    1/1     Running     0             16h
kube-system   pod/rke2-multus-rke2-whereabouts-hv6g2                                    1/1     Running     0             16h
kube-system   pod/rke2-multus-rke2-whereabouts-mgmcw                                    1/1     Running     1 (16h ago)   16h
kube-system   pod/rke2-multus-rke2-whereabouts-tbfn8                                    1/1     Running     0             16h
kube-system   daemonset.apps/rke2-multus                     4         4         4       4            4           kubernetes.io/os=linux   16h
kube-system   daemonset.apps/rke2-multus-rke2-whereabouts    4         4         4       4            4           kubernetes.io/os=linux   16h
kube-system   job.batch/helm-install-rke2-multus                        1/1           83s        16h
```
- General networking checks continue to function
- Ensured expected CRDs are present:
```
$ kubectl get crds | grep network-attachment
network-attachment-definitions.k8s.cni.cncf.io           2024-03-18T23:05:33Z
```
- Applied multus-test.yaml, retrieved pod IPs (verified there were multiple) and confirmed that pinging between them on all IPs was successful:
```
$ kubectl -n test-daemonset exec -ti pod-macvlan -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if258: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 4e:db:20:31:7c:ba brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.3.254/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4cdb:20ff:fe31:7cba/64 scope link 
       valid_lft forever preferred_lft forever
3: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
    link/ether c2:b0:57:49:47:f1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.1.1.101/24 brd 10.1.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::c0b0:57ff:fe49:47f1/64 scope link 
       valid_lft forever preferred_lft forever

$ kubectl -n test-daemonset exec -ti pod2-macvlan -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if259: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 22:ef:72:8f:ae:62 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.3.3/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20ef:72ff:fe8f:ae62/64 scope link 
       valid_lft forever preferred_lft forever
3: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
    link/ether c2:b0:57:45:47:f1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.1.1.102/24 brd 10.1.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::c0b0:57ff:fe45:47f1/64 scope link 
       valid_lft forever preferred_lft forever

$ kubectl -n test-daemonset exec -ti pod2-macvlan -- ping 10.42.3.254
PING 10.42.3.254 (10.42.3.254) 56(84) bytes of data.
64 bytes from 10.42.3.254: icmp_seq=1 ttl=63 time=0.118 ms
64 bytes from 10.42.3.254: icmp_seq=2 ttl=63 time=0.096 ms
64 bytes from 10.42.3.254: icmp_seq=3 ttl=63 time=0.090 ms
64 bytes from 10.42.3.254: icmp_seq=4 ttl=63 time=0.095 ms
^C
--- 10.42.3.254 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3075ms
rtt min/avg/max/mdev = 0.090/0.099/0.118/0.010 ms

$ kubectl -n test-daemonset exec -ti pod2-macvlan -- ping 10.1.1.101
PING 10.1.1.101 (10.1.1.101) 56(84) bytes of data.
64 bytes from 10.1.1.101: icmp_seq=1 ttl=64 time=0.088 ms
64 bytes from 10.1.1.101: icmp_seq=2 ttl=64 time=0.050 ms
64 bytes from 10.1.1.101: icmp_seq=3 ttl=64 time=0.052 ms
64 bytes from 10.1.1.101: icmp_seq=4 ttl=64 time=0.050 ms
^C
--- 10.1.1.101 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3053ms
rtt min/avg/max/mdev = 0.050/0.060/0.088/0.016 ms
```
