### ISSUE TITLE
opentelemetry can't be enabled with  rke2-ingress-nginx

### ISSUE THREAD

**Issue by albundy83** [rancher/rke2#5539]
**Environmental Info:**
RKE2 Version: 

```bash
root@ip-10-0-1-10:~# rke2 -v
rke2 version v1.26.13+rke2r1 (637e8a38334f603b60650b30547252a5c461fa0d)
go version go1.20.13 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

```bash
root@ip-10-0-1-10:~# uname -a
Linux ip-10-0-1-10 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Cluster Configuration:

3 control planes, 4 workers, calico

**Describe the bug:**

When I enable opentelemetry, I correctly see the new init container:
```yaml
...
        - name: opentelemetry
          image: >-
            registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5@sha256:13bee3f5223883d3ca62fee7309ad02d22ec00ff0d7033e3e9aca7a9f60fd472
          command:
            - /init_module
          resources: {}
          volumeMounts:
            - name: modules
              mountPath: /modules_mount
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
      containers:
        - name: rke2-ingress-nginx-controller
          image: rancher/nginx-ingress-controller:nginx-1.9.3-hardened1
...
```
But, nginx can't load the `otel_ngx_module.so` file, here the error:
```bash
-------------------------------------------------------------------------------
Error: exit status 1
2024/03/01 13:27:48 [emerg] 10241#10241: dlopen() "/modules_mount/etc/nginx/modules/otel/otel_ngx_module.so" failed (libssl.so.3: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfg1131410920:7
nginx: [emerg] dlopen() "/modules_mount/etc/nginx/modules/otel/otel_ngx_module.so" failed (libssl.so.3: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfg1131410920:7
nginx: configuration file /tmp/nginx/nginx-cfg1131410920 test failed
-------------------------------------------------------------------------------
```

I have tried to add the init container but not enable opentelemetry and I confirm the error message:
```bash
www-data@rke2-ingress-nginx-controller-5wnr5:/etc/nginx> ldd /modules_mount/etc/nginx/modules/otel/otel_ngx_module.so 
ldd: warning: you do not have execution permission for `/modules_mount/etc/nginx/modules/otel/otel_ngx_module.so'
  linux-vdso.so.1 (0x00007fffd3ffc000)
  /usr/local/lib/libmimalloc.so (0x00007f172ba00000)
  libssl.so.3 => not found      # sadness
  libcrypto.so.3 => not found      # sadness
  libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f172b400000)
  libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f172b000000)
  libc.musl-x86_64.so.1 => not found      # sadness
  libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f172afdc000)
  librt.so.1 => /lib64/librt.so.1 (0x00007f172afd2000)
  libc.so.6 => /lib64/libc.so.6 (0x00007f172addb000)
  libm.so.6 => /lib64/libm.so.6 (0x00007f172ac8f000)
  /lib64/ld-linux-x86-64.so.2 (0x00007f172c818000)
```

**Steps To Reproduce:**

- Installed RKE2: 
 v1.26.13+rke2r1

**Expected behavior:**

It will be nice to be able to enable opentelemetry.

Maybe add `libssl.so.3` in the nginx-1.9.3-hardened1 container but we will need also `libcrypto.so.3` and `libc.musl-x86_64.so.1`.

**Actual behavior:**

**Additional context / logs:**

My full rke2 ingress nginx config, I use HelmChartConfig to override default values:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |
    controller:
      opentelemetry:
        enabled: true
      extraVolumes:
        - name: crowdsec-bouncer-plugin
          emptyDir: {}
      extraInitContainers:
        - name: init-clone-crowdsec-bouncer
          image: crowdsecurity/lua-bouncer-plugin
          imagePullPolicy: IfNotPresent
          env:
            - name: API_URL
              value: http://crowdsec-service.crowdsec.svc.cluster.local:8080
            - name: API_KEY
              value: VKhR5iDayZObawimKcHLnQ
            - name: BOUNCER_CONFIG
              value: /crowdsec/crowdsec-bouncer.conf
            - name: CAPTCHA_PROVIDER
              value: turnstile
            - name: SECRET_KEY
              value: xxxxxxxxxxxxxxxxxsomethinglongxxxxxxxxxxxxxx
            - name: SITE_KEY
              value: xxxxxxxxxxxxxxxxxsomethinglongxxxxxxxxxxxxxx
            - name: BAN_TEMPLATE_PATH
              value: /etc/nginx/lua/plugins/crowdsec/templates/ban.html
            - name: CAPTCHA_TEMPLATE_PATH
              value: /etc/nginx/lua/plugins/crowdsec/templates/captcha.html
          command: ['sh', '-c', 'sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp -R /crowdsec/* /lua_plugins/crowdsec/']
          volumeMounts:
            - name: crowdsec-bouncer-plugin
              mountPath: /lua_plugins
      extraVolumeMounts:
        - name: crowdsec-bouncer-plugin
          mountPath: /etc/nginx/lua/plugins/crowdsec
          subPath: crowdsec
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            release: kube-prometheus-stack
          relabelings:
            - targetLabel: cluster
              replacement: myprecious-rke2-cluster
      maxmindLicenseKey: xxxxxxxxxxxxxxxxxsomethinglongxxxxxxxxxxxxxx
      config:
        enable-opentelemetry: true
        opentelemetry-config: /etc/nginx/opentelemetry.toml
        opentelemetry-operation-name: HTTP $request_method $service_name $uri
        opentelemetry-trust-incoming-span: 'true'
        otlp-collector-host: tempo.tempo
        otlp-collector-port: '4317'
        otel-max-queuesize: '2048'
        otel-schedule-delay-millis: '5000'
        otel-max-export-batch-size: '512'
        otel-service-name: nginx-proxy
        otel-sampler: AlwaysOn
        otel-sampler-ratio: '1.0'
        otel-sampler-parent-based: false
        compute-full-forward-for: true
        server-tokens: false
        use-forwarded-headers: true
        use-proxy-protocol: true
        client-body-buffer-size: 40M
        proxy-body-size: 40M
        client-body-timeout: '600'
        use-geopip2: true
        plugins: crowdsec
        proxy-connect-timeout: '600'
        proxy-read-timeout: '600'
        proxy-send-timeout: '600'
        lua-shared-dicts: 'crowdsec_cache: 100m'
        server-snippet: |
          lua_ssl_trusted_certificate '/etc/ssl/ca-bundle.pem';
          resolver local=on ipv6=off;
          opentelemetry_attribute "ingress.namespace" "$namespace";
          opentelemetry_attribute "ingress.service_name" "$service_name";
          opentelemetry_attribute "ingress.name" "$ingress_name";
          opentelemetry_attribute "ingress.upstream" "$proxy_upstream_name";
    dhParam: xxxxxxxxxxxxxxxxxsomethingverylongxxxxxxxxxxxxxx
````
