### ISSUE TITLE
RKE2 cluster with CNI flannel fails to be created using Rancher UI

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#5637]
**Environmental Info:**
RKE2 Version: 

RKE2 release in March

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

Any

**Describe the bug:**

In clusters with taints, such as:
```
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
```
Flannel fails to start because the daemonset has wrong tolerations

**Steps To Reproduce:**

- Installed RKE2: 
Deploy rke2+flannel in a cluster with the previous taints

**Expected behavior:**

Flannel daemonset deploys

**Actual behavior:**

Flannel daemonset does not deploy and hence the cluster is never ready

**Additional context / logs:**
