### ISSUE TITLE
NodePort only responding on node where pod is running

### ISSUE THREAD

**Issue by jobins-devs** [rancher/rke2#5657]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.29.3+rke2r1 (1c82f7ed292c4ac172692bb82b13d20733909804)
go version go1.21.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux dev-k8s-master-1 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 master nodes

**Describe the bug:**
Service with type NodePort is reachable only with node IP where the pod is running

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
  labels:
    app.kubernetes.io/instance: app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app
  name: app
  namespace: app
spec:
  clusterIP: 10.43.245.148
  clusterIPs:
  - 10.43.245.148
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30011
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

# Cluster Config:
```yaml
token: <token>
write-kubeconfig-mode: "0644"
tls-san:
  - k8s.app.com
cni:
  - calico
node-label:
  - "node=master"
  - "env=dev"
```

**Comment by gensahil1997** [comment]
Faced the same issue

**Comment by manuelbuil** [comment]
I can't reproduce the problem, let me try to understand what might be going on. Could you please provide the output of:
* `kubectl get svc -A`
* `kubectl get endpoints -A`

In a node where pod is **not** running, can you provide the output of:
* `cat /etc/cni/net.d/10-calico.conflist`
* `iptables -nt nat --list -v | grep CNI-HOSTPORT-DNAT -n5`
And then specify how you are trying to access the service please

**Comment by mhrznamn068** [comment]
```
kubectl get svc -A
NAMESPACE       NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
calico-system   calico-kube-controllers-metrics           ClusterIP   None            <none>        9094/TCP        8d
calico-system   calico-typha                              ClusterIP   10.43.60.199    <none>        5473/TCP        8d
default         kubernetes                                ClusterIP   10.43.0.1       <none>        443/TCP         8d
app              app                                    NodePort    10.43.245.148   <none>        80:30011/TCP    17h
kube-system     rke2-coredns-rke2-coredns                 ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP   8d
kube-system     rke2-ingress-nginx-controller-admission   ClusterIP   10.43.112.218   <none>        443/TCP         8d
kube-system     rke2-metrics-server                       ClusterIP   10.43.6.141     <none>        443/TCP         8d
kube-system     rke2-snapshot-validation-webhook          ClusterIP   10.43.174.139   <none>        443/TCP         8d

kubectl get endpoints -A
NAMESPACE       NAME                                      ENDPOINTS                                                  AGE
calico-system   calico-kube-controllers-metrics           10.42.155.1:9094                                           8d
calico-system   calico-typha                              10.10.0.11:5473,10.10.0.12:5473                            8d
default         kubernetes                                10.10.0.10:6443,10.10.0.11:6443,10.10.0.12:6443            8d
app          app                                    10.42.59.151:80                                            17h
kube-system     rke2-coredns-rke2-coredns                 10.42.155.2:53,10.42.92.65:53,10.42.155.2:53 + 1 more...   8d
kube-system     rke2-ingress-nginx-controller-admission   10.42.155.3:8443,10.42.228.201:8443,10.42.42.71:8443       8d
kube-system     rke2-metrics-server                       10.42.59.129:10250                                         8d
kube-system     rke2-snapshot-validation-webhook          10.42.92.66:8443                                           8d
```

**Comment by brandond** [comment]
What is the internalTrafficPolicy and externalTrafficPolicy on your service? Can you provide the service definition yaml?

**Comment by mhrznamn068** [comment]
> What is the internalTrafficPolicy and externalTrafficPolicy on your service? Can you provide the service definition yaml?
**externalTrafficPolicy: Cluster**

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
  labels:
    app.kubernetes.io/instance: app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app
  name: app
  namespace: app
spec:
  clusterIP: 10.43.245.148
  clusterIPs:
  - 10.43.245.148
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30011
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
  ```
