### ISSUE TITLE
Kube Proxy misconfiguration after rke2-agent service restart

### ISSUE THREAD

**Issue by brandtkeller** [rancher/rke2#573]
Noticing a consistent problem for kube-proxy pods running on agent nodes when the agent service is restarted on that node. Confirmed behavior on multiple default/minimal configuration rke2 clusters (centos 7/8)

Through a quick search I see it might be possible to set the configs via a configmap instead of the configuration file. If someone can walk me through this process, that would be appreciated. 

## Context
I was having trouble with pod to pod communication anytime the source of the communication was a pod located on an agent node.
Looking through all of the kube-system pods - I noticed the kube-proxy pods on the agent nodes were having throwing error: `Failed to watch *v1.Endpoints` (More verbose output below)

## Process
Deploy cluster then restart each node's rke2 service.

## Expected Result
rke2-agent service restarts and uses the same port as previously allocated in `/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig`. This allows the kube-proxy pod that pulled that configuration previously to continue running.

OR

Update/restart the currently running kube-proxy pod for each updated configuration

## Current Result
rke2-agent service restarts, writes a new `/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig`, but this isn't reconciled with the running kube-proxy pod and the pod isn't restarted to pickup the new configurations. kube-proxy pod on agents starts logging:

```
E1206 22:07:22.854725       1 reflector.go:383] k8s.io/client-go/informers/factory.go:135: Failed to watch *v1.Endpoints: Get https://127.0.0.1:44993/api/v1/endpoints?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=7800933&timeout=6m39s&timeoutSeconds=399&watch=true: dial tcp 127.0.0.1:44993: connect: connection refused
```
The port mentioned above `44993` is the previous configuration.

**Comment by BillKlineVT** [comment]
I ran into this issue with v1.18.13+rke2r1

thank you for writing this up as I spent a few hours troubleshooting why pod to pod comms were being refused.

Per your description, a workaround for me after a rke2-agent service restart is to delete the kube-proxy pods and when they come back, all is good.

My setup is a single rke2-server with 3 rke2-agents all running on CentOS 7 in a vSphere cluster.

**Comment by jonaz** [comment]
We also ran into this. Good thing we notices before we started moving production load to our new rke2 clusters. Will have to wait before we can use our new clusters now.

**Comment by marshallford** [comment]
Still running into this on `v1.19.7+rke2r1`.

**Comment by brandond** [comment]
Just to confirm the issue here - kube-proxy on agent nodes communicates with the apiserver via the tunnel proxy. The tunnel proxy on *agents* binds to a random port on startup; every time RKE2 starts the tunnel proxy binds to a new port and the port is written to /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig. 

For static pods that reference local config files, we hash the content of files on-disk and update the manifest when they change to trigger an update to the pod. Unfortunately, kube-proxy is deployed as a DaemonSet via helm chart, so we have no way to signal to it that the content has changed.

**Comment by jonaz** [comment]
We have this workaroud in place on our centos 8 machines: 
```
# cat /etc/systemd/system/rke2-agent.service.d/10-restart-kube-proxy.conf
[Service]
ExecStartPost=sh -c 'kill "$(pidof kube-proxy)"; exit 0'
```

Until this is fixed :)

**Comment by rancher-max** [comment]
#### Validated on master build

- Previously, the port in kubeproxy kubeconfig would be randomized
- Now, the port is locked in at 6443:
```
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /var/lib/rancher/rke2/agent/server-ca.crt
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate: /var/lib/rancher/rke2/agent/client-kube-proxy.crt
    client-key: /var/lib/rancher/rke2/agent/client-kube-proxy.key
```
- Do not see the errors in the pod logs with this fix
- Pod to Pod communication appears to be working correctly after restart
