### ISSUE TITLE
Lack of configuration posibilities to enable DNS cache with Cilium CNI without kubeproxy

### ISSUE THREAD

**Issue by chrpinedo** [rancher/rke2#5832]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.8+rke2r1 (42cab2f61939504cb17073e47deaea0b29fe2c1b)
go version go1.21.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux k8s-pruebas-cp1-800312fa-dv692 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 control planes and 3 workers

**Describe the bug:**
Lack of configuration posibilities to enable DNS cache with Cilium CNI without kubeproxy.

RKE2 documentation provides the steps to enable Cilium CNS and replace kube-proxy with Cilium [1]. RKE2 documentation also provides the steps to enable DNS Cache with nodelocal [2]. However it lacks the information of how to enable nodelocal in the case of replacing kube-proxy with Cilium.

Furthermore, taking a look at the values of the rke2-coredns 1.29.002 chart [3], it seems to lack the options to deploy nodelocal without kube-proxy.

[1] https://docs.rke2.io/networking/basic_network_options?_highlight=cilium#install-a-cni-plugin
[2] https://docs.rke2.io/networking/networking_services?_highlight=cache#nodelocal-dnscache
[3] https://github.com/rancher/rke2-charts/tree/main/charts/rke2-coredns/rke2-coredns/1.29.002

**Comment by thomasferrandiz** [comment]
Validation steps:
- set rke2 configuration:
```yaml
```
- set cilium configuration:
```yaml
---
# /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <KUBE_API_SERVER_IP>
    k8sServicePort: <KUBE_API_SERVER_PORT>
    localRedirectPolicy: true
 ```
 
 - set coredns configuration:
 ```yaml
---
# /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    nodelocal:
      enabled: true
      use_cilium_lrp: true
```
