### ISSUE TITLE
RKE2 server breaks nginx

### ISSUE THREAD

**Issue by koxu1996** [rancher/rke2#5840]
### Environmental Info

- RKE2 Version: `v1.27.12+rke2r1 (25b27b4e4709a2ac4c550609ad730a9e172d110a)`

Node - medium size VPS running in Linode:

- OS: Arch Linux
- Architecture: x64
- Kernel version: 6.8.7

No firewalld, no network managers.
Nginx server installed and listening on ports 80/443.

### Cluster Configuration:

1 server with WireGuard backend:

```
# /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      backend: "wireguard"
```

### Problem Description

After installing RKE2 server, my website served with nginx suddenly stopped working:

![image](https://github.com/rancher/rke2/assets/6506780/4b5797ce-dd47-4329-b445-5306236450e4)

I see that network traffic is hijacked by Kuberenetes ingress:

![image](https://github.com/rancher/rke2/assets/6506780/111b72de-10a8-4b6a-b2b7-76ff472a3303)

Interestingly, there is no other process listening on port 443:

```
$ sudo ss -tulpn | grep 443
tcp   LISTEN 0      511            0.0.0.0:443        0.0.0.0:*    users:(("nginx",pid=1153231,fd=7),("nginx",pid=1130375,fd=7))
tcp   LISTEN 0      4096                 *:6443             *:*    users:(("kube-apiserver",pid=949,fd=3))
```

I guess RKE2 or CNI uses iptables to hijack the whole traffic. This is unexpected behavior and I am looking for fix/workaround.
