### ISSUE TITLE
RKE2 kube-proxy readiness probe fails when--healthz-bind-address set to 127.0.0.1

### ISSUE THREAD

**Issue by Badrmoh** [rancher/rke2#5860]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.29.3+rke2r1 (1c82f7ed292c4ac172692bb82b13d20733909804)
go version go1.21.8 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
setup is installed on 2 virtual machines on vSphere

**- Master**: Linux master 6.1.0-20-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
**- Agent**: Linux agent 6.1.0-20-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux 

Cluster Configuration:
- 1 master node
- 1 agent node

**Describe the bug:**
- readiness probe fails with connection refused **on agent** when using `--healthz-bind-address=127.0.0.1`

**Steps To Reproduce:**
- Installed RKE2 Server and Agent using `https://get.rke2.io` script and by setting `INSTALL_RKE2_CHANNEL=latest`
- Added `/etc/rancher/rke2/config.yaml` with token and server address on agent
- watched kube-proxy pod restarting every few minutes and not getting ready

**Expected behavior:**
- Readiness probe should have succeeded such that kube-proxy keeps running and does not keep restarting every 4-5 minutes.

**Actual behavior:**
- Readiness Probe keeps reporting connection refused

**Additional context / logs:**
- The same exact problem happens in RKE2 v1.27.12 which was installed using `https://get.rke2.io` script.
- Testing using curl on both the Agent node itself and inside pod worked as expected

```
$ kubectl exec -it -n kube-system  kube-proxy-agent -- curl http://localhost:10256/healthz
{"lastUpdated": "2024-04-29 07:24:26.951815018 +0000 UTC m=+231.679213685","currentTime": "2024-04-29 07:24:26.951815018 +0000 UTC m=+231.679213685", "nodeEligible": true}
```

**Comment by brandond** [comment]
The kube-proxy pod's liveness and startup probes (the only two probes defined) already target localhost, not the node IP. There is no readiness probe configured. Can you confirm **specifically** what you're looking at in regards to the failing probe?

```yaml
    command:
    - kube-proxy
    env:
    - name: FILE_HASH
      value: 69088f8f6ef0f26935d659eeeac8d50ae97cd150d49754fdff0c19fdb8a9465a
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    image: index.docker.io/rancher/hardened-kubernetes:v1.29.4-rke2r1-build20240416
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /healthz
        port: 10256
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-proxy
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
    securityContext:
      privileged: true
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: localhost
        path: /healthz
        port: 10256
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
```
