### ISSUE TITLE
registries.yaml does not work as expected

### ISSUE THREAD

**Issue by sepauli** [rancher/rke2#5947]
**Environmental Info:**
RKE2 Version:
``` 
$ rke2 --version
rke2 version v1.30.1-rc3+rke2r1 (e7f87c6dd56fdd76a7dab58900aeea8946b2c008)
go version go1.22.2 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 
```
$ cat /etc/issue
Ubuntu 24.04 LTS \n \l

x86_64
```

Cluster Configuration:
1 controlplane, 2 agents

**Describe the bug:**
config containerd registry with following configuration in `/etc/rancher/rke2/registries.yaml`
```
mirrors:
  "[docker_registry_ipv6]:5000":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "$1"
  # This is for Docker images that don't have an explicit registry prefix.
  "":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "docker.io/$1"
  "docker.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "docker.io/$1"
  "index.docker.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "docker.io/$1"
  "registry-1.docker.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "docker.io/$1"
  "quay.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "quay.io/$1"
  "ghcr.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "ghcr.io/$1"
  "gcr.io":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "gcr.io/$1"
  "public.ecr.aws":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
    rewrite:
      "(.*)": "public.ecr.aws/$1"
```
an internal docker registry is accessible via the ipv6 which holds the image (twuni/docker-registry).
the registry has no https/certificates
this configuration works in the rke version: `v1.26.6+rke2r1` and the containers can be pulled from the internal docker-registry

if i use this configuration for a cluster with the version `v1.30.1-rc3+rke2r1` it does not work and I get the following error
```
Warning  Failed     98s (x4 over 3m8s)  kubelet            Failed to pull image "rook/ceph:v1.13.5": failed to pull and unpack image "docker.io/rook/ceph:v1.13.5": failed to resolve reference "docker.io/rook/ceph:v1.13.5": failed to do request: Head "https://registry-1.docker.io/v2/rook/ceph/manifests/v1.13.5": dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: server misbehaving
```

the hosts.toml for containerd is created as follows
```
$ cat /var/lib/rancher/rke2/agent/etc/containerd/certs.d/docker.io/hosts.toml 
# File generated by rke2. DO NOT EDIT.

server = "https://registry-1.docker.io/v2"
capabilities = ["pull", "resolve", "push"]


[host]
[host."http://[docker_registry_ipv6]:5000/v2"]
  capabilities = ["pull", "resolve"]
  [host."http://[docker_registry_ipv6]:5000/v2".rewrite]
    "(.*)" = "docker.io/$1"
```

As a workaround, I have created the following config.toml.tmpl for containerd. `/var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl`
With this config it works.
```
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/rke2/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "index.docker.io/rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true
  



[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true

#[plugins."io.containerd.grpc.v1.cri".registry]
#  config_path = "/var/lib/rancher/rke2/agent/etc/containerd/certs.d"


[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors.""]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."".rewrite]
    "(.*)" = "docker.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io".rewrite]
    "(.*)" = "docker.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ docker_registry_ipv6 }}:{{ docker_registry_port }}"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ docker_registry_ipv6 }}:{{ docker_registry_port }}".rewrite]
    "(.*)" = "$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io".rewrite]
    "(.*)" = "gcr.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io".rewrite]
    "(.*)" = "ghcr.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."index.docker.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."index.docker.io".rewrite]
    "(.*)" = "docker.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws".rewrite]
    "(.*)" = "public.ecr.aws/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io".rewrite]
    "(.*)" = "quay.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io"]
  endpoint = ["http://[{{ docker_registry_ipv6 }}]:{{ docker_registry_port }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io".rewrite]
    "(.*)" = "docker.io/$1"

[plugins."io.containerd.grpc.v1.cri".registry.configs."{{ docker_registry_ipv6 }}:{{ docker_registry_port }}".tls]
  insecure_skip_verify = true

```

If it is possible, I would have the configuration created via registry.yaml and rke2.
Do I have to make changes to the registries.yaml so that it creates the config for containerd correctly?

**Steps To Reproduce:**

- install rke2 v1.30.1-rc3+rke2r1 (ipv6 only)
- config /etc/rancher/rke2/registries.yaml
- restart rke2-server or rke2-agent
- check if containers are loaded from internal docker-registry without tls

**Comment by brandond** [comment]
```yaml
mirrors:
  "[docker_registry_ipv6]:5000":
    endpoint:
      - "http://[docker_registry_ipv6]:5000"
```

containerd does not support IPv6 literals in registry mirror endpoints. See https://github.com/containerd/containerd/issues/10055
