### ISSUE TITLE
[Release-1.30] Bump Harvester cloud provider v0.2.4

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rke2#6008]
Bump Harvester cloud provider v0.2.4

PR: https://github.com/rancher/rke2/pull/5980

cc @Vicente-Cheng, @bk201, @w13915984028, @innobead

**Comment by VestigeJ** [comment]
Valid across all release branches 

v1.30 COMMIT_ID=3aaa16c9b17da45e9f3475ba5011ed90a49a2e42
v1.29 COMMIT_ID=0c6c6ff050d277db532021437fd94a66e46b1337
v1.28 COMMIT_ID=2c90f3baa0dbd555d5972db542421f3d2cded7b5
v1.27 COMMIT_ID=c852d3c71b5fdd741a7df7513836ef719087e282

$ sudo cat /var/lib/rancher/rke2/data/v1.30.1-dev.3aaa16c9-ce6ea36723d0/charts/harvester-cloud-provider.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: "harvester-cloud-provider"
  namespace: "kube-system"
  annotations:
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/harvester-cloud-provider/harvester-cloud-provider-0.2.400.tgz"
    rke2.cattle.io/inject-cluster-config: "true"
```
