### ISSUE TITLE
Allow disabling HelmChart cluster variable injection

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#6009]
RKE2 currently rewrites all HelmChart manifests found in `/var/lib/rancher/rke2/server/manifests` to inject cluster configuration variables.

This may be undesirable in certain circumstances - for example, if using a configuration management system such as Ansible to drop these files. Ansible will revert the changes, and rke2 will put them back when restarted, and so on.

In retrospect, we should have made injecting these values opt-in, via an annotation on our packaged HelmChart resources. Since the behavior has been this way for a long time, some users may be relying on it, so we should probably make it opt-out. An Annotation on the HelmChart resource would be a good way to do this. Perhaps `rke2.cattle.io/no-inject-cluster-config=true` or `rke2.cattle.io/inject-cluster-config=false`?

The annotation would need to be in the manifest **on disk**:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
  annotations:
    rke2.cattle.io/inject-cluster-config: "false"
spec:
  chart: cert-manager
  createNamespace: true
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
  targetNamespace: cert-manager
  version: v1.9.1
```

Perhaps at some point in the future we could make this opt-in, and set the annotation value to enable on all our packaged HelmChart manifests. This would need to be announced a ways out.
