### ISSUE TITLE
Snapshot retention does not work with etcd-s3-folder

### ISSUE THREAD

**Issue by vitorsavian** [rancher/rke2#6115]
**Environmental Info:**
RKE2 Version: 1.30.1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

- 1 server with etcd

**Describe the bug:**

- Snapshot retention does not work when s3 folder is set 

**Steps To Reproduce:**

- Install RKE2
- Setup RKE2 with the `etcd-s3-folder` flag
```yaml
cluster-init: true
etcd-s3: true
etcd-snapshot-schedule-cron: '*/1 * * * *'
etcd-snapshot-retention: 5
etcd-s3-bucket: bucket-name
etcd-s3-folder: bucket-folder
etcd-s3-region: bucket-region
etcd-s3-access-key: s3-access-key
etcd-s3-secret-key: s3-secret-key
```

**Expected behavior:**

- Snapshot retention needs to maintain the retention deleting old snapshots when `etcd-s3-folder` is set

**Actual behavior:**

- Snapshot retention does not occur when `etcd-s3-folder` is set

**Additional context / logs:**
