### ISSUE TITLE
config.yaml.d/50-rancher.yaml contains JSON content

### ISSUE THREAD

**Issue by anmazzotti** [rancher/rke2#6221]
**Environmental Info:**
RKE2 Version:  v1.27.8+rke2r1

```
# /opt/rke2/bin/rke2 -v
rke2 version v1.27.8+rke2r1 (77c9470934d7073341fb297aefa2dda0b97909c9)
go version go1.20.11 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
```yaml
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: volcano
  namespace: fleet-default
spec:
  rkeConfig:
    machineGlobalConfig:
      etcd-expose-metrics: false
      profile: null
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: fire-machine-selector
        name: fire-pool
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: 
      mirrors:
        "172.18.0.2:30000":
          endpoint:
            - "http://172.18.0.2:30000"
      configs:
        "172.18.0.2:30000":
          insecureSkipVerify: true    
  kubernetesVersion: v1.27.8+rke2r1
```

**Describe the bug:**

The generated (by Rancher provisioning) RKE2 configuration file contains JSON content, instead of YAML.

```
# cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml 
{
  "agent-token": "5spbtdwvrmll6gwz45g48g4w7wfbm9sdtd542fpf8px4wmwg27lfrc",
  "cni": "calico",
  "etcd-expose-metrics": false,
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "rke.cattle.io/machine=5c0d4813-3c26-475c-98e4-ecae91df34c0"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "token": "9qxx76r2nmfwnmbpnrtn96vmjppzpxfkm2n2cltbwf7mw4ccj2rw2l"
}
```

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

All .yaml files should contain YAML content.

**Actual behavior:**

This .yaml file contains JSON content.

**Additional context / logs:**

While it is theoretically safe to load JSON content using a YAML parser, I am not sure whether all parser support it and how actually safe it is.
