### ISSUE TITLE
`rke2-cloud-controller-manager` RB/CRBs subject lists grow without bound

### ISSUE THREAD

**Issue by yoderme** [rancher/rke2#6272]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.28.6+rke2r1 (572f367fd08e0e650a278477fdeea551dba48af7)

Node(s) CPU architecture, OS, and Version: 

Linux (redacted) 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

24 nodes.

**Describe the bug:**

In the `kube-system` namespace the `rke2-cloud-controller-manager-authentication-reader` RoleBinding appears to grow without bound. We have an older cluster where there are nearly 20,000 subjects, all alike.

```
❯ kubectl -n kube-system get rolebinding rke2-cloud-controller-manager-authentication-reader -o yaml | head -n 50
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rke2-cloud-controller-manager-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rke2-cloud-controller-manager
  namespace: kube-system
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rke2-cloud-controller-manager
  namespace: kube-system
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rke2-cloud-controller-manager
  namespace: kube-system
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: rke2-cloud-controller-manager
  namespace: kube-system
...
```
This just keeps going and going with the same subject over and over again.

We have other clusters that are younger; they have a smaller number of the subjects in that RoleBinding but there are still an unhealthy number.

The role it's referring to is
```
❯ kubectl --context c048 -n kube-system get role extension-apiserver-authentication-reader -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extension-apiserver-authentication-reader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
```

We think a a dup subject is added every time `rke2-server` is restarted.

**Steps To Reproduce:**

Just wait.  Restart rke2-server if you like.

**Expected behavior:**

Just one subject. ;-)

**Actual behavior:**

As above.
