### ISSUE TITLE
OpenStack Cloud Controller Manager - Helm addon completes, but ccm not deployed

### ISSUE THREAD

**Issue by PoulTur** [rancher/rke2#6384]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.11+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux samplecluster-master-001 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Linux samplecluster-worker-001 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 1 agent

**Describe the bug:**
I've installed the OpenStack Cloud Controller Manager as Helm add-on. The Helm chart pod completes and logs indicate as if the chart was installed. But the pod of OpenStack Cloud Controller Manager is not coming up. Below logs from the Helm chart pod:

```
$:~/rke2-terraform$ kubectl logs helm-install-openstack-cloud-controller-manager-2v8wx -n kube-system
if [[ ${KUBERNETES_SERVICE_HOST} =~ .*:.* ]]; then
        echo "KUBERNETES_SERVICE_HOST is using IPv6"
        CHART="${CHART//%\{KUBERNETES_API\}%/[${KUBERNETES_SERVICE_HOST}]:${KUBERNETES_SERVICE_PORT}}"
else
        CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
fi

set +v -x
+ [[ true != \t\r\u\e ]]
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ shopt -s nullglob
+ [[ -f /config/ca-file.pem ]]
+ [[ -f /tmp/ca-file.pem ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/openstack-cloud-controller-manager.tgz.base64
+ CHART_PATH=/tmp/openstack-cloud-controller-manager.tgz
+ [[ ! -f /chart/openstack-cloud-controller-manager.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ [[ openstack-cloud-controller-manager/openstack-cloud-controller-manager == stable/* ]]
+ [[ -n https://kubernetes.github.io/cloud-provider-openstack ]]
+ [[ -f /auth/username ]]
+ [[ -f /auth/tls.crt ]]
+ helm_v3 repo add openstack-cloud-controller-manager https://kubernetes.github.io/cloud-provider-openstack
"openstack-cloud-controller-manager" has been added to your repositories
+ helm_v3 repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "openstack-cloud-controller-manager" chart repository
Update Complete. ⎈Happy Helming!⎈
+ helm_update install --namespace kube-system --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^openstack-cloud-controller-manager$' --namespace kube-system --output json
++ jq -r '"\(.[0].chart),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace kube-system --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 openstack-cloud-controller-manager openstack-cloud-controller-manager/openstack-cloud-controller-manager --values /config/values-01_HelmChart.yaml
NAME: openstack-cloud-controller-manager
LAST DEPLOYED: Mon Jul 22 09:33:34 2024
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
+ exit
```
**Steps To Reproduce:**
- Installed RKE2 with TerraForm with following entries in the /etc/rancher/rke2/config.yaml:

```
    token: "${rke2_token}"
    write-kubeconfig-mode: "0640"
    tls-san: "${public_address}"
    disable-cloud-controller: True
```
- Added to `/var/lib/rancher/rke2/server/manifests/rke2-openstack-cloud-controller-manager.yaml`

```
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: openstack-cloud-controller-manager
      namespace: kube-system
    spec:
      chart: openstack-cloud-controller-manager
      repo: https://kubernetes.github.io/cloud-provider-openstack
      targetNamespace: kube-system
      bootstrap: True
      valuesContent: |-
        cloudConfig:
          global:
            auth-url: xxxx
            application-credential-id: xxxx
            application-credential-secret: xxxx
            region: xxxx
            tenant-id: xxxx
          loadBalancer:
            floating-network-id: xxxx
```

**Expected behavior:**
OpenStack Cloud Controller Manager pod is deployed, possible to create LoadBalancer using OpenStack CCM

**Actual behavior:**
OpenStack Cloud Controller Manager pod is not deployed, not possible to create LoadBalancer using OpenStack CCM

**Additional context / logs:**
