### ISSUE TITLE
RKE2 failed to run due to certificate issue

### ISSUE THREAD

**Issue by tomerleib** [rancher/rke2#646]
I've setup one instance and NLB in AWS.
The config.yaml is:
```yaml
token: secret
tls-san:
  - rke2-12345.elb.us-east-2.amazonaws.com
```
When I attempted to start rke2-server, the logs were flooded with TLS errors:
```bash
Dec 30 15:48:22 ip-10-2-69-130 rke2[8167]: time="2020-12-30T15:48:22Z" level=info msg="Cluster-Http-Server 2020/12/30 15:48:22 http: TLS handshake error from 10.2.67.120:10024: EOF"
```

I tried to reset it by uninstalling and providing the server dns address inside the tls-san section, but the above error is still flooding the logs and rke2-server service is not running.
