### ISSUE TITLE
rke2-ingress-nginx does not watch Ingress resources without IngressClassName set

### ISSUE THREAD

**Issue by hyeluoh** [rancher/rke2#6510]
**Environmental Info:**
RKE2 Version:  v1.30.3

rke2 version v1.30.3+rke2r1
go version go1.22.5 X:boringcrypto
Node(s) CPU architecture, OS, and Version: 

 arm64 centos 7.9
Cluster Configuration:

1 server 3 agents
**Describe the bug:**

After upgrading from RKE2 v1.29.7 to v1.30.3, services within the Kubernetes cluster that are accessed through Ingress are returning 404 errors.
**Steps To Reproduce:**

- update rke2
- When I entered the nginx-ingress-controller pod, I found that the domain configuration for the inaccessible service was missing.
- When I deleted and then reconfigured the Ingress settings for the corresponding domain, the service was restored.

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment]
Can you provide an example showing how exactly you'd configured the ingress settings? What specifically was missing?

**Comment by nugzarg** [comment]
The reason fro this issue is missing annotation ```ingressclass.kubernetes.io/is-default-class: "true"``` for nginx IngressClass.
I'm not sure, but it seems that nginx IngressClass was set automatically as default in previous version of nginx ingress. Which is not the case now. 
Simple workaround is t0 set this annotation manually, or change nginx-ingress helm chart configuration. Example:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
```
