### ISSUE TITLE
HelmChartConfig modifications not taking effect

### ISSUE THREAD

**Issue by brandtkeller** [rancher/rke2#663]
## Context
Attempting to deploy a new cluster w/ modifications to the nginx-ingress chart made through [HelmChartConfig resource](https://docs.rke2.io/helm/) 

## Process

- Create a new node
- Run the quickstart curl command as root
- There is no `/var/lib/rancher/rke2/server/manifests/` directory - create one `mkdir -p /var/lib/rancher/rke2/server/manfiests`
- Copy my HelmChartConfig into the `var/lib/rancher/rke2/server/manfiests`directory
- Enable and Start my rke2-server.service
- Check for the HelmChartConfig to be deployed - `kubectl get helmchartconfig -n kube-system
- Check for modifications to the rke2-ingress-nginx-controller - `kubectl get deployment rke2-ingress-nginx-controller -n kube-system -o yaml`

my HelmChartConfig - `nginx-ingress-config.yaml`
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller.nodeSelector:
      node-role.kubernetes.io./master: "true"
    controller.replicaCount: 3
```
## Expected Result

The `rke2-ingress-nginx-controller` deployment should be attempting to deploy 3 replicas and have the `nodeSelector` populated.

## Current Result
The values modifications annotated in the HelmChartConfig are not overriding the actual values that are deployed.

## Questions
The docs state:

> The HelmChartConfig resource must match the name and namespace of its corresponding HelmChart

I know the namespace is correct. The example in the docs makes me think the Helm Release name has to match. But I may be understanding this wrong? Can anyone set me straight if there is an obvious problem here?
Thanks

**Comment by brandtkeller** [comment]
Are any of the behaviors above incorrect? I can't find anything in the documents to indicate the HelmChartConfig is incorrect. It deploys to the cluster and I can see it with `kubectl get helmchartconfig -n kube-system` but it does not make modifications to the packaged helm chart as the docs indicated.

**Comment by brandond** [comment]
Your ValuesContent is incorrect. It's not like --set on the helm command, the format needs to match the structure in [values.yaml](https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/values.yaml):

```yaml
spec:
  valuesContent: |-
    controller:
      nodeSelector: node-role.kubernetes.io./master=true
      replicaCount: 3
```
