### ISSUE TITLE
rke2 redeployed rke2-ingress-nginx with default config

### ISSUE THREAD

**Issue by dehoej** [rancher/rke2#6668]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.28.11+rke2r1 (6b12d7a783238b72da8450fa1b6ec587cebb79ed)
go version go1.21.11 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Linux <hostname> 5.14.0-427.31.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 9 14:06:03 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 servers, 8 agents

**Describe the bug:**
I have a custom rke2-ingress-nginx-config.yaml that is very important for our setup. Eg. we set a specific log-format in json and set default ssl-certificate. This has been running fine for a long time, but yesterday suddenly rke-ingress-nginx was redeployed automatically with default settings. I had to make a change in rke2-ingress-nginx-config.yaml to make it redeploy with the right settings. 

**Expected behavior:**
rke2-ingress-nginx will use the provided config in /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
**Actual behavior:**
It was redeployed with a default config.

**Additional context / logs:**

`level=error msg="error syncing 'kube-system/rke2-ingress-nginx': handler helm-controller-chart-registration: DesiredSet - Replace Wait batch/v1, Kind=Job kube-system/helm-install-rke2-ingress-nginx for helm-controller-chart-registration kube-system/rke2-ingress-nginx, requeuing"`

**Comment by brandond** [comment]
> I have a custom rke2-ingress-nginx-config.yaml that is very important for our setup

What is in this file? It sounds like you're customizing the ingress-nginx configmap or deployment directly, instead of using a HelmChartConfig resource to customize the chart deployment. If you don't follow the documented process to modify the chart values, any resources managed by the chart will be reverted to the versions generated by the chart.

Ref: https://docs.rke2.io/helm#customizing-packaged-components-with-helmchartconfig

**Comment by dehoej** [comment]
No, I don't edit the config file directly. I edit /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml. I am following the procedure specified in the documentation exactly: [https://docs.rke2.io/networking/networking_services?_highlight=nginx&_highlight=ingres#nginx-ingress-controller](https://docs.rke2.io/networking/networking_services?_highlight=nginx&_highlight=ingres#nginx-ingress-controller)
By "custom," I just mean that I have edited the config, so it is not the default configuration, and I have followed the documentation.

Let me know if you need any further adjustments!

**Comment by brandond** [comment]
>  I edit /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

This isn't a file that RKE2 provides or will create by default. What is in that file? Do you perhaps have something else that is managing its contents?

**Comment by dehoej** [comment]
@brandond 
As stated, I’m simply following the documentation, which specifically mentions that you should use the file: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

![image](https://github.com/user-attachments/assets/c9bcc7f3-96b4-481c-96c8-c95bdfa7af6b)

**Comment by brandond** [comment]
That is an example. You've still not said what content is in that file. If that file contains a HelmChartConfig as shown in the docs example, the values provided via the config should still be honored by the ingress-nginx chart, even if it is redeployed. Please provide the requested information regarding what content you've placed in that file.

**Comment by dehoej** [comment]
It is a HelmChartConfig

Here is the content of the file

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
        enable-real-ip: "true"
        log-format-escape-json: "true"
        log-format-upstream: '{ "msec": "$msec", "connection": "$connection", "connection_requests": "$connection_requests", "pid": "$pid", "request_id": "$request_id", "request_length": "$request_length", "remote_addr": "$remote_addr", "remote_user": "$remote_user", "remote_port": "$remote_port", "time_local": "$time_local", "time_iso8601": "$time_iso8601",  "request": "$request", "request_uri": "$request_uri", "args": "$args", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "bytes_sent": "$bytes_sent", "http_referer": "$http_referer", "http_user_agent": "$http_user_agent", "http_x_forwarded_for": "$http_x_forwarded_for", "http_host": "$http_host", "server_name": "$server_name", "request_time": "$request_time", "upstream": "$upstream_addr", "upstream_connect_time": "$upstream_connect_time", "upstream_header_time": "$upstream_header_time", "upstream_response_time": "$upstream_response_time", "upstream_response_length": "$upstream_response_length", "upstream_cache_status": "$upstream_cache_status", "ssl_protocol": "$ssl_protocol", "ssl_cipher": "$ssl_cipher", "scheme": "$scheme", "request_method": "$request_method", "server_protocol": "$server_protocol", "pipe": "$pipe", "gzip_ratio": "$gzip_ratio", "http_cf_ray": "$http_cf_ray"}'
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      maxmindLicenseKey: "REDACTED"
      extraArgs:
        default-ssl-certificate: "default/dk-certificate-tls"
        maxmind-edition-ids: "GeoLite2-Country"
        tcp-services-configmap: "kube-system/tcp-services"
      admissionWebhooks:
        patch:
          networkPolicy:
            enabled: true
      containerPort:
        mysql-prod: 13306
        mysql-dev: 53306
      dnsConfig:
        options:
          - name: single-request-reopen
          - name: ndots
            value: "1"

```

And the file is managed as an addon and enabled according to `kubectl get addon -A`.
