### ISSUE TITLE
cilium 1.16 enable envoy by default

### ISSUE THREAD

**Issue by albundy83** [rancher/rke2#6682]
**Environmental Info:**
RKE2 Version: 
gbellongervais@localhost:~> kubectl version
Client Version: v1.28.13
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.13+rke2r1

Cluster Configuration:
3 control-planes
2 workers

**Describe the bug:**
If I don't specify to disable Envoy deployment, I have Envoy deployed as DaemonSet, which is the new correct behaviour according to cilium doc https://github.com/cilium/cilium/commit/471f19a16593e1e9342c31bf3e26e5383737cb0a

I need to specify:
```yaml
envoy:
  enabled: false
```
I don't know if it's really a bug or a new feature but maybe we could document this somewhere.

**Comment by albundy83** [comment]
Here my full config to deploy cilium with network policies enabled:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  bootstrap: true
  valuesContent: |
    cluster:
      name: my-lovely-kube
      id: 1
    kubeProxyReplacement: true
    k8sServiceHost: my-kubernetes-load-balancer-hostname.fr
    k8sServicePort: 6443
    envoy:
      enabled: false   # Now it's mandatory or you have new cilium-envoy DaemonSet
    cni:
      chainingMode: none
    bpf:
      masquerade: true
    MTU: 1500
    encryption:
      enabled: false
      type: wireguard
      nodeEncryption: false
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
        serviceMonitor:
          enabled: true
          relabelings:
            - sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: node
              replacement: ${1}
            - targetLabel: cluster
              replacement: my-lovely-kube
              action: replace
        dashboards:
          enabled: true
      relay:
        enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
            relabelings:
              - targetLabel: cluster
                replacement: my-lovely-kube
                action: replace
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          className: nginx
          hosts:
            - hubble.my-lovely-hostname.fr
          tls:
            - secretName: hubble.my-lovely-hostname.fr
              hosts:
                - hubble.my-lovely-hostname.fr
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        relabelings:
          - sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: node
            replacement: ${1}
          - targetLabel: cluster
            replacement: my-lovely-kube
            action: replace
    dashboards:
      enabled: true
    operator:
      enabled: true
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          relabelings:
            - targetLabel: cluster
              replacement: my-lovely-kube
              action: replace
      dashboards:
        enabled: true
    
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-to-hubble
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble
  ingress:
    - ports:
        - protocol: TCP
          port: hubble-metrics
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              app.kubernetes.io/name: prometheus
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-to-hubble-relay
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-relay
  ingress:
    - ports:
        - protocol: TCP
          port: prometheus
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              app.kubernetes.io/name: prometheus
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
  policyTypes:
    - Ingress
```
