### ISSUE TITLE
Dynamic rbd/ceph storage provisioning doesn't work

### ISSUE THREAD

**Issue by thehejik** [rancher/rke2#694]
While testing SUSE Enterprise Storage 7 / rook-ceph on RKE2 cluster we found that dynamic rbd provisioning is not working due missing `rbd` binary in image `docker.io/rancher/hardened-kubernetes:v1.19.7-rke2r1` used by rke2 for `kube-controller-manager` pod on server/master.

Basically we are trying to follow and prove this legacy CaaSP4.5 documentation https://documentation.suse.com/suse-caasp/4.5/html/caasp-admin/_integration.html#_using_rbd_in_storage_classes for later transition of SUSE CaaSP product users  to Rancher's RKE2.

**What kind of request is this (question/bug/enhancement/feature request):** bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
* prereq: working rook-ceph/SES7 cluster, rke2 cluster with 1 server and 1 agent deployed on SLES15SP2.
```yaml
$ echo "---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd-sc
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/rbd
parameters:
  monitors: 1.2.3.4:6789, 5.6.7.8:6789, 9.10.11.12:6789
  adminId: myPoolAdmin 
  adminSecretName: ceph-admin
  adminSecretNamespace: default
  pool: myPool 
  userId: myPoolUser 
  userSecretName: ceph-user
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rbd-sc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi" | kubectl apply -f -
```
**Result:**
```yaml
$ kubectl describe pvc ceph-rbd-sc
Name:          ceph-rbd-sc
Namespace:     default
StorageClass:  ceph-rbd-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  5s (x2 over 19s)  persistentvolume-controller  Failed to provision volume with StorageClass "ceph-rbd-sc": failed to create rbd image: executable file not found in $PATH, command output:
```

Static rbd provisioning using pv and pvc defined with existing RBD resources (pool, image) works normally with RKE2.

What are the options for RKE2? - can we have the `rbd` command (eg. `ceph-common` pkg in sles) in k8s image or somehow use out-of-tree CSI rbd driver?

Using RKE2 v1.19.7+rke2r1

**Comment by thehejik** [comment]
CC @kravciak @rancher-max

**Comment by dweomer** [comment]
Is the problem that `rbd` is not on the system or merely that the pv-controller doesn't have it in it's `$PATH` ?

**Comment by brandond** [comment]
To follow up on @dweomer's response - normally it is documented as a prerequisite that the host binaries be installed on the node ahead of time. Plugin-specific binaries such as the rbd command should not be built into the core images; things that need them should either include them in their images, or know how to mount them from the host.

**Comment by ron1** [comment]
Is there a reason why the StorageClass is not using standard rook-ceph provisioner rook-ceph.rbd.csi.ceph.com?

**Comment by thehejik** [comment]
@ron1 the reason is that I wanted to use in-tree ceph/rbd driver which works well with a static ceph resources - the one you mention stands for external out-of-tree driver if I'm not wrong.

@dweomer the binary is not present in the controller-manager container - but it is available on nodes/hosts

@brandond could you please say more about mounting them from host? Well rbd (from ceph-common) has tons of dependencies.

**Comment by xhejtman** [comment]
Hello, is there any solution how to use built-in ceph driver with rke2? it worked with rke1

**Comment by Martin-Weiss** [comment]
@xhejtman @thehejik  - as an alternative for the internal provisioner I have been using the ceph-csi driver (https://github.com/ceph/ceph-csi) with RKE2 without a problem. Could you give a bit more insights why you do not want or can not use that one? What exactly does not work with the CSI driver?

**Comment by xhejtman** [comment]
@Martin-Weiss thanks, that probably could be used. However, if kubernetes did not deprecate internal ceph provisioner, I would expect it working with rke2. I will give it a try with ceph-csi anyway.

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss thanks, that probably could be used. However, if kubernetes did not deprecate internal ceph provisioner, I would expect it working with rke2. I will give it a try with ceph-csi anyway.

I agree - from a complexity and usability point of view using the internal one would be the simpler way.. regarding lifecycle and future strategy for internal ceph I do not have information...

**Comment by thehejik** [comment]
@Martin-Weiss If I remember correctly the problem was with rbd driver only. Anyway it has been resolved and documented here https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/ceph/

**Comment by xhejtman** [comment]
as rke2 is focused on restricted PSP, does it work with ceph rbd image? As user does not possess root privileges, he cannot change access rights on ext4 formated rbd devices. If there is no workaround for this, ceph rbd is not much usable here. fsgroup could help, but only if one can set 0770 rights on root of the rbd image.

**Comment by Martin-Weiss** [comment]
> 
> 
> as rke2 is focused on restricted PSP, does it work with ceph rbd image? As user does not possess root privileges, he cannot change access rights on ext4 formated rbd devices. If there is no workaround for this, ceph rbd is not much usable here. fsgroup could help, but only if one can set 0770 rights on root of the rbd image.

In my case https://github.com/ceph/ceph-csi did work well with cis-1.5 profile.. and I have configure
```

  nodeplugin:
    podSecurityPolicy:
      enabled: true
  provisioner:
    podSecurityPolicy:
      enabled: true
```
