### ISSUE TITLE
[Release 1.31] Update Canal version to v3.28.2

### ISSUE THREAD

**Issue by rbrtbnfgl** [rancher/rke2#6967]
Backport for #6955

**Comment by aganesh-suse** [comment]
Branch: release-1.31
Commit: 

Cloud Setup: 
OS: Ubuntu 24.04
1 server node 

Flags: 
```
server_flags   = "profile: cis\nselinux: true"
```

```
kubectl get node -o yaml  --kubeconfig=/tmp/archrke2comps22_kubeconfig  | grep 'hardened-flannel' -A1

        - docker.io/rancher/hardened-flannel:v0.25.7-build20241007
        sizeBytes: 80844396
```
```
  kubectl get node -o yaml  --kubeconfig=/tmp/archrke2comps22_kubeconfig  | grep 'hardened-calico' -A1

        - docker.io/rancher/hardened-calico:v3.28.2-build20241003
        sizeBytes: 204269087

```

```
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pod/rke2-canal-cd42s -n kube-system -o yaml | grep -i image
IMAGE_VERSION:     
    image: rancher/hardened-calico:v3.28.2-build20241003
    imagePullPolicy: IfNotPresent
    image: rancher/hardened-flannel:v0.25.7-build20241007
    imagePullPolicy: IfNotPresent
```
