### ISSUE TITLE
Pod security admission username exemtion not working

### ISSUE THREAD

**Issue by Mapmo** [rancher/rke2#7060]
**Environmental Info:**
RKE2 Version: 
 v1.29.9+rke2r

Node(s) CPU architecture, OS, and Version: 
various CPUs, Ubuntu 22.04.2

Cluster Configuration:

3 servers, 5 agents

**Describe the bug:**

I am using pod security admission to restrict my pods to the baseline PodSecurity level for the entire cluster. Due to having some resources that require exemption, I tried using the username approach, but the controller fails to create new pods because that violates the PodSecurity baseline rule. When using namespace exemption the problem is gone.

**Steps To Reproduce:**

***On the cluster nodes***
- Create PodSecurity configuration file
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: DefaultPodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1alpha1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "v1.29"
    exemptions:
      usernames: ["nginx"]
      runtimeClassNames: []
      namespaces: []
```
- Add the configuration file in rke2 config file as pod-security-admission-config-file

***On the cluster***
- Create a serviceAccount called nginx
- Create a deployment that has serviceAccountName: nginx and has a hostPath volume (the hostPath violates baseline rules), e.g:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: host-volume
          mountPath: /test
      volumes:
      - name: host-volume
        hostPath:
          path: /home
```
**Expected behavior:**

The controller is successfully creating pod(s) for the deployment
**Actual behavior:**

The controller fails to create pods because it's forbidden due to violating the PodSecurity rule
**Additional context / logs:**
