### ISSUE TITLE
How to configure authenticated registry access to fetch RKE2 images "secure" from on-premise registry

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#710]
It seems we have just "anonymous" access as option for fetching images from the on-premise registry in the RKE2 deployment process.

Is there any way to give RKE2 credentials to fetch the images non-anonymous from an on-premise registry?

Background: for security and auditing reasons "anonymous" access is not allowed.

P.S. yes - I know about the tarball image solution - but that is not a nice way to distribute images to new and existing servers and image transport standard is to use a registry ;-).

**Comment by brandond** [comment]
cc @cjellick

**Comment by brandond** [comment]
In case it wasn't clear from the status updates, this is being actively worked on.

**Comment by Martin-Weiss** [comment]
> 
> 
> In case it wasn't clear from the status updates, this is being actively worked on.

Cool- that is great news!

Btw. I have seen this message during rke-server start:

`rancher-master-01 rke2[5844]: No matching credentials were found, falling back on anonymous`

so is this already implemented "somehow"?

**Comment by brandond** [comment]
Yes, right now it will read creds from root's docker credentials at /root/.docker/config.json, but only when pulling the runtime image. This will be unified to pull creds from registries.yaml.

**Comment by Martin-Weiss** [comment]
Ok - so as a temporary workaround I just need to create that config.json?
I do not have docker installed - but creating that file is not much of a challenge ;-)

**Comment by rancher-max** [comment]
#### Validated using v1.20.4-rc2+rke2r1

- There is now the ability to use mirrors to fetch images from secure registry. By default, this is at `/etc/rancher/rke2/registries.yaml`. See below example registries file with dummy data:
```yaml
---
mirrors:
  docker.io:
    endpoint:
      - "my.private.registry"
  k8s.gcr.io:
    endpoint:
      - "my.private.registry"
configs:
  "my.private.registry":
    auth:
      username: fakeuser
      password: fakepass
    tls:
      cert_file: /home/ubuntu/cert.pem
      key_file:  /home/ubuntu/key.pem
      ca_file: /home/ubuntu/ca.pem
```
- Can store this file anywhere, and pass location when starting rke2 such as: `rke2 server --private-registry=/this/is/my/test/folder/auth.yaml` 
- If desired, can use this in conjunction with tarball and/or `--system-default-registry` flag (for anonymous access to same or different registry).
