### ISSUE TITLE
Unable to edit calico-node daemonset 

### ISSUE THREAD

**Issue by Rocky-Li-Adam** [rancher/rke2#7149]
I tried to add the following configuration using "kubectl edit daemonset calico-node -n calico-system" but  it did not update.

```yaml
spec:
  ...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
    ...           
```

[https://www.cnblogs.com/ltaodream/p/15200259.html](https://www.cnblogs.com/ltaodream/p/15200259.html)
