### ISSUE TITLE
Cannot scrape ETCD metrics on client port with TLS: error 415 (gRPC content-type NOK)

### ISSUE THREAD

**Issue by penoux** [rancher/rke2#7170]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.29.9+rke2r1 (429b6bbac506250ccc93e3c17967849223529c50)
go version go1.22.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version:
Linux pen-mgt01-dev-control-plane-bl6rm 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 control plane nodes, 2 worker nodes

**Describe the bug:**
I cannot scrape ETCD metrics on client port 2379, despite having activated it in `config.yaml` with cluster API provider RKE2 (`serverConfig.etcd.exposeMetrics: true` in rke2controlplane manifest): 415 error into Prometheus. 
When trying to scrape directly with curl onto a control plane node, I get the same error.

**Steps To Reproduce:**
- Installed RKE2 with CAPI provider bootstrap for RKE2, which generates the following `config.yaml`:

```yaml
cluster-cidr: 172.16.0.0/18
cni:
- none
disable:
- rke2-ingress-nginx
disable-cloud-controller: true
disable-kube-proxy: true
etcd-arg:
- auto-compaction-mode=periodic
- auto-compaction-retention=12h
- quota-backend-bytes=4294967296
etcd-expose-metrics: true
kube-apiserver-arg:
- cloud-provider=external
- oidc-issuer-url=https://auth.pen-mgt01-dev.com.intraorange
- oidc-client-id=loginapp
- oidc-ca-file=/usr/local/share/ca-certificates/extra-ca-certs.crt
- oidc-username-claim=name
- oidc-groups-claim=groups
- oidc-username-prefix=-
- goaway-chance=0.001
kubelet-arg:
- anonymous-auth=false
- cloud-provider=external
- config=kubelet-configuration-file.yaml
node-label:
- sylva.org/label-scope=test
profile: cis-1.23
server: https://192.168.2.64:9345
service-cidr: 10.43.0.0/18
tls-san:
- pen-mgt01-dev.api.intraorange
- 10.238.80.204
token: 6022714c20937d9c8aca3c38b9f008ff
```

- Try to get metrics from ETCD endpoints 2379, with client certificate

```bash
curl -v --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert /var/lib/rancher/rke2/server/tls/etcd/client.crt --key /var/lib/rancher/rke2/server/tls/etcd/client.key https://127.0.0.1:2379/metrics
...

> GET /metrics HTTP/2
> Host: 127.0.0.1:2379
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 415
< content-type: application/grpc
< grpc-status: 3
< grpc-message: invalid gRPC request content-type ""
<
* Connection #0 to host 127.0.0.1 left intact
```

**Expected behavior:**
ETCD metrics should be returned

**Actual behavior:**
HTTP 415 error returned, stating that gRPC content-type is NOK. Is there an issue with internal ETCD gRPC gateway?

[EDIT]

When looking at generated ETCD config file, I can see that dedicated port 2382 has been declared (by CABPR provider? documented nowhere) for HTTP client traffic, thus disabling HTTP on standard port 2379

```
listen-client-http-urls: https://127.0.0.1:2382
listen-client-urls: https://127.0.0.1:2379,https://192.168.2.19:2379
listen-metrics-urls: http://127.0.0.1:2381,http://192.168.2.19:2381
```

Then if I "curl" on this port, it works.

```
curl -v --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert /var/lib/rancher/rke2/server/tls/etcd/client.crt --key /var/lib/rancher/rke2/server/tls/etcd/client.key https://127.0.0.1:2382/metrics
...
metrics returned OK
```

However it does not work for Prometheus, as only localhost is bound => override necessary in rke2 config.

To work properly without binding `0.0.0.0:2382` RKE2 should probably set localhost + nodeIP, 

In the example, what should be set:

```
listen-client-http-urls: https://127.0.0.1:2382,https://192.168.2.19:2382
```

instead of:
```
listen-client-http-urls: https://127.0.0.1:2382
```

**Comment by brandond** [comment]
Why are you trying to scrape from the client port in the first place, instead of using the dedicated metrics port?

**Comment by brandond** [comment]
The reason for disabling http on the client port is covered at https://github.com/k3s-io/k3s/pull/8402
Ref: 
* https://github.com/etcd-io/etcd/issues/15402
* https://github.com/kubernetes/kubernetes/pull/118460

**Comment by penoux** [comment]
`listen-metrics-urls` only expose on HTTP, no TLS (http://127.0.0.1:2381,http://192.168.2.19:2381). We cannot use it in our case. No need to use `etcd-expose-metrics` for it to work btw...

`etcd-expose-metrics: true` : Expose etcd metrics to client interface, as per [RKE2 doc](https://docs.rke2.io/reference/server_config#database), this can then be used to scrape using TLS and client certificate. Right, good.

Then, *RKE2 dedicated port 2382* for HTTP `listen-client-http-urls` effectively replaces HTTP listening on port 2379 by 2382 from [ETCD doc](https://etcd.io/docs/v3.5/op-guide/configuration/#profiling-and-monitoring). Right too, and working with localhost scraping.

Remaining issue is that the generated settings are `listen-client-http-urls: https://127.0.0.1:2382` (localhost only), where it should integrate also the node IP (`listen-client-http-urls: https://127.0.0.1:2382,https://192.168.2.19:2382`). Without that Prometheus cannot scrape in TLS.

Working configuration is to override `serverConfig` to bind all network interfaces...

```yaml
serverConfig:
  etcd:
    exposeMetrics: true
    customConfig:
      extraArgs:
        - listen-client-http-urls=https://0.0.0.0:2382 # override bind address for monitoring
 ```
