### ISSUE TITLE
Restarting rke2-server with a different audit policy does not send audit logs

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#718]
**Description:**
After updating the audit policy, restarting the rke2 server process, and performing requests on the cluster, I still do not any audit logs generated.
I'm not sure if this is expected behavior or not as I could not find upstream documentation about changing this.

**Steps:**
1. Create an rke2 server in cis mode
2. Update the data located in the audit policy file, located at: `/etc/rancher/rke2/audit-policy.yaml`, to log everything:
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: RequestResponse
```
3. Restart rke2-server process: `sudo systemctl restart rke2-server`
4. When the apiserver pod is running again, submit requests on the server. I applied the following yaml:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: othertest-deploy
  labels:
    app: othertest
spec:
  selector:
    matchLabels:
      app: othertest
  template:
    metadata:
      labels:
        app: othertest
    spec:
      containers:
      - name: othertest
        image: maxross/mytestcontainer:unprivileged
        imagePullPolicy: Always
```

Notice there is no log file created: `sudo ls /var/lib/rancher/rke2/server/logs/`
