### ISSUE TITLE
Audit log configuration can't be overridden by kube-apiserver-arg parameters

### ISSUE THREAD

**Issue by mddamato** [rancher/rke2#724]
It appears that the args are inserted twice, with the user provided args happening first, and getting overridden by the default values rendering it not possible to set.

Reproduction notes:

- Add audit log policy:
```
cat > /etc/rancher/rke2/audit-policy.yaml << EOF
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      # Resource "pods" doesn't match requests to any subresource of pods,
      # which is consistent with the RBAC policy.
      resources: ["pods"]
EOF
```

- Add RKE2 configuration:
```
cat > /etc/rancher/rke2/config.yaml <<EOF
selinux: true
profile: cis-1.5
kube-apiserver-arg: "audit-log-maxsize=200"
kube-apiserver-arg: "audit-log-maxage=60"
kube-apiserver-arg: "audit-log-maxbackup=20"
EOF
```

- Check apiserver args:
`
[root@rhel-8-0 admin]# /var/lib/rancher/rke2/bin/kubectl get po -n kube-system -l component=kube-apiserver -o=jsonpath="{.items[*].spec.containers[*].command}" | grep audit
`

- View results:
`
["kube-apiserver","--allow-privileged=true","--anonymous-auth=false","--api-audiences=unknown","--audit-log-maxage=60","--audit-log-maxbackup=20","--audit-log-maxsize=200","--authorization-mode=Node,RBAC","--bind-address=0.0.0.0","--cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs","--client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt","--enable-admission-plugins=NodeRestriction,PodSecurityPolicy","--encryption-provider-config=/var/lib/rancher/rke2/server/cred/encryption-config.json","--etcd-cafile=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt","--etcd-certfile=/var/lib/rancher/rke2/server/tls/etcd/client.crt","--etcd-keyfile=/var/lib/rancher/rke2/server/tls/etcd/client.key","--etcd-servers=https://127.0.0.1:2379","--insecure-port=0","--kubelet-certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt","--kubelet-client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt","--kubelet-client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key","--profiling=false","--proxy-client-cert-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt","--proxy-client-key-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.key","--requestheader-allowed-names=system:auth-proxy","--requestheader-client-ca-file=/var/lib/rancher/rke2/server/tls/request-header-ca.crt","--requestheader-extra-headers-prefix=X-Remote-Extra-","--requestheader-group-headers=X-Remote-Group","--requestheader-username-headers=X-Remote-User","--secure-port=6443","--service-account-issuer=rke2","--service-account-key-file=/var/lib/rancher/rke2/server/tls/service.key","--service-account-signing-key-file=/var/lib/rancher/rke2/server/tls/service.key","--service-cluster-ip-range=10.43.0.0/16","--storage-backend=etcd3","--tls-cert-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt","--tls-min-version=VersionTLS12","--tls-private-key-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.key","--audit-policy-file=/etc/rancher/rke2/audit-policy.yaml","--audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log","--audit-log-maxage=30","--audit-log-maxbackup=10","--audit-log-maxsize=100"]
`
