### ISSUE TITLE
[Release-1.31] - [Maintenance] vSphere CSI chart version bump

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#7245]
Backport fix for [Maintenance] vSphere CSI chart version bump

* #7137

**Comment by mdrahman-suse** [comment]
# Validated on release-1.31 with commit 5b9a8f82

```
rke2 version v1.31.2+dev.5b9a8f82 (5b9a8f82e455d9e2da999c8e3f6b93174812175a)
go version go1.22.8 X:boringcrypto

$ sudo cat /var/lib/rancher/rke2/data/v1.31.2-dev.5b9a8f82-b14249a4a1c2/charts/rancher-vsphere-cpi.yaml | grep rancher-vsphere-cpi
  name: "rancher-vsphere-cpi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.9.100.tgz"

$ sudo cat /var/lib/rancher/rke2/data/v1.31.2-dev.5b9a8f82-b14249a4a1c2/charts/rancher-vsphere-csi.yaml | grep rancher-vsphere-csi
  name: "rancher-vsphere-csi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-csi/rancher-vsphere-csi-3.3.1-rancher700.tgz"
```

**Comment by ShylajaDevadiga** [comment]
### Validated using v1.31.3-rc2+rke2r1
## Environment
- /etc/rancher/rke2/config.yaml
```
write-kubeconfig-mode: 644
cloud-provider-name: "rancher-vsphere"
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```
pod.yaml
```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim1"
```

## Testing
- Createa VM on vpshere
- Copy config.yaml and vsphere-values.yaml having vsphere configs
- Install rke2
- Verify the vsphere csi and cpi pods are up and running
- Deploy pvc.yaml and pod.yaml
- Verify the pv is created and pvc is bound to the pv
- Verify container volumes in the respective datastore on vsphere is present

```
ubuntu@sdevadiga-csi-test:~$ rke2 -v
rke2 version v1.31.3-rc2+rke2r1 (8d5473d0aa63a3f29706d3f604fe3739d8222fd6)
go version go1.22.8 X:boringcrypto
ubuntu@sdevadiga-csi-test:~$ kubectl get pods -A|grep vsphere
kube-system   helm-install-rancher-vsphere-cpi-hcw9q                 0/1     Completed           0          24m
kube-system   helm-install-rancher-vsphere-csi-j8gc4                 0/1     Completed           1          60s
kube-system   rancher-vsphere-cpi-cloud-controller-manager-s6qp4     1/1     Running             0          24m
kube-system   vsphere-csi-controller-bcf4495bc-fvmkj                 5/5     Running             0          55s
kube-system   vsphere-csi-controller-bcf4495bc-h72s8                 5/5     Running             0          55s
kube-system   vsphere-csi-controller-bcf4495bc-zhdzv                 5/5     Running             0          55s
kube-system   vsphere-csi-node-2ldq5                                 3/3     Running             0          55s
```
```
ubuntu@sdevadiga-csi-test:~$ kubectl get pvc,pv
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/claim1   Bound    pvc-3c0b5d68-af48-41f9-b963-c541fa6a1e92   1Gi        RWO            vsphere-csi-sc   <unset>                 21m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM            STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-3c0b5d68-af48-41f9-b963-c541fa6a1e92   1Gi        RWO            Delete           Bound    default/claim1   vsphere-csi-sc   <unset>                          55s

```
