### ISSUE TITLE
[Release-1.30] - [Maintenance] vSphere CSI chart version bump

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#7246]
Backport fix for [Maintenance] vSphere CSI chart version bump

* #7137

**Comment by mdrahman-suse** [comment]
# Validated on release-1.30 with commit 8353a650

```
$ rke2 -v
rke2 version v1.30.6+dev.8353a650 (8353a650a984d57ddb197cf49411326d526cf196)
go version go1.22.8 X:boringcrypto

$ sudo cat /var/lib/rancher/rke2/data/v1.30.6-dev.8353a650-70dde56051d3/charts/rancher-vsphere-csi.yaml | grep rancher-vsphere-csi
  name: "rancher-vsphere-csi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-csi/rancher-vsphere-csi-3.3.1-rancher700.tgz"

$ sudo cat /var/lib/rancher/rke2/data/v1.30.6-dev.8353a650-70dde56051d3/charts/rancher-vsphere-cpi.yaml | grep rancher-vsphere-cpi
  name: "rancher-vsphere-cpi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.9.100.tgz"
```

**Comment by ShylajaDevadiga** [comment]
### Validated using v1.30.7-rc2+rke2r1 
## Environment
- /etc/rancher/rke2/config.yaml
```
write-kubeconfig-mode: 644
cloud-provider-name: "rancher-vsphere"
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```
pod.yaml
```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim1"
```

## Testing
- Createa VM on vpshere
- Copy config.yaml and vsphere-values.yaml having vsphere configs
- Install rke2
- Verify the vsphere csi and cpi pods are up and running
- Deploy pvc.yaml and pod.yaml
- Verify the pv is created and pvc is bound to the pv
- Verify container volumes in the respective datastore on vsphere is present

```
ubuntu@sdevadiga-csi-test:~$ rke2 -v
rke2 version v1.30.7-rc2+rke2r1 (cfa8d095c7ee315ece702adbc56ef096f5066914)
go version go1.22.8 X:boringcrypto
ubuntu@sdevadiga-csi-test:~$ kubectl get pods -A|grep vsphere
kube-system   helm-install-rancher-vsphere-cpi-jdcxd                 0/1     Completed   0             4h54m
kube-system   helm-install-rancher-vsphere-csi-xb5jn                 0/1     Completed   0             22m
kube-system   rancher-vsphere-cpi-cloud-controller-manager-j6ns7     1/1     Running     1 (30m ago)   4h54m
kube-system   vsphere-csi-controller-758876d99b-5ghzh                5/5     Running     7 (29m ago)   4h54m
kube-system   vsphere-csi-controller-758876d99b-h5hnn                5/5     Running     5 (30m ago)   4h54m
kube-system   vsphere-csi-controller-758876d99b-wdqqf                5/5     Running     5 (30m ago)   4h54m
kube-system   vsphere-csi-node-6mwb6                                 3/3     Running     5 (30m ago)   4h54m
ubuntu@sdevadiga-csi-test:~$ kubectl get pod,pvc,pv
NAME        READY   STATUS    RESTARTS   AGE
pod/basic   1/1     Running   0          21m

NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/claim1   Bound    pvc-dbe3c859-2192-44a7-ae3f-377c8b6fdd8b   1Gi        RWO            vsphere-csi-sc   <unset>                 21m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM            STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-97e7a0b3-1f84-4fe3-88d9-834e5ca969a5   1Gi        RWO            Delete           Released   default/claim1   vsphere-csi-sc   <unset>                          4h53m
persistentvolume/pvc-dbe3c859-2192-44a7-ae3f-377c8b6fdd8b   1Gi        RWO            Delete           Bound      default/claim1   vsphere-csi-sc   <unset>                          21m
ubuntu@sdevadiga-csi-test:~$ 
```
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/196b7b94-c25b-42d4-8193-8373dbf3d166">
