### ISSUE TITLE
[Release-1.29] - [Maintenance] vSphere CSI chart version bump

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#7247]
Backport fix for [Maintenance] vSphere CSI chart version bump

* #7137

**Comment by mdrahman-suse** [comment]
# Validated on release-1.29 with commit

```
$ rke2 -v
rke2 version v1.29.10+dev.65d1e3a4 (65d1e3a4050fe5ee1bb451990d6ed2d6ec105ca0)
go version go1.22.8 X:boringcrypto

$ sudo cat /var/lib/rancher/rke2/data/v1.29.10-dev.65d1e3a4-268f6aabce4f/charts/rancher-vsphere-csi.yaml | grep rancher-vsphere-csi
  name: "rancher-vsphere-csi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-csi/rancher-vsphere-csi-3.3.1-rancher700.tgz"

$ sudo cat /var/lib/rancher/rke2/data/v1.29.10-dev.65d1e3a4-268f6aabce4f/charts/rancher-vsphere-cpi.yaml | grep rancher-vsphere-cpi
  name: "rancher-vsphere-cpi"
    helm.cattle.io/chart-url: "https://rke2-charts.rancher.io/assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.9.100.tgz"
```

**Comment by ShylajaDevadiga** [comment]
### Validated using v1.29.11-rc1+rke2r1
## Environment
- /etc/rancher/rke2/config.yaml
```
write-kubeconfig-mode: 644
cloud-provider-name: "rancher-vsphere"
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-csi-sc
  resources:
    requests:
      storage: 1Gi
```
pod.yaml
```
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "basic"
  labels:
    name: "basic"
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: "basic"
      image: ranchertest/mytestcontainer:unprivileged
      ports:
        - containerPort: 8080
          name: "basic"
      volumeMounts:
        - mountPath: "/data"
          name: "pvol"
  volumes:
    - name: "pvol"
      persistentVolumeClaim:
        claimName: "claim1"
```

## Testing
- Createa VM on vpshere
- Copy config.yaml and vsphere-values.yaml having vsphere configs
- Install rke2
- Verify the vsphere csi and cpi pods are up and running
- Deploy pvc.yaml and pod.yaml
- Verify the pv is created and pvc is bound to the pv
- Verify container volumes in the respective datastore on vsphere is present

```
ubuntu@sdevadiga-csi-test:~$ rke2 -v
rke2 version v1.29.11-rc1+rke2r1 (819792e5ebd31e1d0a275adea8eac712ff0a11bb)
go version go1.22.8 X:boringcrypto
ubuntu@sdevadiga-csi-test:~$ kubectl get pods -A|grep vsphere
kube-system   helm-install-rancher-vsphere-cpi-k6v24                  0/1     Completed   0             115s
kube-system   helm-install-rancher-vsphere-csi-v668l                  0/1     Completed   0             115s
kube-system   rancher-vsphere-cpi-cloud-controller-manager-fn8sq      1/1     Running     0             110s
kube-system   vsphere-csi-controller-6dddf8f775-6qglr                 5/5     Running     1 (81s ago)   109s
kube-system   vsphere-csi-controller-6dddf8f775-8w5ds                 5/5     Running     0             109s
kube-system   vsphere-csi-controller-6dddf8f775-mg9ph                 5/5     Running     0             109s
kube-system   vsphere-csi-node-jf2wk                                  3/3     Running     2 (82s ago)   96s
ubuntu@sdevadiga-csi-test:~$ kubectl get pods,pvc,pv
NAME        READY   STATUS    RESTARTS   AGE
pod/basic   1/1     Running   0          29s

NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/claim1   Bound    pvc-f0b13259-3464-47e7-8092-0655412deb76   1Gi        RWO            vsphere-csi-sc   <unset>                 29s

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM            STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-f0b13259-3464-47e7-8092-0655412deb76   1Gi        RWO            Delete           Bound    default/claim1   vsphere-csi-sc   <unset>                          29s
ubuntu@sdevadiga-csi-test:~$ 
```
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/9a6fcdf8-ae00-421a-9501-e3c84fd6a195">
