### ISSUE TITLE
traefik service dont get assigned external ip by default 

### ISSUE THREAD

**Issue by vrbgtrhr** [rancher/rke2#7305]
the traefik  crd and daemonset are created without problem but no external ip is created as in k3s ( i'm imagining it should be the same )

config.yaml
```
ingress-controller: traefik
disable:
  - rke2-ingress-nginx
```

the service/rke2-traefik created:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: rke2-traefik
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: rke2-traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rke2-traefik
    helm.sh/chart: rke2-traefik-27.0.200
  name: rke2-traefik
  namespace: kube-system
spec:
  clusterIP: 10.43.195.200
  clusterIPs:
  - 10.43.195.200
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: rke2-traefik-kube-system
    app.kubernetes.io/name: rke2-traefik
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by brandond** [comment]
No. Traefik and nginx are both deployed as daemonsets on RKE2.

**Comment by vrbgtrhr** [comment]
i understand that, but how can i expose the traefik port outside the cluster since is not working like this?

**Comment by brandond** [comment]
Use ports 80 and 443 on the hosts, same as you would with traefik+servicelb on k3s:

https://docs.rke2.io/networking/networking_services#nginx-ingress-controller
> nginx-ingress is deployed by default when starting the server. Ports 80 and 443 will be bound by the ingress controller in its default configuration, making these unusable for HostPort or NodePort services in the cluster.

**Comment by vrbgtrhr** [comment]
i still dont understand well, if i change the service/rke2-traefik to type: LoadBalancer another d

it still not working. my full configuration:

config.yaml
```
ingress-controller: traefik
enable-servicelb: true
node-label:
  - "svccontroller.rke2.cattle.io/enablelb=true"
disable:
  - rke2-ingress-nginx
```

**Comment by brandond** [comment]
Yes, because - as I quoted above - the daemonset is already occupying ports 80 and 443. If you want to use ServiceLB on the host ports, instead of the daemonset, you should change the daemonset to a depolyment, and disable the hostPorts.

**Comment by vaskokj** [comment]
@brandond new user here trying to wrap my mind around this as I was kind of expecting to see `rke2-ingress-nginx-controller` have a service deployed and an external-ip. Seeing this post indicates that it isn't the case. 

I have basically a stock RKE2 install. The only configuration changes was 

```
$ cat /etc/rancher/rke2/config.yaml
enable-servicelb: true
```
If I am understanding you correctly, I should just use the IP of the hosts? Maybe my lack of understanding of k8s, but I'm trying to understand how this would work for a HA setup. If several servers are running the  `rke2-ingress-nginx-controller` is the idea to just to use the VIP/Round-robin DNS/external Load balancer (e.g. HAProxy as example) to point to all of the `rke2-ingress-nginx-controller` nodes? My understanding was that `rke2-ingress-nginx-controller` (could) run on any node (agent or master node) that wasn't marked `--node-taint CriticalAddonsOnly=true:NoExecute`. I'm really unclear on how this would work if that is the case. What is the intended way for this to function?

**Comment by brandond** [comment]
> If several servers are running the rke2-ingress-nginx-controller is the idea to just to use the VIP/Round-robin DNS/external Load balancer (e.g. HAProxy as example) to point to all of the rke2-ingress-nginx-controller nodes.

Yes. Either you deploy a LoadBalancer controller and modify the ingress chart to use a Deployment+LoadBalancer service, or you use the default DaemonSet and point some external LB directly at your nodes.

> My understanding was that rke2-ingress-nginx-controller (could) run on any node (agent or master node) that wasn't marked --node-taint CriticalAddonsOnly=true:NoExecute

Yes, it does.

> What is the intended way for this to function?

RKE2 does not have a LB controller, and many users deploy RKE2 to environments that do not have a LB integration available, so they just deploy RKE2 and point some external LB or DNS alias at the cluster members. If you do have an external LB service available, and deploy a LB controller to integrate with it, then you can do as I described above and reconfigure the ingress to take advantage of it.

**Comment by vaskokj** [comment]
> > If several servers are running the rke2-ingress-nginx-controller is the idea to just to use the VIP/Round-robin DNS/external Load balancer (e.g. HAProxy as example) to point to all of the rke2-ingress-nginx-controller nodes.
> 
> Yes. Either you deploy a LoadBalancer controller and modify the ingress chart to use a Deployment+LoadBalancer service, or you use the default DaemonSet and point some external LB directly at your nodes.

Maybe it is because I'm not super familiar with k8s, but reading docs about LoadBalancers there seems to be some nuance to the term where docs are referring to different types of tools that are used in different ways but both called "Load Balancers" or "LoadBalancers"? It kind of seems implied here in the "Tip" on the K3s side. https://docs.k3s.io/datastore/cluster-loadbalancer?_highlight=haproxy&ext-load-balancer=HAProxy#setup-load-balancer. 

So implementation wise, sounds like I need to deploy something like MetalLB and then change the ingress-nginx-controller chart to be a Deployment and change it to type "LoadBlancer"? 

I tried the following configuration, it didn't seem to change anything. 

```
# /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      service:
        type: LoadBalancer
```

`kubectl apply -f /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml`



> > My understanding was that rke2-ingress-nginx-controller (could) run on any node (agent or master node) that wasn't marked --node-taint CriticalAddonsOnly=true:NoExecute
> 
> Yes, it does.
> 
> > What is the intended way for this to function?
> 
> RKE2 does not have a LB controller, and many users deploy RKE2 to environments that do not have a LB integration available, so they just deploy RKE2 and point some external LB or DNS alias at the cluster members. If you do have an external LB service available, and deploy a LB controller to integrate with it, then you can do as I described above and reconfigure the ingress to take advantage of it.

I think it is starting to make more sense now to me. I was just confused with the different "solutions" and how they operate like the need for HAProxy, ServiceLB, MetalLB, Kube-VIP, Traefik, PureLB etc. ServiceLB being a "LoadBalancer" that uses NodePorts, but, to do HA, more "Load Balancing" is discussed while using HAProxy, while the other "LoadBalancers" like MetalLB that provide more of a cloud like solution, all run together and as a newcomer is quite confusing on how they are utilized.
