### ISSUE TITLE
Include `tzdb` package in RKE2 core images

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#7331]
**Is your feature request related to a problem? Please describe.**

Currently, users who want to use zone names in the TZ env var have to mount `/usr/share/zoneinfo` into the Kubernetes pods. We should include tzdb in the images so that this is not necessary.

Ref: https://github.com/rancher/rke2/issues/2192

**Describe the solution you'd like**

tzdb files are available to Kubernetes pods

**Describe alternatives you've considered**

* Mount /usr/share/zoneinfo into all the static pods whenever setting TZ
  ```yaml
  kube-apiserver-extra-mount:
    - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro:Directory"
  kube-apiserver-extra-env:
    - "TZ=Europe/Madrid"
  ```
* Have RKE2 just always mount /usr/share/zoneinfo into the static pods

**Additional context**

* https://github.com/rancher/rke2/issues/2192
