### ISSUE TITLE
v1.30.6+rke2r1 duplicate hostname after re-install of rke2

### ISSUE THREAD

**Issue by mmolisch** [rancher/rke2#7372]
**Environmental Info:**
RKE2 Version: `v1.30.6+rke2r1`

Node(s) CPU architecture, OS, and Version:  `Linux bob 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration: `3 master nodes (servers) in HA, 5 working nodes (agents), 3 not working (agents)`

**Describe the bug:**
I removed node `bob` from rke2 cluster using `kubectl delete node bob`, then ran `sudo rke2-uninstall.sh`, removed `bob.node-password.rke2` secret from `kube-system` ns, but everytime I try to re-register it back, I always get this error. `kubectl get-all | grep -i bob` doesn't return anything. I als tried to try [this guide](https://blog.codybunch.com/2020/10/13/Kubernetes-Fix-Node-Password-Rejected/), but `/var/lib/rancher/rke2/server/cred/node-passwd` file is not present in `cred` folder on any of the master nodes.

**Steps To Reproduce:**

- /etc/rancher/rke2/config.yaml: 
```
      server: https://{{ kube_vip_ip }}:9345
      token: super-secret
      data-dir: /var/lib/rancher/rke2
      snapshotter: overlayfs
      kubelet-arg:
      - feature-gates=SizeMemoryBackedVolumes=true
      # inspired by:
      # https://cloud.google.com/kubernetes-engine/docs/concepts/plan-node-sizes#memory_and_cpu_reservations
      # https://learnk8s.io/allocatable-resources
      # https://mihai-albert.com/2022/02/13/out-of-memory-oom-in-kubernetes-part-4-pod-evictions-oom-scenarios-and-flows-leading-to-them/#oom-scenario-3-node-available-memory-drops-below-the-eviction-hard-flag-value
      - kube-reserved=cpu=0.7,memory=1Gi,ephemeral-storage=25Gi
      - eviction-hard=memory.available<2.5Gi
      # kernel-memcg-notification doesnt seem to be doing anything on cgroupsv2
      - kernel-memcg-notification=true
      # housekeeping interval is currently not doing anything, PR is opened https://github.com/kubernetes/kubernetes/pull/126052
      - housekeeping-interval=1s
```
```
curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION="{{ rke2_version }}" sh -
systemctl enable --now rke2-agent.service
cp /var/lib/rancher/rke2/agent/etc/containerd/config.toml /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
kubectl delete node bob
rke2-uninstall.sh
kubectl delete secret bob.node-password.rke2 -n kube-system
# repeat from step 1
```
- in logs:
```
Nov 29 09:59:37 bob rke2[2362181]: time="2024-11-29T09:59:37Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: /var/lib/rancher/rke2/agent/serving-kubelet.crt: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"
```

**Expected behavior:**

Node registers with new password and the same hostname as before.

**Actual behavior:**

Node is not registered, because of duplicate hostname.

**Additional context / logs:**
