### ISSUE TITLE
kube-controller-manager pod fails to be created with kube-controller-manager-extra-mount flag

### ISSUE THREAD

**Issue by skanakal** [rancher/rke2#7422]
**Environmental Info:**
RKE2 Version: v1.31.3+rke2r1

Node(s) CPU architecture, OS, and Version: x86_64, Ubuntu, 22.04

Cluster Configuration:

**Describe the bug:**

`kube-controller-manager` pod fails to be created with kube-controller-manager-extra-mount flag

**Steps To Reproduce:**

- Installed RKE2: 
~~~
#/etc/rancher/rke2/config.yaml
      kube-controller-manager-extra-mount:
        - /tmp/example.txt:/tmp/example.txt
        - /var/lib/rancher/rke2/server/logs/:/var/lib/rancher/rke2/server/logs
~~~

**Expected behavior:**

```
  - hostPath:
      path: /tmp/example.txt
      type: File
    name: extra-mount-0
  - hostPath:
      path: /var/lib/rancher/rke2/server/logs/
      type: DirectoryOrCreate
    name: extra-mount-1
```

**Actual behavior:**

~~~
tail -f /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml 
    name: file9
  - hostPath:
      path: /tmp/example.txt
      type: File
    name: extra-mount-0
  - hostPath:
      path: /var/lib/rancher/rke2/server/logs/
      type: File
    name: extra-mount-1
~~~

**Additional context / logs:**

https://jira.suse.com/browse/SURE-9493
