### ISSUE TITLE
Metrics API is not available when metrics server is not running on local API server when running with profile: cis-1.5

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#745]
When deploying rke2 with agents (had three masters and three workers) and having the metric server running on the workers the command "kubectl top nodes" / "kubectl top pods" does not work.

`Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)`

Root cause seems to be that the API server is running with host network and due to that the default-network-policy does not help much..

My "workaround" was to create an additional network policy:

default-network-metrics-policy.yaml:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-metrics-policy
  namespace: kube-system
spec:
  ingress:
  - from:
    - podSelector: {}
  - ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: rke2-metrics-server
  policyTypes:
  - Ingress
```

--> could we get this or a similar network policy auto-created in case we specify the profile cis-1.5?

**Comment by Oats87** [comment]
In a multi-node control plane cluster, when the metrics server is not on the local node, the api server is unable to communicate with the metrics server and thus will lead to API failures. This has a cascading effect such as not being able to `kubectl top` or `kubectl get pod -A` in a reasonable amount of time on various control plane hosts.

**Comment by briandowns** [comment]
@Oats87  and I spent some time pairing on this to figure out what's going on. It appears as though traffic is unable to be passed from host network to the pod network destined for pods on remote nodes. This is a side-effect of:  https://kubernetes.io/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet 

Traffic originating from the host network needs to traverse the flannel interface which results in that traffic being blocked as opposed to traffic originating from the
10.42.0.X/24 subnet.

To resolve this issue, we need to adjust the default NetworkPolicy to get all of the node IP's in the cluster and update the NetworkPolicy with an ingress rule that has
the IP of the flannel interface, e.g. 10.42.0.0, etc.

**Comment by brandond** [comment]
Rather than adding a new controller to keep the policies in sync with the node list, could we just open up access to the metrics server pod? Are there negative security implications to allowing access to the metric server?

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-metrics-server-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      app: rke2-metrics-server
  policyTypes:
  - Ingress
```
