### ISSUE TITLE
rke2 ingress upgrade fails 1.31.4 -> 1.31.5

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#7652]
**Environmental Info:**
RKE2 Version: v1.31.5+rke2r1

Node(s) CPU architecture, OS, and Version:  Linux kub-h1.priv.cerit-sc.cz 6.8.0-50-generic #51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 17:58:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 6 servers

**Describe the bug:**
helm pod with ingress upgrade gets error:
```
+ helm upgrade --set-string 'global.clusterCIDR=10.42.0.0/16\,xxx:8:2::/96' --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterCIDRv6=xxx:8:2::/96 --set-string 'global.clusterDNS=10.43.0.10\,xxx:8:3:0:a' --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string 'global.serviceCIDR=10.43.0.0/16\,xxx:8:3::/112' --set-string global.systemDefaultIngressClass=ingress-nginx rke2-ingress-nginx /tmp/rke2-ingress-nginx.tgz --values /config/values-10_HelmChartConfig.yaml
Error: UPGRADE FAILED: template: rke2-ingress-nginx/templates/_helpers.tpl:266:14: executing "system_default_registry" at <.Values.global.systemDefaultRegistry>: nil pointer evaluating interface {}.global
```

if `defaultBackend` is enabled via values:
```
defaultBackend:
  enabled: true
```

**Steps To Reproduce:**

download the chart: rke2-ingress-nginx-4.12.003.tgz. untar, change `defaultBackend` to `true` in budled values, and run `helm template test . -f values.yaml`.

**Expected behavior:**

upgrade ingress controller

**Actual behavior:**

error

**Comment by brandond** [comment]
Please show the value of your HelmChartConfig valuesContent. It looks like something in there is clobbering the top-level `globals` key. Here's what it should look like:
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-ingress-nginx/rke2-ingress-nginx/4.12.003/values.yaml#L5-L10
```yaml
global:
  image:
    # -- Registry host to pull images from.
    registry: registry.k8s.io
  systemDefaultRegistry: ""
  systemDefaultIngressClass: ""
```

**Comment by xhejtman** [comment]
it seems that `.Values` is nil, not `.Values.global`.

however, it happens also if I use also only bundled values and enable defaultBackend:
```
wget https://rke2-charts.rancher.io/assets/rke2-ingress-nginx/rke2-ingress-nginx-4.12.003.tgz
tar xf rke2-ingress-nginx-4.12.003.tgz
cd rke2-ingress-nginx
helm template test . -f values.yaml --set defaultBackend.enabled=true
Error: template: rke2-ingress-nginx/templates/_helpers.tpl:266:14: executing "system_default_registry" at <.Values.global.systemDefaultRegistry>: nil pointer evaluating interface {}.global

Use --debug flag to render out invalid YAML
```

these are my values (public address and dns name hidden)
```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: Deployment
      extraArgs:
        enable-annotation-validation: true
      hostNetwork: false
      hostPort:
        enabled: false
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
      resources:
        requests:
          cpu: 2
          memory: 2200Mi
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: xxx
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Local
        annotations:
          loadbalancer.openstack.org/timeout-client-data: '1200001'
          loadbalancer.openstack.org/timeout-member-data: '1200001'
      metrics:
        port: 10254
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      watchIngressWithoutClass: true
      ingressClassResource:
          default: true
      config:
          proxy-read-timeout: "1200"
          upstream-keepalive-timeout: "1200"
          custom-http-errors: "500,503"
          limit-req-status-code: "429"
          limit-conn-status-code: "429"
          worker-shutdown-timeout: "7200s"
      extraArgs:
        publish-status-address: xxx
    defaultBackend:
      enabled: true
      autoscaling:
        enabled: false
      image:
        repository: cerit.io/cerit/default-backend
        tag: "v1.1"
        readOnlyRootFilesystem: false
```

**Comment by brandond** [comment]
Ah. I suspect that the template scope for the defaultBackend image helper is broken - cc @dereknola 

In the mean time you might try this:
```yaml
    defaultBackend:
      enabled: true
      autoscaling:
        enabled: false
      image:
        repository: cerit.io/cerit/default-backend
        tag: "v1.1"
        readOnlyRootFilesystem: false
      global:
        systemDefaultRegistry: ""
```

**Comment by xhejtman** [comment]
> We should probably have a test that covers the defaultBackend, I don't think it sees MUCH use since generally all it did for most folks was send a static 404 page.

our use case is that it sends better page than just pure 404 and it handles also 500 and 503 error pages explaining what happened and how it can be fixed.

> In the mean time you might try this:
> 
>     defaultBackend:
>       enabled: true
>       autoscaling:
>         enabled: false
>       image:
>         repository: cerit.io/cerit/default-backend
>         tag: "v1.1"
>         readOnlyRootFilesystem: false
>       global:
>         systemDefaultRegistry: ""

did not help. It seems, that for some reason, `.Values` is `nil`, so it actually does not help to define `global`.

even such fix in `_helpers.tpl`: `{{- if and .Values.global .Values.global.systemDefaultRegistry -}}` do not help

**Comment by brandond** [comment]
Yeah, the root scope (`.`) is replaced by a merge of `.Values.defaultBackend.image .Values.global.image`:
```
          {{- with (merge .Values.defaultBackend.image .Values.global.image) }}
          image: "{{ template "system_default_registry" . }}{{ template "repository_or_registry_and_image" .Values.defaultBackend.image }}"
          {{- end }}
```

This should do it until we can fix the chart in the February release:
```yaml
    defaultBackend:
      enabled: true
      autoscaling:
        enabled: false
      image:
        repository: cerit.io/cerit/default-backend
        tag: "v1.1"
        readOnlyRootFilesystem: false
        Values:
          global:
            systemDefaultRegistry: ""
          defaultBackend:
            image:
              repository: cerit.io/cerit/default-backend
              tag: "v1.1"
```

**Comment by xhejtman** [comment]
> Yeah, the root scope (`.`) is replaced by a merge of `.Values.defaultBackend.image .Values.global.image`:
> 
> ```
>           {{- with (merge .Values.defaultBackend.image .Values.global.image) }}
>           image: "{{ template "system_default_registry" . }}{{ template "repository_or_registry_and_image" .Values.defaultBackend.image }}"
>           {{- end }}
> ```
> 
> This should do it until we can fix the chart in the February release:
> 
>     defaultBackend:
>       enabled: true
>       autoscaling:
>         enabled: false
>       image:
>         repository: cerit.io/cerit/default-backend
>         tag: "v1.1"
>         readOnlyRootFilesystem: false
>         Values:
>           global:
>             systemDefaultRegistry: ""
>           defaultBackend:
>             image:
>               repository: cerit.io/cerit/default-backend
>               tag: "v1.1"

yes, this workaround does work.

**Comment by VestigeJ** [comment]
I do not see this issue replicating the way it should be currently on v1.31.4+rke2r1


$ sudo INSTALL_RKE2_VERSION=v1.31.4+rke2r1 INSTALL_RKE2_EXEC=server ./install-rke2.sh
```
[INFO]  using v1.31.4+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.31.4+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.31.4+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
```

$ go_rke2
```
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/local/lib/systemd/system/rke2-server.service.
```

$ kgn
```
NAME              STATUS     ROLES                       AGE   VERSION
ip                NotReady   control-plane,etcd,master   9s    v1.31.4+rke2r1
```

$ sudo vim /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml
$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running     0          3m5s
kube-system   etcd-ip                                                 1/1     Running     0          2m42s
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed   0          2m58s
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed   0          2m58s
kube-system   helm-install-rke2-ingress-nginx-gvpwx                   0/1     Completed   0          2m58s
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed   0          2m58s
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed   0          2m58s
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed   1          2m58s
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed   0          2m58s
kube-system   kube-apiserver-ip                                       1/1     Running     0          3m2s
kube-system   kube-controller-manager-ip                              1/1     Running     0          3m5s
kube-system   kube-proxy-ip                                           1/1     Running     0          3m1s
kube-system   kube-scheduler-ip                                       1/1     Running     0          3m5s
kube-system   rke2-canal-842vm                                        2/2     Running     0          2m49s
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running     0          2m50s
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running     0          2m50s
kube-system   rke2-ingress-nginx-controller-cxjqn                     1/1     Running     0          116s
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running     0          2m15s
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running     0          2m11s
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running     0          2m14s
```

$ kgp -A

```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running     0          3m9s
kube-system   etcd-ip                                                 1/1     Running     0          2m46s
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed   0          3m2s
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed   0          3m2s
kube-system   helm-install-rke2-ingress-nginx-8n96t                   1/1     Running     0          3s
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed   0          3m2s
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed   0          3m2s
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed   1          3m2s
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed   0          3m2s
kube-system   kube-apiserver-ip                                       1/1     Running     0          3m6s
kube-system   kube-controller-manager-ip                              1/1     Running     0          3m9s
kube-system   kube-proxy-ip                                           1/1     Running     0          3m5s
kube-system   kube-scheduler-ip                                       1/1     Running     0          3m9s
kube-system   rke2-canal-842vm                                        2/2     Running     0          2m53s
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running     0          2m54s
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running     0          2m54s
kube-system   rke2-ingress-nginx-controller-cxjqn                     1/1     Running     0          2m
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running     0          2m19s
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running     0          2m15s
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running     0          2m18s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS              RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running             0          3m17s
kube-system   etcd-ip                                                 1/1     Running             0          2m54s
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed           0          3m10s
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed           0          3m10s
kube-system   helm-install-rke2-ingress-nginx-8n96t                   1/1     Running             0          11s
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed           0          3m10s
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed           0          3m10s
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed           1          3m10s
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed           0          3m10s
kube-system   kube-apiserver-ip                                       1/1     Running             0          3m14s
kube-system   kube-controller-manager-ip                              1/1     Running             0          3m17s
kube-system   kube-proxy-ip                                           1/1     Running             0          3m13s
kube-system   kube-scheduler-ip                                       1/1     Running             0          3m17s
kube-system   rke2-canal-842vm                                        2/2     Running             0          3m1s
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running             0          3m2s
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running             0          3m2s
kube-system   rke2-ingress-nginx-admission-patch-fqwgf                0/1     ContainerCreating   0          0s
kube-system   rke2-ingress-nginx-controller-cxjqn                     1/1     Terminating         0          2m8s
kube-system   rke2-ingress-nginx-defaultbackend-5d948499f5-gtl5t      0/1     ContainerCreating   0          2s
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running             0          2m27s
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running             0          2m23s
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running             0          2m26s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS              RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running             0          3m24s
kube-system   etcd-ip                                                 1/1     Running             0          3m1s
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed           0          3m17s
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed           0          3m17s
kube-system   helm-install-rke2-ingress-nginx-8n96t                   0/1     Completed           0          18s
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed           0          3m17s
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed           0          3m17s
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed           1          3m17s
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed           0          3m17s
kube-system   kube-apiserver-ip                                       1/1     Running             0          3m21s
kube-system   kube-controller-manager-ip                              1/1     Running             0          3m24s
kube-system   kube-proxy-ip                                           1/1     Running             0          3m20s
kube-system   kube-scheduler-ip                                       1/1     Running             0          3m24s
kube-system   rke2-canal-842vm                                        2/2     Running             0          3m8s
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running             0          3m9s
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running             0          3m9s
kube-system   rke2-ingress-nginx-controller-cxjqn                     1/1     Terminating         0          2m15s
kube-system   rke2-ingress-nginx-defaultbackend-5d948499f5-gtl5t      0/1     ContainerCreating   0          9s
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running             0          2m34s
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running             0          2m30s
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running             0          2m33s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running     0          14m
kube-system   etcd-ip                                                 1/1     Running     0          14m
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed   0          14m
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed   0          14m
kube-system   helm-install-rke2-ingress-nginx-8n96t                   0/1     Completed   0          11m
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed   0          14m
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed   0          14m
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed   1          14m
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed   0          14m
kube-system   kube-apiserver-ip                                       1/1     Running     0          14m
kube-system   kube-controller-manager-ip                              1/1     Running     0          14m
kube-system   kube-proxy-ip                                           1/1     Running     0          14m
kube-system   kube-scheduler-ip                                       1/1     Running     0          14m
kube-system   rke2-canal-842vm                                        2/2     Running     0          14m
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running     0          14m
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running     0          14m
kube-system   rke2-ingress-nginx-controller-fxs5r                     1/1     Running     0          11m
kube-system   rke2-ingress-nginx-defaultbackend-5d948499f5-gtl5t      1/1     Running     0          11m
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running     0          13m
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running     0          13m
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running     0          13m
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   cloud-controller-manager-ip                             1/1     Running     0          16m
kube-system   etcd-ip                                                 1/1     Running     0          15m
kube-system   helm-install-rke2-canal-2gw8q                           0/1     Completed   0          15m
kube-system   helm-install-rke2-coredns-jdzdh                         0/1     Completed   0          15m
kube-system   helm-install-rke2-ingress-nginx-8n96t                   0/1     Completed   0          12m
kube-system   helm-install-rke2-metrics-server-gqmpt                  0/1     Completed   0          15m
kube-system   helm-install-rke2-snapshot-controller-crd-l856k         0/1     Completed   0          15m
kube-system   helm-install-rke2-snapshot-controller-z499h             0/1     Completed   1          15m
kube-system   helm-install-rke2-snapshot-validation-webhook-9k9zw     0/1     Completed   0          15m
kube-system   kube-apiserver-ip                                       1/1     Running     0          16m
kube-system   kube-controller-manager-ip                              1/1     Running     0          16m
kube-system   kube-proxy-ip                                           1/1     Running     0          15m
kube-system   kube-scheduler-ip                                       1/1     Running     0          16m
kube-system   rke2-canal-842vm                                        2/2     Running     0          15m
kube-system   rke2-coredns-rke2-coredns-55bdf87668-rtqr7              1/1     Running     0          15m
kube-system   rke2-coredns-rke2-coredns-autoscaler-65c8c6bd64-s62cp   1/1     Running     0          15m
kube-system   rke2-ingress-nginx-controller-fxs5r                     1/1     Running     0          12m
kube-system   rke2-ingress-nginx-defaultbackend-5d948499f5-gtl5t      1/1     Running     0          12m
kube-system   rke2-metrics-server-7c85d458bd-ljjkn                    1/1     Running     0          15m
kube-system   rke2-snapshot-controller-65bc6fbd57-qs5bj               1/1     Running     0          15m
kube-system   rke2-snapshot-validation-webhook-859c7896df-pjt65       1/1     Running     0          15m
```

$ sudo cat /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-ingress-nginx/rke2-ingress-nginx-4.10.503.tgz
    rke2.cattle.io/inject-cluster-config: "true"
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    defaultBackend:
      enabled: true
      autoscaling:
        enabled: false
      image:
        repository: cerit.io/cerit/default-backend
        tag: "v1.1"
        readOnlyRootFilesystem: false
  bootstrap: false
  chartContent:  ........
...............
...............
...............
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultIngressClass: ingress-nginx
```


I'm truncating the output on these commands to focus on the pods in question from the clusters kube-system namespace FYI

$ sudo INSTALL_RKE2_VERSION=v1.31.6-rc1+rke2r1 INSTALL_RKE2_EXEC=server ./install-rke2.sh
```
[INFO]  using v1.31.6-rc1+rke2r1 as release
[INFO]  downloading checksums at https://github.com/rancher/rke2/releases/download/v1.31.6-rc1+rke2r1/sha256sum-amd64.txt
[INFO]  downloading tarball at https://github.com/rancher/rke2/releases/download/v1.31.6-rc1+rke2r1/rke2.linux-amd64.tar.gz
[INFO]  verifying tarball
[INFO]  unpacking tarball file to /usr/local
```

$ go_rke2
```
Created symlink /etc/systemd/system/multi-user.target.wants/rke2-server.service → /usr/local/lib/systemd/system/rke2-server.service.
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-6qnjw                   0/1     Completed   0          12m
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Running     0          11m
```

$ sudo vim /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml
$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-6qnjw                   0/1     Completed   0          15m
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Running     0          14m
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-6qnjw                   0/1     Completed   0          15m
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Running     0          14m
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-6qnjw                   0/1     Completed   0          15m
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Running     0          14m
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   1/1     Running     0          3s
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Running     0          14m
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS              RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   1/1     Running             0          13s
kube-system   rke2-ingress-nginx-admission-patch-6fh2r                0/1     Completed           0          3s
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Terminating         0          14m
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      0/1     ContainerCreating   0          4s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS        RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed     0          20s
kube-system   rke2-ingress-nginx-controller-q4k6t                     1/1     Terminating   0          15m
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running       0          11s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed   0          24s
kube-system   rke2-ingress-nginx-controller-tzbs8                     0/1     Running     0          3s
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running     0          15s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed   0          28s
kube-system   rke2-ingress-nginx-controller-tzbs8                     0/1     Running     0          7s
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running     0          19s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed   0          30s
kube-system   rke2-ingress-nginx-controller-tzbs8                     0/1     Running     0          9s
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running     0          21s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed   0          41s
kube-system   rke2-ingress-nginx-controller-tzbs8                     0/1     Running     0          20s
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running     0          32s
```

$ kgp -A
```
NAMESPACE     NAME                                                    READY   STATUS      RESTARTS   AGE
kube-system   helm-install-rke2-ingress-nginx-2c6kt                   0/1     Completed   0          44s
kube-system   rke2-ingress-nginx-controller-tzbs8                     1/1     Running     0          23s
kube-system   rke2-ingress-nginx-defaultbackend-68d99f5984-cb688      1/1     Running     0          35s
```
