### ISSUE TITLE
CVE-2025-1974 Vulnerability

### ISSUE THREAD

**Issue by shubb30** [rancher/rke2#7953]
Is the RKE2 Ingress controller vulnerable to [CVE-2025-1974](https://github.com/kubernetes/kubernetes/issues/131009), and if so, is there a timeline for a release fix?

**Comment by brandond** [comment]
The announcement was published before patches were available from upstream, ref: https://github.com/kubernetes/kubernetes/issues/131005#issuecomment-2749403386

Our March releases should be available soon and will include a version of ingress-nginx that resolves this vulnerability.

**Comment by MichelZ** [comment]
Can you define "soon" a bit more?

**Comment by dfaltum** [comment]
> > As a workaround, you can disable the admission webhook until then:
> > ```
> > apiVersion: helm.cattle.io/v1
> > kind: HelmChartConfig
> > metadata:
> >   name: rke2-ingress-nginx
> >   namespace: kube-system
> > spec:
> >   valuesContent: |
> >     controller:
> >       admissionWebhooks:
> >         enabled: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Important: With this setting you can't create or modify any existing ingress!
> 
> Actually not true. The changes are just not validated. You can still modify, create and delete ingress's

You're right, thanks for the correction!

**Comment by localleon** [comment]
According to https://github.com/kubernetes/kubernetes/issues/131009 upstream builds are now available: 
> Builds have completed: [v1.11.5](https://github.com/kubernetes/ingress-nginx/pull/13074) and [v1.12.1](https://github.com/kubernetes/ingress-nginx/pull/13073) are now available!

**Comment by dehoej** [comment]
Yes and rancher are also working to get it releases: https://github.com/rancher/ingress-nginx/branches

**Comment by betweenclouds** [comment]
There is now a KB about this:
https://www.suse.com/support/kb/doc/?id=000021756

**Comment by shubb30** [comment]
> There is now a KB about this: https://www.suse.com/support/kb/doc/?id=000021756

According to this article (and the upstream K8s issue) the way to know if you are affected is by running 
```kubectl get pods --all-namespaces --selector app.kubernetes.io/name=ingress-nginx```  

When I run that on my cluster, I do not see any pods.  However, I can clearly see that I have Ingress Nginx Controller pods running in `kube-system`, and if I run 

```kubectl get pods --all-namespaces --selector app.kubernetes.io/name=rke2-ingress-nginx```

 I do see pods.  Are the `rke2-ingress-nginx` images not vulnerable to this?

**Comment by macedogm** [comment]
> I do see pods. Are the rke2-ingress-nginx images not vulnerable to this?

They are too. The KB is being updated. It missed the specific deployment name for RKE2. Sorry about that.

**Comment by shubb30** [comment]
The article also says that the way to disable the admission controller is via 2 methods: the Helm install or the manual install.  What about the standard rke2 install?  I checked the [server config](https://docs.rke2.io/reference/server_config) and there does not appear to be an option to disable the Validating Admission Controller.

**Comment by e100** [comment]
@shubb30 

On one of your nodes create the file:
/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

With content:
```
apiVersion: helm.cattle.io/v1                                                        
kind: HelmChartConfig                                                                                                                                                      
metadata:                                                                            
  name: rke2-ingress-nginx                                                           
  namespace: kube-system                                                             
spec:                                                                                
  valuesContent: |-                                                                  
    controller:                                                                      
      admissionWebhooks:                                                             
        enabled: false                                                               
      extraArgs:                                                                     
        enable-annotation-validation: true 
```

The cluster will automatically apply the change once you create that file.
The above also includes the suggested `enable-annotation-validation: true` option
If you already have such a file you should merge the above changes into your existing file.

I typically place an identical file on all nodes but I'm not sure if that is necessary, it always applies it as soon as I change it on just one node.
