### ISSUE TITLE
Pods insist on trying to connect to IPv6, even when IPv6 is fully disabled

### ISSUE THREAD

**Issue by Inumedia** [rancher/rke2#7982]
I've spent a few days trying to figure out why this is happening, reprovisioned the nodes at least a dozen times testing different set ups and configurations, and spent many hours googling / asking AIs / searching around for why this is happening. It doesn't make sense to me. ☹

**Environmental Info:**
RKE2 Version: rke2 version v1.31.7+rke2r1 (7b18bda1c5ec1e110cec206f9163f6aba3a2154d)
go version go1.23.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version:  6x: Linux _____ 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 servers, 3 agents, 6 nodes total set up on Harvester, Ubuntu 24.04 cloudimg, set up with IPv4 CIDR, IPv6 fully disabled (tried without this), IPv4 NAT and IPv4 Ingress through Harvester loadbalancer.

**Describe the bug:** 
CoreDNS resolves DNS to IPv6, cluster pods try to connect to IPv6:
`Error initializing issuer: Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp [2001:19f0:6401:a26:5400:4ff:fe46:4392]:443: connect: network is unreachable`

**Steps To Reproduce:**

Scripts used for installing nodes:
```
sudo swapoff -a
echo '      routes:' | sudo tee -a /etc/netplan/50-cloud-init.yaml
echo '      - to: 10.0.0.0/8' | sudo tee -a /etc/netplan/50-cloud-init.yaml
echo '        via: 10.69.0.1' | sudo tee -a /etc/netplan/50-cloud-init.yaml
sed -i '/      dhcp6: true/d' /etc/netplan/50-cloud-init.yaml # Disable IPv6 DHCP
sudo netplan apply

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
sudo apt update && sudo apt install -y qemu-guest-agent cachefilesd nfs-common
sudo systemctl enable --now qemu-guest-agent.service
echo "RUN=yes" >> /etc/default/cachefilesd
mkdir /mnt/store
echo "..." >> /etc/fstab
sudo systemctl daemon-reload
mount -a
```

Scripts used for installing server/agent:
```
mkdir -p /etc/rancher/rke2/
echo 'token: ...' | sudo tee -a /etc/rancher/rke2/config.yaml
echo 'tls-san:' | sudo tee -a /etc/rancher/rke2/config.yaml
echo '  - ...' | sudo tee -a /etc/rancher/rke2/config.yaml
curl -sfL https://get.rke2.io | sh -
systemctl enable rke2-server.service && systemctl start rke2-server.service
```

kubectl/helm commands ran after rke2 install completes:
```
kubectl label nodes ___-01 node-role.kubernetes.io/worker=true
kubectl label nodes ___-02 node-role.kubernetes.io/worker=true
kubectl label nodes ___-03 node-role.kubernetes.io/worker=true
kubectl label nodes ___-04 node-role.kubernetes.io/worker=true
kubectl label nodes ___-05 node-role.kubernetes.io/worker=true
kubectl label nodes ___-06 node-role.kubernetes.io/worker=true
kubectl get nodes
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml
kubectl create ns cattle-system
 helm upgrade rancher rancher-stable/rancher `
>>    --install `
>>    --namespace cattle-system `
>>    --set hostname=____ `
>>    --set ingress.tls.source=letsEncrypt `
>>    --set letsEncrypt.email=____ `
>>    --set letsEncrypt.ingress.class=nginx
```

**Expected behavior:**
Pods should not be attempting to connect to IPv6, CoreDNS should only resolve to IPv4

**Actual behavior:**
Pods attempt to connect to IPv6, with default settings

**Additional context / logs:**
Creating a deployment `ubuntu:24.04`, with the commands: `sleep 10000` is able to pull down the image and runs without issue, but if you connect to the shell of the pod and run command `apt update`, it fails because it attempts to connect to IPv6:
```
root@ubuntu-64d67c4cc8-6lhjt:/# apt update
Ign:1 http://archive.ubuntu.com/ubuntu noble InRelease
Ign:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Ign:3 http://security.ubuntu.com/ubuntu noble-security InRelease
Err:4 http://security.ubuntu.com/ubuntu noble-security Release
  Cannot initiate the connection to security.ubuntu.com:80 (2001:19f0:6401:a26:5400:4ff:fe46:4392). - connect (101: Network is unreachable)
Ign:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu noble Release
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:19f0:6401:a26:5400:4ff:fe46:4392). - connect (101: Network is unreachable)
Err:7 http://archive.ubuntu.com/ubuntu noble-updates Release
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:19f0:6401:a26:5400:4ff:fe46:4392). - connect (101: Network is unreachable)
Err:8 http://archive.ubuntu.com/ubuntu noble-backports Release
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:19f0:6401:a26:5400:4ff:fe46:4392). - connect (101: Network is unreachable)
```

Canal config:
```
root@____-01:/home/ubuntu# cat /var/lib/rancher/rke2/server/manifests/rke2-canal.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helm.cattle.io/chart-url: https://rke2-charts.rancher.io/assets/rke2-canal/rke2-canal-v3.29.2-build2025030601.tgz
    rke2.cattle.io/inject-cluster-config: "true"
  name: rke2-canal
  namespace: kube-system
spec:
  bootstrap: true
  chartContent: ...
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultIngressClass: ingress-nginx
```
