### ISSUE TITLE
server port 9345 is not working over bgp but others are

### ISSUE THREAD

**Issue by ashtonian** [rancher/rke2#8030]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.32.3+rke2r1 (18005e93ee0b015b78be47cf6515ae6d3a9afd55)
go version go1.23.6 X:boringcrypto

Node(s) CPU architecture, OS, and Version: 
Ubuntu 24 LTS

Cluster Configuration:
3 servers, 3 agents

**Describe the bug:**
I'm using cilium bgp to announce a external kubernetes service api on 10.46.0.60, The underlying node ip is 10.42.0.50. If I run curl https://10.46.0.60:443. I get a response from the kubernetes service. If I curl 10.42.0.50:9345 I get a response, however I cannot get a response from 10.46.0.60:9345 which is preventing me from registering agents. 

I'm not sure why its working for 443 and not 9345. I understand there isn't a kube pod or service for 9345 and thats handled by the rke2 server service listening on the node, but that shouldn't matter as BGP is announcing the ip route so that should be shared.

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
```
/etc/rancher/rke2$ cat config.yaml
write-kubeconfig-mode: "0644"
token: redacted
cluster-cidr: 10.44.0.0/16
service-cidr: 10.45.0.0/16
disable-kube-proxy: true
advertise-address: 10.46.0.60
tls-san-security: false
disable:
  - rke2-canal
  - rke2-kube-proxy
tls-san:
  - 10.46.0.60
cni:
  - cilium
```
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      repository: quay.io/cilium/cilium-ci
       #fixes https://github.com/cilium/cilium/issues/38210#issuecomment-2789795047
      tag: 3d3fe685fa430034a7315b932f31e3eebb1a2d2f@sha256:a98ba52a629d83d00a1227803e4816d7c3289971ff163a3bc89afb6ce6292b2f
    policyEnforcementMode: never # default
    nodePort:
      enabled: true
    hostPort:
      enabled: true
    externalIPs:
      enabled: true
    socketLB:
      enabled: false
    bgpControlPlane:
      enabled: true
    daemon:
      enableSourceIPVerification: false
    kubeProxyReplacement: true
    k8sServiceHost: 10.42.0.50
    k8sServicePort: 6443
```
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "poolio"
spec:
  blocks:
  - cidr: "10.46.0.0/24"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  bgpInstances:
  - name: "instance-65001"
    localASN: 65001
    # localPort: 179   # (Optional) If you want to *listen* for inbound sessions.
    peers:
    - name: "peer-10-42-0-1"
      peerASN: 65000
      peerAddress: "10.42.0.1"
      peerConfigRef:
        name: cilium-peer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: service-lb-ips
  namespace: kube-system
  labels:
    advertise: "bgp"
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
        - ExternalIP
        - LoadBalancerIP
      # Optional: aggregatorLengthIPv4: 32  (defaults to /32 announcements for LB IPs)
      # aggregatorLengthIPv6: 128
      # externalTrafficPolicy logic is respected automatically
    selector:
      # This example *matches all* Services by using a "NotIn" expression
      # on a dummy key, so effectively everything is selected:
      matchExpressions:
      - { key: somekey, operator: NotIn, values: ["never-used-value"] }
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
  namespace: kube-system
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 10.46.0.60
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kubernetes-external
  namespace: kube-system
spec:
  selector:
    component: kube-apiserver
    tier: control-plane
  ports:
  - name: svcport
    port: 6443
    protocol: TCP
    targetPort: 6443
  - name: https
    protocol: TCP
    port: 443
    targetPort: 6443
  type: LoadBalancer
  loadBalancerIP: 10.46.0.60
---
```
