### ISSUE TITLE
RKE2 + Cilium + multus + whereabouts

### ISSUE THREAD

**Issue by cloudcafetech** [rancher/rke2#8106]
Trying to setup kubevirt on top of RKE2 along with Cilium + multus + whereabouts

```
cat << EOF >  config.yaml
token: pkar-rke2
write-kubeconfig-mode: "0644"
cluster-cidr: 10.244.0.0/16
service-cidr: 10.96.0.0/12
node-label:
- "region=master"
tls-san:
  - "rke2-centos-m1"
  - "192.168.0.126"
cni:
  - multus
  - cilium
disable-kube-proxy: true
disable-cloud-controller: true
disable:
  - disable-cloud-controller
  - rke2-snapshot-controller
  - rke2-snapshot-controller-crd
  - rke2-snapshot-validation-webhook
  - rke2-ingress-nginx
EOF

cat << EOF > rke2-cilium-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    ipam:
      mode: kubernetes
    cni:
      exclusive: false
    l2announcements
      enabled: true
    externalIPs:
      enabled: true
    socketLB: 
      hostNamespaceOnly: true
    ingressController:
      enabled: true
    gatewayAPI:
      enabled: false
EOF

cat << EOF > rke2-multus-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-multus
  namespace: kube-system
spec:
  valuesContent: |-
    rke2-whereabouts:
      enabled: true
EOF


curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.31 sh -
mkdir -p /etc/rancher/rke2/
mkdir -p /var/lib/rancher/rke2/manifests
cp config.yaml /etc/rancher/rke2/
cp rke2-*-config.yaml /var/lib/rancher/rke2/manifests/

systemctl enable --now rke2-server
```

Looks like CNI pod not ready, both (cilium + multus) CrashLoopBackOff 

```
get po -n kube-system
NAME                                                    READY   STATUS                  RESTARTS        AGE
cilium-f8d5n                                            0/1     Init:CrashLoopBackOff   5 (2m27s ago)   13m
cilium-operator-6bc46df4c9-45vxb                        0/1     Pending                 0               13m
cilium-operator-6bc46df4c9-mpz7p                        0/1     Running                 7 (2m52s ago)   13m
etcd-rke2-centos-m1                                     1/1     Running                 0               13m
helm-install-rke2-cilium-dr9p7                          0/1     Completed               0               14m
helm-install-rke2-coredns-t7s9w                         0/1     Completed               0               14m
helm-install-rke2-metrics-server-dbf2l                  0/1     Pending                 0               14m
helm-install-rke2-multus-g57ps                          0/1     Completed               0               14m
helm-install-rke2-runtimeclasses-zpkcv                  0/1     Pending                 0               14m
kube-apiserver-rke2-centos-m1                           1/1     Running                 0               13m
kube-controller-manager-rke2-centos-m1                  1/1     Running                 0               14m
kube-scheduler-rke2-centos-m1                           1/1     Running                 0               14m
rke2-coredns-rke2-coredns-6d54d78648-qnf2k              0/1     Pending                 0               13m
rke2-coredns-rke2-coredns-autoscaler-596dcdf688-5zkhk   0/1     Pending                 0               13m
rke2-multus-c82nz                                       0/1     CrashLoopBackOff        7 (2m14s ago)   13m
```

Am I missing anything or any sequence ?
