### ISSUE TITLE
RKE2 Helm controller prepends metadata.name to spec.chart when resolving chart name

### ISSUE THREAD

**Issue by Albe83** [rancher/rke2#8113]
**Environmental Info:**
RKE2 Version: 
```
rke2 version v1.31.7+rke2r1 (7b18bda1c5ec1e110cec206f9163f6aba3a2154d)
go version go1.23.6 X:boringcrypto
```

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**
The Helm controller in RKE2 prepends the `metadata.name` value to the `spec.chart` value in HelmChart CRDs, resulting in an incorrect chart name when resolving the chart from the repository.

**Steps To Reproduce:**
- Installed RKE2: Standard installation (details omitted here for brevity)
- Created the following HelmChart manifest:

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-operator
  namespace: kube-system
spec:
  repo: https://charts.rook.io/release
  chart: rook-ceph
  version: v1.17.0
  targetNamespace: storage-system
  createNamespace: true
```

**Expected behavior:**
The chart should be resolved as:
```
helm install rook-operator rook-ceph --repo https://charts.rook.io/release --version 1.17.0
```

**Actual behavior:**
From environment variables observed during execution:
```
CHART: rook-operator/rook-ceph
```
This causes Helm to look for a non-existent chart path and fail the installation.

**Additional context / logs:**
- The chart `rook-ceph` exists in the repository at `https://charts.rook.io/release` without any prefix.
- This behavior occurs regardless of the formatting of the `spec.chart` field.
- The behavior was confirmed via environment dump from the controller.

Could you please confirm whether this is expected behavior or a bug? If intentional, it would be helpful to document how the chart name is composed internally by the Helm controller.

Thanks!

**Comment by brandond** [comment]
> The chart should be resolved as:
>
> `helm install rook-operator rook-ceph --repo https://charts.rook.io/release --version 1.17.0`

That is not correct. The repo is added first, using the name of the HelmChart resource, and then the chart is installed as `<repo>/<chart>`. You can see this if you look at the logs:

```console
+ helm repo add rook-operator https://charts.rook.io/release
"rook-operator" has been added to your repositories
+ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "rook-operator" chart repository
Update Complete. ⎈Happy Helming!⎈
+ helm_update install --namespace storage-system --create-namespace --version v1.17.0
++ helm ls --all -f '^rook-operator$' --namespace storage-system --output json
++ jq -r '"\(.[0].chart),\(.[0].status)"'
++ tr '[:upper:]' '[:lower:]'
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm chart'
+ helm install --namespace storage-system --create-namespace --version v1.17.0 rook-operator rook-operator/rook-ceph
NAME: rook-operator
LAST DEPLOYED: Wed Apr 23 15:54:34 2025
NAMESPACE: storage-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The Rook Operator has been installed. Check its status by running:
```

As you can see the chart is installed correctly and with the correct name.

**Comment by Albe83** [comment]
Hi Brandon, thank you.
Doc (https://docs.rke2.io/helm#using-the-helm-crd) is misleading: suggests that installation is done via --repo...

Ty

**Comment by brandond** [comment]
The docs say that it is the equivalent flag for the helm CLI, which is correct. It functions identically. It does not say anywhere that this is how the chart installation is actually implemented.

**Comment by jansenfuller** [comment]
In reference to the first post from @brandond, how would you specify that you want the release name to be different from the chart name? As I understand it and from my own tests the following HelmChart
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: release-name
  namespace: kube-system
spec:
  repo: https://charts.k8s.io/release
  chart: chart-name/repo-name
  version: v1.17.0
  targetNamespace: kube-system
```
currently produces the following command
```
helm upgrade --namespace kube-system release-name release-name/chart-name/repo-name
```
