### ISSUE TITLE
Can't provide Windows node with enabled registry mirror

### ISSUE THREAD

**Issue by Ihor-kolomiiets** [rancher/rke2#8138]
**Environmental Info:**
RKE2 Version: 
v1.28.13+rke2r1

Node(s) CPU architecture, OS, and Version: 
5.15.0-200.131.27.el9uek.x86_64 #2 SMP Wed Oct 4 22:09:54 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux

Windows: 
OS Name:                   Microsoft Windows Server 2022 Datacenter Evaluation
OS Version:                10.0.20348 Build 20348

Cluster Configuration:
18 nodes (3 master, 1 windows)

**Describe the bug:**
Windows node fail to povisioning when embedded-registry is enabled

**Steps To Reproduce:**
- Installed RKE2: via Rancher
- Provided cluster, and set additional parameter
```
machineSelectorConfig:
      - config:
          embedded-registry: true
          supervisor-metrics: true
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
```
with 
```
registries:
      mirrors:
        "*" :
```
for the `registries.yaml`

**Expected behavior:**
Windows node after updating stays available

**Actual behavior:**
Windows node become unavailable with waiting for kubelet

**Additional context / logs:**
Launching rke2.exe file will exit with error 
```
time="2025-05-06T12:40:56+02:00" level=info msg="Windows bootstrap okay. Exiting setup."
time="2025-05-06T12:40:56+02:00" level=fatal msg="mkdir C:\\var\\lib\\rancher\\rke2\\agent\\etc\\containerd\\certs.d\\127.0.0.1:9345: The directory name is invalid."
```
since rke2 trying to create folder which can't be created in Windows
