### ISSUE TITLE
rkeConfig is not updating cilium chart when hubble.metrics.enabled is set

### ISSUE THREAD

**Issue by todeb** [rancher/rke2#8200]
**Environmental Info:**
RKE2 Version: 
v1.28.15+rke2r1

**Describe the bug:**

hubble.metrics.enabled value set in rkeConfig is not propagated to chart values:
```
rkeConfig:
    chartValues:
      rke2-cilium:
        hubble:
          enabled: true
          metrics:
            enableOpenMetrics: true
            enabled: '{dns,drop,tcp,flow,port-distribution,icmp}'
```
I had tried with double quotes, but this is not working too.
All other values when hubble.metrics.enabled is not set are working.

Eventually i want to set this helm value, but as it doesn't work I tried simpler, which also doesn't work.
```
hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}"
```

**Expected behavior:**
```
helm get values rke2-cilium -n kube-system
```
should show hubble.metrics.enabled.

**Actual behavior:**
```
helm get values rke2-cilium -n kube-system
```
does not have hubble.metrics.enabled
