### ISSUE TITLE
kube-controller-manager throws unhandled error while syncing jobs, leading to node in NotReady state

### ISSUE THREAD

**Issue by fdegir** [rancher/rke2#8357]
**Environmental Info:**
RKE2 Version: 
`v1.32.5+rke2r1`

Node(s) CPU architecture, OS, and Version: 
`x86_64`, `SUSE Linux Micro 6.1` with `kernel 6.4.0-28-default` on libvirt VMs with 8 vcpus and 16GB RAM

Cluster Configuration:
3 control plane nodes (no agent nodes)

**Describe the bug:**
When deploying RKE2 on SUSE Linux Micro 6.1, the `kube-controller-manager` may intermittently throw an unhandled error while syncing Kubernetes Jobs. This results in the initial control plane node remaining in a `NotReady` state.

The issue may be caused by a race condition where the `Helm Controller` updates a Job while the `Job Controller` is attempting to sync job status. This scenario appears to be unhandled by the `Job Controller`.

Logs indicate the following error:

```
E0605 14:29:43.957315       1 job_controller.go:631] "Unhandled Error" err="syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch \"helm-install-rke2-cilium\": StorageError: invalid object, Code: 4, Key: /registry/jobs/kube-system/helm-install-rke2-cilium, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: d6ac6936-4ddd-4583-a4c2-98a472ca1b0a, UID in object meta: 653a94d7-ae29-41a9-a222-72ac98aff7a8" logger="UnhandledError"```

```

**Steps To Reproduce:**
* Install RKE2
* Observe initializer node status after installation
* Check `kube-controller-manager` pod logs

Please note that the issue is very intermittent and may not occur every time. Multiple attempts might be needed to reproduce it.

**Expected behavior:**
The kube-controller-manager should gracefully handle concurrent Job updates and status syncs, avoiding unhandled errors.

**Actual behavior:**
The initial control plane node remains in a `NotReady` state due to an unhandled error in the `kube-controller-manager`. Recovery requires manually stopping and removing the affected `kube-controller-manager` pod.

**Additional context / logs:**
Additional logs will be added to this issue once the problem is reproduced.

**Comment by brandond** [comment]
This occurs when a controller deletes and recreates a Job while the Job controller is attempting to update the status to count pods. Wrangler-based controllers do this when the job.spec.template needs to be modified to apply changes, as the template is immutable: https://github.com/rancher/wrangler/blob/1345a309299c3e4aaf0f12188795b15978d5b9a2/pkg/apply/reconcilers.go#L148-L150

It seems the Job controller does not handle this, and simply skips handling the new job unless further changes are made to the resource that cause it to reenqueue for processing.

**Comment by brandond** [comment]
I am still waiting on debug logs from RKE2, which would show why the apply controller is recreating the job so quickly. While this is definitely an issue with the Job controller, we can probably avoid triggering it if we can figure out what else is going on.

**Comment by fdegir** [comment]
The log of rke2-server service is available [here](https://paste.opensuse.org/pastes/63802f0ae93e).

`kube-controller-manager` pod that was created initially and thrown unhandled error.

`Jun 25 19:24:28 host1rke2 rke2[3024]: time="2025-06-25T19:24:28.532730388Z" level=info msg="CreateContainer within sandbox \"675cb4b12f8c62d03951306b2aaac074ff44cedec56e042deaa1b36034ed5d47\" for &ContainerMetadata{Name:kube-controller-manager,Attempt:0,} returns container id \"c117f1decbfaf4d904c78b13d6e02c8dfe0d558d949512860f265c3243c520f6\""`

and then stopping and removing this pod resulted in `kube-controller-manager` pod to be recreated and the deployment to recover.

`Jun 25 19:29:43 host1rke2 rke2[3024]: time="2025-06-25T19:29:43.224594133Z" level=info msg="CreateContainer within sandbox \"675cb4b12f8c62d03951306b2aaac074ff44cedec56e042deaa1b36034ed5d47\" for &ContainerMetadata{Name:kube-controller-manager,Attempt:0,} returns container id \"f3259ec61c82cc976fd89c92f635ce3d574e6f6964f6864937c6a228ebc749a1\""`

**Comment by brandond** [comment]
I can see that it is patching the secrets and jobs to add values from the HelmChartConfig, which suggests that those resources did not exist when the chart was initially seen by the Helm controller:

`brandond@dev01:~$ for PATCH in $(grep -o 'PATCH:{.*}, ORIGINAL' rke2-8357.log | sed -e 's/, ORIGINAL//; s/PATCH://; s/\\"/"/g'); do echo "${PATCH}" | yq -P . - ; echo ---; done` 

```yaml
data:
  HelmChartConfigValuesContent: Y25pOgogIGV4Y2x1c2l2ZTogZmFsc2U=
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySS2/UMBSF/wq6a3vIYzJpLHU1iIdYVIIyUotY3Ng3GRM/ItsZqKr57yhhKKUwwNK27vE537n3gKPeUYjaOxBwyIGBwoQg7uE1GbvdY0hb7zrd79BMFLfeJXIJBNwU1XjV+/7Nq936pviay8IUt9e+v7Uvoyw+XMKRwaCdAgHvSQZKwMBSwh/y6JxPmLR3cT769jPJFCmtgvYriSkZWmn/XM8CezKWS+9S8MZQ4HK2xQP1OqawaAA7q+C/OAq8PwwnoUdPh5w9e6udunzI+k8dh5ZAQBio4FIbPdn/GokjynlumFri8S4msjMgGWixf60txYR2BOEmYxgYbMn8Fcwe4x4EFPUmkw3WG8yyUilZ1VlZFA11dZapTK0buaGqK7P5t5P37/QOS5/81yDnrDJYoryjjgI5SRHExye78xtaYNAaL4erefIFGVp6Eh2aSAx+tvlwddqWx138kfa07IRsq6rNy5znVUZ8LZuGX2CT80bVdae68qKhBo6fjgzS3Ugng0v0uHrqdUEBx28BAAD//5Njoi4OAwAA
---
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7RXW2/qPBb9KyM/JyHhDlIfciAdmEMBJZxqRkcVMs4GPDh2xnY4ZSr++ycnaZtQenv43ojjtbIvy8ubJ4RTeg9SUcHREG2wJvvG0UMWOlAeoyH6l9ggCyWgcYw1RsMnhDkXGmsquDKPYvNfIFqBdiQVDsFaM3CoaFCD3gNLbCK4loIxkDbZY6ltCTuqtMw5kPUug/jDQdq746Ekqrw6etY/flIe30yAJSND+ikPxwmgIZIHaNqEMpolX4KoFBODO2QbsNVJaUjQ2UJEQh7+iiagNE5SNOQZYxZieAMsL4wJOc9XORfR56tfjmWP1R4NUbPXdckA97rYdVtxTDo9t9VsDmDbc93YjdsD0oXOtuWa6Mpc8+pTrjRmzK5/7L3ULJSnHsIWJHACCg1/X2jkTSuQhTZMkMPCIMfAIO/rcIuZAgu9dv9lqZRWtXdXu5PlGiKbTmfjtTzb67hgt8lgYPfxwLMHca+3jbet/gAG6PxwtpBKgZjKbzA5iO12RhOq0dBzXddCGpKUYQ3m/Qdq/qBpgm/pblI0I5r4zU73ZtQcuD2/2e8G/Y47GNz6fr83Dvo/OmPvtt8J2v3ebcfteKOx2236Tdf1fa/lNTv99t8ioXOlBKbqmHKQZQPlzvxApRiQhWxbgbaVlpTvkIV2TGwwcwjLlAY5mo7DG8912k3HddyG1/0K4Nj+FmQ8j/L9Lcd1PPfT3SLBlN+UTw4TBL+fhSnKGGs8pvKmccSyweimITEne5AN8/JdpAJ5pARe8m99lkxxbMawxRnTU76ToNSIYaVuaPFg8x3lj+jBQsCPeS9Kqc/9uwBZ6IhZdqn8s/Wy6z4Io+liXl0Kg+Wi+jwJZnfrcTi9D8IKnwIiQVf3jSZ+uFqbz0ZLf1T9dt3b6oA3X7oS0coP/xl8i9r/tZqsl34UrUdhMA7mq6k/iyqw3CiqgOk8Cka/wmAd/Zwu16tZZOKY3v7nI8xy5k/n68lqtfxo189fP4JwHqyCaB0F4f10FKwni2hVgXjNnpGB430CWy7CKqzbbreqiB+LxSpahX41Gi2zWjDzxXoZLv5dTctRR2I5NeFb1XNm1XRa4br1pzNTseViNh1VGSU828D5wUI0wbt8tTwfB0bTFKRtDGd4dJ2B07E3GWVx02123JZrzkKOWWaMLQWj5GT6s50LvZSggFfs3HAgC0lQIpP5ZfJkPApIJqk+jQTX8KhzF2ZM/FlKeqQMdhAoghmu3yI4xRvKqKY5C4qlSI2h+bMZMtYvAccLzk6hEPqWMiglNzQFPlvoKFiWwJ3IuC4MMTE/l1gbM2/sRQK1vBtOGXmZR/VdXuLP4ASTPbzFF8tfIshvmysMxfobCp2kr5vNw5sdl4y5GtSVffUb2VwkpqfnByOWvVB6DvqPkIeithbiIoYIGBAtpOmMOfGSgwaVD1IKDRGjPHtExVZbCgZOfVM5Itgpw7xyKoxuNJb6RWQLfospy6Sp7BURyYz7ai640cBzdAoIEUm6lGJLWX7561Oau2jGNU2gdO7i7izM3yfE1GNemaHqY4kWDOTzyPD7CcF2C8RcxnMRkT3EGTMBHsCEbFK+yJYLMwHj+JTX/rvgovh2xvERU4Y3DL5GQ5jI4lSKI41BXpBmnHKqKWb0/xCbETA1+Zl2ouB/WX7RvjGsgnokqaYEMz+OBVfmAF7AH6nS6jLC4BFIpusBXtMFaHIZzlW+qxl/LrSrzA/PZlH2Nkn1aUxlMTbGRgBDdAeJkKfKoP3GH74He7WFb+JezeBrwGdjqFuAhVIpzH8PiA38xat/Pz1PEcMnRDUkxVpR4pfhfZQHcZ9TjUqzsFBauEnxBduzXde1LyB2DeOccFJcSM/Gk/9VLAnqY+7D2SRRZH+HUxNeDVR6Vh11zdHyU6+xzvKb6fxXAAAA//+X0VG7DQ8AAA
spec:
  template:
    metadata:
      annotations:
        helmcharts.helm.cattle.io/configHash: SHA256=C2907A286E85099FAA87DE8B5D1F85E487F5051CD062A200AA131258416A1B16
    spec:
      $setElementOrder/volumes:
        - name: klipper-helm
        - name: klipper-cache
        - name: klipper-config
        - name: tmp
        - name: values
        - name: content
      volumes:
        - $retainKeys:
            - name
            - projected
          name: values
          projected:
            sources:
              - secret:
                  items:
                    - key: HelmChartConfigValuesContent
                      path: values-1-000-HelmChartConfig-ValuesContent.yaml
                  name: chart-values-rke2-cilium
---
data:
  HelmChartConfigValuesContent: Y29udHJvbGxlcjoKICBjb25maWc6CiAgICB1c2UtZm9yd2FyZGVkLWhlYWRlcnM6ICJ0cnVlIgogICAgZW5hYmxlLXJlYWwtaXA6ICJ0cnVlIgogIHB1Ymxpc2hTZXJ2aWNlOgogICAgZW5hYmxlZDogdHJ1ZQogIHNlcnZpY2U6CiAgICBlbmFibGVkOiB0cnVlCiAgICB0eXBlOiBMb2FkQmFsYW5jZXIKICAgIGV4dGVybmFsVHJhZmZpY1BvbGljeTogTG9jYWw=
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySX2/TMBTFvwq6z3FpsvxpIvHAgtjGQEgDWm2Ih2v7JnXj2JXthlVTvztKKGMabPCYWPfcc37n3gFu1ZKcV9ZABUMMEUgMCNUdnJPu6zW6UFvTqHaJeke+tiaQCVDBdVLu5Pm7gZ/darGxlxf16YYnWY8rkdfqdXtRn8Yi+RJu+nIvk7f7m7Nl93611terKy3MhxwOEXTKSKjgEwlHASLoKeCv9WiMDRiUNX78tHxDIngKM6fsTGAImmbKvlSjwJp0z4Q1wVmtyTEx2maOWuWDmzQgelLBfjfkWDt0R6EHT0McvbhURr66Z/FPHYM9QQWuo4Qp0zrynplWmdv/mvRbFON4t+PE/N4H6kdOwtGU4rPqyQfst1CZndYRaOSkn+WzRr+GCooyPinzsliQSBpZSE4nskyTPE0py3BeZlhwnnI+bjtG+AlxmGpnf83zlOMIpkRX1JAjI8hD9fXRpf0BGiLg2oru4zj5hjRNrVUNak8R/O72/tfxdh428xz73XQovMjlvMwalicyZinJjOFiUbIEizTjTUyYzuHw7RBB2G/p6HMC4WePLU9g4PAjAAD//+wSBUNDAwAA
---
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7RWXW/iOBT9Kys/JyF8BEqkPmRC2LJDIQKm2tWoQk5yAS+OHdkOM6jiv6/spG1o6dfDviWOz8m9PsfHfkC4IHcgJOEM+SjBKt21Dm1koT1hGfLRXzxBFspB4QwrjPwHhBnjCivCmdSvPPkXUiVBOYJwJ8VKUXAIbxGN3gHN7ZQzJTilIOx0h4WyBWyJVMJwIOtNBv6LgbC3h31N1Ph0aFt/fCcsu74Bmoea9EMehnNAPhJ76NiEbQVIabMtYb8/hZQFTjV8XyZgy6NUkKOThVIBposVyUEqnBfIZyWlFqI4AWrWR1du2pbOiybM6FdL2mG5Qz4aDNvdYX84uIK0s8kGWQLdbNjr9Hs98DzsDj08SJJekugi686NFoRJhSm1L/7zrUYtZBZiARsQwFKQyP/5wjiv9EEWSihP93ONHAEFI7a/wVSChZ4t8TRU+60p6HuSlcZfyaCfuUNvY/c7WdvuQebZ+OpqaHfwoOclmzbgnotO9ycLyQJSLUeC0z3fbKYkJwr5bdd1LaQgLyhWoL+/4/R3lORsQ7Y3lTTLm6Dj9a+7o25/PAyH4VW3PRh7g3HnW9QPw2jgDrrfvH5wFblet3s19oZhNwrDwO25QeebNw7/T1+dGiuhNcCEgajlFFv9gGqHIAvZtgRlSyUI2yILbSlPMHVSWkoFIpyMFtdt1+l1HNdxW+3+ZwCH3pcgo9nSzO86rtN2P5zNc0zYdf3mUJ7it7vQazPCCo+IuG4dsGhRkrQEZukOREt/fBMpQRxICk/9dz9qptpEI9jgkqpJJUdIsZTX59rcWwjYwWhRG38W3EbIQgdMyzf2wcl6mnwXLZaT+aw5tIjiefP9JprerkeLyV20aNBKSAWo5rzwJlis1vrvyzgImyWcx9854NWfLlS0ChZ/Rl+iDn6sbtZxsFyuw0U0imarSTBdNmAmPZqAyWwZhT8W0Xr5fRKvV9OlrmMy/uc9TDwNJrP1zWoVvzdrNl/Hi/nfTSZHHlLLObOc1XS4deaQBtc4mEx1kfF8OgmbjAIeN+Dp3kIkx1szWjtzT0lRgLD1jvcPrjN0PDspCc06bsdzu652ocHEJaUxpyQ96iXZzLiKBUhgjVjVHMhCAiQvhQn1B50OkJaCqGPImYLfysQgpfxXLMiBUNhCJFNM8Xma4wInhBJFDAvKBC90lATTKdLZKwBnc0aPC87VmFCoVfaVKOFkoQOnZQ63vGSqiqJcP8ZY6TRt7XgOZ323nLryuo/mN7PEH8FTnO7gNb4a/hSBifsLDNX4KwqVF8+T9curGS8ZjRvkhXnnJ6OOcK3p6V6bhfEMlkAhVVxoGfSOEgwUSHOXkchHlLBSp4ZWXWGhniwyZ2NMaCn0ulywgChZIGecaQUr3cy0lOdFLPiGUHN2qmNhYqdkiuRQJ1515lShGaSp7mbWuJBcPNwrR1RmgLxQxxER1eGckTJHPrqFnItj43LzygRfgz1r/0Xcs+KfAz6qf66zhQrB9X0PMg1/2pA/Hx7T2X9AREFeje3h2LwphaaIO0MV1o6wUFFZpvqD3bZd17VfQOwzjHPEeZU6j+4yl/Wa4OJl4v6ke6kW4RYXusozbO3Pi+BLJjZWUViVJoxO/wUAAP//vvE0OZ0MAAA
spec:
  template:
    metadata:
      annotations:
        helmcharts.helm.cattle.io/configHash: SHA256=3D36F9C9C8317F57F2BE6CCE7073B56A8E05338F59C3ECCA040A2B5FCC1CA230
    spec:
      $setElementOrder/volumes:
        - name: klipper-helm
        - name: klipper-cache
        - name: klipper-config
        - name: tmp
        - name: values
        - name: content
      volumes:
        - $retainKeys:
            - name
            - projected
          name: values
          projected:
            sources:
              - secret:
                  items:
                    - key: HelmChartConfigValuesContent
                      path: values-1-000-HelmChartConfig-ValuesContent.yaml
                  name: chart-values-rke2-ingress-nginx
---
```

The logs do NOT show creation of any HelmChartConfig resources from manifests in the manifests dir on the server, which makes me suspect they are being created some other way:

```console
brandond@dev01:~$ grep -rF 'Created helm.cattle.io/v1' rke2-8357.log
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-cilium for  kube-system/rke2-cilium"
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-coredns for  kube-system/rke2-coredns"
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-ingress-nginx for  kube-system/rke2-ingress-nginx"
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-metrics-server for  kube-system/rke2-metrics-server"
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-multus for  kube-system/rke2-multus"
Jun 25 19:24:32 host1rke2 rke2[3024]: time="2025-06-25T19:24:32Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-runtimeclasses for  kube-system/rke2-runtimeclasses"
Jun 25 19:24:33 host1rke2 rke2[3024]: time="2025-06-25T19:24:33Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-snapshot-controller-crd for  kube-system/rke2-snapshot-controller-crd"
Jun 25 19:24:33 host1rke2 rke2[3024]: time="2025-06-25T19:24:33Z" level=debug msg="DesiredSet - Created helm.cattle.io/v1, Kind=HelmChart kube-system/rke2-snapshot-controller for  kube-system/rke2-snapshot-controller"
```
