### ISSUE TITLE
Different behavior with kube-apiserver-arg between RKE2 v1.32.1 and v1.32.5

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#8365]
### Discussed in https://github.com/rancher/rke2/discussions/8358

<div type='discussions-op-text'>

<sup>Originally posted by **crtvmn** June 12, 2025</sup>
Hello,

I have the same `config.yaml` on 2 platforms with 2 different versions of RKE2 (`v1.32.1` and `v1.32.5`) and the generated `kube-apiserver.yaml` is different:

`config.yaml`:
```
[...]
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction,DenyServiceExternalIPs,EventRateLimit"
[...]
```

Generated `kube-apiserver.yaml` on the `v1.32.1` cluster:
```
spec:
  containers:
  - args:
    [...]
    - --enable-admission-plugins=NodeRestriction
    - --enable-admission-plugins=NodeRestriction,DenyServiceExternalIPs,EventRateLimit
```

Generated `kube-apiserver.yaml` on the `v1.32.5` cluster:
```
spec:
  containers:
  - args:
    [...]
    - --enable-admission-plugins=NodeRestriction,DenyServiceExternalIPs,EventRateLimit
    - --enable-admission-plugins=NodeRestriction
```

On the `v1.32.1` cluster, we can see that the `kube-apiserver-arg` is taken into account and the "extra" value overrides the default value (default is first). However, it's no longer the case on the `v1.32.5` cluster. The order seems important because the second value overrides the first one. Has there been a change in the behavior of the kube-apiserver?
</div>
