### ISSUE TITLE
v1.20.5+rke2r1 Helm Controller injects index.docker.io into image registry path

### ISSUE THREAD

**Issue by estenrye** [rancher/rke2#849]
# What am I trying to achieve?

I am trying to install rke2 v1.20.5+rke2r1 and configure the builtin ingress controller add-on to deploy as a DaemonSet with an image from the us.gcr.io registry: `us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2`

# What am I observing?

The ingress controller deploys as a DaemonSet but fails to successfully start any pods due to failure to locate image at `index.docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2`.

I believe this is due to the job adding `--set-string global.systemDefaultRegistry=index.docker.io` to the `helm_v3 upgrade` command.

# How to reproduce the failure?

1. Provision an Ubuntu 20.04 host.
2. Install rke2

```bash
curl -sfL https://get.rke2.io -o install.sh
chmod u+x install.sh
sudo INSTALL_RKE2_CHANNEL="latest" INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION="v1.20.5+rke2r1" ./install.sh
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
```

3. Wait for node to be ready and nginx controller deployment to finish.
4. Apply DaemonSet configuration to ingress controller.

```bash
sudo -i
cat > /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml <<EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      image:
        repository: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
        tag: "v0.41.2"
      daemonset:
        useHostPort: true
      config:
        use-forwarded-headers: "true"
      metrics:
        enabled: False
        serviceMonitor:
          enabled: False
      service:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "False"
          external-dns.alpha.kubernetes.io/hostname: example.com
          external-dns.alpha.kubernetes.io/ttl: "120"
EOF
```
5. Inspect the image used for the newly created DaemonSet

```bash
sudo /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kube-system get ds rke2-ingress-nginx-controller -o jsonpath="{.spec.template.spec.containers[0].image}"
```

**Actual Output:** index.docker.io/us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2
**Expected Output:** us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2

**Job YAML Specification**
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7RV0W7jNhD8lWKfKVmSJdsnIA+KLddpL7bhBEGL4hBQ1FpmTZEGSakXBP73goqbk++cFHm4t1CcnR3uzsTPsOeyhBR+UwUQoAf+gNpwJSGFglq2G7QhEKjR0pJaCukzSFojpLBDUXtcGkuF8PQeI4/LSqMxnqy4/AqkA5oDZQ69bwr0zJOxWAMBppFaruQ9r9FYWh8glY0QBAQtUBjXxdGzHdXW+O5Pn1FrBfpcDbqvkMLFnqr4G5k1aH3NVa9oR80OUhglUTLGEd1GSVzEGI3G8SiiwxCjqCi2QVhOtiUWjMKRAJVS2U5mJ+gtZl7+NwympNVKCNTvCFH/SNRe1e5PVb2rNiS//M5lebVAUU+7V/4fz2kXHxrFt8pLyzkeCZgDMvfkgrK92m4/85pbSMMgCAhYrA+CWnT3fVf8rJX+uIh3aJTc8mrxsuq7RRYlo6tJOJtMr4NpPk/GyTCaxcE0j/PgUxLn4zgfX8+vk/F0Nh7Nr8ef5slwOJtP8skkDMJsnmVxFJ4NpFWiqdFA+tdrDFoqGjTO013zW3roZaST6b1ALmXkeCTfsEpalPZdphPmMtWXrtJSLlGfSXRTAgK8ppU7clniV79UbI/aTU1TyXaoB3vBDwfUnoOnbeDH/tArGi7KKIjCIIoS9/9BV44aTrkHAp5n0HrGai4rIFAJVVDhO4EzaumM66tBS/VA8OK1kbt8s/LFhjPc0kbYDVbcWP109Z1m+EIAZdt/5DK7zYG8rOMtJ72CH/LN3c1q2f+0yder/nmRf759nG1uHvJNj9Yg02j7uOki29w/uu5362zal3CWqu8Kfuh0QdF9tvk1/xD1cvW43qz++LOH9E3LiM9EYyxqXyhGBQkDP478wA8G4ag7DE8HcB7SaFSjmXP585GcLH+rGmkv+752V2tqXeZOCYSLtj4Hdol3/Tpbrhsh1kpw9gQp3GyXyq41Gld3kmSptq+AlZxTLhqNQMCgbjnDjDFHv+z9Nl0MiQuzpbbpXnf8NwAA///SOSEy/gYAAA
    objectset.rio.cattle.io/id: helm-controller
    objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
    objectset.rio.cattle.io/owner-name: rke2-ingress-nginx
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2021-04-06T03:41:48Z"
  labels:
    helmcharts.helm.cattle.io/chart: rke2-ingress-nginx
    objectset.rio.cattle.io/hash: 65257e6af254b4e267462a31e22bbf01d8fdebca
  name: helm-install-rke2-ingress-nginx
  namespace: kube-system
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 204665b7-92ba-4ad2-9fe7-f89dacdb2529
  template:
    metadata:
      annotations:
        helmcharts.helm.cattle.io/configHash: SHA256=81D8CB0CEF57532D40CE4E0954E74E7BFB57CD76FB79F533DF8E88101AFAA421
      creationTimestamp: null
      labels:
        controller-uid: 204665b7-92ba-4ad2-9fe7-f89dacdb2529
        helmcharts.helm.cattle.io/chart: rke2-ingress-nginx
        job-name: helm-install-rke2-ingress-nginx
    spec:
      containers:
      - args:
        - install
        - --set-string
        - global.rke2DataDir=/var/lib/rancher/rke2
        - --set-string
        - global.systemDefaultRegistry=index.docker.io
        env:
        - name: NAME
          value: rke2-ingress-nginx
        - name: VERSION
        - name: REPO
        - name: HELM_DRIVER
          value: secret
        - name: CHART_NAMESPACE
          value: kube-system
        - name: CHART
        - name: HELM_VERSION
        - name: TARGET_NAMESPACE
          value: kube-system
        - name: NO_PROXY
          value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
        image: index.docker.io/rancher/klipper-helm:v0.4.3-build20210225
        imagePullPolicy: IfNotPresent
        name: helm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: values
        - mountPath: /chart
          name: content
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: helm-rke2-ingress-nginx
      serviceAccountName: helm-rke2-ingress-nginx
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: chart-values-rke2-ingress-nginx
        name: values
      - configMap:
          defaultMode: 420
          name: chart-content-rke2-ingress-nginx
        name: content
```

# How to reproduce the expected result.

1. Provision an Ubuntu 20.04 host.
2. Install rke2

```bash
curl -sfL https://get.rke2.io -o install.sh
chmod u+x install.sh
sudo INSTALL_RKE2_CHANNEL="latest" INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION="v1.19.9+rke2r1" ./install.sh
sudo systemctl enable rke2-server.service
sudo systemctl start rke2-server.service
```

3. Wait for node to be ready and nginx controller deployment to finish.
4. Apply DaemonSet configuration to ingress controller.

```bash
sudo -i
cat > /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml <<EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      image:
        repository: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller
        tag: "v0.41.2"
      daemonset:
        useHostPort: true
      config:
        use-forwarded-headers: "true"
      metrics:
        enabled: False
        serviceMonitor:
          enabled: False
      service:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "False"
          external-dns.alpha.kubernetes.io/hostname: example.com
          external-dns.alpha.kubernetes.io/ttl: "120"
EOF
```
5. Inspect the image used for the newly created DaemonSet

```bash
sudo /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml -n kube-system get ds rke2-ingress-nginx-controller -o jsonpath="{.spec.template.spec.containers[0].image}"
```

**Actual Output:** us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2
**Expected Output:** us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.41.2

**Job YAML Specification**

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7RVUW/iRhD+K9U8r41tbOAs5cEB06S9ACJR1Ko6ReNlgC3rXbS7dnuK+O/VOlzO6XGp7qFv7M4333w7Mx9+hoNQG8jhF10BAzyKRzJWaAU5VOj4ftDGwKAmhxt0CPkzKKwJctiTrAOhrEMpA3OgJBBqZ8jaQO2E+htYB7RH5B59aCoK7GfrqAYG3BA6odWDqMk6rI+Qq0ZKBhIrktZX8fR8j8bZ0P8MOTonKRR60N1CDhdr6upP4s6SC43QvaQ92j3kMMqSbEwj3CZZWqWUjMbpKMFhTElSVdso3ky2G6o4wokBKqVdJ7MT9D1msfnSDK6VM1pKMu8I0X8pMsGuPZyzeqE2Zj/9KtTm6oZkPe1e+V8851n8UCu+Zl4azunEwB6J+ydXyA96u/0oauEgj6MoYuCoPkp05OP9rfi/RvrtIN6h0Wordjcvo76/KZJsdDWJZ5PpdTQt59k4GyazNJqWaRl9yNJynJbj6/l1Np7OxqP59fjDPBsOZ/NJOZnEUVzMiyJN4jcNabVsarKQ//FqgxZlQ9bvdFf8Do89j3QygxfIJY+cTuwrVitHyr3LdMZcpvrUZToUiswbib5LwEDUuOuWBRXfkxkcpDgeyQQ+nLdRmIbDoGqE3CRREkdJkvn/A7PzVHD2OTAIAksusM4ItQMGO6krlKEXNEOHM2GuBi2agRTV4EshH4RPDEi1fVmL4q4E9tLA783+FfxYru9vl4v+1bpcLfvnm/Lj3dNsfftYrnu0lrgh18dNb4r1w5Ovfr8qpn0Jb3zwr4RvKl1Q9FCsfy5/iHqxfFqtl7/93kOGtuUs5LKxjkwoNUfJ4ihMkzAKo0E86g7D8wH81A1Z3Rju9/L5xM5Leqcb5S5vau1DK3TeJWfPwMVFfAvsPOrrdYu0aqRcaSn4Z8jhdrvQbmXI+ryzJIfGvQKWao5CNoaAgSXTCk4F555+0fuaXFxrbz+Hruled/onAAD//6irZl2wBgAA
    objectset.rio.cattle.io/id: helm-controller
    objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
    objectset.rio.cattle.io/owner-name: rke2-ingress-nginx
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2021-04-06T03:52:39Z"
  labels:
    helmcharts.helm.cattle.io/chart: rke2-ingress-nginx
    objectset.rio.cattle.io/hash: 65257e6af254b4e267462a31e22bbf01d8fdebca
  name: helm-install-rke2-ingress-nginx
  namespace: kube-system
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 9067df64-72ba-461c-bee6-2958e62017e4
  template:
    metadata:
      annotations:
        helmcharts.helm.cattle.io/configHash: SHA256=81D8CB0CEF57532D40CE4E0954E74E7BFB57CD76FB79F533DF8E88101AFAA421
      creationTimestamp: null
      labels:
        controller-uid: 9067df64-72ba-461c-bee6-2958e62017e4
        helmcharts.helm.cattle.io/chart: rke2-ingress-nginx
        job-name: helm-install-rke2-ingress-nginx
    spec:
      containers:
      - args:
        - install
        - --set-string
        - global.rke2DataDir=/var/lib/rancher/rke2
        env:
        - name: NAME
          value: rke2-ingress-nginx
        - name: VERSION
        - name: REPO
        - name: HELM_DRIVER
          value: secret
        - name: CHART_NAMESPACE
          value: kube-system
        - name: CHART
        - name: HELM_VERSION
        - name: TARGET_NAMESPACE
          value: kube-system
        - name: NO_PROXY
          value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
        image: rancher/klipper-helm:v0.4.3-build20210225
        imagePullPolicy: IfNotPresent
        name: helm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: values
        - mountPath: /chart
          name: content
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: helm-rke2-ingress-nginx
      serviceAccountName: helm-rke2-ingress-nginx
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: chart-values-rke2-ingress-nginx
        name: values
      - configMap:
          defaultMode: 420
          name: chart-content-rke2-ingress-nginx
        name: content
```

# Key Difference

v1.20.5+rke2r1 includes the following yaml in its arguments for helm controller jobs while v1.19.9+rke2r1 does not.

```yaml
        - --set-string
        - global.systemDefaultRegistry=index.docker.io
```

I think this may be the root cause of the issue.
