### ISSUE TITLE
Bootstrap image pull in v1.20.5+rke2r1 ignores path of endpoint URL in registries.yaml

### ISSUE THREAD

**Issue by tallaxes** [rancher/rke2#853]
If `registries.yaml` looks like this:

```yaml
mirrors:
  docker.io:
    endpoint:
    - https://<myregistry>/<path>
```

then the path part of the endpoint URL is ignored / lost by the bootstrap image pull logic. Yes, using path here is somewhat unusual, but containerd itself handles it just fine. 

Fixing this is likely just a matter of including / propagating the path part (or maybe URL as a whole?) in the bootstrap logic - unless there is some very good reason to explicitly not support this ...
