### ISSUE TITLE
Allow users to deploy Cilium with dual stack config 

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rke2#861]
The dual stack config requires the helm variables: `clusterPoolIPv6PodCIDR` and `ipv6` to be set. We are currently hiding those and using upstream default values, which disable dual stack.

Connected to issue: https://github.com/k3s-io/k3s/issues/3158

**Comment by sep76** [comment]
in addition to this, and perhaps even more important, you would need those to run ipv6 only

**Comment by manuelbuil** [comment]
https://github.com/rancher/rke2-charts/pull/64

**Comment by davidnuzik** [comment]
Please update the status as you get linked PRs in review and To Test. I have done so in this case.

**Comment by rancher-max** [comment]
#### Validated in 1.21.0-alpha2+rke2r1

Using a helmchart such as below allows rke2-cilium to deploy with dual stack config:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-cilium
  bootstrap: true
  valuesContent: |
    cilium:
      ipv6:
        enabled: true
```
Dual stack has a few other issues of its own, but this piece appears to be working successfully as I see the pods come up and running without any restarts in rke2.
