### ISSUE TITLE
Align channel server schema and our RPM repo

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#864]
The channel server's current approach to handling different streams/channels is to have 1 stable channel, 1 latest channel, 1 testing channel, and unique channels for each minor release (1.18, 1.19, 1.20, etc).

This doesn't really conform to how the RPM repo is handled. With the RPM repo, we have 3 lines, each 1.18, 1.19, and 1.20 currently. Each of these lines has three channels: testing, latest, stable. This results in a matrix of 9, which is more complex than the approach with channel server today.

We should rethink how the channel server works. We need to align the RPM repo model and channel server approach to channels. Perhaps this results in the channel server being iterated on such that we have at least a stable and latest entry for each line (major,minor). Something like this, as an example:

```
channels:
- name: stable
  latest: v1.20.5+rke2r1
- name: latest
  latestRegexp: .*
  excludeRegexp: ^[^+]+-
- name: v1.18-latest
  latestRegexp: v1\.18\..*
  excludeRegexp: ^[^+]+-
- name: v1.18-stable
  latest: v1.18.17+rke2r1
- name: v1.19-latest
  latestRegexp: v1\.19\..*
  excludeRegexp: ^[^+]+-
- name: v1.19-stable
  latest: v1.19.9+rke2r1
- name: v1.20-latest
  latestRegexp: v1\.20\..*
  excludeRegexp: ^[^+]+-
- name: v1.20-stable
  latest: v1.20.5+rke2r1
- name: testing
  latestRegexp: -(alpha|beta|rc)
github:
  owner: rancher
  repo: rke2
redirectBase: https://github.com/rancher/rke2/releases/tag/
```

This would result in more maintenance of the channels.yaml file, but would align better with how the RPM repo works.
Also, note that in order to keep compatability we probably need to keep the old 1.18, 1.19, 1.20 entries.
