### ISSUE TITLE
Helm chart deployment image/registry prefix

### ISSUE THREAD

**Issue by ClaudiuLSH** [rancher/rke2#874]
While playing with helm chart manifests located at `/var/lib/rancher/rke2/server/manifests/` I noticed that all image names are prefixed with index.docker.io.

For instance I tried to enable hubble for cilium with:
```
  valuesContent: |-
    cilium:
      hubble:
        listenAddress: ":4244"
        relay:
          enabled: true
        ui:
          enabled: true
```
And all image definitions in deployments looked similar to this: `image: index.docker.io/quay.io/cilium/hubble-ui:v0.7.3`.
So this should not contain index.docker.io since the image is located at quay.io.

I have the same issue while following this documentation step: https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/ha-rke2/#5-configure-nginx-to-be-a-daemonset

While looking at an updated manifest after being created, I noticed `global.systemDefaultRegistry: index.docker.io` so I am assuming this is my issue. Is there any proper way of configuring this?
