### ISSUE TITLE
default-network-dns-policy does not allow access to monitoring port TCP 9153

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rke2#909]
**Environmental Info:**
RKE2 Version:  1.20.5

Cluster Configuration:
cis-1.5

**Describe the bug:**
Prometheus alerts show up for dns down.

**Steps To Reproduce:**
Deploy monitoring on an rke2 cluster with cis1.5 active / network policies active
Check alerts

**Expected behavior:**
No alert should show up in case dns is up and running well

**Actual behavior:**
Alert is there because prometheus check to dns pods on 9153 does not work / is blocked by network policy

Workaround:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-dns-monitoring-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 9153
      protocol: TCP
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
  - Ingress
```
