### ISSUE TITLE
Registry rewrite example

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#915]
Would it be possible to add a rewrite example to the [private registry methods section](https://docs.rke2.io/install/airgap/#private-registry-method) of the air-gap docs? Specifically for the case where the rke2 container images specified in `rke2-images.linux-<arch>.txt` are pushed to `some.registry.lan/foo/bar/baz/`, but the entirety of `docker.io` **is not** mirrored to the nested registry namespace. I'm unclear on if I should be setting `system-default-registry`, using `rewrite` somehow in `registries.yaml`, or perhaps both?

_Originally posted by @marshallford in https://github.com/rancher/rke2/issues/865#issuecomment-824496074_

**Comment by brandond** [comment]
You might try something like this; I haven't tested it myself but I believe it should work:

```yaml
mirrors:
  docker.io:
    endpoint:
      - https://some.registry.lan
    rewrite:
      "^rancher/(.*)": "foo/bar/baz/$1"
configs:
  some.registry.lan:
    tls:
      insecure_skip_verify: true
```

This relies on the fact that containerd will fall back to the default endpoint for docker.io if the endpoint specified in the config file fails to provide the image.

**Comment by Martin-Weiss** [comment]
Maybe this helps a but - this works well for me in 1.20.6 rc2:

```
mirrors:
  docker.io:
    endpoint:
      - "https://registry01.suse:5000/v2/"
    rewrite:
      "(.*)": "rke-prod/docker.io/$1"
  quay.io:
    endpoint:
      - "https://registry01.suse:5000/v2/"
    rewrite:
      "(.*)": "rke-prod/quay.io/$1"
  gcr.io:
    endpoint:
      - "https://registry01.suse:5000/v2/"
    rewrite:
      "(.*)": "rke-prod/gcr.io/$1"
configs:
  "registry01.suse:5000":
    auth:
      username: rancher-cluster # this is the registry username
      password: 6t2n-NtR5DeWCfCwBkrV # this is the registry password
    tls:
      ca_file: /etc/ssl/ca-bundle.pem
```

Please do not add "insecure_skip_verify: true" to the example as disabling security should not be the default...
The better alternative should be to have the cert of the CA signing the registries cert as trusted CA in /etc/ssl/ca-bundle.pem.

**Comment by marshallford** [comment]
Couple of thoughts:

1. @Martin-Weiss to your comment on security. I _suspect_ @brandond was just demonstrating that you can still set fields as usual under `configs.<registry>` when using the `mirrors.<registry>.rewrite` feature.
2. Looking over the image names in `rke2-images.linux-<arch>.txt`, only `rke2-runtime` is prefixed with `rke2`. @brandond perhaps all of the images should have the prefix so that the regex you suggested would exclusively match rke2 related container images? I'd like to avoid a wild regex expression or having to mirror all container images in `docker.io/rancher` to `some.registry.lan`.

**Comment by brandond** [comment]
Yes, that is just an example. I probably wouldn't recommend prefixing things with foo and bar, and as was noted, all of the images don't start with rke2- either.

I think renaming everything to start with rke2- is not likely to happen, as many of the images that are required for airgap are not rke2 specific.

**Comment by marshallford** [comment]
I'm running into `failed to get runtime image` errors when using the rewrite example alongside `system-default-registry: some.registry.lan`. Any ideas?

First attempt:

```
# registries.yaml
mirrors:
  docker.io:
    endpoint:
      - https://some.registry.lan
    rewrite:
      "^rancher/(rke2-runtime|hardened-kubernetes|hardened-calico|hardened-coredns|hardened-etcd|hardened-flannel|hardened-k8s-metrics-server|hardened-kube-proxy|klipper-helm|pause|nginx-ingress-controller-defaultbackend|nginx-ingress-controller)": "rke2/$1"
configs:
    some.registry.lan:
      auth: ...
```

```
failed to get runtime image some.registry.lan/rancher/rke2-runtime:v1.20.6-rke2r1: GET https://some.registry.lan/v2/rancher/rke2-runtime/manifests/v1.20.6-rke2r1: UNAUTHORIZED: access to the requested resource is not authorized; map[]
```

Second attempt since the rewrite from `rancher` to `rke2` wasn't happening:

```
# registries.yaml
mirrors:
  some.registry.lan: <-- changed
    endpoint:
      - https://some.registry.lan
    rewrite:
      "^rancher/(rke2-runtime|hardened-kubernetes|hardened-calico|hardened-coredns|hardened-etcd|hardened-flannel|hardened-k8s-metrics-server|hardened-kube-proxy|klipper-helm|pause|nginx-ingress-controller-defaultbackend|nginx-ingress-controller)": "rke2/$1"
configs:
    some.registry.lan:
      auth: ...
```

```
failed to get runtime image some.registry.lan/rancher/rke2-runtime:v1.20.6-rke2r1: GET https://index.docker.io/v2/rke2/rke2-runtime/manifests/v1.20.6-rke2r1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:rke2/rke2-runtime Type:repository]]
```
