### ISSUE TITLE
Need to pass additional CLI flags through to RKE2 HelmCharts

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#917]
We currently pass through the `--system-default-registry` CLI flag to all HelmChart manifests. We are going to need to pass through additional flags, such as the `--cluster-cidr` and `--service-cidr` flags, and probably others as well.
* Identify what flags we need to pass through
* Create a naming scheme or standard for pass-through flags
* Enhance the existing scaffolding that is used to pass through flags to be more generic
* Modify existing charts to use the new pass-through values

**Comment by rancher-max** [comment]
#### Validated on v1.21.1-alpha5+rke2r1

- These flags, among others, are now passed through to the helmcharts:
```
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
```
- Ensured these show up on default helmcharts and custom ones that were dropped into `/var/lib/rancher/rke2/server/manifests` before starting the rke2 server process.
