### ISSUE TITLE
Ability to configure/disable calico FailsafeOutboundHostPorts and FailsafeInboundHostPorts for host protection

### ISSUE THREAD

**Issue by jonaz** [rancher/rke2#921]
We have added policy to allow ssh access from only operations network using calico GlobalNetworkpolicy it still allows ssh from anywhere since you are using default calico FailsafeInboundHostPorts in the chart. 

```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: ingress-k8s-masters
spec:
  selector: has(node-role.kubernetes.io/master)
  types:
  - Ingress
  - Egress
  egress:
  - action: Allow
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 22
    source:
      nets:
      - 10.0.0.0/24

```

When i manually edited `kubectl edit daemonsets.apps --namespace kube-system rke2-canal`
and added: 
```
        - name: FELIX_FAILSAFEINBOUNDHOSTPORTS
          value: none

```
It works and ssh is blocked from everywhere but 10.0.0.0/24

Support for FailsafeOutboundHostPorts and FailsafeInboundHostPorts needs to be added here: 
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-canal/charts/values.yaml

I can make a PR if you want!
