### ISSUE TITLE
Cilium returns timeout

### ISSUE THREAD

**Issue by vaisov** [rancher/rke2#922]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04 (Upgraded from 18.04 with `do-release-upgrade`). Same issue was present on 18.04 prior upgrade to 20.04
Linux de-azure-kubernetes-test01 5.4.0-1046-azure #48-Ubuntu SMP Tue Apr 13 07:18:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 1 master

**Describe the bug:**

Cilium CNI doesn't work, Cilium pods are crashing with error described below.

**Steps To Reproduce:**

- Installed RKE2: 
```
mkdir -p /etc/rancher/rke2/
cat << EOF > /etc/rancher/rke2/config.yaml
disable:
  - rke2-canal
  - rke2-kube-proxy
EOF

mkdir -p /var/lib/rancher/rke2/server/manifests/
cat << EOF > /var/lib/rancher/rke2/server/manifests/rke2-cilium.yml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-cilium
  bootstrap: true
  valuesContent: |-
    cilium: {}
EOF

curl -sfL https://get.rke2.io | sh - && systemctl enable rke2-server.service && systemctl start rke2-server.service && journalctl -u rke2-server -f
```

**Expected behavior:**
Cilium pods are up and running without crashes

**Actual behavior:**
Cilium pods are crashing with error:
```
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.43.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.43.0.1:443: i/o timeout" ipAddr="http
s://10.43.0.1:443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get \"https://10.43.0.1:443/api/v1/namespac
es/kube-system\": dial tcp 10.43.0.1:443: i/o timeout" subsys=daemon
```

**Additional context / logs:**

**Comment by Martin-Weiss** [comment]
Not sure if this is related - but could you try with ipam: mode: kubernetes?

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  repo: https://rke2-charts.rancher.io
  chart: rke2-cilium
  bootstrap: true
  valuesContent: |-
    cilium:
      ipam:
        mode: "kubernetes"
```

**Comment by vaisov** [comment]
I still get the same error even with provided setting. Here's the settings I've tried to use to install Cilium `v1.10.0-rc0` (we need WireGuard encryption, hence the RC):
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  valuesContent: |-
    cilium:
      version: v1.10.0-rc0
      masquerade: true
      prometheus:
        enabled: true
      operator:
        prometheus:
          enabled: true
      nodeinit:
        enabled: true
      ipam:
        mode: "kubernetes"
```
