### ISSUE TITLE
kube-apiserver : no access to Admission Controller / PodNodeSelector.yaml file 

### ISSUE THREAD

**Issue by massep88** [rancher/rke2#930]
**Environmental Info:**
RKE2 Version: 

rke2 version v1.20.5+rke2r1 (e3d8dc388a5a70b2b9e1355f4708dd8090ba8b05)
go version go1.15.8b5

Node(s) CPU architecture, OS, and Version: 

Linux rke-master01 5.3.18-24.52-default #1 SMP Tue Mar 2 13:15:25 UTC 2021 (c35b124) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

3 servers + 1 agent cluster

**Describe the bug:**

It seems that it is not possible to configure PodNodeSelector Admission Controller on kube-apiserver.
When a file, provided as input kube-apiserver static pod argument with --kube-apiserver-arg, point to another file, this other file is not defined as hostPath volume in the static pod.

Am I missing something or is this an RKE2 limitation ?

Notes : 
* With RKE2, the manifest files of static pods such as kube-apiserver are automatically generated by RKE2 upon bootstrap. There is no way to pre-tune them to present "default parameters" ...
* Besides files, a list of directories gets automatically mounted in kube-api static pod. However, these directories are not related to admission controller and I do not see any ways to add another directory in the list.
* This behavior is likely to be the same for any RKE2 static pods (etcd, kube-controller, kube-apiserver and kube-scheduler).

**Steps To Reproduce:**

- Installed RKE2: 

RKE2 installed thanks to install.sh / rke2 tar ball.

- RKE2 Configuration
The rke2 configuration has been updated with the kube-apiserver args pointing to the admission control config file, which is mounted as hostPath volume in kube-apiserver pods. 

Extract from RKE2 config.yaml :
 
kube-apiserver-arg:
  \- "enable-admission-plugins=NodeRestriction,PodSecurityPolicy"
  \- "admission-control-config-file=/path/to/admission-control.yaml"

The admission control config file points to another file, podnodeselector.yaml, which is not mounted in the pod.

Extract from admission-control.yaml :

apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
\- name: PodNodeSelector
  path: /path/to/podnodeselector.yaml

**Expected behavior:**

Both files, admission-control.yaml and podnodeselector.yaml, are mounted in kube-apiserver static pods.

Expected extract from kube-apisever static pod manifest, generated by rke2 /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml :

[..]
volumeMounts:
[..]
    \- mountPath: /path/to/admission-control.yaml
      name: file2
      readOnly: true
     \- mountPath: /path/to/podnodeselector.yaml
      name: fileX
      readOnly: true
[..]
volumes:
  [..]
  \- hostPath:
      path: /path/to/admission-control.yaml
      type: File
    name: file2
 \- hostPath:
      path: /path/to/podnodeselector.yaml
      type: File
    name: fileX

**Actual behavior:**

No hostPath volume is defined for podnodeselector.yaml file, which is therefore not accessible from the kube-apiserver, hence preventing to properly configure the PodNodeSelector Admission Controller.

**Additional context / logs:**

**Comment by brandond** [comment]
That is correct. We automatically add mounts for any files referenced by arguments, but there is not currently a way to pass in additional files to be mounted ad-hoc.

**Comment by massep88** [comment]
Thank you, Brad.

**Comment by tangentToNothing** [comment]
Our organization is also encountering this with CIS 1.6 Hardening--initially with [control 1.2.10](https://docs.rke2.io/security/cis_self_assessment15/#1210). Is there a workaround for performing the stated remediation? 

For example, from the `EventRateLimit` [k8s docs](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#eventratelimit):

<admissionConfig.yaml>
```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: EventRateLimit
  path: <path/to/otherFile.yaml>
```

<otherFile.yaml>
```yaml
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Namespace
  qps: 50
  burst: 100
  cacheSize: 2000
- type: User
  qps: 10
  burst: 50
```

**Comment by brandond** [comment]
No, there is not currently any workaround for this issue.

**Comment by rancher-max** [comment]
#### Validated using master branch commit `525479888074426ea6019474c33e184a947c197c`

It should be noted that the functionality of this is different than mentioned in the original issue comment. There is a new value available in the config.yaml to supply mount **directories.** See https://docs.rke2.io/advanced/#extra-control-plane-component-volume-mounts for details.
FWIW this should also be working on v1.21.3+rke2r3 as I previously validated the use of these extra volume mounts in a backport issue there.

Example of my steps:
```yaml
# /etc/rancher/rke2/config.yaml
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction,PodSecurityPolicy,EventRateLimit"
  - "admission-control-config-file=/home/ubuntu/admission-control.yaml"
write-kubeconfig-mode: 644
profile: cis-1.6
kube-apiserver-extra-mount: /max/is/testing:/max/is/testing:ro
```
Directory contents just contain one file `/max/is/testing/otherfile.yaml`
```yaml
# /max/is/testing/otherfile.yaml
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Namespace
  qps: 50
  burst: 100
  cacheSize: 2000
- type: User
  qps: 10
  burst: 50
```
```yaml
# /home/ubuntu/admission-control.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: EventRateLimit
  path: /max/is/testing/otherfile.yaml
```

Describing the apiserver pod shows mounts as expected:
```
Volumes:
...
  file2:
    Type:          HostPath (bare host directory volume)
    Path:          /home/ubuntu/admission-control.yaml
    HostPathType:  File
...
  extra-mount-0:
    Type:          HostPath (bare host directory volume)
    Path:          /max/is/testing
    HostPathType:  DirectoryOrCreate
```
exec'ing into the running apiserver pod and viewing the contents of each of `/home/ubuntu/admission-control.yaml` and `/max/is/testing/otherfile.yaml` yields correct results.

We had some internal discussion related to the passing of a directory only here for extra mounts, so I created https://github.com/rancher/rke2/issues/1793 to address that.
