### ISSUE TITLE
Setup with Network Optional of Canal not work

### ISSUE THREAD

**Issue by scila1996** [rancher/rke2#964]
Hi all

I was configured follow document 

https://docs.rke2.io/install/network_options/

This is my config file

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    podCidr: "10.20.0.0/16"
    flannel:
      iface: "ens192"
```

but seem like is not work. Pod CIDR still default 10.42.0.0/16 and iface too not update to another interface !
