### ISSUE TITLE
[release-1.20] Feature backports for cni, vsphere, registry auth plugin support

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#997]
We need to backport the following features in to the 1.20 release branch, along with any bugfixes for these features:

* Use --system-default-registry flag from K3s #959
* Use rancher/wharfie code for bootstrap #958 
* Need to pass additional CLI flags through to RKE2 HelmCharts #917
* vSphere CPI/CSI support #916 
* Add --cni flag as an option to RKE2 #887

**Comment by rancher-max** [comment]
#### Validated in v1.20.7-rc1+rke2r1

- `cni` flag is now available and correctly uses the cni chosen. Default is still canal when this is not passed
- additional helm parameters are passed via the `set` flag in the charts:
```yaml
...
  set:
    global.clusterCIDR: 10.42.0.0/16
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
```
- All airgap testing continues to pass. This includes: tarball, private registry via mirror with registries.yaml, system-default-registry. This means both the `system-default-registry` flag from k3s is being passed through correctly and rancher/wharfie is working correctly in rke2 in this release as well.
- vSphere CNI backport is also working as expected
